Repository adobecom/milo, pull requests merged in 2022-09, with the labels that each got.

#149 Merge data-viz into main
  .eslintrc.js
  .github/workflows/run-tests.yaml
  libs/blocks/chart/chart.css
  libs/blocks/chart/chart.js
  libs/blocks/chart/chartLightTheme.js
  libs/blocks/chart/list.css
  libs/blocks/chart/list.js
  libs/blocks/chart/utils.js
  libs/blocks/section-metadata/section-metadata.css
  libs/blocks/section-metadata/section-metadata.js
  libs/deps/echarts.common.min.js
  libs/utils/utils.js
  test/blocks/chart/chart.test.js
  test/blocks/chart/chartLightTheme.test.js
  test/blocks/chart/list.test.js
  test/blocks/chart/mocks/areaChart.json
  test/blocks/chart/mocks/chart.html
  test/blocks/chart/mocks/columnChart.json
  test/blocks/chart/mocks/list.html
  test/blocks/chart/mocks/listChartMulti.json
  test/blocks/chart/mocks/listChartMultiTable.json
  test/blocks/chart/mocks/listChartSingle.json
  test/blocks/chart/mocks/listChartSingleTable.json
  test/blocks/chart/utils.test.js
  test/utils/utils.test.js
Labels: release

#162 MWPW-116458 - Merch at Scale
  libs/blocks/merch/merch.css
  libs/blocks/merch/merch.js
  libs/deps/tacocat-index.js
  test/blocks/merch/merch.test.js
  test/blocks/merch/mocks/body.html
  test/blocks/merch/mocks/head.html
Labels: release

#169 Fix chart.test.js import
  test/blocks/chart/chart.test.js
Labels: trivial

#165 Hide carousel
  libs/blocks/carousel/carousel.css
  libs/blocks/carousel/carousel.js
  test/blocks/carousel/carousel.test.js
  test/blocks/carousel/mocks/body.html
Labels: in test, verified fixed

#166 Adding youtube as a block
  libs/blocks/youtube/youtube.css
  libs/blocks/youtube/youtube.js
  libs/utils/utils.js
  test/blocks/youtube/mocks/body.html
  test/blocks/youtube/youtube.test.js
Labels: release, in test, verified fixed

#148 MWPW-105618 - Consonant Icon block
  libs/blocks/icon-block/icon-block.css
  libs/blocks/icon-block/icon-block.js
  libs/blocks/section-metadata/section-metadata.css
  libs/utils/utils.js
  test/blocks/icon-block/icon-block.test.js
  test/blocks/icon-block/mocks/body.html
Labels: release, in test, verified fixed

#156 MWPW-115134 - Consonant Marquee V6
  libs/blocks/marquee/marquee.css
  libs/blocks/marquee/marquee.js
  libs/styles/styles.css
  libs/styles/typography.css
  libs/styles/variables.css
  libs/utils/decorate.js
  test/blocks/marquee/marquee.test.js
  test/blocks/marquee/mocks/body.html
Labels: release, verified fixed

#172 MWPW-116364 - 404
  404.html
  libs/styles/styles.css
  libs/templates/404/404.css
  libs/templates/404/404.js
  libs/utils/utils.js
Labels: release, verified

#175 MWPW-113009 - Oversized Number Chart
  libs/blocks/chart/chart.css
  libs/blocks/chart/chart.js
  test/blocks/chart/chart.test.js
  test/blocks/chart/mocks/oversized-number.json
Labels: enhancement, release

#178 MWPW-115566 - OneTrust
  libs/utils/utils.js
Labels: release, verified

#167 MWPW-116415 Use import metadata if avail
  tools/send-to-caas/send-to-caas.js
Labels: trivial

#179 MWPW-105583 - Social Share Block
  libs/blocks/share/share.css
  libs/blocks/share/share.js
  libs/blocks/share/share.svg
  libs/utils/utils.js
  test/blocks/share/getSVGsFromFile.test.js
  test/blocks/share/mocks/body.html
  test/blocks/share/share.test.js
Labels: release, verified

#180 Fix region selector alignment
  libs/blocks/footer/footer.css
Labels: trivial

#174 [MWPW-105625] - Consonant Text block
  libs/blocks/text/text.css
  libs/blocks/text/text.js
  test/blocks/text/mocks/body.html
  test/blocks/text/text.test.js
Labels: release, verified

#181 Trivial: Add M@S API Key
  libs/blocks/merch/merch.js
Labels: trivial

#177 Marquee design polish and 2 image per-viewport support
  libs/blocks/marquee/marquee.css
  libs/blocks/marquee/marquee.js
  libs/styles/typography.css
  libs/utils/decorate.js
  test/blocks/marquee/marquee.test.js
  test/blocks/marquee/mocks/body.html
Labels: enhancement, verified

#185 Chart accessibility MWPW-116840
  libs/blocks/chart/chart.js
Labels: trivial

#187 Region Modal Styling
  libs/blocks/footer/footer.css
  libs/blocks/modal/modal.css
Labels: release, verified

#188 MWPW-109311 - Gnav UX & Breadcrumbs
  .vscode/launch.json
  libs/blocks/footer/adchoices-small.svg
  libs/blocks/footer/footer.css
  libs/blocks/footer/footer.js
  libs/blocks/gnav/gnav.css
  libs/blocks/gnav/gnav.js
  libs/blocks/section-metadata/section-metadata.css
  libs/styles/styles.css
  libs/utils/favicon.js
  libs/utils/utils.js
  test/blocks/gnav/gnav.test.js
  test/blocks/gnav/mocks/body.html
  test/blocks/gnav/mocks/section.plain.html
  test/utils/mocks/body.html
  test/utils/utils.test.js
Labels: release, verified

#189 Update preact
  .hlxignore
  build/htm-preact-debug.js
  build/htm-preact.js
  libs/deps/htm-preact.js
  package-lock.json
  package.json
  test/blocks/caas-config/caas-config.test.html
  test/helpers/selectors.js
Labels: in test

#193 Fix iOS bug for animated marquee MWPW-117337
  libs/blocks/marquee/marquee.js
Labels: bug, trivial

#182 Include analytics utility
  libs/blocks/marquee/marquee.css
  libs/blocks/marquee/marquee.js
  libs/blocks/media/media.js
  libs/utils/analytics.js
  libs/utils/analytics.md
  libs/utils/decorate.js
Labels: verified

#199 Delay privacy
  libs/utils/utils.js
  test/blocks/gnav/gnav.test.js
Labels: trivial

#190 MWPW-107820 Consonant Tabs
  libs/blocks/tabs/tabs.css
  libs/blocks/tabs/tabs.js
  libs/utils/utils.js
  test/blocks/tabs/mocks/body.html
  test/blocks/tabs/tabs.test.js
Labels: release, verified

#201 dont load the fail block on production
  libs/utils/utils.js
Labels: trivial

#202 Add Bacom as a source
  libs/blocks/caas-config/caas-config.js
Labels: trivial

#203 Send full url for images to caas
  tools/send-to-caas/send-to-caas.js
Labels: trivial

#204 MWPW-117636 - Block library updates
  libs/ui/img/collapse.svg
  libs/ui/img/expand.svg
  libs/ui/img/spectrum-preview.svg
  libs/ui/library/library.css
  libs/ui/library/library.js
  tools/sidekick/config.js
Labels: trivial

#207 Add option to show card ids in configurator
  libs/blocks/caas-config/caas-config.css
  libs/blocks/caas-config/caas-config.js
Labels: release

#211 Set display none at section-metadata.css so consumer sites can have it.
  libs/blocks/section-metadata/section-metadata.css
  libs/styles/styles.css
Labels: bug, verified

#206 MWPW-116861 - Fragment Unwrap
  libs/utils/utils.js
  test/blocks/section-metadata/mocks/body.html
  test/blocks/section-metadata/section-meta.test.js
  test/utils/mocks/body.html
  test/utils/utils.test.js
Labels: release, trivial

#209 Manual Card MWPW-115384
  libs/blocks/manual-card/manual-card.css
  libs/blocks/manual-card/manual-card.js
  libs/utils/utils.js
  test/blocks/manual-card/manual-card.test.js
  test/blocks/manual-card/mocks/default.html
  test/blocks/manual-card/mocks/double-width.html
  test/blocks/manual-card/mocks/half-height.html
  test/blocks/manual-card/mocks/half.html
  test/blocks/manual-card/mocks/product.html
Labels: release, verified

#213 Inline Aside MWPW-115383
  libs/blocks/aside/aside.css
  libs/blocks/aside/aside.js
  test/blocks/aside/aside.test.js
  test/blocks/aside/mocks/body.html
Labels: release

#214 Remove undefined on Manual Card if no description MWPW-117924
  libs/blocks/manual-card/manual-card.js
  test/blocks/manual-card/manual-card.test.js
  test/blocks/manual-card/mocks/double-width.html
  test/blocks/manual-card/mocks/half-height.html
Labels: bug

#216 Add caas-config to MILO_BLOCKS so it can be used by consumers
  libs/blocks/caas-config/caas-config.js
  libs/ui/controls/Accordion.js
  libs/ui/controls/MultiField.js
  libs/ui/controls/TagSelector.js
  libs/utils/utils.js
Labels: trivial

#217 Fix Manual Card title characters cut off on bottom MWPW-118021
  libs/blocks/manual-card/manual-card.css
Labels: bug, trivial

#219 Fix for CaaS Top Filters UI
  libs/blocks/caas/caas.css
Labels: bug, trivial
