Repository adobecom/milo, pull requests merged in 2022-12, with the labels that each got.

#338 Fix lana bug found in MWPW-121954
  libs/utils/lana.js
  test/utils/lana.test.js
Labels: verified

#336 MWPW-116988 - SEO long form Icon Blocks
  libs/blocks/icon-block/icon-block.css
  libs/blocks/icon-block/icon-block.js
  libs/blocks/media/media.js
  libs/blocks/section-metadata/section-metadata.css
  libs/blocks/text/text.js
  libs/styles/typography.css
  libs/styles/variables.css
  libs/utils/decorate.js
  test/blocks/icon-block/icon-block.test.js
  test/blocks/icon-block/mocks/body.html
Labels: release, verified

#335 Play and objectives icon addition
  libs/img/icons/icons.svg
Labels: verified

#346 This is to match with AEM FaaS style.
  libs/blocks/faas/faas.css
Labels: verified, trivial

#347 faas tool field validation added.
  libs/blocks/faas-config/faas-config.css
  libs/blocks/faas-config/faas-config.js
  libs/blocks/faas/utils.js
Labels: bug, trivial

#351 MWPW-122039 Tabs bugs
  libs/blocks/tabs/tabs.js
Labels: bug, verified

#309 MWPW-97639 - GeoRouting
  libs/blocks/modal/modal.css
  libs/blocks/modal/modal.js
  libs/features/georouting/georouting.js
  libs/img/favicons/favicon.webmanifest
  libs/img/icons/Smock_GlobeOutline_18_N.svg
  libs/scripts/scripts.js
  libs/utils/utils.js
  test/features/georouting/georouting.test.js
Labels: verified

#349 MWPW-122629 - Fix PDF Relative Link
  libs/utils/utils.js
Labels: verified, trivial

#353 Set the edgeConfigId on window
  libs/martech/martech.js
Labels: trivial

#322 MWPW-122131 - Recommended Articles
  libs/blocks/article-feed/article-feed.css
  libs/blocks/article-feed/article-helpers.js
  libs/blocks/featured-article/featured-article.js
  libs/blocks/recommended-articles/recommended-articles.css
  libs/blocks/recommended-articles/recommended-articles.js
  libs/styles/article-card.css
  libs/styles/lazy-styles.css
  libs/utils/utils.js
  test/blocks/featured-article/taxonomy.json
  test/blocks/recommended-articles/mocks/blog-milo.html
  test/blocks/recommended-articles/mocks/body.html
  test/blocks/recommended-articles/mocks/placeholders.json
  test/blocks/recommended-articles/mocks/taxonomy.json
  test/blocks/recommended-articles/mocks/voices-of-our-community.html
  test/blocks/recommended-articles/recommended-articles.test.js
Labels: release, verified

#354 MWPW-119166 - Fix chart date unit
  libs/blocks/chart/chart.js
  test/blocks/chart/chart.test.js
Labels: verified

#355 MWPW-122756 - Fix PDF Viewer on Consumer Live
  libs/blocks/pdf-viewer/pdf-viewer.js
Labels: verified

#362 Move loadLana to utils
  libs/scripts/scripts.js
  libs/utils/utils.js
Labels: trivial

#366 Lana options hardening
  libs/utils/lana.js
  test/scripts/scripts.test.js
  test/utils/lana.test.js
  test/utils/lanaDefaultOptions.test.js
Labels: trivial

#361 MWPW-121861 - Text block updates to support SEO Long form content
  libs/blocks/quote/quote.css
  libs/blocks/quote/quote.js
  libs/blocks/text/text.css
  libs/blocks/text/text.js
  libs/styles/typography.css
  test/blocks/text/mocks/body.html
Labels: bug, enhancement, verified
