Repository adobecom/milo, pull requests merged in 2022-11, with the labels that each got.

#282 Faas style
  libs/blocks/faas-config/faas-config.js
  libs/blocks/faas/faas.css
  libs/blocks/faas/utils.js
Labels: release, verified

#278 Enhance CaaS author link
  libs/blocks/caas-config/caas-config.js
  libs/blocks/caas/utils.js
  test/blocks/caas-config/caas-config.test.html
Labels: enhancement

#273 MWPW-119010 - Fix card race condition
  libs/blocks/card/card.js
Labels: bug, verified

#283 Eslint plugin for react hooks
  .eslintrc.js
  package-lock.json
  package.json
Labels: trivial

#276 MWPW-109802 - [SEO Structured Data] Breadcrumb
  libs/blocks/gnav/gnav.js
  test/blocks/gnav/gnav.test.js
  test/blocks/gnav/mocks/head-breadcrumb-seo-disabled.html
Labels: release, verified

#285 MWPW-119918 SendToCaaS manifest v3 upgrade
  libs/scripts/scripts.js
  libs/utils/sidekick.js
  libs/utils/utils.js
  tools/send-to-caas/bulk-publish-to-caas.js
  tools/send-to-caas/send-to-caas.js
  tools/send-to-caas/send-utils.js
  tools/sidekick/config.json
Labels: enhancement

#274 Bug fix for Gnav Multi Sign-in
  libs/blocks/gnav/gnav.css
  libs/blocks/gnav/gnav.js
Labels: bug

#293 Update codeql to ignore loc files.
  .github/codeql/codeql-config.yml
  .github/workflows/codeql.yml
Labels: enhancement

#284 fix potential JS error (reading 'firstChild' of null)
  libs/blocks/share/share.js
Labels: bug, trivial

#265 feat(region-picker): inline-dialog variant
  libs/blocks/footer/footer.css
  libs/blocks/footer/footer.js
Labels: enhancement, run-nala

#296 Add ability to turn off martech via metadata
  libs/utils/utils.js
Labels: trivial

#298 Add ability to pass in additional block library locations
  libs/blocks/library-config/library-config.js
Labels: trivial

#299 Use for-of so that blocks are added correctly
  libs/blocks/library-config/library-config.js
Labels: trivial

#301 Load send-to-caas.js from milo directly
  libs/utils/sidekick.js
Labels: trivial

#302 Fix caas tag issue; update fallback tags
  libs/blocks/caas-config/caas-tags.js
  tools/send-to-caas/send-utils.js
Labels: trivial

#290 MWPW-114236 - [SEO Structured Data] Article
  libs/blocks/gnav/gnav.js
  libs/features/richresults.js
  libs/utils/utils.js
  test/utils/mocks/head-rich-results.html
  test/utils/richresults.test.js
Labels: verified

#310 Remove unnecessary white bar for the GNAV
  libs/blocks/gnav/gnav.css
Labels: enhancement, trivial

#311 Remove type module
  package.json
Labels: trivial

#312 Allow SVGs to be used in a large menu.
  libs/blocks/gnav/gnav.js
Labels: trivial

#307 MWPW-109329 - Placeholders
  libs/blocks/library-config/library-config.css
  libs/blocks/library-config/library-config.js
  libs/blocks/library-config/library-utils.js
  libs/blocks/library-config/lists/blocks.js
  libs/blocks/library-config/lists/placeholders.js
  libs/features/placeholders.js
  libs/templates/library/library.css
  libs/utils/utils.js
  test/features/placeholders/placeholders.json
  test/features/placeholders/placeholders.test.js
  test/utils/mocks/body.html
  test/utils/utils.test.js
  tools/sidekick/config.json
Labels: release

#306 MWPW-116985 Multi-column sections
  libs/blocks/icon-block/icon-block.css
  libs/blocks/icon-block/icon-block.js
  libs/blocks/section-metadata/section-metadata.css
  libs/styles/variables.css
  test/blocks/icon-block/icon-block.test.js
  test/blocks/section-metadata/mocks/body.html
  test/blocks/section-metadata/section-meta.test.js
Labels: release, run-nala

#314 Cleanup of utils.js
  libs/blocks/caas-config/caas-config.js
  libs/blocks/faas-config/faas-config.js
  libs/blocks/footer/footer.js
  libs/blocks/fragment/fragment.js
  libs/blocks/gnav/gnav.js
  libs/martech/attributes.js
  libs/utils/utils.js
  test/blocks/caas-config/caas-config.test.html
  test/blocks/caas/mocks/utils.js
  test/utils/getUuid.test.js
  test/utils/utils.test.js
Labels: trivial, run-nala

#313 MWPW-119523 Chart Aria Label Improvement
  libs/blocks/chart/chart.js
  libs/blocks/chart/chartLightTheme.js
Labels: verified

#319 MWPW-120503 - Move PDF Viewer Config
  libs/blocks/pdf-viewer/pdf-viewer.js
  libs/scripts/scripts.js
  libs/utils/utils.js
  test/blocks/pdf-viewer/pdf-viewer.test.js
Labels: trivial

#294 MWPW-117619 Gnav App Launcher
  libs/blocks/gnav/gnav-appLauncher.js
  libs/blocks/gnav/gnav-profile.js
  libs/blocks/gnav/gnav.css
  libs/blocks/gnav/gnav.js
  test/blocks/gnav/gnav-apps.test.js
  test/blocks/gnav/mocks/app-launcher.plain.html
  test/blocks/gnav/mocks/applauncher.html
Labels: verified, run-nala

#325 MWPW-119392 - Text block updates
  .gitignore
  libs/blocks/how-to/how-to.css
  libs/blocks/section-metadata/section-metadata.css
  libs/blocks/text/text.css
  libs/blocks/text/text.js
  libs/styles/typography.css
  libs/utils/decorate.js
  test/blocks/text/mocks/body.html
  test/blocks/text/text.test.js
Labels: enhancement, verified

#326 Removing whitespace for internal campaign id.
  libs/blocks/faas/utils.js
Labels: bug

#323 Fix Marketo form scroll on iOS
  libs/blocks/marketo/marketo.js
  test/blocks/marketo/marketo.test.js
Labels: bug

#330 [MWPW-121449] Search dropdown width between 1200-1400px
  libs/blocks/gnav/gnav.css
Labels: bug, verified

#327 MWPW-121295 - Tabs block authoring bugs
  libs/blocks/tabs/tabs.css
  libs/blocks/tabs/tabs.js
Labels: bug, verified

#329 MWPW-106279 - Add Franklin RUM to Milo
  libs/templates/404/404.js
  libs/utils/samplerum.js
  libs/utils/utils.js
  test/utils/samplerum.test.js
Labels: release

#321 [MWPW-121159] Gnav Search dropdown positioning
  libs/blocks/gnav/gnav-search.js
  libs/blocks/gnav/gnav.css
  libs/blocks/gnav/gnav.js
Labels: bug, verified

#332 MWPW-121560 Correct alignment of Review component on desktop viewport
  libs/blocks/review/review.css
Labels: bug, trivial
