Repository adobecom/milo, pull requests merged in 2022-10, with the labels that each got.

#212 MWPW-115380 Adding pdf viewer block
  libs/blocks/pdf-viewer/pdf-viewer.css
  libs/blocks/pdf-viewer/pdf-viewer.js
  libs/scripts/scripts.js
  libs/utils/utils.js
  test/blocks/pdf-viewer/mocks/body.html
  test/blocks/pdf-viewer/pdf-viewer.test.js
  test/utils/mocks/body.html
  test/utils/utils.test.js
Labels: release

#220 Increase gnav test coverage
  libs/blocks/caas-config/caas-config.js
  libs/blocks/caas/utils.js
  package.json
  test/blocks/caas-config/caas-config.test.html
  test/blocks/caas/mocks/utils.js
  test/blocks/gnav/gnav-search.test.js
  test/blocks/gnav/gnav.test.js
  test/blocks/gnav/missing-gnav.test.js
  test/blocks/gnav/mocks/body.html
  test/blocks/gnav/mocks/head.html
  test/blocks/gnav/mocks/missing-gnav.html
Labels: trivial

#222 MWPW-113517 - Tag pages as Milo
  libs/utils/martech.js
Labels: trivial

#226 MWPW-118492 - Fix youtube performance
  libs/blocks/youtube/youtube.js
  test/blocks/youtube/youtube.test.js
Labels: trivial

#224 Add code scanning
  .github/workflows/codeql.yml
  libs/ui/library/library.js
  libs/utils/lana.js
  tools/translation/lib/msal-browser-2.14.2.js
  tools/translation/lib/msal-browser.js
  tools/translation/lib/msal-browser.js.map
  tools/translation/sharepoint.js
Labels: trivial

#215 MWPW-115387 - Table Of Contents
  libs/blocks/table-of-contents/table-of-contents.css
  libs/blocks/table-of-contents/table-of-contents.js
  libs/utils/utils.js
  test/blocks/table-of-contents/mocks/body.html
  test/blocks/table-of-contents/table-of-contents.test.js
Labels: release, verified

#230 MWPW-117777 Add support for modal videos
  libs/blocks/caas-config/caas-config.js
  libs/blocks/caas/caas.css
  libs/blocks/caas/caas.js
  libs/blocks/caas/utils.js
Labels: release

#232 CaaS Performance Improvement
  libs/blocks/caas-config/caas-config.js
  libs/blocks/caas/utils.js
  test/blocks/caas-config/caas-config.test.html
  test/blocks/caas-config/expectedConfigs/defaultConfig.js
  test/blocks/caas/utils.test.js
Labels: verified, trivial

#236 MWPW-118022 - Improve Modal Accessibility
  libs/blocks/modal/modal.css
  libs/blocks/modal/modal.js
Labels: verified

#238 MWPW-118743 table of contents error on older Safari and Firefox
  libs/blocks/table-of-contents/table-of-contents.js
Labels: bug, verified

#235 Add no-lazy option to CaaS
  libs/blocks/caas/caas.js
Labels: trivial

#227 MWPW-118067 CaaS Bulk Publisher updates
  libs/blocks/caas-config/caas-config.js
  libs/blocks/caas/utils.js
  test/blocks/caas-config/caas-config.test.html
  tools/send-to-caas/bulk-publish-to-caas.js
  tools/send-to-caas/bulkpublish.css
  tools/send-to-caas/bulkpublish.html
  tools/send-to-caas/send-to-caas.js
  tools/send-to-caas/send-utils.js
  tools/sidekick/config.js
Labels: trivial

#225 MWPW-118484 - Rename analytics
  libs/blocks/marquee/marquee.js
  libs/blocks/media/media.js
  libs/martech/attributes.js
  libs/martech/martech.js
  libs/utils/decorate.js
  libs/utils/utils.js
Labels: verified

#240 FaaS test fix.
  libs/blocks/faas/utils.js
  test/blocks/faas/utils.test.js
Labels: trivial

#242 Integrate Janus
  .github/workflows/run-janus.yml
  .github/workflows/run-tests.yaml
Labels: trivial, run-janus

#243 MWPW-109693 - Janus Feature Labels
  .github/workflows/run-janus.yml
Labels: trivial

#250 Review support
  libs/utils/utils.js
Labels: trivial, run-janus, @marquee

#237 MWPW-117986 - Safari Modals Bug Fix
  .vscode/launch.json
  libs/blocks/modal/modal.css
  libs/blocks/modal/modal.js
  test/blocks/modals/mocks/body.html
  test/blocks/modals/modals.test.js
Labels: verified

#258 Nala Rebrand
  .github/workflows/run-nala.yml
Labels: trivial, run-nala

#231 MWPW-116984 - Split Marquee
  libs/blocks/marquee/marquee.css
  test/blocks/marquee/mocks/body.html
Labels: release, verified

#249 MWPW-116276 - Notification Aside
  libs/blocks/aside/aside.css
  libs/blocks/aside/aside.js
  test/blocks/aside/aside.test.js
  test/blocks/aside/mocks/body.html
Labels: release, verified

#256 MWPW-118735: CaaS Config Featured Sort Issue
  libs/blocks/caas/utils.js
  test/blocks/caas-config/caas-config.test.html
  test/blocks/caas-config/expectedConfigs/defaultConfig.js
  test/blocks/caas/utils.test.js
Labels: verified

#260 MWPW-118345 - Tabs
  libs/blocks/tabs/tabs.css
  libs/blocks/tabs/tabs.js
  libs/styles/styles.css
  test/blocks/media/media.test.js
  test/blocks/tabs/mocks/body.html
  test/blocks/tabs/tabs.test.js
Labels: release

#266 MWPW-119185 - Move Martech to PostLCP
  libs/utils/utils.js
Labels: trivial, run-nala

#268 Tabs hot fix: `not block` styles are applied to tab content incorrectly
  libs/blocks/tabs/tabs.css
  libs/blocks/tabs/tabs.js
Labels: bug

#257 Milo Gnav Multi Cloud Sign In
  libs/blocks/gnav/gnav.css
  libs/blocks/gnav/gnav.js
Labels: verified

#267 MWPW-119080 [Core] Languages & Locales
  libs/scripts/scripts.js
Labels: release, verified

#269 Remove section-metadata as a supported block
  libs/blocks/list.js
Labels: trivial

#241 MWPW-117984 - Card Block
  libs/blocks/card/card.css
  libs/blocks/card/card.js
  libs/blocks/section-metadata/section-metadata.js
  libs/deps/caas.css
  libs/styles/styles.css
  libs/utils/utils.js
  test/blocks/card/card.test.js
  test/blocks/card/mocks/default.html
  test/blocks/card/mocks/double-width.html
  test/blocks/card/mocks/half-height.html
  test/blocks/card/mocks/half.html
  test/blocks/card/mocks/product.html
  test/blocks/section-metadata/section-meta.test.js
Labels: verified, run-nala
