Repository adobecom/milo, pull requests merged in 2023-08, with the labels that each got.

#1037 Skms integration
  .github/workflows/skms.yaml
Labels: trivial

#954 MWPW-132883: Add RTL attribute for RTL region's langstore file
  libs/utils/utils.js
  test/utils/utils.test.js
Labels: needs-verification

#912 MWPW-133262: Adds localization functionality to custom filters
  libs/blocks/caas/utils.js
Labels: verified, new-feature

#999 Mep preview
  libs/blocks/fragment/fragment.js
  libs/features/personalization/add-fragment-link-headers.js
  libs/features/personalization/add-preview-to-config.js
  libs/features/personalization/personalization.js
  libs/features/personalization/preview.css
  libs/features/personalization/preview.js
  libs/features/placeholders.js
  libs/utils/utils.js
Labels: verified

#1049 MWPW-134412 Fix sidekick send-to-caas
  libs/utils/utils.js
  tools/send-to-caas/bulkpublisher.html
  tools/send-to-caas/send-to-caas.js
  tools/send-to-caas/send-utils.js
Labels: trivial

#1036 [Global-navigation] Localise breadcrumb links
  libs/blocks/global-navigation/features/breadcrumbs/breadcrumbs.js
  test/blocks/global-navigation/features/breadcrumbs.test.js
Labels: verified

#1063 Personalization cleanup
  .eslintrc.js
  libs/features/personalization/add-preview-to-config.js
  libs/features/personalization/manifest-utils.js
  libs/features/personalization/personalization.js
  libs/features/personalization/preview.js
  libs/martech/martech.js
  libs/utils/utils.js
Labels: trivial

#1064 ES lint fixes for section metadata and actions files
  libs/blocks/section-metadata/section-metadata.js
  libs/utils/action.js
Labels: trivial

#1067 [MWPW-134624] Space out column sections in GNAV full-width dropdown
  libs/blocks/global-navigation/utilities/menu/menu.css
Labels: trivial, run-nala

#1065 MWPW-131747 - Support structured data API for Video SEO
  CODEOWNERS
  libs/features/seotech/README.md
  libs/features/seotech/seotech.js
  libs/utils/utils.js
  test/features/seotech/seotech.test.js
  test/utils/mocks/head-seotech-video.html
  test/utils/utils.test.js
Labels: trivial, run-nala, new-feature

#1070 Rename table to columns-table to avoid conflicting table block's css.
  libs/blocks/columns/columns.css
  libs/blocks/columns/columns.js
Labels: bug, trivial

#1018 MWPW-134057 | Replace image links in place
  libs/utils/utils.js
  test/utils/imageLinks.test.js
  test/utils/mocks/image-links.html
Labels: verified, run-nala

#1082 ost tool overlaps with sidekick.
  libs/blocks/ost/ost.css
Labels: trivial

#1068 [MWPW-134429] Marketo form privacy language width
  libs/blocks/marketo/marketo.css
Labels: verified

#1073 Fragment preview video support
  libs/blocks/marquee/marquee.js
  libs/utils/utils.js
Labels: bug, needs-verification

#1025 [MWPW-133904] Fixing duplicated icon issue and other table issues
  libs/blocks/table-metadata/table-metadata.js
  libs/blocks/table/table.css
  libs/blocks/table/table.js
  libs/features/icons/icons.js
  libs/utils/utils.js
  test/blocks/table/mocks/body.html
  test/blocks/table/table.test.js
Labels: bug, verified, run-nala

#1091 Add gnav-source to gnav lana logs
  libs/blocks/global-navigation/utilities/utilities.js
Labels: trivial

#1066 Mep button on target only
  libs/features/personalization/personalization.js
Labels: needs-verification

#1095 Personalization Tests
  libs/blocks/fragment/fragment.js
  libs/features/personalization/personalization.js
  libs/utils/utils.js
  test/features/personalization/mocks/fragmentReplaced.plain.html
  test/features/personalization/mocks/manifestInsertContentAfter.json
  test/features/personalization/mocks/manifestInsertContentBefore.json
  test/features/personalization/mocks/manifestPageFilterExclude.json
  test/features/personalization/mocks/manifestPageFilterInclude.json
  test/features/personalization/mocks/manifestRemove.json
  test/features/personalization/mocks/manifestReplace.json
  test/features/personalization/mocks/manifestReplaceFragment.json
  test/features/personalization/mocks/manifestReplacePage.json
  test/features/personalization/mocks/manifestUpdateMetadata.json
  test/features/personalization/mocks/manifestUseBlockCode.json
  test/features/personalization/mocks/manifestUseBlockCode2.json
  test/features/personalization/mocks/metadata.html
  test/features/personalization/mocks/myblock/myblock.css
  test/features/personalization/mocks/myblock/myblock.js
  test/features/personalization/mocks/newpromo/newpromo.css
  test/features/personalization/mocks/newpromo/newpromo.js
  test/features/personalization/mocks/personalization.html
  test/features/personalization/mocks/replacePage.plain.html
  test/features/personalization/pageFilter.test.js
  test/features/personalization/personalization.test.js
  test/features/personalization/replacePage.test.js
Labels: trivial

#1026 MWPW-129918: Masonry styles for section metadata
  libs/blocks/section-metadata/section-metadata.js
  test/blocks/section-metadata/mocks/body.html
Labels: needs-verification

#1071 MWPW-134269 - Adding nested fragments based upon the primary product as well as secondary
  libs/blocks/quiz/utils.js
Labels: verified

#1074 MWPW-130312 Adding Consumer Tags to Tag Selector
  libs/blocks/tag-selector/tag-selector.css
  libs/blocks/tag-selector/tag-selector.js
  libs/ui/controls/TagSelectPicker.js
  libs/utils/utils.js
  test/blocks/tag-selector/tag-selector.test.js
  test/blocks/tag-selector/taxonomy.js
Labels: verified, new-feature

#1092 Relax global navigation sign profile dropdown in check
  libs/blocks/global-navigation/global-navigation.js
  test/blocks/global-navigation/global-navigation.test.js
Labels: trivial

#1094 [MWPW-134805] Remove borders when more sections are used
  libs/blocks/global-navigation/global-navigation.css
  libs/blocks/global-navigation/global-navigation.js
  test/blocks/global-navigation/keyboard/mocks/global-nav-mobile.html
  test/blocks/global-navigation/keyboard/mocks/global-nav.html
Labels: trivial

#1096 Merch Table: Fixing the double border and border on cell's text.
  libs/blocks/table/table.css
Labels: bug, trivial

#971 Added additional options for media block
  libs/blocks/media/media.css
  libs/blocks/media/media.js
  libs/blocks/z-pattern/z-pattern.js
  libs/styles/typography.css
  test/blocks/media/media.test.js
  test/blocks/media/mocks/body.html
Labels: run-nala, needs-verification

#1088 [MWPW-131690] Update horizontal rule styles within text blocks
  libs/blocks/text/text.css
Labels: needs-verification

#1101 MWPW-134968 - [Blog2Milo] Broken links on Homepage
  libs/blocks/article-feed/article-helpers.js
  libs/blocks/featured-article/featured-article.js
  libs/blocks/recommended-articles/recommended-articles.js
  libs/utils/helpers.js
  test/blocks/bulk-publish/performance.test.js
Labels: bug, verified, new-feature, needs-verification

#913 MWPW-133172 - Add Floodgate option in Caas Configurator and Pass floodgate param to Caas
  libs/blocks/caas-config/caas-config.js
  libs/blocks/caas/utils.js
  test/blocks/caas-config/caas-config.test.html
  test/blocks/caas-config/expectedConfigs/defaultConfig.js
  test/blocks/caas/mocks/utils.js
  test/blocks/caas/utils.test.js
Labels: new-feature, needs-verification

#1110 MWPW-134889 Icon block link style update
  libs/blocks/icon-block/icon-block.css
Labels: bug, verified

#727 MWPW-129730 - Word wrap function
  libs/deps/budoux-index-ja.min.js
  libs/features/japanese-word-wrap.js
  libs/utils/utils.js
  test/features/japanese-word-wrap/japanese-word-wrap.test.js
  test/features/japanese-word-wrap/mocks/body.html
  test/features/japanese-word-wrap/mocks/head-disabled.html
  test/features/japanese-word-wrap/mocks/head.html
Labels: trivial, run-nala

#1103 MWPW-128325: authoring dialog changes for hiding ctas using tags
  libs/blocks/caas-config/caas-config.js
  libs/blocks/caas/utils.js
  test/blocks/caas-config/caas-config.test.html
  test/blocks/caas-config/expectedConfigs/defaultConfig.js
  test/blocks/caas/utils.test.js
Labels: verified

#1112 MWPW-134131 - Fixing issue when there are more than one rule with same number of grouping
  libs/blocks/quiz/utils.js
Labels: verified

#1106 Play video on hover
  libs/blocks/aside/aside.js
  libs/blocks/figure/figure.js
  libs/blocks/marquee/marquee.js
  libs/blocks/media/media.js
  libs/blocks/video/video.js
  libs/utils/decorate.js
  test/blocks/video/mocks/body.html
  test/blocks/video/video.test.js
Labels: new-feature, needs-verification

#1113 [MWPW-134861] Remove loading of App Launcher
  libs/blocks/global-navigation/features/appLauncher/appLauncher.js
  libs/blocks/global-navigation/global-navigation.js
Labels: trivial

#1104 MWPW-131211 Personalization Entitlement Support
  libs/blocks/global-navigation/utilities/getUserEntitlements.js
  libs/features/personalization/personalization.js
  libs/martech/martech.js
  libs/utils/utils.js
  test/blocks/global-navigation/mocks/subscriptionsAll.js
  test/blocks/global-navigation/utilities/getUserEntitlements.test.js
Labels: new-feature, needs-verification

#1080 MWPW-133055 Sticky bottom section functionality enhancement
  libs/blocks/section-metadata/section-metadata.css
  libs/blocks/section-metadata/section-metadata.js
  libs/blocks/section-metadata/sticky-section.js
  test/blocks/section-metadata/mocks/body.html
  test/blocks/section-metadata/section-meta.test.js
Labels: verified, run-nala, new-feature

#1119 Run dispatch workflow only for adobecom/milo
  .github/workflows/dispatch.yml
Labels: trivial

#1114 MWPW-135191 Hide caas link that has a query param
  .eslintrc-code-compatibility.js
  libs/blocks/caas-config/caas-config.js
  libs/blocks/caas/caas.css
  libs/blocks/faas-config/faas-config.js
  libs/hooks/useHover.js
Labels: trivial

#1116 MWPW-134481 - Add section xxs spacing variant
  libs/blocks/section-metadata/section-metadata.css
Labels: bug, trivial

#1122 MWPW-131211 Clear entitlements from localStorage on logout
  libs/blocks/global-navigation/features/profile/dropdown.js
  libs/features/personalization/personalization.js
Labels: trivial

#1117 MWPW-135198 - Optimizes quiz-results DOM handling
  libs/blocks/quiz-results/quiz-results.js
Labels: verified

#979 MWPW-129917 - Milo Aside block enhancements
  libs/blocks/aside/aside.css
  libs/blocks/aside/aside.js
  libs/blocks/section-metadata/section-metadata.css
  libs/blocks/video/video.js
  libs/styles/variables.css
  libs/utils/decorate.js
  test/blocks/aside/aside.test.js
  test/blocks/aside/mocks/body.html
Labels: verified, run-nala, new-feature

#1120 MWPW-133733: add promo support to OST links
  libs/blocks/merch/merch.css
  libs/blocks/ost/ost.js
  test/blocks/ost/ost.test.js
Labels: verified

#1127 Do not lana log IMS timeouts for the global nav
  libs/blocks/global-navigation/global-navigation.js
Labels: trivial

#1124 fix video loading issue in figure block
  libs/blocks/figure/figure.js
Labels: trivial

#1129 MWPW-135276 Fix video selector
  libs/blocks/marquee/marquee.js
  libs/blocks/video/video.js
  libs/utils/decorate.js
Labels: bug, trivial, run-nala

#1130 add optional chaining operator to get hash value for hoverplay
  libs/utils/decorate.js
Labels: trivial

#1115 MWPW-133754 - Support structured data API for SEO
  libs/features/seotech/README.md
  libs/features/seotech/seotech.js
  libs/utils/utils.js
  test/features/seotech/seotech.test.js
Labels: trivial, run-nala

#1132 interlinks in marquee anchor block fixed
  libs/blocks/marquee-anchors/marquee-anchors.js
Labels: trivial

#1134 fix issue of video not loading in figure block
  libs/blocks/figure/figure.js
Labels: needs-verification

#1131 Mwpw 135206 geo routing popup is displayed on top of the commerce iframe modal.
  libs/blocks/modal/modal.css
Labels: trivial

#1135 MWPW-134677 Fix aside mobile spacing
  libs/blocks/aside/aside.css
Labels: bug, verified

#1118 MWPW-129922 - Consonant Actions Blocks
  libs/blocks/action-item/action-item.css
  libs/blocks/action-item/action-item.js
  libs/blocks/action-scroller/action-scroller.css
  libs/blocks/action-scroller/action-scroller.js
  libs/blocks/icon-block/icon-block.css
  test/blocks/action-item/action-item.test.js
  test/blocks/action-item/mocks/body.html
  test/blocks/action-scroller/action-scroller.test.js
  test/blocks/action-scroller/mocks/body.html
Labels: verified, new-feature

#1142 MWPW-135413 Support multiple link features
  libs/blocks/fragment/fragment.js
  libs/utils/utils.js
Labels: trivial

#1141 [MWPW-129920] Marquee large updates - new height variants
  libs/blocks/marquee/marquee.css
Labels: verified

#1148 MWPW-135447 Add useDotHtml in config to force .html links
  libs/utils/utils.js
  test/utils/mocks/body.html
  test/utils/mocks/useDotHtml.html
  test/utils/utils.test.js
Labels: high-impact, verified

#1126 Modify Hide Georouting Cookie
  libs/features/georoutingv2/georoutingv2.js
  test/features/georoutingv2/georoutingv2.test.js
Labels: trivial

#1151 Action Blocks added to config for consumers
  libs/utils/utils.js
Labels: bug, verified, trivial

#1145 MWPW-130835 search osi in OST
  libs/blocks/ost/ost.js
Labels: trivial

#1156 Only run when MEP or MEP param is enabled
  libs/features/personalization/add-preview-to-config.js
  libs/utils/utils.js
Labels: trivial

#1159 Fix failing tests
  libs/utils/utils.js
  test/utils/richresults.test.js
Labels: trivial

#1160 MWPW-131688: FG support for other drives
  tools/floodgate/js/utils.js
Labels: trivial

#1165 MWPW-134560 Add Bulk Un-publish and Delete to the Milo bulk-publish tool
  libs/blocks/bulk-publish/bulk-publish-utils.js
  libs/blocks/bulk-publish/bulk-publish.js
  test/blocks/bulk-publish/bulk-publish-utils.test.js
Labels: trivial

#1164 Removes temporary CSS code for Card-Logo from CAAS Configurator
  libs/blocks/caas/caas.css
Labels: trivial

#1157 Add support for Google Yolo
  libs/blocks/global-navigation/global-navigation.css
  libs/features/google-login.js
  libs/scripts/delayed.js
  libs/utils/utils.js
  test/features/google-login/google-login.test.js
  test/features/google-login/mocks/google-login.html
  test/scripts/delayed.test.js
Labels: verified, new-feature

#1111 [MWPW-134658] Localize meta links
  libs/utils/utils.js
Labels: high-impact, verified

#1128 MWPW-132277 - Breakpoint content for Quiz Results
  libs/blocks/quiz-results/quiz-results.css
Labels: verified

#1169 Remove extra spaces and new lines from tracking attribute values
  libs/martech/attributes.js
Labels: bug, trivial, run-nala

#1174 MWPW-134726: Delete functionality in Floodgate
  tools/floodgate/index.html
  tools/floodgate/js/floodgate.js
  tools/floodgate/js/ui.js
Labels: trivial

#1175 [MWPW-135717] Ensure dropdowns are visible on Safari
  libs/blocks/global-navigation/global-navigation.css
Labels: trivial

#1153 MWPW-135125 Quiz button fix
  libs/blocks/quiz/quiz.css
Labels: verified

#1177 MWPW-135603: FG Status API payload update
  tools/floodgate/js/floodgate.js
Labels: trivial

#1178 Marquee: Make sure there's actually text before loading handleFocalPoint
  libs/blocks/marquee/marquee.js
Labels: trivial

#1180 Applying intersectionobserver for faas.
  libs/blocks/faas/faas.js
  test/blocks/faas/faas.test.js
Labels: run-nala, @faas, needs-verification

#1172 MWPW-135595 Marketo - Remove focus scroll on desktop
  libs/blocks/marketo/marketo.js
Labels: verified, run-nala, @marketo

#1181 [MWPW-135765] Visibility of Gnav absolute elements in Safari
  libs/blocks/global-navigation/features/profile/dropdown.css
  libs/blocks/global-navigation/global-navigation.css
Labels: verified, trivial

#1183 MWPW-135787 Hide faas link before it's autoblocked
  libs/blocks/faas/faas.css
Labels: trivial

#1163 MWPW-134632 Bulk Index
  libs/blocks/bulk-publish/bulk-publish-utils.js
  libs/blocks/bulk-publish/bulk-publish.css
  libs/blocks/bulk-publish/bulk-publish.js
  test/blocks/bulk-publish/bulk-publish-utils.test.js
Labels: verified, needs-verification

#1108 Merch cards creation
  CODEOWNERS
  libs/blocks/card/card.js
  libs/blocks/card/cardUtils.js
  libs/blocks/merch-card/merch-card.css
  libs/blocks/merch-card/merch-card.js
  test/blocks/merch-card/merch-card.test.js
  test/blocks/merch-card/mocks/plans-card.html
  test/blocks/merch-card/mocks/segment-card.html
  test/blocks/merch-card/mocks/special-offers.html
Labels: verified, new-feature

#1186 MWPW-134986 - Rendering nested fragments in the order of products
  libs/blocks/quiz/utils.js
Labels: verified

#1171 [MWPW-135217] Use decorateLinks before decorating Gnav
  libs/blocks/global-footer/global-footer.js
  libs/blocks/global-navigation/base.css
  libs/blocks/global-navigation/features/breadcrumbs/breadcrumbs.js
  libs/blocks/global-navigation/global-navigation.js
  libs/blocks/global-navigation/utilities/menu/menu.js
  libs/blocks/global-navigation/utilities/utilities.js
  test/blocks/global-navigation/features/breadcrumbs.test.js
  test/blocks/global-navigation/global-navigation.test.js
  test/blocks/global-navigation/mocks/global-navigation-long.plain.js
  test/blocks/global-navigation/mocks/global-navigation-only-brand-no-image.plain.js
  test/blocks/global-navigation/mocks/global-navigation-only-brand.plain.js
  test/blocks/global-navigation/mocks/global-navigation-only-non-svg-brand.plain.js
  test/blocks/global-navigation/mocks/global-navigation.plain.js
  test/blocks/global-navigation/mocks/large-menu.plain.html
  test/blocks/global-navigation/test-utilities.js
  test/blocks/global-navigation/utilities/utilities.test.js
Labels: verified, run-nala

#1182 Use constants for milo events
  libs/blocks/carousel/carousel.js
  libs/blocks/table/table.js
  libs/blocks/tabs/tabs.js
  libs/features/personalization/preview.js
  libs/utils/utils.js
  test/blocks/table/table.test.js
Labels: trivial, run-nala

#1193 Revert "[MWPW-135217] Use decorateLinks before decorating Gnav"
  libs/blocks/global-footer/global-footer.js
  libs/blocks/global-navigation/base.css
  libs/blocks/global-navigation/features/breadcrumbs/breadcrumbs.js
  libs/blocks/global-navigation/global-navigation.js
  libs/blocks/global-navigation/utilities/menu/menu.js
  libs/blocks/global-navigation/utilities/utilities.js
  test/blocks/global-navigation/features/breadcrumbs.test.js
  test/blocks/global-navigation/global-navigation.test.js
  test/blocks/global-navigation/mocks/global-navigation-long.plain.js
  test/blocks/global-navigation/mocks/global-navigation-only-brand-no-image.plain.js
  test/blocks/global-navigation/mocks/global-navigation-only-brand.plain.js
  test/blocks/global-navigation/mocks/global-navigation-only-non-svg-brand.plain.js
  test/blocks/global-navigation/mocks/global-navigation.plain.js
  test/blocks/global-navigation/mocks/large-menu.plain.html
  test/blocks/global-navigation/test-utilities.js
  test/blocks/global-navigation/utilities/utilities.test.js
Labels: trivial

#1192 MWPW-134823 - QUIZ - Fix Acessibility warning
  libs/blocks/quiz/quizoption.js
Labels: verified

#1161 MWPW-134907 - decorate plain text in text block
  libs/blocks/text/text.css
  libs/utils/decorate.js
Labels: bug, trivial, run-nala

#1152 Media block - added variants (merch, bio, static links) to support a product icon stack in the content column
  libs/blocks/media/media.css
  libs/blocks/media/media.js
  libs/utils/decorate.js
  test/blocks/media/media.test.js
  test/blocks/media/mocks/body.html
Labels: verified, run-nala

#1190 MWPW-135645: remove image label from mdast
  tools/loc/rollout.js
Labels: trivial

#1173 MWPW-134576: Fixing update fragments in CC folder
  tools/loc/config.js
  tools/loc/sharepoint.js
Labels: trivial, run-nala

#1185 [Blog Migration] Featured Article LCP help
  libs/blocks/article-feed/article-feed.js
  libs/blocks/featured-article/featured-article.css
  libs/blocks/featured-article/featured-article.js
Labels: trivial
