Repository adobecom/milo, pull requests merged in 2023-04, with the labels that each got.

#618 MWPW-128867: fixes number of Results per page being ignored
  libs/blocks/caas-config/caas-config.js
  libs/blocks/caas/utils.js
  test/blocks/caas-config/caas-config.test.html
  test/blocks/caas-config/expectedConfigs/defaultConfig.js
  test/blocks/caas/mocks/utils.js
  test/blocks/caas/utils.test.js
  tools/caas-import/parseCaasConfig.js
Labels: verified

#616 MWPW-126637: add support for checkout ctx params
  libs/blocks/merch/merch.js
  test/blocks/merch/merch.test.js
  test/blocks/merch/mocks/body.html
  test/blocks/merch/mocks/head-metadata.html
Labels: verified

#611 MWPW-109800: Add video-metadata block
  libs/blocks/video-metadata/video-metadata.css
  libs/blocks/video-metadata/video-metadata.js
  test/blocks/video-metadata/expected/video-object-adobe.json
  test/blocks/video-metadata/expected/video-object-broadcast-event.json
  test/blocks/video-metadata/expected/video-object-clip.json
  test/blocks/video-metadata/expected/video-object.json
  test/blocks/video-metadata/mocks/body-adobe.html
  test/blocks/video-metadata/mocks/body-bad.html
  test/blocks/video-metadata/mocks/body-broadcast-event.html
  test/blocks/video-metadata/mocks/body-clip.html
  test/blocks/video-metadata/mocks/body.html
  test/blocks/video-metadata/video-metadata.test.js
Labels: enhancement, verified

#617 MWPW-129009: Video Loop Enhancement
  libs/blocks/video/video.js
  test/blocks/video/mocks/body.html
  test/blocks/video/video.test.js
Labels: verified, run-nala

#609 MWPW-128373 - Adding a confirmation modal(pop-up) for fg promote step.
  tools/floodgate/css/floodgate.css
  tools/floodgate/index.html
  tools/floodgate/js/floodgate.js
Labels: enhancement

#627 Aside Notification Centered Block Update
  libs/blocks/aside/aside.css
  libs/blocks/aside/aside.js
Labels: enhancement, verified

#637 stabilize unit test for disable auto bloking
  test/utils/utils.test.js
Labels: trivial

#649 Add faas form id class
  libs/blocks/faas/utils.js
Labels: verified

#621 Improve Codecov config for unexpected coverage changes
  codecov.yaml
Labels: trivial

#620 Tabs block update/enhancements
  libs/blocks/tabs/tabs.css
  libs/blocks/tabs/tabs.js
  libs/features/georoutingv2/georoutingv2.css
  test/blocks/tabs/mocks/body.html
  test/blocks/tabs/tabs.test.js
Labels: bug, enhancement

#644 Added stage env
  libs/blocks/faas/utils.js
  test/blocks/faas/utils.test.js
Labels: trivial

#654 Tabs bug: minor style color format fix
  libs/blocks/tabs/tabs.css
Labels: bug, trivial

#655 MWPW-129891 - checkout button build fix
  libs/blocks/merch/merch.js
Labels: trivial

#639 MWPW-126640 Offer Selector Tool in Milo
  libs/blocks/ost/README.md
  libs/blocks/ost/ost.js
  libs/utils/utils.js
  tools/sidekick/config.json
Labels: enhancement, commerce

#656 Faas env
  libs/blocks/faas/utils.js
  test/blocks/faas/utils.test.js
Labels: trivial

#559 Bulk preview and publish tool
  libs/blocks/caas/utils.js
  libs/blocks/review/components/helixReview/HelixReview.js
  libs/blocks/review/utils/localStorageUtils.js
  libs/blocks/utils/utils.js
  test/blocks/review/utils/localStorageUtils.test.js
  test/tools/bulk-publish/performance.test.js
  test/tools/bulk-publish/utils.test.js
  tools/bulk-publish/css/bulk.css
  tools/bulk-publish/img/arrow-group.svg
  tools/bulk-publish/img/dots.svg
  tools/bulk-publish/img/emphasis-shape.svg
  tools/bulk-publish/img/mesh.svg
  tools/bulk-publish/index.html
  tools/bulk-publish/js/bulk.js
  tools/bulk-publish/js/utils.js
  tools/send-to-caas/bulk-publish-to-caas.js
  tools/send-to-caas/send-to-caas.js
  tools/send-to-caas/send-utils.js
  tools/utils/utils.js
Labels: release

#658 Card block authoring compatablity
  libs/blocks/card/card.js
  test/blocks/card/card.test.js
  test/blocks/card/mocks/two-up-cards.html
Labels: enhancement

#601 Bring in Global Navigation progress into 'main' branch
  libs/blocks/global-footer/adchoices-small.svg
  libs/blocks/global-footer/footer-social.svg
  libs/blocks/global-footer/global-footer.css
  libs/blocks/global-footer/global-footer.js
  libs/blocks/global-navigation/blocks/appLauncher/appLauncher.js
  libs/blocks/global-navigation/blocks/navDropdown/dropdown.css
  libs/blocks/global-navigation/blocks/navDropdown/dropdown.js
  libs/blocks/global-navigation/blocks/profile/dropdown.css
  libs/blocks/global-navigation/blocks/profile/dropdown.js
  libs/blocks/global-navigation/blocks/search/gnav-search.css
  libs/blocks/global-navigation/blocks/search/gnav-search.js
  libs/blocks/global-navigation/global-navigation.css
  libs/blocks/global-navigation/global-navigation.js
  libs/blocks/global-navigation/utilities/getUserEntitlements.js
  libs/blocks/global-navigation/utilities/getUserEventHistory.js
  libs/blocks/global-navigation/utilities/utilities.js
  libs/styles/styles.css
  libs/utils/utils.js
  package.json
Labels: enhancement

#668 Correctly parse profile data for global-navigation
  libs/blocks/global-navigation/global-navigation.js
Labels: trivial

#657 Text Block - typography token override bug
  libs/blocks/media/media.js
  libs/blocks/text/text.css
  libs/blocks/text/text.js
  libs/styles/typography.css
  libs/utils/decorate.js
  test/blocks/marquee/mocks/body.html
Labels: bug

#667 Improve unit test output
  test/blocks/author-header/mocks/body.html
  test/blocks/card/mocks/default.html
  test/blocks/card/mocks/double-width.html
  test/blocks/card/mocks/half-height.html
  test/blocks/card/mocks/half.html
  test/blocks/card/mocks/product.html
  test/blocks/card/mocks/two-up-cards.html
  test/blocks/carousel/mocks/body.html
  test/blocks/featured-article/mocks/voices-of-our-community.html
  test/blocks/figure/figure.test.js
  test/blocks/figure/mocks/body.html
  test/blocks/gnav/mocks/app-launcher.plain.html
  test/blocks/how-to/how-to.test.js
  test/blocks/how-to/mocks/body.html
  test/blocks/how-to/mocks/mock.png
  test/blocks/marquee/mocks/body.html
  test/blocks/marquee/mocks/video.html
  test/blocks/read-more/mocks/body-with-recommended.html
  test/blocks/read-more/mocks/body.html
  test/blocks/recommended-articles/mocks/blog-milo.html
  test/blocks/recommended-articles/mocks/voices-of-our-community.html
  test/blocks/section-metadata/mocks/body.html
  test/blocks/table-of-contents/mocks/body.html
  web-test-runner.config.mjs
Labels: trivial

#670 con-button styles have bad defaults
  libs/styles/typography.css
Labels: bug, verified
