Repository adobecom/milo, pull requests merged in 2023-09, with the labels that each got.

#1158 Mwpw 135324 continue button is not seen in iphone
  .stylelintrc.json
  libs/styles/iframe.css
Labels: trivial, run-nala

#1194 Merge initial styles into one file
  libs/styles/styles.css
  libs/styles/typography.css
  libs/styles/variables.css
  test/blocks/global-navigation/keyboard/keyboard.test.js
  test/blocks/merch/mocks/head.html
Labels: high-impact, trivial

#1184 [MWPW-135263] Adding variant to figure block
  libs/blocks/figure/figure.css
Labels: trivial

#1200 MWPW-135442 - Fixing the issue of NOT operator when the order of selection is changed
  libs/blocks/quiz/utils.js
Labels: verified

#1207 ost version changed in milo
  libs/blocks/ost/ost.js
Labels: trivial

#1208 MWPW-135903: If nestedObject[fragKey] exists, append to it instead of replacing
  libs/blocks/quiz/utils.js
Labels: verified

#1216 MWPW-135983 Support caas tags delimited by ;
  tools/send-to-caas/send-utils.js
Labels: trivial

#1218 Personalization: make all manifest paths relative
  libs/features/personalization/manifest-utils.js
Labels: trivial

#890 MWPW-130163 - Version History
  libs/blocks/version-history/img/download.svg
  libs/blocks/version-history/img/help.svg
  libs/blocks/version-history/index.js
  libs/blocks/version-history/state.js
  libs/blocks/version-history/version-history.css
  libs/blocks/version-history/version-history.js
  libs/deps/msal-browser-2.34.0.js
  libs/tools/sharepoint/README.md
  libs/tools/sharepoint/login.js
  libs/tools/sharepoint/msal.js
  libs/tools/sharepoint/state.js
  libs/tools/sharepoint/version.js
  libs/utils/service-config.js
  libs/utils/service-config.md
  test/utils/mocks/.milo/config.json
  test/utils/service-config.test.js
  tools/sidekick/config.json
Labels: new-feature, needs-verification

#1211 [MWPW-135217] Use correct approach for decorateLinks in Gnav
  libs/blocks/global-footer/global-footer.js
  libs/blocks/global-navigation/base.css
  libs/blocks/global-navigation/features/breadcrumbs/breadcrumbs.js
  libs/blocks/global-navigation/global-navigation.js
  libs/blocks/global-navigation/utilities/menu/menu.js
  libs/blocks/global-navigation/utilities/utilities.js
  test/blocks/global-navigation/features/breadcrumbs.test.js
  test/blocks/global-navigation/global-navigation-with-html-extension.test.html
  test/blocks/global-navigation/global-navigation.test.js
  test/blocks/global-navigation/mocks/global-navigation-long.plain.js
  test/blocks/global-navigation/mocks/global-navigation-only-brand-no-image.plain.js
  test/blocks/global-navigation/mocks/global-navigation-only-brand.plain.js
  test/blocks/global-navigation/mocks/global-navigation-only-non-svg-brand.plain.js
  test/blocks/global-navigation/mocks/global-navigation.plain.js
  test/blocks/global-navigation/mocks/large-menu.plain.html
  test/blocks/global-navigation/test-utilities.js
  test/blocks/global-navigation/utilities/utilities.test.js
Labels: verified, run-nala

#1213 Add a gnav PR template
  .github/gnav.md
Labels: trivial

#1197 [Blog to Milo] MWPW-135804 Add taxonomyRoot config
  libs/blocks/article-feed/article-helpers.js
  libs/blocks/featured-article/featured-article.js
  libs/blocks/recommended-articles/recommended-articles.js
  libs/scripts/scripts.js
  test/blocks/article-header/article-header.test.js
  test/blocks/recommended-articles/mocks/body.html
  test/blocks/recommended-articles/recommended-articles.test.js
  test/blocks/tags/tags.test.js
Labels: high-impact, verified

#1212 Mwpw 135924 fallback css property added to iframe
  libs/styles/iframe.css
Labels: trivial

#1081 Anchor links
  libs/styles/styles.css
  libs/utils/utils.js
  test/utils/utils.test.js
Labels: verified

#1191 MWPW-135814 Add underline in static link
  libs/blocks/section-metadata/section-metadata.css
Labels: trivial, run-nala

#1224 [MWPW-136078] Ensure breadcrumbs based on URL are built
  libs/blocks/global-navigation/global-navigation.js
Labels: verified, trivial

#1233 [MWPW-135932] Define Gnav custom PR template
  .github/PULL_REQUEST_TEMPLATE/gnav.md
Labels: trivial

#1219 MWPW-135296 - Quiz css and related markup cleanup
  libs/blocks/quiz/quiz.css
  libs/blocks/quiz/quiz.js
  libs/blocks/quiz/quizcontainer.js
  libs/blocks/quiz/quizoption.js
  libs/blocks/quiz/stepIndicator.js
  libs/deps/caas-uar.css
Labels: verified, run-nala

#1196 Merch Card block - UAR enhancement
  libs/blocks/merch-card/merch-card.css
  libs/blocks/merch-card/merch-card.js
  libs/utils/decorate.js
  test/blocks/merch-card/merch-card.test.js
  test/blocks/merch-card/mocks/uar-card.html
Labels: verified, uar

#1229 MWPW-135977 Marketo Checkbox Error Icon
  libs/blocks/marketo/marketo.css
Labels: verified, run-nala, @marketo

#1238 Update static links style in section metadata to support modal links
  libs/blocks/section-metadata/section-metadata.css
Labels: trivial

#1246 Fix hidden IG and /reel/ links
  libs/blocks/instagram/instagram.js
Labels: bug, verified

#1234 fix(MWPW-136057):background scrolls when modal is open fixed
  libs/blocks/modal/modal.css
  libs/blocks/modal/modal.js
Labels: trivial, run-nala

#1249 New Merge strategy
  tools/loc/rollout.js
Labels: trivial

#1239 MWPW-135823: handling asset copy and reference for FG
  tools/floodgate/index.html
  tools/floodgate/js/floodgate.js
  tools/floodgate/js/utils.js
  tools/loc/fragments.js
Labels: trivial

#1248 Add analytics tracking attributes for columns and merch
  libs/blocks/columns/columns.js
  libs/blocks/merch/merch.js
  libs/martech/attributes.js
Labels: verified

#1243 MWPW-125774 - Quiz block accessibility
  libs/blocks/quiz/quiz.css
  libs/blocks/quiz/quiz.js
  libs/blocks/quiz/quizoption.js
Labels: needs-verification

#1215 MWPW-135674 Desktop Commerce Modal Style
  libs/blocks/modal/modal.css
  libs/styles/iframe.css
Labels: run-nala, needs-verification

#1236 MWPW-131760: fixes max-height limiting number of entries
  libs/blocks/caas-config/caas-config.css
Labels: bug, needs-verification, caas-configurator

#1251 MWPW-136311: Fixes merge issue with docx having duplicate blocks
  tools/loc/rollout.js
Labels: trivial

#1227 MWPW-136001 fix for safari
  libs/blocks/card/cardUtils.js
Labels: trivial

#1254 MWPW-133119 - Adding Unit Tests for Quiz (Utils.js)
  libs/blocks/quiz/utils.js
  test/blocks/quiz/mocks/index.html
  test/blocks/quiz/mocks/mock-states.js
  test/blocks/quiz/mocks/questions.json
  test/blocks/quiz/mocks/result-resources.json
  test/blocks/quiz/mocks/results.json
  test/blocks/quiz/mocks/strings.json
  test/blocks/quiz/utils.test.js
Labels: verified

#1220 MWPW-135950 Add "commerce" library to Milo deps, update commerce, merch and OST blocks
  libs/blocks/commerce/commerce.js
  libs/blocks/merch/merch.js
  libs/blocks/ost/ost.js
  libs/deps/commerce.js
  test/blocks/commerce/commerce.test.js
  test/blocks/commerce/mocks/body.html
  test/blocks/merch/merch.test.js
  test/blocks/merch/mocks/body.html
  test/blocks/merch/mocks/fetch.js
  test/blocks/merch/mocks/ims.js
  test/blocks/merch/mocks/literals.json
  test/blocks/merch/mocks/offers.json
  test/blocks/ost/mocks/ost-utils.js
  test/blocks/ost/mocks/wcs-artifacts-mock.json
  test/blocks/ost/ost.test.html.js
  test/blocks/ost/ost.test.js
Labels: verified

#1260 Quiz tests
  libs/blocks/quiz/quiz.js
  libs/blocks/quiz/quizoption.js
  libs/blocks/quiz/utils.js
  test/blocks/quiz/quiz.test.js
  test/blocks/quiz/stepIndicator.test.js
Labels: verified

#1241 Mwpw-135989 - Special Offers Merch Card styling fixes
  libs/blocks/merch-card/merch-card.css
Labels: bug, commerce, needs-verification

#1261 [Blog Migration] Article feed update to work with metadata
  libs/blocks/article-feed/article-feed.js
Labels: verified

#1222 MWPW-135967: card container to support fragments
  libs/blocks/card/card.css
  libs/blocks/card/card.js
  libs/blocks/card/cardUtils.js
  libs/blocks/merch-card/merch-card.js
  test/blocks/merch-card/merch-card.test.js
  test/blocks/merch-card/mocks/special-offers.html
Labels: verified, commerce

#1210 Changed accordion analytics tracking
  libs/blocks/accordion/accordion.js
  test/blocks/accordion/accordion.test.js
  test/blocks/accordion/mocks/body.html
Labels: run-nala, needs-verification

#1259 Section metadata grid-width styles for mobile and tablet viewports
  libs/blocks/icon-block/icon-block.css
  libs/blocks/section-metadata/section-metadata.css
  libs/blocks/text/text.css
Labels: verified

#1247 mwpw-135988 - segment card styling fixes
  libs/blocks/merch-card/merch-card.css
Labels: bug, commerce, needs-verification

#1271 turn on impression tracking for accordion block
  libs/blocks/accordion/accordion.js
Labels: trivial, run-nala

#1250 fix(MWPW-133207):Intermittent screen freeze, backdrop does not close when modal is closed.
  libs/blocks/modal/modal.js
Labels: trivial

#1272 MWPW-136505 - Aside notification content alignment
  libs/blocks/aside/aside.css
Labels: bug, verified, trivial

#1242 MWPW-135676 Inline Fragments
  libs/blocks/fragment/fragment.js
  libs/utils/utils.js
  test/blocks/fragment/fragment.test.js
  test/blocks/fragment/mocks/body.html
  test/blocks/fragment/mocks/fragments/col-content.plain.html
  test/blocks/fragment/mocks/fragments/marquee-content.plain.html
Labels: high-impact, verified, run-nala

#1276 Add accordion to donotinline
  libs/utils/utils.js
Labels: trivial

#1277 Revert "fix(MWPW-133207):Intermittent screen freeze, backdrop does no…
  libs/blocks/modal/modal.js
Labels: bug, verified, run-nala, @modal

#1275 MWPW-135675 Fix marquee video
  libs/blocks/marquee/marquee.js
Labels: bug, verified, run-nala

#1230 MWPW-135782 | Removing min height from mobile Asides
  libs/blocks/aside/aside.css
  libs/blocks/aside/aside.js
Labels: verified, run-nala

#1268 MWPW-136171 - Icon block consistant variant convention from "fullwidth" to "full-width"
  libs/blocks/icon-block/icon-block.css
  libs/blocks/icon-block/icon-block.js
  libs/styles/styles.css
  test/blocks/icon-block/mocks/body.html
Labels: bug, trivial, run-nala

#1280 MWPW-136619: Update CODEOWNERS for quiz and quiz-results
  CODEOWNERS
Labels: trivial

#1252 MWPW-136094 Fix links authored using placeholders
  libs/blocks/global-footer/global-footer.js
  libs/blocks/global-navigation/global-navigation.js
  libs/blocks/global-navigation/utilities/menu/menu.js
  libs/features/placeholders.js
  libs/utils/utils.js
  test/features/placeholders/placeholders.json
  test/features/placeholders/placeholders.test.js
Labels: bug, verified, run-nala, needs-verification

#1281 MWPW-136624 | Update run-nala.yml
  .github/workflows/run-nala.yml
Labels: trivial, run-nala

#1284 Manifest data fix
  libs/features/personalization/personalization.js
  libs/martech/martech.js
Labels: trivial

#1262 MWPW-135990 fix styles for merch cards
  libs/blocks/merch-card/merch-card.css
  libs/blocks/merch-card/merch-card.js
  test/blocks/merch-card/merch-card.test.js
  test/blocks/merch-card/mocks/plans-card.html
  test/blocks/merch-card/mocks/special-offers.html
Labels: bug, commerce, needs-verification

#1257 MWPW-130838 Remove offer id from chekcout link
  libs/blocks/ost/ost.js
Labels: trivial

#1287 mwpw-136633: safeguard scrolling
  libs/utils/utils.js
Labels: verified

#1285 Restrict changes done for MWPW-136057 to commerce modal
  libs/blocks/modal/modal.css
  libs/blocks/modal/modal.js
Labels: trivial, run-nala, needs-verification

#1289 PR 1264 quiz.js feedback refactor
  libs/blocks/quiz/quiz.js
Labels: verified

#1282 [9/20] MWPW-136568: Table - Mobile issue with new milo events
  libs/blocks/table-metadata/table-metadata.js
  libs/blocks/table/table.css
  libs/blocks/table/table.js
  libs/utils/utils.js
  test/blocks/table/table.test.js
Labels: bug, run-nala, needs-verification

#1299 MWPW-136688 Added quiz and quiz results to MILO_BLOCKS
  libs/utils/utils.js
Labels: trivial

#1298 PR 1264 quiz_results.js feedback
  libs/blocks/quiz-results/quiz-results.js
  test/blocks/quiz-results/quiz-results.test.js
Labels: verified

#1279 [MWPW-136611] Replace default experience name with IMS client ID
  libs/blocks/global-navigation/utilities/utilities.js
  test/blocks/global-navigation/utilities/utilities.test.js
Labels: verified, trivial

#1209 MWPW-127223 | Adding video play on image with link
  libs/blocks/aside/aside.css
  libs/blocks/card/card.js
  libs/blocks/card/cardUtils.js
  libs/blocks/figure/figure.js
  libs/blocks/marquee/marquee.js
  libs/styles/consonant-play-button.css
  libs/utils/image-video-link.js
  libs/utils/utils.js
  test/blocks/card/card.test.js
  test/blocks/card/mocks/half-height.html
  test/blocks/card/mocks/two-up-cards.html
  test/blocks/figure/figure.test.js
  test/blocks/figure/mocks/body.html
  test/utils/imageLinks.test.js
  test/utils/mocks/image-links.html
Labels: run-nala, new-feature, needs-verification

#1292 [MWPW-135557] - Font size tweak to text links in Large Split Marquees
  libs/blocks/marquee/marquee.css
Labels: verified, trivial, run-nala, @marquee

#1283 [marquee-anchors] enhancement - author-proof input, include link attributes.
  libs/blocks/marquee-anchors/marquee-anchors.js
  test/blocks/marquee-anchors/mocks/body.html
Labels: bug, trivial, run-nala

#1162 [MWPW-131763] Variable Aside backgrounds based on media breakpoints
  libs/blocks/aside/aside.css
  libs/blocks/aside/aside.js
  libs/blocks/marquee/marquee.css
  libs/blocks/marquee/marquee.js
  libs/styles/styles.css
  libs/utils/decorate.js
  test/blocks/aside/mocks/body.html
Labels: verified, run-nala

#1235 MWPW-136802: CaaS Configurator UI controls update
  libs/blocks/caas-config/caas-config.css
  libs/blocks/caas-config/caas-config.js
  libs/blocks/caas/caas.css
  libs/ui/controls/formControls.js
Labels: bug, trivial, run-nala

#1311 MWPW-136515 - Icon Block: fix image distortion in smaller viewports
  libs/blocks/icon-block/icon-block.css
Labels: bug, trivial

#1313 Mock metadata block
  libs/blocks/library-config/lists/blocks.js
Labels: trivial

#1340 Skms integration "hello" 'hello' \hello
  .github/workflows/skms.yaml
Labels: trivial

#1265 MWPW-133052 | New Aside variation - Promobar
  libs/blocks/aside/aside.css
  libs/blocks/aside/aside.js
  libs/blocks/section-metadata/sticky-section.js
  libs/utils/decorate.js
  test/blocks/aside/aside.test.js
  test/blocks/aside/mocks/body.html
Labels: verified, run-nala, new-feature

#1310 [MWPW-136612] Gnav/Footer menus mobile accordion tracking
  libs/blocks/global-footer/global-footer.js
  libs/blocks/global-navigation/utilities/menu/menu.js
  test/blocks/global-navigation/global-navigation.test.js
Labels: verified

#1328 Exclude locales from automated breadcrumb URLs
  libs/blocks/global-navigation/features/breadcrumbs/breadcrumbs.js
  test/blocks/global-navigation/ch_de/breadcrumbs-from-file.test.html
Labels: verified, run-nala

#1330 MWPW-136802: CaaS Configurator UI controls update (Part II)
  libs/blocks/caas-config/caas-config.css
  libs/blocks/caas-config/caas-config.js
  libs/blocks/caas/caas.css
Labels: trivial, caas-configurator

#1341 Fix table filter
  libs/blocks/table/table.js
  test/blocks/table/mocks/body.html
  test/blocks/table/table.test.js
Labels: bug, verified, run-nala

#1350 Update Adobe red references
  libs/blocks/article-header/adobe-logo.svg
  libs/blocks/gnav/gnav.css
  libs/blocks/gnav/gnav.js
Labels: trivial

#1329 PR 1264 utils.js feedback refactor
  libs/blocks/quiz/utils.js
Labels: verified

#1349 MWPW-135730 - Results card-list alignment correction
  libs/blocks/quiz-results/quiz-results.css
Labels: verified

#1348 MWPW-136982: fix invalid selector
  libs/features/personalization/personalization.js
  test/features/personalization/mocks/manifestInvalid.json
  test/features/personalization/personalization.test.js
Labels: trivial

#1356 MWPW-115213 - Addressing review comments
  libs/blocks/quiz-results/quiz-results.css
  libs/blocks/quiz/quiz.js
Labels: verified

#1357 MWPW-136232 Localize faas destination url
  libs/blocks/faas/utils.js
  test/blocks/faas/utils.test.js
Labels: verified, run-nala, @faas

#1353 safeguard milo modals from invalid query selectors
  libs/blocks/modal/modal.js
  test/blocks/modals/modals.test.js
Labels: needs-verification

#1264 MWPW-115213 - Uber App Recommender a.k.a. Quiz
  CODEOWNERS
  libs/blocks/quiz-results/quiz-results.css
  libs/blocks/quiz-results/quiz-results.js
  libs/blocks/quiz/quiz.css
  libs/blocks/quiz/quiz.js
  libs/blocks/quiz/quizcontainer.js
  libs/blocks/quiz/quizoption.js
  libs/blocks/quiz/stepIndicator.js
  libs/blocks/quiz/utils.js
  libs/utils/utils.js
  test/blocks/quiz-results/mocks/body.html
  test/blocks/quiz-results/mocks/fragments/basic-frag.plain.html
  test/blocks/quiz-results/mocks/fragments/nested-frag.plain.html
  test/blocks/quiz-results/mocks/quiz-results.mock-data.js
  test/blocks/quiz-results/quiz-results.test.js
  test/blocks/quiz/mocks/index.html
  test/blocks/quiz/mocks/mock-states.js
  test/blocks/quiz/mocks/questions.json
  test/blocks/quiz/mocks/quiz.html
  test/blocks/quiz/mocks/result-resources.json
  test/blocks/quiz/mocks/results.json
  test/blocks/quiz/mocks/strings.json
  test/blocks/quiz/quiz.test.js
  test/blocks/quiz/utils.test.js
  test/helpers/createHTML.js
Labels: verified, run-nala, new-feature

#1364 MWPW-137162: [LocUI] Temporarily remove exclude path for localization
  tools/sidekick/config.json
Labels: bug

#1359 MWPW-135816 enable ability to get forced VAT exclusive prices
  libs/blocks/merch/merch.js
  libs/blocks/ost/ost.js
  test/blocks/merch/merch.test.js
  test/blocks/merch/mocks/body.html
  test/blocks/ost/ost.test.js
Labels: commerce, needs-verification

#1368 MWPW-137171: Temp Fix for Sidekick
  tools/sidekick/config.json
Labels: trivial

#1365 Add support for sections
  libs/features/personalization/personalization.js
Labels: trivial

#1367 MWPW-136429 Transform Image alt links
  libs/utils/utils.js
Labels: trivial

#1363 UAR - quiz-card-list update
  libs/blocks/quiz-results/quiz-results.css
Labels: verified, run-nala

#1371 Revert "MWPW-136429 Transform Image alt links"
  libs/utils/utils.js
Labels: bug, needs-verification

#1291 [MWPW-136442] Marketo field adjustment with grid
  libs/blocks/marketo/marketo.css
Labels: verified

#1373 MWPW-120357 - Make alt text links relative
  libs/utils/utils.js
Labels: trivial, run-nala

#1303 MWPW-133600 - Floodgate for loading Caas Card Collections
  libs/blocks/caas-config/caas-config.js
  libs/blocks/caas/caas.js
  libs/blocks/caas/utils.js
  test/blocks/caas/mocks/utils.js
  test/blocks/caas/utils.test.js
  tools/send-to-caas/send-utils.js
Labels: high-impact, new-feature, needs-verification

#1376 meaningless comment
  libs/blocks/locui/locui.js
  test/blocks/locui/locui.test.js
Labels: trivial
