Repository adobecom/milo, pull requests merged in 2023-06, with the labels that each got.

#803 Unit tests - surface external requests
  web-test-runner.config.mjs
Labels: trivial

#815 Surface unit test errors and point to a solution source
  package.json
  web-test-runner.config.mjs
Labels: verified

#817 Update CODEOWNERS
  CODEOWNERS
Labels: trivial

#775 MWPW-129575 - Authorable Tooltip
  libs/blocks/article-header/article-header.js
  libs/features/icons.js
  libs/features/icons/icons.css
  libs/features/icons/icons.js
  libs/styles/styles.css
  libs/utils/utils.js
  test/features/icons/icons.test.js
  test/features/icons/mocks/body.html
Labels: verified, new-feature

#827 Update label email groups
  .github/workflows/email-release.yaml
Labels: do not merge

#829 MWPW-132152 - Gist block
  libs/blocks/gist/gist.css
  libs/blocks/gist/gist.js
  test/blocks/gist/gist.test.js
  test/blocks/gist/mocks/body.html
Labels: trivial, new-feature

#828 Bulk preview/publish: increase throttling
  libs/blocks/bulk-publish/bulk-publish-utils.js
Labels: trivial

#822 Remove `overflow: visible` from img to avoid undesired behaviour
  libs/styles/typography.css
Labels: trivial

#812 MWPW-131063-Fix for bold link not transformed to button
  libs/utils/decorate.js
  test/blocks/media/media.test.js
  test/blocks/media/mocks/body.html
Labels: verified

#834 MWPW-132176 .html send to caas toggle
  tools/send-to-caas/bulk-publish-to-caas.js
  tools/send-to-caas/bulkpublisher.html
  tools/send-to-caas/send-utils.js
Labels: trivial

#753 MWPW-129094 Iframe Block Classes and Height Issue
  libs/blocks/iframe/iframe.js
  libs/styles/iframe.css
  test/blocks/iframe/iframe.test.js
Labels: verified

#800 Adding the current locale code to the local storage key
  libs/blocks/quiz/utils.js
Labels: trivial

#790 MWPW-129909-inline variation of icon block
  libs/blocks/icon-block/icon-block.css
  libs/blocks/icon-block/icon-block.js
  test/blocks/icon-block/icon-block.test.js
  test/blocks/icon-block/mocks/body.html
Labels: verified, new-feature

#784 MWPW-125482 Fixing line length and function defined before used eslint issue
  libs/utils/utils.js
Labels: verified

#801 MWPW-130725 Marketo Configurator
  libs/blocks/marketo-config/context.js
  libs/blocks/marketo-config/marketo-config.css
  libs/blocks/marketo-config/marketo-config.js
  libs/blocks/marketo/marketo.css
  libs/blocks/marketo/marketo.js
  libs/scripts/scripts.js
  libs/ui/controls/Accordion.js
  libs/ui/controls/CopyBtn.js
  libs/ui/controls/copyBtn.css
  libs/ui/controls/formControls.js
  test/blocks/marketo-config/marketo-config.test.js
  test/blocks/marketo-config/mocks/body.html
  test/blocks/marketo-config/mocks/options.json
  test/blocks/marketo/marketo.test.js
  test/blocks/marketo/mocks/body.html
Labels: verified, new-feature

#813 Configure Jarvis chat for mobile / desktop
  libs/scripts/delayed.js
  test/scripts/delayed.test.js
Labels: verified, new-feature

#854 Remove for..of, await in loop eslint warnings
  .eslintrc.js
  libs/blocks/article-feed/article-feed.js
  libs/blocks/bulk-publish/bulk-publish-utils.js
  libs/blocks/global-footer/global-footer.js
  libs/blocks/global-navigation/global-navigation.js
  libs/blocks/global-navigation/utilities/menu/menu.js
  libs/blocks/gnav/gnav-contextual-search.js
  libs/blocks/preflight/panels/seo.js
  libs/utils/tree.js
  libs/utils/utils.js
  test/helpers/selectors.js
  tools/floodgate/js/copy.js
  tools/floodgate/js/promote.js
  tools/loc/rollout.js
  tools/loc/sharepoint.js
  tools/send-to-caas/bulk-publish-to-caas.js
  tools/send-to-caas/send-utils.js
Labels: trivial

#856 Also support cardDescription in caas metadata
  tools/send-to-caas/send-utils.js
Labels: trivial

#857 Update caas to support cardTitle too
  tools/send-to-caas/send-utils.js
Labels: trivial

#853 [MWPW-132468] Legal Block Content Not rendered in italics - Bug Fix
  libs/blocks/text/text.css
Labels: bug, verified

#850 Fix lang attribute and accented character issue for text on georouting modal
  libs/features/georoutingv2/georoutingv2.css
  libs/features/georoutingv2/georoutingv2.js
Labels: verified

#858 [MWPW-132406] Long text links are not seen getting wrapped in Linkfarm
  libs/blocks/text/text.css
Labels: bug

#819 MWPW-132078: hide ctas by id (feature parity with caas on dexter)
  libs/blocks/caas-config/caas-config.js
  libs/blocks/caas/utils.js
  test/blocks/caas-config/caas-config.test.html
  test/blocks/caas-config/expectedConfigs/defaultConfig.js
  test/blocks/caas/mocks/utils.js
  test/blocks/caas/utils.test.js
Labels: verified

#864 Table block
  libs/blocks/table/README.md
  libs/blocks/table/table.css
Labels: trivial

#861 [MWPW-132198] Make S/M marquee media, buttons match Consonant designs at mobile breakpoint
  libs/blocks/marquee/marquee.css
Labels: run-nala, @marquee

#832 Global footer keyboard navigation
  libs/blocks/global-navigation/utilities/keyboard/index.js
  libs/blocks/global-navigation/utilities/keyboard/mainNav.js
  libs/blocks/global-navigation/utilities/keyboard/mobilePopup.js
  libs/blocks/global-navigation/utilities/keyboard/popup.js
  libs/blocks/global-navigation/utilities/keyboard/utils.js
  test/blocks/global-navigation/keyboard/keyboard.test.js
  test/blocks/global-navigation/keyboard/mocks/adobe-logo.svg
  test/blocks/global-navigation/keyboard/mocks/global-nav-mobile.html
  test/blocks/global-navigation/keyboard/mocks/global-nav.html
Labels: trivial

#810 MWPW-123036 [Milo] Custom filter panel options
  libs/blocks/caas-config/caas-config.css
  libs/blocks/caas-config/caas-config.js
  libs/blocks/caas/utils.js
  libs/ui/controls/MultiField.js
  test/blocks/caas-config/caas-config.test.html
  test/blocks/caas/caas.test.html
  test/blocks/caas/mocks/utils.js
Labels: verified

#873 [UAR] Card refinement
  libs/blocks/quiz/quiz.css
Labels: verified

#867 MWPW-131421 - Marketo Form Style Changes
  libs/blocks/marketo/marketo.css
Labels: verified

#855 MWPW-129907 [Blog Migration] Allow Custom Article Feed
  libs/blocks/article-feed/article-feed.js
  test/blocks/article-header/article-header.test.js
  test/blocks/article-header/mocks/body-invalid.html
  test/blocks/article-header/mocks/placeholders.json
Labels: trivial

#860 [MWPW-118520] Menuless gnav
  .github/pull_request_template.md
  libs/blocks/global-navigation/global-navigation.js
Labels: verified

#771 MWPW-127984: Make OST locale- and metadata-aware
  libs/blocks/merch/merch.js
  libs/blocks/ost/README.md
  libs/blocks/ost/ost.js
  test/blocks/merch/merch.test.js
  test/blocks/ost/mocks/ost-utils.js
  test/blocks/ost/ost.test.html
  test/blocks/ost/ost.test.html.js
  test/blocks/ost/ost.test.js
  tools/sidekick/config.json
Labels: verified

#875 MWPW-128375: Ignore list for FG
  tools/floodgate/js/config.js
  tools/floodgate/js/utils.js
Labels: verified

#811 MWPW-131815 - Override text alignment in icon blocks on rtl pages
  libs/blocks/icon-block/icon-block.css
Labels: verified, trivial

#866 Mwpw 132409 - Optional Headings for Link Farms
  libs/blocks/text/text.css
  libs/blocks/text/text.js
  test/blocks/text/mocks/body.html
  test/blocks/text/text.test.js
Labels: verified

#780 MWPW-131645 Linking images in milo via alt text
  libs/utils/utils.js
  test/utils/imageLinks.test.js
  test/utils/mocks/image-links.html
  test/utils/utils.test.js
Labels: verified, new-feature

#869 Marquee block design updates and ESLint issues resolved
  libs/blocks/marquee/marquee.css
  libs/blocks/marquee/marquee.js
  libs/styles/typography.css
  libs/utils/decorate.js
Labels: verified

#884 MWPW-129654: Add 'needs-verification' to PR label check
  .github/workflows/enforce-labels.yml
Labels: needs-verification

#877 MWPW-132977: Support global navigation link group modifier 'blue'
  libs/blocks/global-navigation/base.css
  libs/blocks/global-navigation/global-navigation.css
  libs/blocks/global-navigation/utilities/menu/menu.js
  test/blocks/global-navigation/global-navigation.test.js
  test/blocks/global-navigation/mocks/global-navigation.plain.js
Labels: verified

#892 Fix flaky utils twitter unit test
  test/helpers/generalHelpers.js
  test/utils/mocks/body.html
  test/utils/mocks/head.html
  test/utils/utils.test.js
Labels: trivial

#888 MWPW-131109: Faas safari issues
  libs/blocks/faas/faas.css
Labels: verified, trivial

#870 MWPW-129660 Override Marketo Form Params
  libs/blocks/marketo/marketo.js
  test/blocks/marketo/marketo.test.js
  test/blocks/marketo/mocks/body.html
Labels: verified, trivial

#898 MWPW-133219: Hide default content before the preact app loads
  libs/blocks/quiz/quiz.css
Labels: verified

#883 Update pdf embed API url
  libs/blocks/pdf-viewer/pdf-viewer.js
  test/blocks/pdf-viewer/mocks/body.html
  test/utils/mocks/body.html
Labels: trivial

#874 Personalization
  CODEOWNERS
  README.md
  experiments/test001/blocks/quote/quote.css
  experiments/test001/blocks/quote/quote.js
  libs/blocks/fragment-personalization/fragment-personalization.css
  libs/blocks/fragment-personalization/fragment-personalization.js
  libs/blocks/fragment/fragment.js
  libs/blocks/global-navigation/global-navigation.js
  libs/blocks/gnav/gnav.js
  libs/blocks/how-to/how-to.css
  libs/blocks/library-config/library-config.css
  libs/blocks/library-config/library-config.js
  libs/blocks/library-config/lists/personalization.js
  libs/deps/martech.main.standard.min.js
  libs/features/personalization/manifest-utils.js
  libs/features/personalization/personalization.js
  libs/martech/martech.js
  libs/scripts/scripts.js
  libs/styles/styles.css
  libs/utils/utils.js
  test/blocks/review/components/helixReview/HelixReview.test.js
  test/features/personalization/personalization.test.js
  test/helpers/mockFetch.js
Labels: high-impact, verified

#673 MWPW-127384 Ability to anchor/focus background image at certain point…
  libs/blocks/marquee/marquee.js
  libs/blocks/section-metadata/section-metadata.js
  test/blocks/section-metadata/mocks/body.html
  test/blocks/section-metadata/section-meta.test.js
Labels: run-nala, @marquee, new-feature

#909 Personalization martech fix: also check for window._satellite presence
  libs/utils/utils.js
Labels: trivial
