Repository adobecom/milo, pull requests merged in 2023-01, with the labels that each got.

#345 MWPW-116104 - New Window Links
  libs/features/links.js
  libs/features/nofollow.js
  libs/scripts/scripts.js
  libs/utils/utils.js
  test/blocks/links/links.test.js
  test/blocks/links/mocks/body.html
  test/blocks/links/mocks/links.json
  test/blocks/nofollow/mocks/nofollow.json
  test/blocks/nofollow/nofollow.test.js
  test/utils/utils.test.js
Labels: release, verified

#341 MWPW-120524 Append .html postfix for local links when hosting page ends with .html
  libs/utils/utils.js
  test/utils/htmlpostfix.test.html
Labels: trivial

#367 MWPW-120941 Add Modal Focus Trap
  libs/blocks/modal/modal.js
  test/blocks/modals/mocks/milo.plain.html
  test/blocks/modals/mocks/paragraph.plain.html
  test/blocks/modals/mocks/title.plain.html
  test/blocks/modals/modals.test.js
Labels: verified

#334 MWPW-121476 call interlinks
  libs/utils/utils.js
Labels: run-nala

#370 MWPW-122331 Add JP Font
  libs/styles/variables.css
Labels: verified

#364 MWPW-116989 - Consonant card horizontal block
  libs/blocks/card-horizontal/card-horizontal.css
  libs/blocks/card-horizontal/card-horizontal.js
  libs/styles/variables.css
  test/blocks/card-horizontal/card-horizontal.test.js
  test/blocks/card-horizontal/mocks/body.html
Labels: enhancement, verified

#373 FaaS import config update when the faas link is clicked in the word doc.
  libs/blocks/faas-config/faas-config.js
  libs/blocks/faas/utils.js
Labels: verified

#382 MWPW-122993 Increase pdf viewer specificity to avoid initial load issue
  libs/blocks/pdf-viewer/pdf-viewer.css
Labels: trivial

#374 MWPW-120863 - Modal Button Focus Bug
  libs/blocks/modal/modal.js
Labels: verified

#386 Testing for building faas by state.complete (faas config from rendere…
  test/blocks/faas/utils.test.js
Labels: trivial

#371 [MWPW-121124] Updates to split marquee
  libs/blocks/marquee/marquee.css
  libs/blocks/marquee/marquee.js
  libs/styles/styles.css
  libs/styles/variables.css
  test/blocks/marquee/marquee.test.js
  test/blocks/marquee/mocks/body.html
Labels: bug, enhancement, verified

#379 MWPW-121471 Layout in section metadata
  libs/blocks/section-metadata/section-metadata.css
  libs/blocks/section-metadata/section-metadata.js
  test/blocks/section-metadata/mocks/body.html
  test/blocks/section-metadata/section-meta.test.js
Labels: enhancement, verified

#387 MWPW-123765 - Fix link styles in icon block body
  libs/blocks/icon-block/icon-block.css
Labels: bug, verified

#394 added the pulling in of missing secrets for Run-Nala
  .github/workflows/run-nala.yml
Labels: trivial, run-nala

#393 MWPW-120782 - Fix Chart Color Order
  libs/blocks/chart/chart.js
  test/blocks/chart/chart.test.js
Labels: verified

#375 MWPW-109331 - Carousel
  libs/blocks/carousel/carousel.css
  libs/blocks/carousel/carousel.js
  libs/blocks/carousel/img/arrow.svg
  libs/blocks/carousel/img/close.svg
  libs/blocks/carousel/img/expand.svg
  libs/styles/styles.css
  libs/styles/typography.css
  libs/utils/utils.js
  test/blocks/carousel/carousel.test.js
  test/blocks/carousel/mocks/body.html
Labels: release, verified

#407 MWPW-124632 [Milo] No character count in the review component text box
  libs/blocks/review/components/review/Comments.js
  libs/blocks/review/review.css
Labels: verified

#411 MWPW-124584
  libs/blocks/gnav/gnav.js
Labels: trivial

#409 MWPW-124845 - Start Project button missing for only some projects
  tools/loc/ui.js
Labels: bug, trivial

#415 MWPW-123893 - Review Schema
  libs/blocks/review/review.js
Labels: verified

#401 MWPW-123745 SVG alt text
  libs/utils/utils.js
Labels: verified

#403 MWPW-120020 - Event-driven Modals
  libs/blocks/card/card.js
  libs/blocks/fragment/fragment.js
  libs/blocks/modal-metadata/modal-metadata.css
  libs/blocks/modal-metadata/modal-metadata.js
  libs/blocks/modal/modal.js
  libs/blocks/section-metadata/README.md
  libs/blocks/section-metadata/section-metadata.js
  libs/scripts/scripts.js
  libs/utils/utils.js
  test/blocks/fragment/fragment.test.js
  test/blocks/modals/modals.test.js
  test/blocks/section-metadata/section-meta.test.js
Labels: release, verified

#383 MWPW-123760
  libs/utils/utils.js
Labels: verified

#420 MWPW-124906 - Embed links inside text block
  libs/blocks/instagram/instagram.js
  libs/blocks/slideshare/slideshare.js
  libs/blocks/tiktok/tiktok.js
  libs/blocks/twitter/twitter.js
  libs/blocks/vimeo/vimeo.js
  libs/blocks/youtube/youtube.js
  libs/utils/utils.js
Labels: verified

#419 MWPW-124846 - Loc Support fragments at any level in hierarchy
  tools/loc/fragments.js
Labels: trivial

#422 MWPW-125032 Brand Block: using an SVG link for logo breaks gnav rendering
  libs/blocks/gnav/gnav.js
Labels: verified, trivial

#412 MWPW-120802 - Diagonal Labels for Chart
  libs/blocks/chart/chart.js
  test/blocks/chart/chart.test.js
Labels: release, verified

#427 Add utils test coverage
  test/utils/mocks/body.html
  test/utils/utils.test.js
Labels: trivial
