Repository adobecom/milo, pull requests merged in 2023-07, with the labels that each got.

#904 MWPW-131607: Extend feds.entitlements with the offer ID
  libs/blocks/global-navigation/utilities/getUserEntitlements.js
  test/blocks/global-navigation/mocks/subscriptionsAll.js
  test/blocks/global-navigation/utilities/getUserEntitlements.test.js
Labels: trivial

#911 Fix global navigation tests
  libs/blocks/global-navigation/global-navigation.js
  test/blocks/global-navigation/test-utilities.js
Labels: needs-verification

#893 [MWPW-132444] Save up nav space when content is overflowing
  libs/blocks/global-navigation/base.css
  libs/blocks/global-navigation/global-navigation.css
  libs/blocks/global-navigation/global-navigation.js
  libs/blocks/global-navigation/utilities/utilities.js
  test/blocks/global-navigation/global-navigation.test.js
  test/blocks/global-navigation/mocks/global-navigation-long.plain.js
  test/blocks/global-navigation/test-utilities.js
Labels: verified

#920 Skip personalization test for now
  test/features/personalization/personalization.test.js
Labels: trivial

#919 MWPW-133443: Fetch gnav placeholders from correct location
  libs/blocks/global-navigation/utilities/utilities.js
  test/blocks/global-navigation/utilities/utilities.test.js
Labels: trivial

#882 [MWPW-132443] Gnav updates for Blog migration
  libs/blocks/global-footer/global-footer.js
  libs/blocks/global-navigation/global-navigation.js
  libs/blocks/global-navigation/utilities/menu/menu.js
  libs/blocks/global-navigation/utilities/utilities.js
  test/blocks/global-navigation/global-navigation.test.js
  test/blocks/global-navigation/mocks/global-navigation-only-brand-no-image.plain.js
  test/blocks/global-navigation/mocks/subscriptionsAll.js
  test/blocks/global-navigation/test-utilities.js
  test/blocks/global-navigation/utilities/getUserEntitlements.test.js
  test/blocks/global-navigation/utilities/utilities.test.js
Labels: verified

#895 MWPW-127110 - Quiz footer fragment based on string.json
  libs/blocks/quiz/quiz.js
Labels: verified

#921 MWPW-133441: Merch: custom elements deps for Safari
  libs/blocks/merch/merch.js
  libs/deps/custom-elements.js
Labels: verified

#916 Use locale from getConfig (gnav)
  libs/blocks/gnav/gnav.js
Labels: trivial

#926 [MWPW-132443] Visible brand label if no image exists
  libs/blocks/global-navigation/global-navigation.css
  test/blocks/global-navigation/global-navigation.test.js
Labels: trivial

#924 MWPW-133465: Localise gnav mega menus
  libs/blocks/global-navigation/utilities/menu/menu.js
Labels: verified

#908 MWPW-131420 Fixing Configurator copy button
  CODEOWNERS
  libs/blocks/faas-config/faas-config.js
  libs/blocks/faas/utils.js
  libs/blocks/marketo-config/context.js
  libs/blocks/marketo-config/marketo-config.js
  libs/ui/controls/CopyBtn.js
  libs/ui/controls/copyBtn.css
  test/blocks/marketo-config/marketo-config.test.js
Labels: bug, verified, trivial, Ready To Merge

#899 marquee-anchors - new block
  libs/blocks/library-config/lists/icons.js
  libs/blocks/marquee-anchors/marquee-anchors.css
  libs/blocks/marquee-anchors/marquee-anchors.js
  libs/utils/utils.js
  test/blocks/marquee-anchors/marquee-anchors.test.js
  test/blocks/marquee-anchors/mocks/body.html
Labels: new-feature, needs-verification

#932 MWPW-133653 Extra checks for decorateHTML
  libs/utils/utils.js
Labels: trivial

#934 Target Personalization: Correctly pass in utils
  libs/martech/martech.js
Labels: trivial

#905 [MWPW-132503] Honor heading tag level as authored on Accordion block titles
  libs/blocks/accordion/accordion.css
  libs/blocks/accordion/accordion.js
  test/blocks/accordion/accordion.test.js
  test/blocks/accordion/mocks/body.html
Labels: trivial

#936 Do not show current breadcrumb page by default
  libs/blocks/global-navigation/features/breadcrumbs/breadcrumbs.js
  test/blocks/global-navigation/features/breadcrumbs.test.js
  test/blocks/global-navigation/features/breadcrumbsFromFile.test.html
Labels: needs-verification

#933 Ensure multiple places can load IMS from the milo utils
  libs/blocks/global-navigation/global-navigation.js
  libs/blocks/gnav/gnav.js
  libs/utils/utils.js
  test/blocks/global-navigation/global-navigation.test.js
Labels: high-impact, verified

#903 MWPW-132987 Adjusting Modal Fragment Widths
  libs/blocks/modal/modal.css
Labels: verified

#915 Use only language subtag for html lang attribute
  libs/scripts/scripts.js
  libs/utils/utils.js
Labels: trivial

#938 Chore: Sort locales entries
  libs/scripts/scripts.js
Labels: trivial

#896 MWPW-125937 Tag Selector
  CODEOWNERS
  libs/blocks/tag-selector/tag-selector.css
  libs/blocks/tag-selector/tag-selector.js
  libs/ui/controls/TagSelectPicker.js
  libs/ui/controls/TagSelector.js
  libs/ui/controls/tagSelector.css
  test/blocks/tag-selector/tag-selector.test.js
  test/helpers/selectors.js
  tools/sidekick/config.json
Labels: verified, new-feature

#931 MWPW-132150 - Strikethrough prices text style fix
  libs/blocks/merch/merch.css
Labels: verified

#949 MWPW-133738: Use a different comparison to process question values
  libs/blocks/quiz/utils.js
Labels: trivial

#939 [MWPW-133469]Interlink fix for languages that don't have word boundary
  libs/features/interlinks.js
  libs/scripts/delayed.js
  test/features/interlinks/interlinks.test.js
  test/features/interlinks/mocks/body.html
  test/features/interlinks/mocks/body_en.html
  test/features/interlinks/mocks/body_fr.html
  test/features/interlinks/mocks/body_ko.html
  test/features/interlinks/mocks/empty.json
  test/features/interlinks/mocks/interlinks.plain.html
  test/features/interlinks/mocks/keywords.json
  test/features/interlinks/mocks/keywords_lang.json
  test/features/interlinks/mocks/maxlinks.plain.html
  test/features/interlinks/mocks/nomain.plain.html
  test/features/interlinks/mocks/nomatches.json
Labels: verified

#849 Table block
  libs/blocks/table-metadata/table-metadata.css
  libs/blocks/table-metadata/table-metadata.js
  libs/blocks/table/README.md
  libs/blocks/table/table.css
  libs/blocks/table/table.js
  libs/features/icons/icons.js
  libs/ui/img/chevron-wide-black.svg
  libs/ui/img/collapse2.svg
  libs/ui/img/expand2.svg
  libs/utils/utils.js
  package-lock.json
  test/blocks/table/mocks/body.html
  test/blocks/table/table.test.js
Labels: new-feature, needs-verification

#945 Use locale from getConfig (caas)
  libs/blocks/caas/utils.js
  test/blocks/caas/utils.test.js
Labels: verified

#940 [MWPW-133763] Long breadcrumbs UI
  libs/blocks/global-navigation/features/breadcrumbs/breadcrumbs.js
  libs/blocks/global-navigation/global-navigation.css
  test/blocks/global-navigation/features/breadcrumbs-from-file.test.html
Labels: verified

#957 Reverse the package.json
  package-lock.json
Labels: trivial

#955 Add title-append feature
  libs/features/title-append/README.md
  libs/features/title-append/title-append.js
  libs/utils/utils.js
  test/features/title-append/mocks/head-social.html
  test/features/title-append/mocks/head.html
  test/features/title-append/title-append.test.js
  test/utils/mocks/head-title-append.html
  test/utils/utils.test.js
Labels: trivial

#956 MWPW-133942 Consumer can change martech urls
  libs/martech/martech.js
Labels: trivial

#948 MWPW-133297 Reduce Marketo Form TBT
  libs/blocks/marketo/marketo.css
  libs/blocks/marketo/marketo.js
  test/blocks/marketo/marketo.test.html
  test/blocks/marketo/marketo.test.js
  test/blocks/marketo/mocks/marketo-utils.js
Labels: verified, trivial

#942 MWPW-129914 Rich Media Accordion (Editorial Carousel)
  libs/blocks/accordion/accordion.css
  libs/blocks/accordion/accordion.js
  test/blocks/accordion/editorial-accordion.test.js
  test/blocks/accordion/mocks/editorial-body.html
Labels: new-feature, needs-verification

#935 MWPW-133412 Pass correct country/lang to filters
  libs/blocks/caas/utils.js
  test/blocks/caas/utils.test.js
  web-test-runner.config.mjs
Labels: trivial

#969 Skms integration
  .github/workflows/skms.yaml
Labels: verified

#960 Minor Bug fix for Table block
  libs/blocks/table/table.css
  libs/blocks/table/table.js
Labels: bug, trivial

#972 Skms integration
  .github/workflows/skms.yaml
Labels: trivial

#962 MWPW-133268 - Rename uar-results to quiz-results
  libs/blocks/quiz-results/quiz-results.css
  libs/blocks/quiz-results/quiz-results.js
  test/blocks/quiz-results/mocks/body.html
  test/blocks/quiz-results/mocks/fragments/basic-frag.plain.html
  test/blocks/quiz-results/mocks/fragments/nested-frag.plain.html
  test/blocks/quiz-results/mocks/quiz-results.mock-data.js
  test/blocks/quiz-results/quiz-results.test.js
Labels: verified

#974 Skms integration
  .github/workflows/skms.yaml
Labels: trivial

#975 Skms integration
  .github/workflows/skms.yaml
Labels: trivial

#976 Skms integration
  .github/workflows/skms.yaml
Labels: trivial

#977 Skms integration
  .github/workflows/skms.yaml
Labels: trivial

#978 Skms integration
  .github/workflows/skms.yaml
Labels: trivial

#980 Skms integration
  .github/workflows/skms.yaml
Labels: trivial

#981 Skms integration
  .github/workflows/skms.yaml
Labels: trivial

#982 Skms integration
  .github/workflows/skms.yaml
Labels: trivial

#967 Don't run UT or label checks if you edit PR title/body
  .github/workflows/enforce-labels.yml
  .github/workflows/run-tests.yaml
Labels: trivial

#963 Use "content-language" metadata for html lang attribute
  libs/utils/utils.js
Labels: trivial

#970 Update CONTRIBUTING.md
  CONTRIBUTING.md
Labels: trivial

#951 WPW-132896 image margin rtl issue
  libs/blocks/figure/figure.css
Labels: trivial

#987 Autofix subset of eslint errors
  build/htm-preact-debug.js
  build/htm-preact.js
  libs/blocks/accordion/accordion.js
  libs/blocks/aside/aside.js
  libs/blocks/bulk-publish/bulk-publish-utils.js
  libs/blocks/bulk-publish/bulk-publish.js
  libs/blocks/caas-config/caas-config.js
  libs/blocks/caas-config/caas-tags.js
  libs/blocks/card/card.js
  libs/blocks/chart/chart.js
  libs/blocks/commerce/commerce.js
  libs/blocks/global-navigation/features/search/gnav-search.js
  libs/blocks/icon-block/icon-block.js
  libs/blocks/marketo/marketo.js
  libs/blocks/marquee/marquee.js
  libs/blocks/recommended-articles/recommended-articles.js
  libs/blocks/review/components/helixReview/HelixReview.js
  libs/blocks/review/components/review/Comments.js
  libs/blocks/review/components/review/Ratings.js
  libs/blocks/review/components/review/Review.js
  libs/blocks/review/utils/sanitizeComment.js
  libs/blocks/review/utils/utils.js
  libs/blocks/section-metadata/section-metadata.js
  libs/blocks/share/share.js
  libs/blocks/tabs/tabs.js
  libs/blocks/tag-selector/tag-selector.js
  libs/blocks/text/text.js
  libs/features/georoutingv2/georoutingv2.js
  libs/hooks/useHover.js
  libs/ui/controls/MultiField.js
  libs/ui/controls/TagSelectPicker.js
  libs/utils/action.js
  libs/utils/decorate.js
  libs/utils/lana.js
  libs/utils/tree.js
  test/blocks/accordion/editorial-accordion.test.js
  test/blocks/caas-config/expectedConfigs/defaultConfig.js
  test/blocks/card/card.test.js
  test/blocks/carousel/carousel.test.js
  test/blocks/commerce/commerce.test.js
  test/blocks/faas/utils.test.js
  test/blocks/footer/footer.test.js
  test/blocks/gnav/gnav-contextual-search.test.js
  test/blocks/gnav/gnav-search.test.js
  test/blocks/gnav/gnav.test.js
  test/blocks/iframe/iframe.test.js
  test/blocks/marketo/mocks/marketo-utils.js
  test/blocks/marquee/marquee.test.js
  test/blocks/read-more/read-more.test.js
  test/blocks/share/share.test.js
  test/blocks/text/text.test.js
  test/features/georoutingv2/georoutingv2.test.js
  test/utils/action.test.js
  test/utils/lanaDefaultOptions.test.js
  test/utils/richresults.test.js
  tools/caas-import/parseCaasConfig.js
  tools/send-to-caas/send-to-caas.js
  tools/utils/utils.js
Labels: trivial

#772 MWPW-130073 - [Library] Add block patterns/grouping to the block library
  libs/blocks/library-config/lists/blocks.js
  libs/blocks/library-container-end/library-container-end.css
  libs/blocks/library-container-end/library-container-end.js
  libs/blocks/library-container-start/library-container-start.css
  libs/blocks/library-container-start/library-container-start.js
  libs/blocks/library-metadata/library-metadata.css
  test/blocks/library-config/library-config.test.js
  test/blocks/library-config/mocks/blocks/chart/body.html
  test/blocks/library-config/mocks/blocks/chart/docx.html
  test/blocks/library-config/mocks/blocks/container/body-containers.html
  test/blocks/library-config/mocks/blocks/container/body-mixed.html
  test/blocks/library-config/mocks/blocks/container/body-no-blocks-no-containers.html
  test/blocks/library-config/mocks/blocks/container/body-single-blocks.html
  test/blocks/library-config/mocks/blocks/container/docx-container.html
  test/blocks/library-config/mocks/blocks/container/docx-single-block.html
  test/blocks/library-config/mocks/blocks/marquee/body.html
  test/blocks/library-config/mocks/blocks/marquee/docx.html
  test/blocks/library-config/mocks/blocks/text/body.html
  test/blocks/library-config/mocks/blocks/text/docx.html
  test/blocks/library-config/mocks/media_1.png
Labels: new-feature

#965 Soft revert of lang/reg #915
  libs/scripts/delayed.js
  libs/scripts/scripts.js
  libs/utils/utils.js
Labels: trivial

#985 [Blog Migration] Topics URL 404s on lang pages
  libs/scripts/taxonomy.js
Labels: bug

#995 [MWPW-133763] Breadcrumbs mobile alignment
  libs/blocks/global-navigation/global-navigation.css
Labels: verified

#990 Make sure to always display the breadcrumbs when a base is set
  libs/blocks/global-navigation/features/breadcrumbs/breadcrumbs.js
  libs/utils/utils.js
Labels: verified

#991 MWPW-131707 Get correct region for caas autolang
  libs/blocks/caas/utils.js
  libs/utils/utils.js
  test/blocks/caas/utils.test.js
Labels: trivial

#1003 Add tracking attributes to links in card block
  libs/blocks/card/card.js
  test/blocks/card/card.test.js
Labels: verified, trivial

#988 Add run-lint workflow
  .github/workflows/run-lint.yaml
  test/utils/utils.test.js
Labels: trivial

#1001 [MWPW-128449] Extract fragments from the docs and add it to the floodgate project
  tools/floodgate/index.html
  tools/floodgate/js/floodgate.js
  tools/floodgate/js/project.js
  tools/floodgate/js/ui.js
  tools/loc/fragments.js
  tools/loc/ui.js
Labels: trivial

#968 Run code checks on PR against any branch
  .github/workflows/code-compatibility.yaml
  .github/workflows/codeql.yml
  .github/workflows/run-tests.yaml
Labels: trivial

#998 MWPW-130838 OST version rump up
  libs/blocks/ost/ost.js
Labels: trivial

#961 MWPW-125174: Adds functionality so that authors can chose what is displayed in the eyebrow section
  libs/blocks/caas-config/caas-config.js
  libs/blocks/caas/utils.js
  test/blocks/caas-config/caas-config.test.html
  test/blocks/caas-config/expectedConfigs/defaultConfig.js
  test/blocks/caas/utils.test.js
Labels: verified, new-feature

#843 MWPW-131134 - Marquee: media-credit container text disappears if italicized
  libs/blocks/marquee/marquee.js
  test/blocks/marquee/marquee.test.js
  test/blocks/marquee/mocks/body.html
Labels: verified

#1006 Disable failing media credit test until it can be fixed
  test/blocks/marquee/marquee.test.js
Labels: trivial

#1005 Fix flakey title-append test
  test/helpers/waitfor.js
  test/utils/utils.test.js
Labels: trivial

#1007 [MWPW-133865] Update default font color in dark section variants
  libs/blocks/section-metadata/section-metadata.css
Labels: trivial

#879 How-to block design enhancement
  libs/blocks/card/card.js
  libs/blocks/how-to/how-to.css
  libs/blocks/how-to/how-to.js
  test/blocks/how-to/how-to.test.js
  test/blocks/how-to/mocks/body.html
Labels: high-impact, verified

#1009 Improve linting: only warn on cycles, ignore console in tests
  .eslintrc.js
  package-lock.json
  package.json
Labels: trivial

#1011 feat(marquee): unit test fix
  test/blocks/marquee/marquee.test.js
  test/blocks/marquee/mocks/body.html
Labels: trivial

#1004 Mwpw 134073 table alignment fixed in mobile windows.
  libs/blocks/table/table.css
Labels: trivial

#1015 mwpw-134299 - localize global navigation logo links
  libs/blocks/global-navigation/global-navigation.js
Labels: verified

#1012 Fix loadLana test
  test/scripts/scripts.test.js
  test/utils/loadLana.test.js
Labels: trivial

#1008 MWPW-133232 Remove default Article tag
  tools/send-to-caas/bulk-publish-to-caas.js
  tools/send-to-caas/send-to-caas.js
  tools/send-to-caas/send-utils.js
  tools/sidekick/config.json
Labels: trivial

#1016 MWPW-133028 | Making aside button action area a flex container
  libs/blocks/aside/aside.css
Labels: verified, trivial

#1024 Skms integration
  .github/workflows/skms.yaml
Labels: trivial

#1023 Add tracking attributes in share block
  libs/blocks/share/share.js
  test/blocks/share/share.test.js
Labels: needs-verification

#1027 Bug: Fix bulk publisher
  tools/send-to-caas/bulk-publish-to-caas.js
  tools/send-to-caas/bulkpublisher.html
  tools/send-to-caas/send-to-caas.js
  tools/send-to-caas/send-utils.js
Labels: trivial

#1028 Caas Bulk Publisher: Backward Compatibility Fix
  tools/send-to-caas/bulk-publish-to-caas.js
Labels: trivial

#1017 mwpw-134306: always show authored breadcrumbs-page-title
  libs/blocks/global-navigation/features/breadcrumbs/breadcrumbs.js
  test/blocks/global-navigation/features/breadcrumbs.test.js
Labels: verified

#1032 [Global-navigation] Fix an undefined error
  libs/blocks/global-navigation/global-navigation.js
Labels: trivial

#1020 MWPW-134309: Milo to always use Prod WCS
  libs/blocks/merch/merch.js
  test/blocks/merch/merch.test.js
Labels: verified, commerce

#950 MWPW-133181 marquee rtl issue.
  libs/blocks/marquee/marquee.css
Labels: trivial

#1035 Add tracking for copy link to clipboard in share block
  libs/blocks/share/share.js
Labels: needs-verification

#881 MWPW-132693: Icon block inline variant style fix
  libs/blocks/icon-block/icon-block.css
  libs/blocks/icon-block/icon-block.js
  libs/styles/variables.css
  test/blocks/icon-block/icon-block.test.js
  test/blocks/icon-block/mocks/body.html
Labels: high-impact, @icon-block, needs-verification

#1034 MWPW-134424 | Center notification buttons are not center aligned
  libs/blocks/aside/aside.css
Labels: verified

#1030 Add analytics tracking to modal
  libs/blocks/modal/modal.js
  libs/features/georoutingv2/georoutingv2.js
Labels: verified

#1031 iframe window opened in mobile view is too small
  libs/blocks/modal/modal.css
  libs/blocks/modal/modal.js
  libs/styles/iframe.css
  test/blocks/modals/mocks/body.html
  test/blocks/modals/modals.test.js
Labels: needs-verification

#1021 MWPW-133747 Tag Selector Safari Style
  libs/blocks/tag-selector/tag-selector.css
  libs/ui/controls/tagSelector.css
Labels: verified, trivial, needs-verification
