Repository adobecom/milo, pull requests merged in 2023-03, with the labels that each got.

#503 [MWPW-126441] Unblock style-linting by lowercasing all t-shirt sizes in classnames
  libs/blocks/aside/aside.css
  libs/blocks/aside/aside.js
  libs/blocks/card-horizontal/card-horizontal.js
  libs/blocks/gnav/gnav.js
  libs/blocks/icon-block/icon-block.css
  libs/blocks/icon-block/icon-block.js
  libs/blocks/marquee/marquee.css
  libs/blocks/marquee/marquee.js
  libs/blocks/media/media.js
  libs/blocks/merch/merch.js
  libs/blocks/tabs/tabs.js
  libs/blocks/text/text.js
  libs/blocks/z-pattern/z-pattern.js
  libs/styles/typography.css
  libs/utils/decorate.js
  test/blocks/card-horizontal/card-horizontal.test.js
  test/blocks/marquee/marquee.test.js
  test/blocks/media/media.test.js
  test/blocks/text/text.test.js
Labels: enhancement, do not merge, trivial

#507 MWPW-126724 - Support non-link text in copyright
  libs/blocks/footer/footer.js
  test/blocks/footer/footer.test.js
  test/blocks/footer/mocks/copyright-p.html
  test/blocks/footer/mocks/copyright-ul.html
Labels: release, verified

#515 MWPW-126915 Fix gnav link order
  libs/blocks/gnav/gnav.js
Labels: verified

#529 Fix eslint import errors
  .eslintrc-code-compatibility.js
Labels: trivial

#532 Fixing bug when there is no firstelementchild on footer div.
  libs/blocks/footer/footer.js
Labels: verified, trivial

#530 MWPW-127078: Implement Privacy on all domains
  libs/utils/utils.js
Labels: verified

#495 fix: Article feed - filters bug
  libs/blocks/article-feed/article-feed.css
  libs/blocks/article-feed/article-feed.js
  libs/blocks/article-feed/article-helpers.js
  libs/blocks/featured-article/featured-article.css
  libs/scripts/taxonomy.js
  libs/styles/article-card.css
Labels: verified

#536 MWPW-127611 - Preflight Performance
  libs/blocks/preflight/panels/general.js
  libs/blocks/preflight/preflight.css
Labels: verified

#478 MWPW-123645 & MWPW-123653 - [Blog2Milo]
  libs/blocks/video/video.css
  libs/blocks/video/video.js
  libs/utils/utils.js
  test/blocks/adobetv/adobetv.test.js
  test/blocks/adobetv/mocks/body.html
  test/blocks/video/mocks/body.html
  test/blocks/video/video.test.js
  test/utils/dist/utils.test.dev.js
  test/utils/utils.test.js
Labels: verified

#538 MWPW-127324 - Second line copyright
  libs/blocks/footer/footer.css
  libs/blocks/footer/footer.js
  test/blocks/footer/footer.test.js
  test/blocks/footer/mocks/copyright-p.html
  test/blocks/footer/mocks/copyright-ul.html
Labels: verified

#535 MWPW-127532 Disable Auto Block
  libs/utils/utils.js
  test/utils/mocks/body.html
  test/utils/utils.test.js
Labels: verified, run-nala

#534 MWPW-126734 Breadcrumbs active style for current page
  libs/blocks/gnav/gnav.css
Labels: bug

#539 Remove generated file
  test/utils/dist/utils.test.dev.js
Labels: trivial

#544 Fixing sidekick for localhost.
  libs/utils/utils.js
Labels: trivial

#469 MWPW-121123 - Aside Block Updates
  libs/blocks/aside/aside.css
  libs/blocks/aside/aside.js
  libs/styles/styles.css
  test/blocks/aside/aside.test.js
  test/blocks/aside/mocks/body.html
Labels: enhancement, verified

#542 [MWPW-126441] Clean up typography.css
  libs/styles/typography.css
Labels: enhancement, trivial

#390 Vhargrave/universal buttons
  libs/blocks/aside/aside.js
  libs/blocks/card/card.js
  libs/blocks/gnav/gnav.js
  libs/blocks/marquee/marquee.js
  libs/utils/decorate.js
  libs/utils/utils.js
  test/blocks/marquee/marquee.test.js
  test/blocks/marquee/mocks/body.html
  test/scripts/scripts.test.js
  test/utils/mocks/buttons.html
  test/utils/utils.test.js
Labels: run-nala

#552 MWPW-127797 Manually override incorrect caas lang and country tags
  libs/blocks/caas-config/caas-config.js
  libs/ui/controls/formControls.js
Labels: trivial

#543 fix: author-header no social links
  libs/blocks/author-header/author-header.js
Labels: verified

#553 Text block override - lowercase typography class names
  libs/blocks/text/text.js
Labels: bug, verified

#560 MWPW-127286 Localize filter titles
  libs/blocks/caas/utils.js
Labels: trivial

#466 MWPW-123655 [Blog2Milo] - Contextual search Feature
  libs/blocks/gnav/gnav-contextual-search.js
  libs/blocks/gnav/gnav-search.js
  libs/blocks/gnav/gnav.css
  libs/blocks/gnav/gnav.js
  libs/styles/article-card.css
  test/blocks/gnav/gnav-contextual-search.test.js
Labels: enhancement

#554 MWPW-127043 Fix Region Selector US Link
  libs/utils/utils.js
  test/utils/htmlpostfix.test.html
Labels: bug, verified

#566 [MWPW-117906] Localnav and dropdown enhancements
  libs/blocks/global-navigation/blocks/navDropdown/dropdown.css
  libs/blocks/global-navigation/blocks/navDropdown/dropdown.js
  libs/blocks/global-navigation/blocks/profile/profile.css
  libs/blocks/global-navigation/blocks/search/gnav-search.css
  libs/blocks/global-navigation/blocks/search/gnav-search.js
  libs/blocks/global-navigation/global-navigation.css
  libs/blocks/global-navigation/global-navigation.js
  libs/blocks/global-navigation/utilities/utilities.js
Labels: enhancement

#562 MWPW-127806 Better CaaS tag delimiter support
  tools/send-to-caas/send-utils.js
Labels: trivial

#568 Make split marquees fully modularized
  libs/blocks/marquee/marquee.css
Labels: enhancement, trivial

#573 small caas unit test change
  test/blocks/caas-config/caas-config.test.html
Labels: trivial

#574 Updating milo to point to new location where CaaS files will be hosted
  libs/blocks/caas/utils.js
Labels: trivial

#571 Gnav dropdown shadows
  libs/blocks/gnav/gnav.css
Labels: trivial

#556 Region selector
  libs/blocks/locale-nav/img/aec-icon.svg
  libs/blocks/locale-nav/img/word-icon.svg
  libs/blocks/locale-nav/locale-nav.css
  libs/blocks/locale-nav/locale-nav.js
  tools/sidekick/config.json
Labels: release, verified

#564 MWPW-127736 Fix Safari sign-in dropdown
  libs/blocks/gnav/gnav.css
  libs/blocks/gnav/gnav.js
  test/blocks/gnav/gnav.test.js
  test/blocks/gnav/mocks/gnav.plain.html
  web-test-runner.config.mjs
Labels: bug, verified

#582 Adding auto response as exception as well.
  libs/blocks/faas/utils.js
Labels: trivial

#570 MWPW-127876: Gap issue Table of Contents
  libs/blocks/table-of-contents/table-of-contents.css
Labels: verified

#592 MWPW-122649 - Carousel transition update
  libs/blocks/carousel/carousel.css
Labels: trivial

#593 MWPW-126981 Fix georouting modal scroll
  libs/blocks/modal/modal.js
Labels: verified

#579 MWPW-125604: Enable Sorting for Card Modified Date (Oldest to Newest)
  libs/blocks/caas-config/caas-config.js
  libs/blocks/caas/utils.js
  test/blocks/caas-config/caas-config.test.html
  tools/caas-import/parseCaasConfig.js
Labels: verified

#599 MWPW-128724 Clickable marquee image
  libs/blocks/marquee/marquee.js
  test/blocks/marquee/marquee.test.js
  test/blocks/marquee/mocks/body.html
Labels: verified

#595 MWPW-120932: Org Logo JSON LD Schema
  libs/features/richresults.js
  test/utils/mocks/head-rich-results-org.html
  test/utils/richresults.test.js
Labels: release, verified, run-nala

#608 fixing the case issue in search
  libs/blocks/locale-nav/locale-nav.js
Labels: trivial

#604 MWPW-128378 Missing unit bug
  libs/blocks/chart/chart.js
Labels: verified
