Repository adobecom/milo, pull requests merged in 2023-11, with the labels that each got.

#1465 fix: update sampleRUM to its latest version
  libs/utils/samplerum.js
Labels: verified

#1450 [MWPW-117914] Allow promobar use on top of Gnav
  libs/blocks/aside/aside.css
  libs/blocks/global-navigation/base.css
  libs/blocks/global-navigation/features/aside/aside.js
  libs/blocks/global-navigation/global-navigation.css
  libs/blocks/global-navigation/global-navigation.js
  libs/styles/styles.css
  libs/utils/utils.js
  test/blocks/global-navigation/global-navigation.test.js
  test/blocks/global-navigation/mocks/correctPromoFragment.plain.js
  test/blocks/global-navigation/mocks/global-navigation-only-brand-no-explicit-image.js
  test/blocks/global-navigation/test-utilities.js
Labels: verified, run-nala

#1469 MWPW-137193 - Quiz results validation improvements
  libs/blocks/quiz-results/quiz-results.js
Labels: verified, run-nala

#1474 MWPW-138684: Fix merch block for safari
  libs/blocks/merch-card/merch-card.css
  libs/blocks/merch-card/merch-card.js
  libs/blocks/merch/merch.css
  libs/blocks/merch/merch.js
  libs/deps/commerce.d.ts
  libs/deps/commerce.js
  libs/deps/commerce.js.map
  libs/utils/decorate.js
  test/blocks/merch/merch.test.js
Labels: verified

#1478 MWPW-138740: fix strikethrough price
  libs/blocks/merch/merch.css
Labels: verified

#1454 [MWPW-137523] Add dark and large styles for quiet marquee
  libs/blocks/marquee/marquee.css
Labels: trivial, run-nala, @marquee

#1470 MWPW-138223 - Aside - max width on large notifications
  libs/blocks/aside/aside.css
Labels: bug, verified, trivial, run-nala

#1325 MWPW-136763: Fixes wrong origins being used by consumers
  tools/send-to-caas/send-utils.js
Labels: needs-verification

#1487 MWPW-136763: Fixes wrong origins being used by consumers #1325
  tools/send-to-caas/send-utils.js
Labels: verified

#1488 MWPW-136763: Fixes cases where origin is not in mapping
  tools/send-to-caas/send-utils.js
Labels: verified

#1477 Add analytics to 404 page template
  libs/templates/404/404.js
Labels: trivial

#1439 MWPW-130730 - Geo modal CTA highlight inconsistency
  libs/features/georoutingv2/georoutingv2.css
Labels: bug

#1480 MWPW-132437: [Q] Mirror margins for RTL locales
  libs/blocks/quiz/quiz.css
Labels: verified, run-nala

#1476 Quiz Results Debugging
  libs/blocks/quiz/quiz.js
Labels: verified, run-nala

#1482 MWPW-138713: [Q] Bogus dependency of step indicator on background
  libs/blocks/quiz/quiz.js
Labels: bug, verified, run-nala

#1466 Implemented disabling scroll when modal with curtain is opened
  libs/blocks/modal/modal.css
  libs/blocks/modal/modal.js
Labels: bug, verified, run-nala, needs-verification

#1472 MWPW-138106: b.a.com Blog category titles fix
  libs/blocks/recommended-articles/recommended-articles.js
  libs/scripts/taxonomy.js
Labels: verified

#1499 MWPW-138337: initial commit for dynamic tutorials
  libs/blocks/quiz-dynamic-tutorials/quiz-dynamic-tutorials-utils.js
  libs/blocks/quiz-dynamic-tutorials/quiz-dynamic-tutorials.css
  libs/blocks/quiz-dynamic-tutorials/quiz-dynamic-tutorials.js
Labels: run-nala, needs-verification

#1436 fix(MWPW-133207):Intermittent screen freeze, backdrop does not close when modal is closed.
  libs/blocks/modal/modal.js
Labels: verified, trivial, run-nala

#1490 MWPW-138808 Apply leaner fix for merch card prices (web components)
  libs/blocks/merch-card/merch-card.css
  libs/blocks/merch-card/merch-card.js
  libs/blocks/merch/merch.css
  libs/blocks/merch/merch.js
  libs/deps/commerce.d.ts
  libs/deps/commerce.js
  libs/deps/commerce.js.map
  libs/utils/decorate.js
  test/blocks/merch/merch.test.js
Labels: verified

#1496 MWPW-137073: Github action to sync repos
  .github/workflows/fg-sync-repos.yml
Labels: trivial

#1508 MWPW-138337 - Dynamic tutorial cards
  libs/blocks/quiz-dynamic-tutorials/quiz-dynamic-tutorials-utils.js
  libs/blocks/quiz-dynamic-tutorials/quiz-dynamic-tutorials.css
  libs/blocks/quiz-dynamic-tutorials/quiz-dynamic-tutorials.js
Labels: needs-verification

#1473 MWPW-137301 XXL Button Style
  libs/styles/styles.css
Labels: verified, run-nala

#1479 MWPW-135425 - Remove icon width limit on small notif aside
  libs/blocks/aside/aside.css
Labels: trivial

#1512 MWPW-137523 - Increase large quiet marquee max-width
  libs/blocks/marquee/marquee.css
Labels: verified, run-nala, @marquee

#1500 MWPW-138185 Update Marketo Intersection Observer
  libs/blocks/marketo/marketo.js
Labels: verified

#1493 MWPW-129984 Contextual Search without Helpx
  libs/blocks/gnav/gnav-contextual-search.js
  libs/blocks/gnav/gnav.css
  libs/blocks/gnav/gnav.js
Labels: verified, run-nala

#1518 MWPW-138197 Fix Adobe Logo on Safari
  libs/blocks/gnav/gnav.css
Labels: bug, verified

#1524 MWPW-138822: Quiz debugging features; bug fixes
  libs/blocks/quiz/quiz.css
  libs/blocks/quiz/quiz.js
Labels: verified, run-nala

#1527 MWPW-139129: Quiz errors when no matchedResults
  libs/blocks/quiz/utils.js
  test/blocks/quiz/mocks/invalid-user-selection.json
  test/blocks/quiz/utils.test.js
Labels: bug, verified, run-nala

#1471 MWPW-137634 footer unit tests
  libs/blocks/global-navigation/utilities/keyboard/utils.js
  test/blocks/global-footer/global-footer.test.js
  test/blocks/global-footer/mocks/base-footer.js
  test/blocks/global-footer/mocks/fetched-footer.js
  test/blocks/global-footer/mocks/icons.js
  test/blocks/global-footer/mocks/media-icon.png
  test/blocks/global-footer/test-utilities.js
  test/blocks/global-navigation/global-navigation.test.js
  web-test-runner.config.mjs
Labels: verified, run-nala

#1516 MWPW-138921 Fixing popup promo image size
  libs/blocks/aside/aside.css
Labels: bug, trivial, run-nala

#1537 Support for prod non milo environment
  libs/blocks/caas/utils.js
Labels: bug, verified, trivial, run-nala

#1535 MWPW-138347 Font display optional
  libs/scripts/scripts.js
Labels: needs-verification

#1438 MWPW-132986 - Add spacing around library blocks
  libs/blocks/library-config/lists/blocks.js
  test/blocks/library-config/library-config.test.js
Labels: trivial, run-nala

#1513 MWPW-138962: Bacom-blog Article Feed Issue
  libs/blocks/article-feed/article-helpers.js
Labels: verified

#1519 MWPW-138565 | Gnav overlapping with popup promobar
  libs/blocks/aside/aside.css
  libs/blocks/section-metadata/section-metadata.css
  libs/blocks/section-metadata/sticky-section.js
Labels: trivial, run-nala, needs-verification

#1545 MWPW-139338: mocked ims for gnav.js unit tests
  test/blocks/gnav/gnav.test.js
  test/blocks/gnav/mocks/head.html
Labels: run-nala, needs-verification

#1549 [MWPW-139039] Table css update for RTL
  libs/blocks/table/table.css
Labels: needs-verification

#1552 Mwpw 139041 sidekick
  libs/utils/utils.js
Labels: verified, trivial

#1553 MWPW-139365 - SEO Tab Canonical Fix
  libs/blocks/preflight/panels/seo.js
Labels: verified

#1455 MWPW-136383 - Add off-origin ability to links.js
  libs/features/links.js
  test/blocks/links/links-off-origin.test.js
  test/blocks/links/mocks/body.html
  test/blocks/links/mocks/off-origin.json
Labels: new-feature, needs-verification

#1532 [MWPW-136943] Colorful Gnav headings for A/B test
  libs/blocks/global-navigation/base.css
  libs/blocks/global-navigation/global-navigation.css
  libs/blocks/global-navigation/utilities/keyboard/utils.js
  libs/blocks/global-navigation/utilities/menu/menu.css
  libs/blocks/global-navigation/utilities/menu/menu.js
  test/blocks/global-navigation/global-navigation.test.js
  test/blocks/global-navigation/mocks/global-navigation-wide-column.plain.js
  test/blocks/global-navigation/mocks/large-menu-wide-column.plain.js
  test/blocks/global-navigation/test-utilities.js
Labels: verified, run-nala

#1548 [MWPW-139201] Allow CTAs in Gnav Promo boxes
  libs/blocks/global-navigation/utilities/menu/menu.css
  libs/blocks/global-navigation/utilities/menu/menu.js
  test/blocks/global-navigation/global-navigation.test.js
  test/blocks/global-navigation/mocks/global-navigation.plain.js
  test/blocks/global-navigation/test-utilities.js
Labels: verified, run-nala

#1562 [MWPW-139201] Allow CTAs in Gnav Promo boxes
  libs/blocks/global-navigation/utilities/menu/menu.css
  libs/blocks/global-navigation/utilities/menu/menu.js
  test/blocks/global-navigation/global-navigation.test.js
  test/blocks/global-navigation/mocks/global-navigation.plain.js
  test/blocks/global-navigation/test-utilities.js
Labels: verified

#1540 MWPW-138986 Fix chart sum with decimals
  libs/blocks/chart/utils.js
  test/blocks/chart/utils.test.js
Labels: bug, verified

#1577 MWPW-138514 - Short quiz dots
  libs/blocks/quiz/quiz.js
  libs/blocks/quiz/utils.js
Labels: verified

#1589 Mwpw 139779: Nested fragments with merch cards fix.
  libs/blocks/merch-card/merch-card.js
Labels: bug, run-nala, needs-verification
