Repository adobecom/milo, pull requests merged in 2023-02, with the labels that each got.

#423 MWPW-122611 - [GH Action] Old browser function detection
  .browserslistrc
  .eslintrc-code-compatibility.js
  .eslintrc.js
  .github/workflows/code-compatibility.yaml
  package-lock.json
  package.json
Labels: verified

#433 removing display none from accordion
  libs/blocks/accordion/accordion.css
Labels: bug, trivial

#429 Media & Z-Pattern updates - content margins and 2-5up grid support
  libs/blocks/aside/aside.css
  libs/blocks/media/media.css
  libs/blocks/media/media.js
  libs/blocks/z-pattern/z-pattern.js
  libs/styles/typography.css
  test/blocks/media/mocks/body.html
Labels: bug, verified

#440 Update node to v18
  .github/workflows/run-tests.yaml
Labels: trivial

#439 MWPW-125458 - Adding chat icon
  libs/img/icons/icons.svg
Labels: verified

#432 MWPW-124277: Localize Gnav Sign In Link
  libs/blocks/gnav/gnav.js
Labels: trivial

#402 PR fixes all feature gap issues between CaaS and milo
  libs/blocks/caas-config/caas-config.js
  libs/blocks/caas/utils.js
  test/blocks/caas-config/caas-config.test.html
  test/blocks/caas-config/expectedConfigs/defaultConfig.js
  test/blocks/caas/caas.test.html
  test/blocks/caas/utils.test.js
Labels: verified

#449 PR fixes all feature gap issues between CaaS and milo
  libs/blocks/caas-config/caas-config.js
  libs/blocks/caas/utils.js
  test/blocks/caas-config/caas-config.test.html
  test/blocks/caas-config/expectedConfigs/defaultConfig.js
  test/blocks/caas/caas.test.html
  test/blocks/caas/utils.test.js
Labels: verified

#442 MWPW-120858 - Chart Data Subheading
  libs/blocks/chart/chart.css
  libs/blocks/chart/chart.js
  test/blocks/chart/chart.test.js
  test/blocks/chart/mocks/lineChartSubheading.json
Labels: enhancement, verified

#389 MWPW-120934 - [SEO Structured Data] Site Search Box
  libs/features/richresults.js
  libs/utils/utils.js
  test/utils/mocks/head-rich-results-sitesearchbox.html
  test/utils/mocks/head-rich-results-unsupported-type.html
  test/utils/richresults.test.js
Labels: verified

#425 MWPW-123040: Adds support for additional button styles to the UI
  libs/blocks/caas-config/caas-config.js
  libs/blocks/caas/utils.js
  test/blocks/caas-config/caas-config.test.html
  test/blocks/caas-config/expectedConfigs/defaultConfig.js
  test/blocks/caas/mocks/utils.js
  test/blocks/caas/utils.test.js
Labels: trivial

#443 MWPW-125464 - Adding events to the modal on close and load
  libs/blocks/modal/modal.js
Labels: verified

#441 Adds sort by "Modified date" to CaaS card collection
  libs/blocks/caas-config/caas-config.js
  libs/blocks/caas/utils.js
  test/blocks/caas-config/caas-config.test.html
Labels: verified

#455 MWPW-123767: added milo container overrides for CaaS
  libs/blocks/caas/caas.css
Labels: verified

#457 MWPW-124262 PDF Viewer Analytics
  libs/blocks/pdf-viewer/pdf-viewer.js
Labels: release, verified

#435 share block: copy to clipboard button added & localization fixed
  libs/blocks/share/share.css
  libs/blocks/share/share.js
  libs/blocks/share/share.svg
Labels: enhancement, stock

#417 MWPW-126073 - Preflight
  libs/blocks/preflight/img/check.svg
  libs/blocks/preflight/img/empty.svg
  libs/blocks/preflight/img/expand.svg
  libs/blocks/preflight/img/green-check.png
  libs/blocks/preflight/img/green-check.svg
  libs/blocks/preflight/img/preflight-bg.png
  libs/blocks/preflight/img/purple-working.svg
  libs/blocks/preflight/img/red-error.svg
  libs/blocks/preflight/panels/general.js
  libs/blocks/preflight/panels/seo.js
  libs/blocks/preflight/preflight.css
  libs/blocks/preflight/preflight.js
  libs/utils/sidekick.js
  libs/utils/utils.js
  tools/sidekick/config.json
Labels: release, verified

#462 MWPW-124814 Horizontal Card Link
  libs/blocks/card-horizontal/card-horizontal.css
  libs/blocks/card-horizontal/card-horizontal.js
  test/blocks/card-horizontal/card-horizontal.test.js
  test/blocks/card-horizontal/mocks/body.html
Labels: release, verified

#359 MWPW-97638 - Region Navigation V2
  libs/blocks/region-nav/region-nav.css
  libs/blocks/region-nav/region-nav.js
  libs/utils/utils.js
  test/blocks/region-nav/mocks/regions.html
  test/blocks/region-nav/region-nav.test.js
Labels: GeoRouting

#470 MWPW-125513 - Cookie preferences bug
  libs/utils/utils.js
  test/utils/utils.test.js
Labels: verified

#471 MWPW-126174 - Horizontal card block image changes size based on title size
  libs/blocks/card-horizontal/card-horizontal.css
Labels: bug, verified

#475 GitHub Actions new variable for Nala PRs
  .github/workflows/run-nala.yml
Labels: trivial, run-nala

#482 MWPW-126454 Enable Card Horizontal for Consumers
  libs/utils/utils.js
Labels: trivial

#459 Removing some same css that coming from modal.css
  libs/blocks/footer/footer.css
  test/blocks/modals/modals.test.js
Labels: bug, verified

#479 Tabs block bug - Fix JP and KN label associations.
  libs/blocks/tabs/tabs.js
Labels: bug

#483 MWPW-124998 - Checkmark icon
  libs/img/icons/icons.svg
Labels: trivial

#480 MWPW-125608 fullscreen embedded tour
  libs/blocks/iframe/iframe.js
Labels: bug, verified

#489 MWPW-126597 load css for custom modals
  libs/blocks/modal/modal.js
Labels: bug

#500 Preflight Polish
  libs/blocks/preflight/img/orange-limbo.svg
  libs/blocks/preflight/img/word-icon.svg
  libs/blocks/preflight/panels/general.js
  libs/blocks/preflight/panels/seo.js
  libs/blocks/preflight/preflight.css
Labels: verified

#391 [MWPW-123840] Placeholders update to handle multiple locales/sheets
  libs/features/placeholders.js
  libs/utils/utils.js
  test/features/placeholders/placeholders.json
  test/features/placeholders/placeholders.test.js
Labels: enhancement, verified, run-nala

#492 MWPW-126479 Adding support for gradient background in section
  libs/blocks/section-metadata/section-metadata.js
  test/blocks/section-metadata/mocks/body.html
  test/blocks/section-metadata/section-meta.test.js
Labels: verified

#486 MWPW-125923 Fix Footer Titles
  libs/blocks/footer/footer.js
Labels: bug, verified

#476 Adds localization support for Caas + Milo
  libs/blocks/caas-config/caas-config.js
  libs/blocks/caas/utils.js
  test/blocks/caas/utils.test.js
Labels: verified

#456 MWPW-124568: Floodgate Admin Base Page
  .github/codeql/codeql-config.yml
  tools/floodgate/css/floodgate.css
  tools/floodgate/index.html
  tools/floodgate/js/config.js
  tools/floodgate/js/floodgate.js
  tools/floodgate/js/project.js
  tools/floodgate/js/ui.js
  tools/floodgate/js/utils.js
  tools/loc/config.js
  tools/loc/glaas.js
  tools/loc/project.js
  tools/loc/sharepoint.js
  tools/loc/ui.js
  tools/loc/utils.js
  tools/sidekick/config.json
Labels: verified

#509 MWPW-126238 Add Footer social links for CN
  libs/blocks/footer/footer-social.svg
  libs/blocks/footer/footer.js
Labels: verified
