Repository adobecom/milo, pull requests merged in 2023-10, with the labels that each got.

#1372 Revert "MWPW-137171: Temp Fix for Sidekick (#1368)"
  tools/sidekick/config.json
Labels: trivial

#1378 MWPW-136232 Localize faas destination url when complete
  libs/blocks/faas/utils.js
Labels: bug, verified, run-nala, @faas

#1379 MWPW-136165 - Background reset for quiz footer
  libs/blocks/quiz/quiz.css
Labels: verified

#1362 MWPW-136469 Fix authored tag link
  libs/scripts/taxonomy.js
Labels: bug, verified

#1369 MWPW-136162 [UAR] Refactored last step signal to dot indicators
  libs/blocks/quiz/quiz.js
  libs/blocks/quiz/utils.js
Labels: verified, run-nala

#1385 Add Tiktok and Instagram icons
  libs/img/icons/icons.svg
Labels: trivial

#1400 MWPW-137456 refactored for last step detection
  libs/blocks/quiz/quiz.js
Labels: verified, run-nala

#1406 Fix failing caas test
  test/blocks/caas/utils.test.js
Labels: trivial

#1390 MWPW-136414: Add Support for PDF Copy for FG
  tools/floodgate/js/utils.js
  tools/loc/fragments.js
Labels: trivial

#1409 MWPW-135875 Add milo property to window.marketingtech
  libs/martech/martech.js
Labels: verified, trivial

#1413 Quiz property name updates
  libs/blocks/quiz/utils.js
Labels: verified, run-nala

#1403 MWPW-135119: Redirect to result pages without loading results.json
  libs/blocks/quiz/quiz.js
  libs/blocks/quiz/utils.js
Labels: verified, run-nala, new-feature

#1415 MWPW-137511 Loc videos do not load
  libs/blocks/video/video.js
Labels: trivial

#1395 Rename helix-cli to aem-cli
  .gitignore
  README.md
  package.json
Labels: high-impact, trivial

#1417 Fix failing video tests
  test/blocks/video/video.test.js
Labels: trivial

#1416 MWPW-137970: make MEP prelinks relative
  libs/features/personalization/personalization.js
Labels: verified

#1343 MWPW-135720 - Marquee Video
  libs/blocks/adobetv/adobetv.css
  libs/blocks/adobetv/adobetv.js
  libs/blocks/aside/aside.js
  libs/blocks/marquee/marquee.css
  libs/blocks/marquee/marquee.js
  libs/blocks/section-metadata/section-metadata.js
  libs/blocks/video/video.css
  libs/blocks/video/video.js
  libs/utils/decorate.js
  libs/utils/utils.js
  test/blocks/adobetv/adobetv.test.js
  test/blocks/adobetv/mocks/body.html
  test/blocks/caas-config/caas-config.test.html
  test/blocks/global-navigation/global-navigation-with-html-extension.test.html
  test/blocks/marquee/marquee.test.js
  test/blocks/marquee/mocks/body.html
  test/blocks/marquee/mocks/video.html
  test/blocks/section-metadata/mocks/body.html
  test/blocks/section-metadata/section-meta.test.js
  test/blocks/video/mocks/body.html
  test/blocks/video/video.test.js
Labels: verified, run-nala, @marquee, needs-verification

#1240 MWPW-128872 - Expands complex queries logic to include exclusions
  libs/blocks/caas-config/caas-config.js
  libs/blocks/caas/utils.js
  test/blocks/caas-config/caas-config.test.html
Labels: run-nala, needs-verification, caas-configurator

#1394 MWPW-137187: Configurable FG Color
  tools/floodgate/js/config.js
  tools/floodgate/js/copy.js
  tools/floodgate/js/floodgate.js
  tools/floodgate/js/project.js
  tools/floodgate/js/ui.js
  tools/floodgate/js/utils.js
  tools/loc/config.js
  tools/loc/utils.js
Labels: trivial

#1382 MWPW-136622 - Caas Bulk Publish enhancements for Floodgate
  tools/send-to-caas/bulk-publish-to-caas.js
  tools/send-to-caas/bulkpublisher.html
  tools/send-to-caas/send-utils.js
Labels: high-impact, new-feature, needs-verification

#1411 MWPW-137755 Fix RTL text issue -how-to ordered lists
  libs/blocks/how-to/how-to.css
Labels: verified, trivial, needs-verification

#1321 MWPW-137671 Add support for hollow buttons and non static links with different breakpoint themes
  libs/blocks/marquee/marquee.css
Labels: trivial, run-nala

#1324 MWPW-136766, MWPW-136143: Milo not supporting sending to CaaS all locales & Autodetect not working
  libs/blocks/caas/utils.js
  test/blocks/caas/utils.test.js
  tools/send-to-caas/send-utils.js
Labels: verified

#1427 Revert "MWPW-136766, MWPW-136143: Milo not supporting sending to CaaS…
  libs/blocks/caas/utils.js
  test/blocks/caas/utils.test.js
  tools/send-to-caas/send-utils.js
Labels: verified

#1383 MWPW-137106 use ost 1.14.1
  libs/blocks/ost/ost.js
Labels: commerce, needs-verification

#1422 Video modal issue
  libs/blocks/adobetv/adobetv.css
  libs/blocks/adobetv/adobetv.js
  libs/blocks/video/video.css
  libs/blocks/video/video.js
Labels: bug, trivial

#1423 MWPW-137999 Marquee deskop only issue
  libs/blocks/marquee/marquee.js
  libs/utils/decorate.js
Labels: bug

#1418 Enable web test runner test retries
  web-test-runner.config.mjs
Labels: trivial

#1421 MWPW-137993 Setup global deferred promise
  libs/utils/utils.js
  test/utils/utils.test.js
Labels: high-impact, verified, needs-verification

#1401 MWPW-135873 Compress the caas hash strings
  libs/blocks/caas-config/caas-config.js
  libs/blocks/caas/caas.js
  libs/blocks/caas/utils.js
  libs/deps/compression-streams-pollyfill.js
  test/blocks/caas-config/caas-config.test.html
  test/blocks/caas/caas.test.html
  tools/caas-import/parseCaasConfig.js
Labels: new-feature, needs-verification

#1347 MWPW-133053 | Promo aside variant - popup promobar
  libs/blocks/aside/aside.css
  libs/blocks/aside/aside.js
  libs/blocks/section-metadata/section-metadata.css
  libs/blocks/section-metadata/sticky-section.js
  libs/styles/styles.css
  test/blocks/aside/aside.test.js
  test/blocks/aside/mocks/body.html
Labels: verified, run-nala, new-feature

#1370 MWPW-137137 - Fix styling of Text block legal variant
  libs/blocks/text/text.css
  libs/blocks/text/text.js
  libs/styles/styles.css
  libs/utils/decorate.js
  test/blocks/text/mocks/body.html
  test/blocks/text/text.test.js
Labels: bug, verified, trivial, run-nala

#1391 Make alt text links relative
  libs/utils/utils.js
Labels: bug, run-nala, needs-verification

#1429 MWPW-136372 - Fixing stuffs to make performance great again..
  libs/blocks/quiz/quiz.css
  libs/blocks/quiz/quiz.js
  test/blocks/quiz/mocks/index.html
Labels: verified, run-nala

#1266 MWPW-136294: authoring support for second source/content-type query in caas
  libs/blocks/caas-config/caas-config.js
  libs/blocks/caas/utils.js
  test/blocks/caas-config/caas-config.test.html
  test/blocks/caas-config/expectedConfigs/defaultConfig.js
  test/blocks/caas/mocks/utils.js
  test/blocks/caas/utils.test.js
Labels: verified, run-nala, new-feature, caas-configurator

#1424 Add new feature to add the ability of using the full qualified links …
  libs/blocks/caas-config/caas-config.js
  libs/blocks/caas/utils.js
  libs/utils/utils.js
  test/blocks/caas-config/caas-config.test.html
  test/blocks/caas/mocks/utils.js
  test/blocks/caas/utils.test.js
  test/utils/getUuid.test.js
  test/utils/utils.test.js
Labels: verified, new-feature

#1361 MWPW-137012 - Preflight Accessibility Tab
  libs/blocks/preflight/panels/accessibility.js
  libs/blocks/preflight/preflight.css
  libs/blocks/preflight/preflight.js
Labels: verified, new-feature

#1399 MWPW-126972: Removes SendToCaas option from dev and preview
  tools/sidekick/config.json
Labels: trivial

#1453 MWPW-138346 Update backup caas tags data
  libs/blocks/caas-config/caas-tags.js
Labels: trivial

#1444 MWPW-136294: authoring support for second source/content-type query in caas
  libs/blocks/caas-config/caas-config.js
  libs/blocks/caas/utils.js
  test/blocks/caas-config/caas-config.test.html
  test/blocks/caas-config/expectedConfigs/defaultConfig.js
  test/blocks/caas/mocks/utils.js
  test/blocks/caas/utils.test.js
Labels: verified, new-feature, caas-configurator

#1426 MWPW-134192-Add caas and faas configurator to sidekick
  tools/sidekick/config.json
Labels: high-impact, verified

#1402 MWPW-137576 - Aside CTA icon coloring
  libs/blocks/aside/aside.css
Labels: bug, verified, trivial, run-nala

#1414 [MWPW-137411] Add support for icon lists
  libs/blocks/text/text.css
  libs/features/icons/icons.js
Labels: verified

#1435 MWPW-137521 - Center icons on centered marquees
  libs/blocks/marquee/marquee.css
Labels: trivial, run-nala, @marquee

#1441 MWPW-138244 - [Milo][Caas][Floodgate] While sending card to Caas Floo…
  tools/send-to-caas/send-utils.js
Labels: bug, needs-verification

#1449 mwpw-137857: increase global navigation loadDelayed delay
  libs/blocks/global-navigation/global-navigation.js
Labels: verified

#1428 MWPW-136766, MWPW-136143: Milo not supporting sending to CaaS all locales & Autodetect not working
  libs/blocks/caas/utils.js
  test/blocks/caas/utils.test.js
  tools/send-to-caas/send-utils.js
Labels: verified

#1460 MWPW-138430 - Set origin to default repo when FG send to caas
  tools/send-to-caas/send-utils.js
Labels: bug, needs-verification

#1447 MWPW-137941: Improve quiz performance
  libs/blocks/quiz/quiz.css
  libs/blocks/quiz/quiz.js
  libs/blocks/quiz/utils.js
  test/blocks/quiz/mocks/index.html
Labels: verified

#1451 MWPW-137193 quiz-result validation improvements
  libs/blocks/quiz-results/quiz-results.js
Labels: verified

#1458 MWPW-137777 Show Article Header Dates in Production
  libs/blocks/article-header/article-header.js
  test/blocks/article-header/article-header.test.js
Labels: verified

#1389 MWPW-130327 Tag-Based Footer Promo
  libs/features/footer-promo.js
  libs/utils/utils.js
  test/utils/mocks/body-footer-promo.html
  test/utils/mocks/taxonomy.json
  test/utils/utils.test.js
Labels: verified, run-nala

#1463 feat: added tags to lana logs
  libs/blocks/global-navigation/features/breadcrumbs/breadcrumbs.js
  libs/blocks/global-navigation/features/profile/dropdown.js
  libs/blocks/global-navigation/features/search/gnav-search.js
  libs/blocks/global-navigation/global-navigation.js
  libs/blocks/global-navigation/utilities/keyboard/index.js
  libs/blocks/global-navigation/utilities/keyboard/mainNav.js
  libs/blocks/global-navigation/utilities/keyboard/mobilePopup.js
  libs/blocks/global-navigation/utilities/keyboard/popup.js
  libs/blocks/global-navigation/utilities/menu/menu.js
  libs/blocks/global-navigation/utilities/utilities.js
  test/blocks/global-navigation/utilities/utilities.test.js
Labels: run-nala

#1322 MWPW-136759: Entity IDs have changed from long format to small format and are not being accepted in configurator
  libs/blocks/caas/utils.js
  test/blocks/caas-config/caas-config.test.html
Labels: do not merge, verified
