Repository adobecom/milo, pull requests merged in 2023-12, with the labels that each got.

#1573 MWPW-136867: Merch-Card Offer Selection
  libs/blocks/merch-card/merch-card.css
  libs/blocks/merch-card/merch-card.js
  libs/blocks/merch-card/offer-selection.js
  test/blocks/merch-card/mocks/acrobat-card.html
  test/blocks/merch-card/offer-selection.test.js
Labels: run-nala, needs-verification

#1594 MWPW-139764: Offer Selector Tool price link type mapping
  libs/blocks/merch/merch.js
Labels: bug, run-nala, commerce, needs-verification

#1570 MWPW-137106: ost promo, href origin fixes
  libs/blocks/ost/ost.js
Labels: bug, verified, needs-verification

#1514 MWPW-138577: Global footer logging
  libs/blocks/global-footer/global-footer.js
  test/blocks/global-footer/global-footer.test.js
Labels: verified, run-nala, Ready To Merge

#1560 MWPW-135656: refactor region selector and social links decoration
  libs/blocks/global-footer/global-footer.js
Labels: verified, run-nala

#1520 MWPW-135830 - Decorate Area for fragments
  libs/blocks/fragment/fragment.js
  test/blocks/fragment/fragment.test.js
  test/blocks/fragment/mocks/body.html
  test/blocks/fragment/mocks/fragments/frag-image.plain.html
Labels: run-nala, needs-verification, Ready To Merge

#1593 MWPW-139841 - Added icon symbol `arrow-down` to icons.svg
  libs/img/icons/icons.svg
Labels: verified, trivial

#1510 MWPW-136152 🆕 `quiz-marquee` block for the app recommender landing page
  CODEOWNERS
  libs/blocks/quiz-marquee/quiz-marquee.css
  libs/blocks/quiz-marquee/quiz-marquee.js
  libs/blocks/text/text.css
  libs/blocks/text/text.js
  libs/img/icons/icons.svg
  libs/styles/styles.css
  libs/utils/decorate.js
  test/blocks/quiz-marquee/mocks/body.html
  test/blocks/quiz-marquee/quiz-marquee.test.js
  test/blocks/text/mocks/body.html
  test/blocks/text/text.test.js
Labels: verified, run-nala, new-feature, Ready To Merge, @quiz-marquee

#1543 MWPW-137835 - Tabs new 'pill' variant with sizes
  libs/blocks/tabs/tabs.css
  libs/blocks/tabs/tabs.js
  test/blocks/tabs/mocks/body.html
  test/blocks/tabs/tabs.test.js
Labels: verified, run-nala, new-feature

#1599 Mwpw 139503: Merch Card link & block analytics
  libs/blocks/merch-card/merch-card.js
  test/blocks/merch-card/mocks/uar-card.html
Labels: bug, verified, run-nala, commerce, needs-verification, merch card

#1567 MWPW-138654 - Quiz breakpoint icons and background
  libs/blocks/quiz/quiz.css
  libs/blocks/quiz/quiz.js
  libs/blocks/quiz/quizoption.js
Labels: verified

#1597 [UAR] Test Coverage Improvement
  libs/blocks/quiz/quiz.js
  libs/blocks/quiz/utils.js
  test/blocks/quiz/quiz.test.js
Labels: verified, run-nala

#1531 Mwpw-138750 analytics update 2.1
  libs/blocks/accordion/accordion.js
  libs/blocks/global-navigation/utilities/utilities.js
  libs/features/personalization/add-preview-to-config.js
  libs/features/personalization/manifest-utils.js
  libs/features/personalization/personalization.js
  libs/features/personalization/preview.css
  libs/features/personalization/preview.js
  libs/martech/analytics.js
  libs/martech/attributes.js
  libs/martech/attributes.md
  libs/martech/martech.js
  libs/templates/404/404.js
  libs/utils/utils.js
  test/blocks/accordion/accordion.test.js
  test/blocks/global-navigation/utilities/utilities.test.js
  test/features/personalization/mocks/manifestTestOrPromo.json
  test/features/personalization/mocks/personalization.html
  test/features/personalization/personalization.test.js
  test/martech/attributes.test.js
Labels: verified, trivial, Ready To Merge

#1530 MWPW-139169 - Vertically center aside notification icon
  libs/blocks/aside/aside.css
Labels: verified, run-nala, Ready To Merge

#1529 MWPW-139129,MWPW-138514,MWPW-138654: Error handling, Progress bar, Background images
  libs/blocks/quiz/quiz.css
  libs/blocks/quiz/quiz.js
  libs/blocks/quiz/quizoption.js
  libs/blocks/quiz/utils.js
  test/blocks/quiz/mocks/invalid-user-selection.json
  test/blocks/quiz/quiz.test.js
  test/blocks/quiz/utils.test.js
Labels: bug, verified, run-nala, Ready To Merge

#1603 MWPW-136152 - Added the `quiz-marquee` to the utils blocks list for consuming sites
  libs/utils/utils.js
Labels: verified, trivial

#1590 MWPW-138486 - Carousel bug with RTL languages
  libs/blocks/carousel/carousel.css
Labels: bug, verified, run-nala

#1600 MWPW-140041: Update merch block for release 3
  libs/blocks/commerce/commerce.js
  libs/blocks/merch-card/legacy-merch-card.css
  libs/blocks/merch/merch.css
  libs/blocks/merch/merch.js
  libs/deps/commerce.js
  libs/deps/merch-card.js
  test/blocks/merch/merch.test.js
  test/blocks/merch/mocks/body.html
Labels: verified, run-nala, commerce, needs-verification

#1582 MWPW-139782 - Marquee alignment for rtl locales
  libs/blocks/marquee/marquee.css
Labels: bug, run-nala, @marquee, needs-verification

#1536 MWPW-131002 - SKMS integration
  .github/workflows/skms.yaml
Labels: trivial

#1528 MWPW-138963 - Article Feed Title for DX Blog
  libs/blocks/article-feed/article-helpers.js
Labels: verified, Ready To Merge

#1592 MWPW-138966: aa for gnav hamburger menu button
  libs/blocks/global-navigation/global-navigation.js
Labels: run-nala, needs-verification

#1568 MWPW-135194: gnav mega menu layout adjustments
  libs/blocks/global-navigation/base.css
  libs/blocks/global-navigation/global-navigation.css
  libs/blocks/global-navigation/utilities/menu/menu.js
Labels: run-nala, needs-verification

#1604 MWPW-140042: Merch Card V3
  CODEOWNERS
  libs/blocks/merch-card/legacy-merch-card.css
  libs/blocks/merch-card/legacy-merch-card.js
  libs/blocks/merch-card/merch-card.css
  libs/blocks/merch-card/merch-card.js
  libs/blocks/merch-card/merch-offer-select.js
  libs/blocks/merch-offers/merch-offers.css
  libs/blocks/merch-offers/merch-offers.js
  libs/deps/merch-card.js
  libs/deps/merch-offer-select.js
  libs/utils/utils.js
  test/blocks/merch-card/legacy-merch-card/legacy-merch-card.test.js
  test/blocks/merch-card/legacy-merch-card/mocks/plans-card.html
  test/blocks/merch-card/legacy-merch-card/mocks/segment-card.html
  test/blocks/merch-card/legacy-merch-card/mocks/special-offers.html
  test/blocks/merch-card/legacy-merch-card/mocks/uar-card.html
  test/blocks/merch-card/merch-card.test.js
  test/blocks/merch-card/merch-offer-select.test.js
  test/blocks/merch-card/mocks/acrobat-card.html
  test/blocks/merch-card/mocks/card-section-metadata.html
  test/blocks/merch-card/mocks/catalog.html
  test/blocks/merch-card/mocks/intro-pricing.html
  test/blocks/merch-card/mocks/plans-card.html
  test/blocks/merch-card/mocks/special-offers.html
  test/blocks/merch-card/mocks/uar-card.html
Labels: high-impact, verified, run-nala, commerce, new-feature, merch card

#1605 Adding decorateArea() into replaceInner()
  libs/features/personalization/personalization.js
Labels: trivial

#1606 MWPW-140076 Update merch-card to match new analytics taxonomy
  libs/blocks/merch-card/merch-card.js
  libs/features/interlinks.js
Labels: verified, trivial

#1615 MWPW-138449 - Mobile progress indicator until 1024px
  libs/blocks/quiz/quiz.css
Labels: verified, run-nala

#1580 MWPW-134799: MEP On/Off
  libs/features/personalization/add-preview-to-config.js
  libs/features/personalization/personalization.js
  libs/features/personalization/preview.js
  libs/features/personalization/promo-utils.js
  libs/utils/utils.js
  test/features/personalization/mocks/head-schedule.html
  test/features/personalization/mocks/manifestScheduledActive.json
  test/features/personalization/mocks/manifestScheduledInactive.json
  test/features/personalization/personalization.test.js
  test/features/personalization/promo-utils.test.js
  test/utils/mocks/head-personalization.html
  test/utils/utils.test.js
Labels: verified, run-nala

#1623 MWPW-139621 - LCP loading via fragments
  libs/blocks/fragment/fragment.js
Labels: trivial

#1622 MWPW-139163 using global val of parameter
  libs/blocks/quiz/quiz.js
  libs/blocks/quiz/quizoption.js
Labels: verified, run-nala

#1584 MWPW-34656: [Milo] Need the ability to reorder filter lists easily
  libs/blocks/caas-config/caas-config.css
  libs/ui/controls/MultiField.js
  libs/ui/controls/multifield.css
Labels: trivial, caas-configurator

#1591 MWPW-139077 - New Form Block
  CODEOWNERS
  libs/blocks/form/form.css
  libs/blocks/form/form.js
  libs/blocks/review/components/review/Review.js
  libs/utils/sanitizeComment.js
  libs/utils/utils.js
  test/blocks/form/form.test.js
  test/blocks/form/mocks/body.html
  test/blocks/form/mocks/form-data.json
  test/utils/sanitizeComment.test.js
Labels: verified, run-nala, new-feature, needs-verification

#1619 MWPW-140160 - fixed styles for accordion rtl lang
  libs/blocks/accordion/accordion.css
Labels: trivial, run-nala

#1497 MWPW-138488 - Arabic font family
  libs/scripts/scripts.js
  libs/styles/styles.css
Labels: verified

#1635 MWPW-140141 Oversized Video Marquee Fix
  libs/blocks/marquee/marquee.js
Labels: bug, verified, run-nala, @marquee

#1634 MWPW-139077 - Form Block checkbox/radio group rule improvements
  libs/blocks/form/form.js
  libs/utils/sanitizeComment.js
  test/blocks/form/form.test.js
  test/blocks/form/mocks/form-data.json
Labels: bug, trivial, run-nala

#1433 MWPW-137906 Round media block
  libs/blocks/media/media.js
  libs/styles/rounded-corners.css
  test/blocks/media/mocks/body.html
Labels: verified, new-feature

#1636 MWPW-140255 Linting
  libs/blocks/quiz/quiz.css
Labels: verified, run-nala

#1626 MWPW-140255: Merge handleOnNextClick and mobile progress indicator updates
  libs/blocks/quiz/quiz.css
  libs/blocks/quiz/quiz.js
  libs/blocks/quiz/quizoption.js
Labels: verified, run-nala

#1638 MWPW-138522: Merch card image variant
  libs/blocks/merch-card/merch-card.js
Labels: run-nala, commerce, needs-verification, merch card

#1326 MWPW-136764: Support sending multiple locales to CaaS
  libs/blocks/caas/utils.js
  test/blocks/caas-config/caas-config.test.html
  test/blocks/caas/utils.test.js
Labels: verified

#1640 MWPW-140390: incorrect Pricing element css when pricing-bottom class is added in table merch
  libs/blocks/table/table.js
Labels: verified, run-nala

#1633 MWPW-140336: Refactor region selector and social links decoration for the footer
  .github/PULL_REQUEST_TEMPLATE/gnav.md
  libs/blocks/global-footer/global-footer.js
  test/blocks/global-footer/global-footer.test.js
  test/blocks/global-footer/mocks/fetched-footer.js
  test/blocks/global-footer/test-utilities.js
Labels: verified, run-nala

#1648 [MWPW-140401] Adapt nav gradient link styles
  libs/blocks/global-navigation/base.css
  libs/blocks/global-navigation/utilities/menu/menu.css
Labels: verified, trivial, run-nala

#1646 MWPW-140445: Fix card text alignment issue under mobile view
  libs/blocks/quiz/quiz.css
Labels: verified, run-nala

#1650 MWPW-139940 - Accessible quiz headings
  libs/blocks/quiz/quizcontainer.js
  libs/blocks/quiz/quizoption.js
  test/blocks/quiz/mocks/quiz.html
Labels: verified, run-nala

#1653 MWPW-140490: Accessibility and text alignment updates
  libs/blocks/quiz/quiz.css
  libs/blocks/quiz/quizcontainer.js
  libs/blocks/quiz/quizoption.js
  test/blocks/quiz/mocks/quiz.html
Labels: verified, run-nala

#1655 MWPW-140468: M@S Lana - clientId and error rate
  libs/deps/commerce.js
Labels: verified, trivial, commerce

#1656 Promo Preview in MEP: fix active schedule display
  libs/features/personalization/personalization.js
Labels: trivial

#1644 MWPW-139506: added lower level endpoints to caas configurator
  libs/blocks/caas-config/caas-config.js
  test/blocks/caas-config/caas-config.test.html
Labels: verified, caas-configurator

#1643 MWPW-139507:Allows the CaaS configurator to a use caas from a developer's host
  libs/blocks/caas/utils.js
Labels: trivial, caas-configurator

#1662 MWPW-140381 Add unit test for libs/features/personalization/preview.js
  test/features/personalization/preview.test.js
Labels: verified, trivial, Ready To Merge

#1609 MWPW-136617 Keep analytics in English (martech-metadata block)
  libs/blocks/accordion/accordion.js
  libs/blocks/global-navigation/features/aside/aside.js
  libs/blocks/global-navigation/global-navigation.js
  libs/blocks/global-navigation/utilities/menu/menu.js
  libs/blocks/global-navigation/utilities/utilities.js
  libs/blocks/martech-metadata/martech-metadata.css
  libs/blocks/martech-metadata/martech-metadata.js
  libs/blocks/merch-card/merch-card.js
  libs/martech/analytics.js
  libs/martech/analytics.md
  libs/martech/attributes.js
  libs/utils/utils.js
  test/blocks/accordion/accordion.test.js
  test/blocks/global-navigation/mocks/global-navigation.plain.js
  test/blocks/martech-metadata/martech-metadata.test.js
  test/blocks/martech-metadata/mocks/body.html
  test/blocks/merch-card/merch-card.test.js
  test/blocks/merch-card/mocks/card-section-metadata.html
  test/martech/attributes.test.js
  test/martech/mocks/body.html
Labels: verified, run-nala, Ready To Merge

#1649 MWPW-138459 XLG Entitlement support
  .vscode/extensions.json
  libs/features/personalization/entitlements.js
  libs/features/personalization/personalization.js
  libs/martech/martech.js
  libs/utils/utils.js
  test/features/personalization/entitlements.test.js
  test/features/personalization/mocks/manifestUseEntitlements.json
  test/features/personalization/personalization.test.js
  test/utils/utils.test.js
Labels: trivial

#1651 MWPW-140172 Fix anchor scroll
  libs/utils/utils.js
  test/utils/mocks/body.html
  test/utils/utils.test.js
Labels: bug, verified, run-nala

#1660 MWPW-140499: fix multiple merch card width issue on result page
  libs/blocks/quiz-results/quiz-results.css
Labels: bug, verified, run-nala

#1667 MWPW-140272 Move MEP button to the left side
  libs/features/personalization/preview.css
  libs/features/personalization/preview.js
Labels: verified, trivial
