Repository adobecom/milo, pull requests merged in 2023-05, with the labels that each got.

#665 MWPW-129482 New Marketo UI
  libs/blocks/marketo/marketo.css
  libs/blocks/marketo/marketo.js
  test/blocks/marketo/marketo.test.js
  test/blocks/marketo/mocks/body.html
Labels: verified

#675 Global navigation TBT improvements
  libs/blocks/global-navigation/blocks/navDropdown/dropdown.js
  libs/blocks/global-navigation/blocks/search/gnav-search.js
  libs/blocks/global-navigation/global-navigation.js
  libs/blocks/global-navigation/utilities/keyboard/mainNav.js
  libs/blocks/global-navigation/utilities/utilities.js
  test/blocks/global-navigation/keyboard/keyboard.test.js
Labels: trivial

#680 Mwpw 125561 uar results block - data model updates
  libs/blocks/uar-results/uar-results.js
Labels: verified

#688 Add CODEOWNERS
  CODEOWNERS
Labels: trivial

#692 [MWPW-128317] No hamburger when menu has no content
  libs/blocks/gnav/gnav.js
Labels: verified

#671 Table sticky
  libs/blocks/table-metadata/table-metadata.js
  libs/blocks/table/table.css
  libs/blocks/table/table.js
Labels: enhancement

#694 Let the footer use contentRoot instead.
  libs/blocks/footer/footer.js
Labels: verified

#701 Fix some flaky unit tests
  test/blocks/instagram/instagram.test.html
  test/blocks/instagram/instagram.test.js
  test/blocks/instagram/mocks/body.html
  test/blocks/instagram/mocks/embed-utils.js
  test/blocks/slideshare/mocks/body.html
  test/blocks/slideshare/mocks/utils.js
  test/blocks/slideshare/slideshare.test.html
  test/blocks/slideshare/slideshare.test.js
  test/blocks/tiktok/mocks/body.html
  test/blocks/tiktok/tiktok.test.html
  test/blocks/tiktok/tiktok.test.js
  test/blocks/twitter/mocks/body.html
  test/blocks/twitter/twitter.test.html
  test/blocks/twitter/twitter.test.js
  test/blocks/vimeo/mocks/body.html
  test/blocks/vimeo/vimeo.test.html
  test/blocks/vimeo/vimeo.test.js
  test/blocks/youtube/mocks/body.html
  test/blocks/youtube/youtube.test.html
  test/blocks/youtube/youtube.test.js
Labels: trivial

#695 Review css update
  libs/blocks/review/review.css
Labels: trivial

#713 Skip unreliable marketo tests for now
  test/blocks/marketo/marketo.test.js
Labels: trivial

#467 Share block updates, Reading Time (inline)
  libs/blocks/reading-time/reading-time.css
  libs/blocks/reading-time/reading-time.js
  libs/blocks/share/share.css
  libs/blocks/share/share.js
  libs/blocks/share/share.svg
  libs/styles/inline.css
  libs/utils/inline.js
  test/blocks/reading-time/mocks/inline.html
  test/blocks/reading-time/reading-time.test.js
  test/blocks/share/mocks/body.html
  test/blocks/share/share.test.js
Labels: enhancement, run-nala, stock

#684 mwpw-130571: Allow for easier QA of the new global-navigation
  libs/utils/utils.js
Labels: verified

#705 [MWPW-117909] Footer block refactor
  CODEOWNERS
  libs/blocks/global-footer/adchoices-small.svg
  libs/blocks/global-footer/footer-social.svg
  libs/blocks/global-footer/global-footer.css
  libs/blocks/global-footer/global-footer.js
  libs/blocks/global-footer/icons.svg
  libs/blocks/global-navigation/base.css
  libs/blocks/global-navigation/blocks/navDropdown/dropdown.css
  libs/blocks/global-navigation/features/appLauncher/appLauncher.js
  libs/blocks/global-navigation/features/profile/dropdown.css
  libs/blocks/global-navigation/features/profile/dropdown.js
  libs/blocks/global-navigation/features/search/gnav-search.css
  libs/blocks/global-navigation/features/search/gnav-search.js
  libs/blocks/global-navigation/global-navigation.css
  libs/blocks/global-navigation/global-navigation.js
  libs/blocks/global-navigation/utilities/keyboard/index.js
  libs/blocks/global-navigation/utilities/keyboard/mainNav.js
  libs/blocks/global-navigation/utilities/keyboard/mobilePopup.js
  libs/blocks/global-navigation/utilities/keyboard/popup.js
  libs/blocks/global-navigation/utilities/keyboard/utils.js
  libs/blocks/global-navigation/utilities/menu/menu.css
  libs/blocks/global-navigation/utilities/menu/menu.js
  libs/blocks/global-navigation/utilities/utilities.js
  libs/utils/utils.js
  test/blocks/global-navigation/global-navigation.test.js
  test/blocks/global-navigation/keyboard/keyboard.test.js
  test/blocks/global-navigation/keyboard/mocks/global-nav-mobile.html
  test/blocks/global-navigation/keyboard/mocks/global-nav.html
  test/blocks/global-navigation/mocks/global-navigation-only-brand.plain.js
  test/blocks/global-navigation/test-utilities.js
  test/blocks/global-navigation/utilities/getUserEntitlements.test.js
Labels: verified

#733 MWPW-129907 - Blog Migration
  libs/blocks/article-header/article-header.css
  libs/blocks/article-header/article-header.js
Labels: bug, verified

#729 Finalized UAR Results
  libs/blocks/uar-results/uar-results.css
  libs/blocks/uar-results/uar-results.js
  test/blocks/uar-results/mocks/body.html
  test/blocks/uar-results/mocks/fragments/basic-frag.plain.html
  test/blocks/uar-results/mocks/fragments/nested-frag.plain.html
  test/blocks/uar-results/mocks/uar-results.mock-data.js
  test/blocks/uar-results/uar-results.test.js
Labels: verified

#724 Fix two failing tests and add a custom test reporter
  test/blocks/reading-time/reading-time.test.js
  test/blocks/tabs/tabs.test.js
  web-test-runner.config.mjs
Labels: trivial

#693 Add support for Jarvis chat
  libs/features/jarvis-chat.js
  libs/scripts/scripts.js
  libs/utils/utils.js
  test/features/jarvis-chat/jarvis-chat.test.js
  test/features/jarvis-chat/mocks/jarvis-chat.html
  test/features/jarvis-chat/mocks/sendChatErrorEvent.json
  test/features/jarvis-chat/mocks/sendChatIconClickEvent.json
  test/features/jarvis-chat/mocks/sendChatIconRenderEvent.json
  test/features/jarvis-chat/mocks/sendPrimaryEvent.json
  test/features/jarvis-chat/mocks/sendProductEvent.json
  test/features/jarvis-chat/mocks/sendSurveyFeedbackEvent.json
Labels: verified

#737 MWPW-131381 Move flags to sharepoint
  .eslintrc.js
  libs/features/georoutingv2/georoutingv2.js
Labels: release, verified

#741 MWPW-129907 - Blog Migration
  libs/blocks/featured-article/featured-article.js
  libs/blocks/recommended-articles/recommended-articles.js
Labels: bug

#736 Address TODOs
  libs/blocks/global-navigation/features/profile/dropdown.js
  libs/blocks/global-navigation/features/search/gnav-search.js
  libs/blocks/global-navigation/global-navigation.js
  libs/blocks/global-navigation/utilities/getUserEntitlements.js
  libs/blocks/global-navigation/utilities/keyboard/mainNav.js
  libs/blocks/global-navigation/utilities/onImsReady.js
  libs/blocks/global-navigation/utilities/utilities.js
  libs/scripts/scripts.js
Labels: verified

#734 Ensure the global navigation is displayed on top of page content
  libs/blocks/global-navigation/global-navigation.css
Labels: bug, verified, trivial

#751 MWPW-130474: remove placeholder syntax from price links
  libs/blocks/ost/ost.js
  test/blocks/ost/ost.test.js
Labels: trivial

#758 minor: Preflight UX
  libs/blocks/preflight/preflight.css
Labels: trivial

#764 Provide default id for privacy
  libs/scripts/delayed.js
Labels: verified, trivial

#745 FEDS Gnav critical bug squashing
  libs/blocks/global-footer/global-footer.css
  libs/blocks/global-footer/global-footer.js
  libs/blocks/global-footer/icons.svg
  libs/blocks/global-navigation/base.css
  libs/blocks/global-navigation/features/profile/dropdown.js
  libs/blocks/global-navigation/features/search/gnav-search.css
  libs/blocks/global-navigation/global-navigation.css
  libs/blocks/global-navigation/global-navigation.js
  libs/blocks/global-navigation/utilities/keyboard/index.js
  libs/blocks/global-navigation/utilities/menu/menu.css
  libs/blocks/global-navigation/utilities/menu/menu.js
  libs/blocks/global-navigation/utilities/utilities.js
Labels: verified

#761 MWPW-129907 Blog Article Typography Corrections
  libs/blocks/featured-article/featured-article.css
  libs/styles/article-card.css
  libs/styles/variables.css
Labels: trivial

#765 MWPW-131664: increase merch resilience to errors
  libs/blocks/merch/merch.js
  test/blocks/merch/merch.test.js
Labels: bug, commerce

#770 Let region nav to use prefix instead content root.
  libs/blocks/region-nav/region-nav.js
Labels: bug, GeoRouting

#763 Highlight expanded navigation menu on mobile
  libs/blocks/global-navigation/global-navigation.css
  libs/blocks/global-navigation/global-navigation.js
  libs/blocks/global-navigation/utilities/menu/menu.js
  libs/blocks/global-navigation/utilities/utilities.js
  test/blocks/global-navigation/global-navigation.test.js
Labels: enhancement, verified

#757 [MWPW-131397] Unset min-height on Aside background image for notification variant
  libs/blocks/aside/aside.css
Labels: bug, trivial

#779 MWPW-131637: improve OST for small screens
  libs/blocks/ost/ost.css
  libs/blocks/ost/ost.js
Labels: verified

#791 Remove all margins from search input
  libs/blocks/global-navigation/features/search/gnav-search.css
Labels: bug, trivial

#711 [MWPW-126504] offer preview in sidekick
  libs/blocks/commerce/commerce.css
  libs/blocks/commerce/commerce.js
  libs/blocks/merch/merch.js
  libs/blocks/section-metadata/section-metadata.js
  libs/utils/utils.js
  test/blocks/commerce/commerce.test.js
  test/blocks/commerce/mocks/body.html
  tools/sidekick/config.json
Labels: commerce

#793 Improve navigation support when modals are displayed
  libs/blocks/modal/modal.js
  libs/features/georoutingv2/georoutingv2.js
Labels: enhancement, verified

#789 [MWPW-131852] Remove footer highlight when element is collapsed on mobile
  libs/blocks/global-navigation/utilities/menu/menu.js
Labels: bug, verified

#787 Add divider-inherit css to support different color divider
  libs/blocks/section-metadata/section-metadata.css
Labels: documentation, enhancement, verified

#799 MWPW-125675 - [Core] Milo Bulk Publish
  libs/blocks/bulk-publish/bulk-publish.js
Labels: verified
