Repository adobecom/milo, pull requests merged in 2024-04, with the labels that each got.

#1935 MWPW-143085 - Assign body font styles to <ul> and <ol>
  libs/utils/decorate.js
Labels: verified, run-nala, @icon-block, @media, Ready for Stage

#1936 MWPW-142961 - Support video in split marquee foreground
  libs/blocks/marquee/marquee.css
  libs/blocks/marquee/marquee.js
Labels: trivial, run-nala, @marquee, Ready for Stage

#1979 MWPW 142643
  libs/blocks/merch-card/merch-card.js
  libs/deps/merch-quantity-select.js
Labels: verified, run-nala, commerce, new-feature, Ready for Stage

#1986 MWPW-143145: add instant preview paramter
  libs/features/personalization/preview.js
  libs/features/personalization/promo-utils.js
  libs/utils/utils.js
  test/features/personalization/preview.test.js
  test/features/personalization/promo-utils.test.js
Labels: verified, run-nala, Ready for Stage

#1998 On Video close events and modal window close events , send adobe_corpnew.digitalData in the alloy call
  libs/blocks/modal/modal.js
  test/blocks/modals/modals.test.js
Labels: trivial, run-nala, high priority, Ready for Stage

#2068 MWPW-145566 remove faq from MILO_BLOCKS array
  libs/utils/utils.js
Labels: trivial, Ready for Stage

#2065 MWPW-144125 and MWPW-144536 [MILO][MEP] Request for New Personalization Tags
  libs/features/personalization/entitlements.js
  libs/features/personalization/stage-entitlements.js
Labels: trivial, new-feature, zero-impact, high priority, Ready for Stage

#2095 MWPW-144810: Quiz Entry - Add option cards and text to the block
  libs/blocks/quiz-entry/mlField.js
  libs/blocks/quiz-entry/quiz-entry.css
  libs/blocks/quiz-entry/quiz-entry.js
  libs/blocks/quiz-entry/quizoption.js
  libs/blocks/quiz-entry/utils.js
Labels: trivial

#2097 MWPW-145643 - Add retry button to lang module on error
  libs/blocks/locui/langs/view.js
Labels: trivial, zero-impact

#2090 [MWPW-145189] Adobe Home post-login redirect
  libs/utils/utils.js
Labels: verified, run-nala, high priority, Ready for Stage

#2101 MWPW-145643 - Revert retry button for now
  libs/blocks/locui/langs/view.js
Labels: trivial, zero-impact

#2096 [Release] Stage to Main
  libs/blocks/marquee/marquee.css
  libs/blocks/marquee/marquee.js
  libs/blocks/merch-card/merch-card.js
  libs/blocks/modal/modal.js
  libs/deps/merch-quantity-select.js
  libs/features/personalization/entitlements.js
  libs/features/personalization/preview.js
  libs/features/personalization/promo-utils.js
  libs/features/personalization/stage-entitlements.js
  libs/utils/decorate.js
  libs/utils/utils.js
  test/blocks/modals/modals.test.js
  test/features/personalization/preview.test.js
  test/features/personalization/promo-utils.test.js
Labels: run-nala, needs-verification, Ready for Main, BAcom SOT 👌, CC SOT 👌, Homepage SOT 👌, MIQ SOT👌

#2083 MWPW-145728 Increase timeout; add metadata support
  libs/features/personalization/personalization.js
  libs/martech/martech.js
Labels: trivial, high priority, Ready for Stage

#2104 MWPW-145921 - [Bulk Publish v2] update for deprecated api methods
  libs/blocks/bulk-publish-v2/services.js
  test/blocks/bulk-publish-v2/mocks/fetch.js
Labels: bug, verified, trivial, high priority, Ready for Stage

#2013 MWPW-144473 Reduce search time for contextual search
  libs/blocks/article-feed/article-feed.js
  libs/blocks/gnav/gnav-contextual-search.js
Labels: bug, verified, run-nala, Ready for Stage

#2040 MWPW-137502 Show inline fragments in preflight
  libs/blocks/preflight/panels/general.js
Labels: trivial, Ready for Stage

#2031 MWPW-143071 added new copy to OST dropdown
  libs/blocks/ost/ctaTextOption.js
  test/blocks/ost/textOption.test.js
Labels: trivial, commerce, Ready for Stage

#2048 MWPW-144813: Add 'xl-size' class for dialog-modal
  libs/blocks/modal/modal.css
Labels: verified, run-nala, Ready for Stage

#2102 MWPW-143159 [MILO TEST] Timeline visualization
  libs/mep/mwpw-143159/timeline/timeline.css
  libs/mep/mwpw-143159/timeline/timeline.js
Labels: verified, trivial, new-feature, zero-impact, high priority, Ready for Stage

#2103 Quiz entry block
  libs/blocks/quiz-entry/quiz-entry.js
Labels: trivial

#2105 TWP block draft
  libs/blocks/merch-twp/merch-twp.css
  libs/blocks/merch-twp/merch-twp.js
  libs/deps/merch-offer-select.js
  libs/deps/merch-subscription-layout.js
  libs/deps/merch-subscription-panel.js
  libs/deps/merch-subscription-tabs.js
  libs/features/spectrum-web-components/README.md
  test/blocks/merch-twp/merch-twp.test.js
  test/blocks/merch-twp/mocks/twp.html
Labels: trivial

#2114 Revert "Revert "MWPW-144813: Add 'xl-size' class for dialog-modal""
  libs/blocks/modal/modal.css
Labels: verified

#2106 Update Kodiak config.yaml
  .kodiak/config.yaml
Labels: trivial, zero-impact, security

#2107 [Release] Stage to Main
  .kodiak/config.yaml
  libs/blocks/article-feed/article-feed.js
  libs/blocks/bulk-publish-v2/services.js
  libs/blocks/gnav/gnav-contextual-search.js
  libs/blocks/modal/modal.css
  libs/blocks/ost/ctaTextOption.js
  libs/blocks/preflight/panels/general.js
  libs/features/personalization/personalization.js
  libs/martech/martech.js
  libs/mep/mwpw-143159/timeline/timeline.css
  libs/mep/mwpw-143159/timeline/timeline.js
  test/blocks/bulk-publish-v2/mocks/fetch.js
  test/blocks/ost/textOption.test.js
Labels: run-nala, needs-verification, Ready for Main, BAcom SOT 👌, CC SOT 👌, DC SOT 👌, MIQ SOT👌

#2081 Localize federal inline fragments before fetching them
  libs/blocks/global-navigation/utilities/utilities.js
Labels: verified, high priority, Ready for Stage

#1945 MWPW-142894: Active element accessibility
  libs/blocks/global-navigation/global-navigation.js
  test/blocks/global-navigation/global-navigation.test.js
Labels: verified, run-nala, Ready for Stage

#2053 MWPW-143900 - [tabs.quiet] increase tab-list spacing
  libs/blocks/tabs/tabs.css
Labels: verified, Ready for Stage, CC SOT 👌

#2113 MWPW-143904-New block: mobile-app-banner
  libs/blocks/mobile-app-banner/mobile-app-banner.css
  libs/blocks/mobile-app-banner/mobile-app-banner.js
  libs/utils/utils.js
Labels: run-nala, new-feature, needs-verification, high priority

#2052 MWPW-145148 Inline tree.js into fragment.js
  libs/blocks/fragment/fragment.js
  libs/utils/tree.js
  test/blocks/fragment/tree.test.js
Labels: trivial, Ready for Stage

#2063 MWPW-144254 [merch-card] per type heading map
  libs/blocks/merch-card/merch-card.js
  test/blocks/merch-card/merch-card.test.js
Labels: verified, run-nala, commerce, Ready for Stage

#2067 MWPW-145302: Added 's-size' class for modal, and horizontal paddings for section
  libs/blocks/modal/modal.css
  libs/blocks/section-metadata/section-metadata.css
Labels: verified, Ready for Stage

#2062 MWPW-140112 Preflight link check
  libs/blocks/preflight/panels/seo.js
  libs/blocks/preflight/preflight.css
Labels: trivial, new-feature, Ready for Stage

#2108 MWPW-145783 - Update completed label
  libs/blocks/locui/langs/view.js
Labels: verified, zero-impact

#2121 MWPW-146243 - Quiz entry code optimization
  libs/blocks/quiz-entry/mlField.js
  libs/blocks/quiz-entry/quiz-entry.css
  libs/blocks/quiz-entry/quiz-entry.js
  libs/blocks/quiz-entry/utils.js
Labels: trivial

#2124 [MWPW-146274] Fix AH redirect
  libs/utils/utils.js
Labels: verified, high priority, Ready for Stage

#2072 Add zero impact to the enforce labels workflow
  .github/workflows/enforce-labels.yml
Labels: trivial, zero-impact, Ready for Stage

#2071 Automatically mark stale PRs & close them after 7 days
  .github/workflows/mark-stale-prs.yaml
Labels: trivial, zero-impact, Ready for Stage

#2091 MWPW-145791 [MILO][Analytics] Martech Preflight tool needs a minor update
  libs/blocks/preflight/panels/martech.js
Labels: trivial, run-nala, new-feature, zero-impact, Ready for Stage

#2079 MWPW-145709 - [Repo automation] Add PR reminders
  .github/workflows/pr-reminders.js
  .github/workflows/pr-reminders.yaml
Labels: trivial, zero-impact, Ready for Stage

#2087 Add a few files to the .hlxignore files
  .hlxignore
  akamai/sureroute-test-object.html
Labels: verified, Ready for Stage

#2080 mwpw-145710: load ims via param from old domain
  libs/utils/utils.js
Labels: verified, Ready for Stage

#2069 MWPW-144600 [Milo FF] ANALYTICS update for proper DOM tagging of Card block - current use case CC Batch 03a Firefly pages
  libs/martech/attributes.js
  test/martech/attributes.test.js
  test/martech/mocks/body.html
Labels: verified, run-nala, high priority, Ready for Stage

#2084 MWPW-144683 Allow Article Header Without Category
  libs/blocks/article-header/article-header.js
  test/blocks/article-header/article-header.test.js
  test/blocks/article-header/mocks/body-without-category.html
Labels: verified, run-nala, Ready for Stage

#2129 [Release] Stage to Main
  .hlxignore
  akamai/sureroute-test-object.html
  libs/blocks/article-header/article-header.js
  libs/martech/attributes.js
  libs/utils/utils.js
  test/blocks/article-header/article-header.test.js
  test/blocks/article-header/mocks/body-without-category.html
  test/martech/attributes.test.js
  test/martech/mocks/body.html
Labels: run-nala, needs-verification, Ready for Main, BAcom SOT 👌, CC SOT 👌, DC SOT 👌, MIQ SOT👌

#2122 MWPW-142955 FaaS One Column Tablet
  libs/blocks/faas/faas.css
  libs/blocks/section-metadata/section-metadata.css
Labels: verified, run-nala, high priority, critical, Ready for Stage

#1976 fix(MWPW-142461):fixed Inconsistent font seen i-phone safari
  libs/blocks/accordion/accordion.css
Labels: verified, Ready for Stage

#2094 MWPW-145779: TWP modal not working when open in new tab
  libs/utils/utils.js
  test/utils/utils.test.js
Labels: verified, run-nala, Ready for Stage

#2086 MWPW-143156 [MILO][MEP] MEP Preview Button Bugs
  libs/features/personalization/preview.js
  libs/utils/utils.js
Labels: trivial, run-nala, Ready for Stage

#2119 MWPW-146209 [MILO][MEP] MEP param override does not work if manifest sent by Target and pzn and chosen column not in Target
  libs/features/personalization/entitlements.js
  libs/features/personalization/personalization.js
  libs/features/personalization/preview.js
  test/features/personalization/personalization.test.js
Labels: bug, verified, trivial, run-nala, Ready for Stage

#2135 [Release] Stage to Main
  libs/blocks/accordion/accordion.css
  libs/blocks/faas/faas.css
  libs/blocks/section-metadata/section-metadata.css
  libs/features/personalization/entitlements.js
  libs/features/personalization/personalization.js
  libs/features/personalization/preview.js
  libs/utils/utils.js
  test/features/personalization/personalization.test.js
  test/utils/utils.test.js
Labels: run-nala, needs-verification, Ready for Main, BAcom SOT 👌, CC SOT 👌, Homepage SOT 👌, MIQ SOT👌

#2126 MWPW-143904-Unit test and small authoring update for mobile-app-banner
  libs/blocks/mobile-app-banner/mobile-app-banner.js
  test/blocks/mobile-app-banner/mobile-app-banner.test.js
  test/blocks/mobile-app-banner/mocks/body.html
  test/blocks/mobile-app-banner/mocks/branch-io-key.json
Labels: verified, high priority, Ready for Stage

#2131 Fix: Adding gray bg and making header bold for group link on gnav
  libs/blocks/global-navigation/base.css
Labels: verified, run-nala, high priority, Ready for Stage

#1925 fix(MWPW-142926):video modal does not close when esc button is pressed.
  libs/blocks/modal/modal.js
Labels: verified, Ready for Stage

#2028 MWPW-143314: lana logs for feds-regionpicker.js 404s
  libs/blocks/global-footer/global-footer.js
Labels: verified, run-nala, Ready for Stage

#2130 MWPW-145591: Enable dom monitoring hook to verify javascript execution
  libs/utils/utils.js
Labels: verified, trivial, Ready for Stage

#2132 MWPW-146268 - [Milo - Tabs] Pill dark/light support
  libs/blocks/tabs/tabs.css
Labels: bug, verified, run-nala, Ready for Stage

#2139 MWPW-146034 - Quiz entry block accessibility
  libs/blocks/quiz-entry/mlField.js
  libs/blocks/quiz-entry/quiz-entry.js
  libs/blocks/quiz-entry/quizoption.js
Labels: trivial

#2128 MWPW-145643 - Add retry button to langs with errors
  libs/blocks/locui/langs/index.js
  libs/blocks/locui/langs/view.js
  libs/blocks/locui/utils/miloc.js
Labels: trivial, zero-impact

#2138 [Release] Stage to Main
  .github/workflows/fg-sync-repos.yml
  libs/blocks/global-footer/global-footer.js
  libs/blocks/global-navigation/base.css
  libs/blocks/mobile-app-banner/mobile-app-banner.js
  libs/blocks/modal/modal.js
  libs/blocks/tabs/tabs.css
  libs/utils/utils.js
  test/blocks/mobile-app-banner/mobile-app-banner.test.js
  test/blocks/mobile-app-banner/mocks/body.html
  test/blocks/mobile-app-banner/mocks/branch-io-key.json
Labels: run-nala, Ready for Main, BAcom SOT 👌, CC SOT 👌, DC SOT 👌, MIQ SOT👌

#2066 MWPW-145531: add close icon to sp-search component
  libs/features/spectrum-web-components/build.mjs
  libs/features/spectrum-web-components/dist/alert-dialog.js
  libs/features/spectrum-web-components/dist/base.js
  libs/features/spectrum-web-components/dist/button-group.js
  libs/features/spectrum-web-components/dist/button.js
  libs/features/spectrum-web-components/dist/checkbox.js
  libs/features/spectrum-web-components/dist/dialog.js
  libs/features/spectrum-web-components/dist/divider.js
  libs/features/spectrum-web-components/dist/field-label.js
  libs/features/spectrum-web-components/dist/help-text.js
  libs/features/spectrum-web-components/dist/icon.js
  libs/features/spectrum-web-components/dist/icons-ui.js
  libs/features/spectrum-web-components/dist/icons/asterisk.js
  libs/features/spectrum-web-components/dist/icons/checkmark.js
  libs/features/spectrum-web-components/dist/icons/chevron.js
  libs/features/spectrum-web-components/dist/icons/cross.js
  libs/features/spectrum-web-components/dist/icons/dash.js
  libs/features/spectrum-web-components/dist/menu.js
  libs/features/spectrum-web-components/dist/overlay.js
  libs/features/spectrum-web-components/dist/popover.js
  libs/features/spectrum-web-components/dist/progress-circle.js
  libs/features/spectrum-web-components/dist/search.js
  libs/features/spectrum-web-components/dist/shared.js
  libs/features/spectrum-web-components/dist/sidenav.js
  libs/features/spectrum-web-components/dist/textfield.js
  libs/features/spectrum-web-components/dist/theme.js
  libs/features/spectrum-web-components/dist/underlay.js
  libs/features/spectrum-web-components/package-lock.json
  libs/features/spectrum-web-components/package.json
  libs/features/spectrum-web-components/src/button.js
  libs/features/spectrum-web-components/src/icons-ui.js
  test/features/spectrum-web-components/button.test.html
Labels: verified, run-nala, Ready for Stage

#2077 Update the imslib sync workflow
  .github/workflows/update-dependencies.yaml
  .github/workflows/update-script.js
  libs/deps/imslib.min.js
Labels: verified, Ready for Stage

#2078 MWPW-136885: Merch Card Accessibility
  libs/deps/merch-card.js
Labels: verified, run-nala, commerce, merch card, Ready for Stage

#2118 MWPW-144811: custom params in co links
  libs/blocks/merch/merch.js
  libs/deps/commerce.js
  test/blocks/merch/merch.test.js
  test/blocks/merch/mocks/fetch.js
Labels: verified, run-nala, commerce, Ready for Stage

#2142 Revert "MWPW-136885: Merch Card Accessibility"
  libs/deps/merch-card.js
Labels: run-nala, needs-verification

#2136 MWPW-144108: Project PEP unit tests
  libs/features/webapp-prompt/webapp-prompt.js
  test/blocks/global-navigation/global-navigation.test.js
  test/features/webapp-prompt/mocks/media-icon.png
  test/features/webapp-prompt/mocks/pep-prompt-content.js
  test/features/webapp-prompt/test-utilities.js
  test/features/webapp-prompt/webapp-prompt.test.js
Labels: verified, trivial, zero-impact

#2140 MWPW-146491 Increase Target timeout again and improve error analytics
  libs/martech/martech.js
  web-test-runner.config.mjs
Labels: trivial, run-nala, high priority, Ready for Stage

#2149 Maintaining 8px padding on all viewports on fed utilities global nav
  libs/blocks/global-navigation/global-navigation.css
Labels: verified, run-nala, Ready for Stage

#2146 [Release] Stage to Main
  .github/workflows/update-dependencies.yaml
  .github/workflows/update-script.js
  libs/blocks/global-navigation/global-navigation.css
  libs/blocks/merch/merch.js
  libs/deps/commerce.js
  libs/deps/imslib.min.js
  libs/features/spectrum-web-components/build.mjs
  libs/features/spectrum-web-components/dist/alert-dialog.js
  libs/features/spectrum-web-components/dist/base.js
  libs/features/spectrum-web-components/dist/button-group.js
  libs/features/spectrum-web-components/dist/button.js
  libs/features/spectrum-web-components/dist/checkbox.js
  libs/features/spectrum-web-components/dist/dialog.js
  libs/features/spectrum-web-components/dist/divider.js
  libs/features/spectrum-web-components/dist/field-label.js
  libs/features/spectrum-web-components/dist/help-text.js
  libs/features/spectrum-web-components/dist/icon.js
  libs/features/spectrum-web-components/dist/icons-ui.js
  libs/features/spectrum-web-components/dist/icons/asterisk.js
  libs/features/spectrum-web-components/dist/icons/checkmark.js
  libs/features/spectrum-web-components/dist/icons/chevron.js
  libs/features/spectrum-web-components/dist/icons/cross.js
  libs/features/spectrum-web-components/dist/icons/dash.js
  libs/features/spectrum-web-components/dist/menu.js
  libs/features/spectrum-web-components/dist/overlay.js
  libs/features/spectrum-web-components/dist/popover.js
  libs/features/spectrum-web-components/dist/progress-circle.js
  libs/features/spectrum-web-components/dist/search.js
  libs/features/spectrum-web-components/dist/shared.js
  libs/features/spectrum-web-components/dist/sidenav.js
  libs/features/spectrum-web-components/dist/textfield.js
  libs/features/spectrum-web-components/dist/theme.js
  libs/features/spectrum-web-components/dist/underlay.js
  libs/features/spectrum-web-components/package-lock.json
  libs/features/spectrum-web-components/package.json
  libs/features/spectrum-web-components/src/button.js
  libs/features/spectrum-web-components/src/icons-ui.js
  libs/martech/martech.js
  test/blocks/merch/merch.test.js
  test/blocks/merch/mocks/fetch.js
  test/features/spectrum-web-components/button.test.html
  web-test-runner.config.mjs
Labels: run-nala, needs-verification, Ready for Main, BAcom SOT 👌, CC SOT 👌, DC SOT 👌, Homepage SOT 👌, MIQ SOT👌

#2143 MWPW-146352 fix georouting dropdown on ios
  libs/features/georoutingv2/georoutingv2.css
Labels: bug, verified, run-nala, high priority, Ready for Stage

#2155 MWPW-146491 Fast follow to add timeout value
  libs/martech/martech.js
Labels: verified, run-nala, high priority, Ready for Stage

#2153 [Release] Stage to Main
  libs/features/georoutingv2/georoutingv2.css
  libs/martech/martech.js
Labels: run-nala, needs-verification, Ready for Main, CC SOT 👌, DC SOT 👌, MIQ SOT👌

#2151 Add RUM click tracking to the sidekick library
  libs/blocks/library-config/library-config.js
  libs/blocks/library-config/lists/blocks.js
  libs/blocks/library-config/lists/icons.js
  libs/blocks/library-config/lists/personalization.js
  libs/blocks/library-config/lists/placeholders.js
  tools/sidekick/config.json
Labels: verified, zero-impact, Ready for Stage

#2137 MWPW-146459 - [LocUI v2] Additional filtering in deep fragment search
  libs/blocks/locui/actions/index.js
Labels: trivial, zero-impact

#2144 MWPW-146582: PEP fixes
  libs/features/webapp-prompt/webapp-prompt.js
Labels: verified, run-nala

#2157 [Release] Stage to Main
  libs/blocks/library-config/library-config.js
  libs/blocks/library-config/lists/blocks.js
  libs/blocks/library-config/lists/icons.js
  libs/blocks/library-config/lists/personalization.js
  libs/blocks/library-config/lists/placeholders.js
  tools/sidekick/config.json
Labels: run-nala, needs-verification, Ready for Main, BAcom SOT 👌, CC SOT 👌, DC SOT 👌, MIQ SOT👌

#2156 MWPW-146582: a11y aria attributes
  libs/utils/image-video-link.js
Labels: verified, run-nala, Ready for Stage

#2147 MWPW-145643 - Stop propagation of lang button, fix retry reqest
  libs/blocks/locui/langs/index.js
  libs/blocks/locui/langs/view.js
Labels: trivial, zero-impact

#2163 MWPW-146491 Fast follow to change timeout analytic and use Date instead of performance
  libs/martech/martech.js
Labels: verified, run-nala, zero-impact, high priority, Ready for Stage

#2059 MWPW-139842 - Block button styling - Support button.fill w/ <strong><em> authoring
  libs/utils/decorate.js
  test/blocks/media/media.test.js
Labels: verified, Ready for Stage

#2070 MWPW-142590 - [Share] enhancement - ability to edit text above icons
  libs/blocks/share/share.js
  libs/blocks/share/share.svg
  test/blocks/share/mocks/body.html
  test/blocks/share/share.test.js
Labels: verified, run-nala, Ready for Stage

#2172 Revert "MWPW-142590 - [Share] enhancement - ability to edit text above icons"
  libs/blocks/share/share.js
  libs/blocks/share/share.svg
  test/blocks/share/mocks/body.html
  test/blocks/share/share.test.js
Labels: verified, Ready for Stage

#2176 MWPW-146877 [LocUI] - Status Details & Sidekick
  libs/blocks/locui/locui.css
  libs/blocks/locui/sync/view.js
Labels: bug, trivial, zero-impact

#2167 [MWPW-146756] Add support for RTL in aside notifications, horizontal cards
  libs/blocks/aside/aside.css
  libs/blocks/card-horizontal/card-horizontal.css
Labels: bug, verified, high priority, Ready for Stage

#2178 MWPW-146756] Add support for RTL in aside notifications, horizontal cards""
  libs/blocks/aside/aside.css
  libs/blocks/card-horizontal/card-horizontal.css
Labels: verified, run-nala, high priority, Ready for Stage

#2093 Mwpw 142003: Mini Compare Chart card fixes
  libs/blocks/merch-card/merch-card.js
  libs/blocks/merch-card/merch-offer-select.js
  libs/deps/merch-card.js
  libs/deps/merch-offer-select.js
  test/blocks/merch-card/merch-card.test.js
  test/blocks/merch-card/mocks/mini-compare-chart.html
Labels: verified, run-nala, commerce, merch card, Ready for Stage

#2181 MWPW-139842 [Revert] Fill button style
  libs/utils/decorate.js
Labels: needs-verification

#2123 MWPW-146129 App Launcher overlaps the menu in Unav in the devices
  libs/blocks/global-navigation/global-navigation.js
Labels: bug, verified, trivial, Ready for Stage

#2182 Revert "MWPW-146129 App Launcher overlaps the menu in Unav in the devices"
  libs/blocks/global-navigation/global-navigation.js
Labels: verified, Ready for Stage

#2179 [Release] Stage to Main
  libs/blocks/aside/aside.css
  libs/blocks/card-horizontal/card-horizontal.css
  libs/blocks/merch-card/merch-card.js
  libs/blocks/merch-card/merch-offer-select.js
  libs/deps/merch-card.js
  libs/deps/merch-offer-select.js
  libs/utils/decorate.js
  test/blocks/merch-card/merch-card.test.js
  test/blocks/merch-card/mocks/mini-compare-chart.html
Labels: run-nala, needs-verification, Ready for Main, high priority, BAcom SOT 👌, CC SOT 👌, DC SOT 👌, Homepage SOT 👌, MIQ SOT👌

#2184 MWPW-146129 [Original: #2123] App Launcher overlaps the menu in Unav in the devices
  libs/blocks/global-navigation/global-navigation.js
Labels: trivial, Ready for Stage

#2152 MWPW-135821 introduce mep custom action & use it for card collection
  libs/blocks/merch-card-collection/merch-card-collection.js
  libs/features/personalization/personalization.js
  test/blocks/merch-card-collection/merch-card-collection.test.js
  test/features/personalization/actions.test.js
  test/features/personalization/mocks/actions/manifestCustomAction.json
Labels: verified, run-nala, commerce, Ready for Stage

#2186 [Release] Stage to Main
  libs/blocks/global-navigation/global-navigation.js
  libs/blocks/merch-card-collection/merch-card-collection.js
  libs/features/personalization/personalization.js
  test/blocks/merch-card-collection/merch-card-collection.test.js
  test/features/personalization/actions.test.js
  test/features/personalization/mocks/actions/manifestCustomAction.json
Labels: run-nala, needs-verification, BAcom SOT 👌, DC SOT 👌, Homepage SOT 👌, MIQ SOT👌

#2175 MWPW-146494-keep gnav sticky when branch banner is displayed
  libs/blocks/mobile-app-banner/mobile-app-banner.js
Labels: verified, Ready for Stage

#2190 MWPW-146036 - Rig up quiz entry button
  libs/blocks/quiz-entry/mlField.js
  libs/blocks/quiz-entry/quiz-entry.css
  libs/blocks/quiz-entry/quiz-entry.js
  libs/blocks/quiz-entry/utils.js
Labels: trivial

#2098 MWPW-144549 CTA alignment for Text, Icon, and Media Blocks
  libs/blocks/icon-block/icon-block.css
  libs/blocks/icon-block/icon-block.js
  libs/blocks/media/media.css
  libs/blocks/media/media.js
  libs/blocks/text/text.css
  libs/blocks/text/text.js
  test/blocks/icon-block/icon-block.test.js
  test/blocks/icon-block/mocks/body.html
  test/blocks/media/media.test.js
  test/blocks/media/mocks/body.html
  test/blocks/text/mocks/body.html
  test/blocks/text/text.test.js
Labels: high-impact, verified, run-nala, Ready for Stage

#2183 MWPW-146999: kodiak CVE 25883
  libs/blocks/caas-marquee/caas-marquee.js
  libs/blocks/global-navigation/utilities/getUserEntitlements.js
  package-lock.json
  package.json
Labels: verified, Ready for Stage

#2207 Revert "MWPW-144549 CTA alignment for Text, Icon, and Media Blocks"
  libs/blocks/icon-block/icon-block.css
  libs/blocks/icon-block/icon-block.js
  libs/blocks/media/media.css
  libs/blocks/media/media.js
  libs/blocks/text/text.css
  libs/blocks/text/text.js
  test/blocks/icon-block/icon-block.test.js
  test/blocks/icon-block/mocks/body.html
  test/blocks/media/media.test.js
  test/blocks/media/mocks/body.html
  test/blocks/text/mocks/body.html
  test/blocks/text/text.test.js
Labels: verified, run-nala

#2203 [Release] Stage to Main
  libs/blocks/caas-marquee/caas-marquee.js
  libs/blocks/global-navigation/utilities/getUserEntitlements.js
  package-lock.json
  package.json
Labels: verified, run-nala, Ready for Main, BAcom SOT 👌, CC SOT 👌, Homepage SOT 👌, MIQ SOT👌

#2194 Update code owners for feds
  CODEOWNERS
Labels: trivial, zero-impact, Ready for Stage

#2169 Harden preflight link checking
  libs/blocks/preflight/panels/general.js
  libs/blocks/preflight/panels/seo.js
  libs/blocks/preflight/preflight.css
Labels: bug, trivial, Ready for Stage

#2162 MWPW-146755: RTL merch icon padding
  libs/deps/merch-card.js
Labels: bug, verified, run-nala, commerce, merch card, Ready for Stage

#2187 MWPW-146001 parallelize literals call
  libs/blocks/merch/merch.js
  libs/deps/commerce.js
  test/blocks/merch/merch.test.js
Labels: verified, run-nala, commerce, Ready for Stage

#2204 Quiz entry block
  libs/blocks/quiz-entry/mlField.js
  libs/blocks/quiz-entry/quiz-entry.css
  libs/blocks/quiz-entry/quiz-entry.js
  libs/blocks/quiz-entry/quizPopover.js
  libs/blocks/quiz/utils.js
Labels: trivial

#2208 [Release] Stage to Main
  CODEOWNERS
  libs/blocks/merch/merch.js
  libs/blocks/preflight/panels/general.js
  libs/blocks/preflight/panels/seo.js
  libs/blocks/preflight/preflight.css
  libs/deps/commerce.js
  libs/deps/merch-card.js
  test/blocks/merch/merch.test.js
Labels: run-nala, needs-verification, Ready for Main, CC SOT 👌, DC SOT 👌, Homepage SOT 👌, MIQ SOT👌

#2191 Sidekick publish button updates
  libs/utils/sidekick.js
Labels: trivial, Ready for Stage

#2201 MWPW-146562 [Workflow] Add base for paths filter when dispatch DC workflow
  .github/workflows/dispatch.yml
Labels: zero-impact, Ready for Stage

#2213 [MWPW-147003] Marquee RTL adaptation
  libs/blocks/marquee/marquee.css
  libs/blocks/marquee/marquee.js
Labels: bug, verified, run-nala, @marquee, Ready for Stage

#2210 MWPW-145513: Tabs block accessibility
  libs/blocks/tabs/tabs.js
Labels: verified, run-nala, Ready for Stage

#2214 MWPW-146782: feat(utils/richersults): Add Article support
  libs/features/richresults.js
  test/utils/mocks/head-rich-results-article.html
  test/utils/richresults.test.js
Labels: trivial, zero-impact, Ready for Stage

#2234 MWPW-147265 - [LocUI] Preview and Live Links
  libs/blocks/locui/url/index.js
Labels: bug, zero-impact

#2227 MWPW-144022: Quiz entry block
  libs/blocks/quiz-entry/quiz-entry.css
  libs/blocks/quiz-entry/quizoption.js
Labels: trivial, run-nala

#2228 [Release] Stage to Main
  .github/workflows/dispatch.yml
  libs/blocks/marquee/marquee.css
  libs/blocks/marquee/marquee.js
  libs/blocks/tabs/tabs.js
  libs/features/richresults.js
  libs/utils/sidekick.js
  test/utils/mocks/head-rich-results-article.html
  test/utils/richresults.test.js
Labels: run-nala, needs-verification, Ready for Main, BAcom SOT 👌, DC SOT 👌, Homepage SOT 👌, MIQ SOT👌

#2233 [MWPW-147145] Allow SVG in PEP Prompt; change redirect method
  libs/features/webapp-prompt/webapp-prompt.css
  libs/features/webapp-prompt/webapp-prompt.js
Labels: needs-verification

#2225 MWPW-147455: Prevent MEP errors from breaking the page
  libs/features/personalization/personalization.js
Labels: verified, run-nala, high priority, critical, Ready for Stage

#2219 MWPW-144521: Jarvis enhancement
  libs/features/jarvis-chat.js
  libs/scripts/delayed.js
  test/features/jarvis-chat/jarvis-chat.test.js
Labels: verified, run-nala, Ready for Stage

#2024 MWPW-135160: Mnemonics inside merch card
  libs/blocks/merch-card/merch-card.js
  libs/blocks/mnemonic-list/mnemonic-list.css
  libs/blocks/mnemonic-list/mnemonic-list.js
  libs/deps/merch-card.js
  test/blocks/merch-card/merch-card.test.js
  test/blocks/merch-card/mocks/plans-card.html
Labels: verified, run-nala, commerce, merch card, Ready for Stage
