Repository adobecom/milo, pull requests merged in 2024-07, with the labels that each got.

#2471 Fix(MWPW-152290):Removed the horizontal scroll seen in windows machines.
  libs/styles/styles.css
Labels: verified, Ready for Stage

#2487 MWPW-147468 - Delayed Activation of Blade Animations on Ps Product Page
  libs/blocks/video/video.js
  libs/utils/decorate.js
  test/blocks/video/mocks/body.html
  test/blocks/video/video.test.js
Labels: verified, Ready for Stage

#2501 Exposing the UNav Config for consumers to modify and reload the UNav if needed
  libs/blocks/global-navigation/global-navigation.js
Labels: verified, Ready for Stage

#2392 MWPW-141022 [Project PEP] Prompt Dismissal + Tie-in with App Launcher UX
  libs/features/webapp-prompt/webapp-prompt.css
  libs/features/webapp-prompt/webapp-prompt.js
  test/features/webapp-prompt/mocks/pep-prompt-content.js
  test/features/webapp-prompt/test-utilities.js
  test/features/webapp-prompt/webapp-prompt.test.js
Labels: verified, Ready for Stage

#2534 Revert "MWPW-152283: [TEST] switch WCS to acom domain"
  libs/deps/commerce.js
Labels: run-nala, commerce, Ready for Stage

#2546 Revert "MWPW-141022 [Project PEP] Prompt Dismissal + Tie-in with App Launcher UX"
  libs/features/webapp-prompt/webapp-prompt.css
  libs/features/webapp-prompt/webapp-prompt.js
  test/features/webapp-prompt/mocks/pep-prompt-content.js
  test/features/webapp-prompt/test-utilities.js
  test/features/webapp-prompt/webapp-prompt.test.js
Labels: verified

#2551 MWPW-153573 - [LocUI] Transcreate UI
  libs/blocks/locui/loc/index.js
  libs/blocks/locui/utils/miloc.js
Labels: zero-impact

#2513 MWPW-152918 Fix Marketo button font
  libs/blocks/marketo/marketo.css
Labels: bug, verified, run-nala, @marketo, Ready for Stage

#2524 [MWPW-152278] Avoid empty CSS requests
  libs/utils/utils.js
Labels: Ready for Stage

#2531 Central georouting support
  libs/blocks/global-navigation/utilities/utilities.js
  libs/features/georouting/georouting.js
  libs/features/georoutingv2/georoutingv2.js
  libs/utils/federated.js
  test/blocks/global-navigation/utilities/utilities.test.js
  test/features/georouting/georouting.test.js
  test/features/georoutingv2/georoutingv2.test.js
Labels: verified, Ready for Stage

#2544 MWPW-153962: Introduce maslibs query parameter
  libs/blocks/merch/merch.js
  test/blocks/merch/mas/libs/commerce.js
  test/blocks/merch/merch.test.js
Labels: verified, run-nala, commerce, Ready for Stage

#2547 MWPW-154013 PEP prompt redirection is broken in stage after the PEP dismissal PR merge
  libs/features/webapp-prompt/webapp-prompt.css
  libs/features/webapp-prompt/webapp-prompt.js
  test/features/webapp-prompt/mocks/pep-prompt-content.js
  test/features/webapp-prompt/test-utilities.js
  test/features/webapp-prompt/webapp-prompt.test.js
Labels: verified, Ready for Stage

#2406 MWPW-151513: Search results vanished when user clicks on Marquee CTA:Start free trail
  libs/blocks/merch-card-collection/merch-card-collection.js
  libs/blocks/modal/modal.js
  libs/deps/merch-card-collection.js
  test/blocks/merch-card-collection/mocks/merch-card-collection.html
  test/blocks/modals/modals.test.js
Labels: verified, run-nala, Ready for Stage

#2514 MWPW-152697 Fix Marketo mobile horizontal scroll
  libs/blocks/marketo/marketo.css
Labels: bug, verified, run-nala, @marketo, Ready for Stage

#2525 MWPW-152280 MEP: Only preload fragments that are in the 1st section
  libs/features/personalization/personalization.js
  test/features/personalization/actions.test.js
  test/features/personalization/mocks/actions/manifestPreloadFrags.json
Labels: Ready for Stage

#2530 MWPW-146962 [milo] Text link behaving like button in FAQ section
  libs/blocks/merch/merch.css
Labels: verified, run-nala, Ready for Stage

#2548 MWPW-153600 [PEP] loader bar on PEP prompt is seen loaded Left to right in RTL locale
  libs/features/webapp-prompt/webapp-prompt.css
Labels: verified, Ready for Stage

#2564 MWPW-152016 - Localization target preview for transcreation
  libs/utils/utils.js
Labels: Ready for Stage

#2553 MWPW-153167: caas-config change to enable hiding date detail information
  libs/blocks/caas-config/caas-config.js
  libs/blocks/caas/utils.js
  test/blocks/caas-config/caas-config.test.html
  test/blocks/caas-config/expectedConfigs/defaultConfig.js
  test/blocks/caas/utils.test.js
Labels: trivial, new-feature, caas-configurator, CaaS, Ready for Stage

#2391 MWPW-149124 Improve Focus Page for Performance Improvement Tiger Team
  libs/features/icons/icons.js
  libs/utils/utils.js
Labels: run-nala, Ready for Stage

#2554 Mwpw-142267: Merch What's Included and Merch Mnemonic List (TwP)
  libs/blocks/merch-card/merch-card.js
  libs/blocks/merch-mnemonic-list/merch-mnemonic-list.css
  libs/blocks/merch-mnemonic-list/merch-mnemonic-list.js
  libs/blocks/merch-twp/merch-twp.js
  libs/blocks/merch-whats-included/merch-whats-included.css
  libs/blocks/merch-whats-included/merch-whats-included.js
  libs/deps/merch-card.js
  libs/deps/merch-mnemonic-list.js
  libs/deps/merch-twp-d2p.js
  libs/deps/merch-whats-included.js
  test/blocks/merch-twp/merch-twp.2cards.test.html
Labels: verified, run-nala, commerce, merch card, Ready for Stage

#2572 Stage pr created to slack stage
  .github/workflows/merge-to-main.yaml
  .github/workflows/merge-to-stage.js
  .github/workflows/merge-to-stage.yaml
Labels: run-nala, zero-impact

#2508 MWPW-147270 Fix the error caused by trying to load Search in Global Navigation
  libs/blocks/global-navigation/global-navigation.js
Labels: verified, Ready for Stage

#2561 Adding support for federated urls in modals
  libs/blocks/global-footer/global-footer.js
  libs/blocks/global-navigation/features/breadcrumbs/breadcrumbs.js
  libs/blocks/global-navigation/utilities/utilities.js
  libs/blocks/modal/modal.js
  libs/utils/federated.js
  test/blocks/global-navigation/utilities/utilities.test.js
  test/utils/federated.test.js
Labels: verified, run-nala, Ready for Stage

#2563 MWPW-152270 - Performance updates and small changes to marketingtech.
  libs/deps/martech.main.standard.min.js
  libs/deps/martech.main.standard.qa.min.js
  libs/martech/martech.js
  test/scripts/scripts.test.js
  test/utils/utils-mep-gnav.test.js
  test/utils/utils.test.js
Labels: Ready for Stage

#2570 MWPW-153703: UAR Milo Localization | JP - Page jumps, enlarges the cards and duplicates copy
  libs/blocks/quiz/quiz.js
Labels: bug, verified, uar, Ready for Stage

#2576 MWPW-154480 Split global-navigation.test.js into multiple files
  test/blocks/global-navigation/global-navigation.test.js
  test/blocks/global-navigation/gnav-brand.test.js
  test/blocks/global-navigation/gnav-cross-cloud.test.js
  test/blocks/global-navigation/gnav-main-nav-popup.test.js
  test/blocks/global-navigation/gnav-main-nav.test.js
  test/blocks/global-navigation/gnav-profile.test.js
  test/blocks/global-navigation/gnav-promo.test.js
  test/blocks/global-navigation/gnav-search.test.js
Labels: trivial, Ready for Stage

#2535 MWPW-147172: Support for callout texts in merch cards
  libs/blocks/merch-card/merch-card.js
  libs/deps/merch-card.js
  test/blocks/merch-card/merch-card.test.js
  test/blocks/merch-card/mocks/callout.html
Labels: verified, run-nala, commerce, new-feature, merch card, Ready for Stage

#2492 MWPW-147907: Allow for 24pt font size for price [Merch Card]
  libs/blocks/merch-card/merch-card.css
  libs/blocks/merch-card/merch-card.js
  test/blocks/merch-card/merch-card.test.js
  test/blocks/merch-card/mocks/plans-card.html
Labels: verified, run-nala, commerce, merch card, Ready for Stage

#2582 MWPW-154054 + MWPW-154192: Blank space caused by delayed modal anchor
  libs/blocks/modal/modal.js
  libs/features/personalization/personalization.js
  test/blocks/modals/modals.test.js
  test/features/personalization/personalization.test.js
Labels: verified, run-nala, commerce, Ready for Stage

#2586 MWPW-154556 Update caas-config.test.html to work on all platforms
  test/blocks/caas-config/caas-config.test.html
Labels: trivial, Ready for Stage

#2587 Skip bulk publish v1 tests as authors now use v2
  test/blocks/bulk-publish/bulk-publish-utils.test.js
Labels: Ready for Stage

#2581 Move the catch to the correct function
  .github/workflows/merge-to-stage.js
Labels: zero-impact

#2500 Mwpw 141119: Change default pricing for Africa site to fix broken prices/promos
  libs/deps/commerce.js
Labels: verified, run-nala, commerce, Ready for Stage

#2588 MWPW-154562 Fix resource form margins
  libs/blocks/marketo/marketo.css
Labels: bug, verified, run-nala, @marketo, high priority, critical, Ready for Stage

#2574 MWPW-153215 - [LocUI] Find fragments in Metadata
  libs/blocks/locui/actions/index.js
  libs/blocks/locui/utils/url.js
Labels: new-feature

#2499 Mwpw-147034: Custom border color + badge/border color decoupling [Merch card]
  libs/blocks/merch-card/merch-card.js
  test/blocks/merch-card/mocks/plans-card.html
Labels: verified, run-nala, commerce, merch card, Ready for Stage

#2557 MWPW-151863 - 🆕 Notification Block
  CODEOWNERS
  libs/blocks/notification/notification.css
  libs/blocks/notification/notification.js
  libs/utils/decorate.js
  libs/utils/utils.js
  test/blocks/notification/mocks/body.html
  test/blocks/notification/notification.test.js
Labels: verified, new-feature, Ready for Stage

#2567 [MWPW-152968] mWeb - Passing ECID to Branch.io banner - Implementation
  libs/blocks/mobile-app-banner/mobile-app-banner.js
  test/blocks/mobile-app-banner/mobile-app-banner.test.js
Labels: verified, Ready for Stage

#2594 [Modal] Dedup Ongoing Dialogs for Same Fragment
  libs/blocks/modal/modal.js
Labels: bug, run-nala, Ready for Stage

#2589 MWPW-141599: Fixes Card Title Accessibility Level
  libs/blocks/caas-config/caas-config.js
Labels: bug, caas-configurator, Ready for Stage

#2533 MWPW-150566 - 🆕 Editorial-Card block
  libs/blocks/editorial-card/editorial-card.css
  libs/blocks/editorial-card/editorial-card.js
  libs/styles/iconography.css
  libs/styles/rounded-corners.css
  libs/styles/styles.css
  libs/utils/utils.js
  test/blocks/editorial-card/editorial-card.test.js
  test/blocks/editorial-card/mocks/body.html
Labels: new-feature, needs-verification, Ready for Stage

#2597 [MWPW-152674] [Gray Box] Desktop gnav not hidden when device view is open
  libs/blocks/graybox/graybox.css
Labels: verified, Ready for Stage

#2604 MWPW-143053 [MEP] Request for New Personalization Tag - CC Paid
  libs/features/personalization/entitlements.js
Labels: Ready for Stage

#2599 [MWPW-154795] Style Feds Global-footer region picker drop-up variant (without hash)
  libs/blocks/global-footer/global-footer.css
Labels: verified, Ready for Stage

#2614 MWPW-153808: fix duplicate tax label
  libs/deps/commerce.js
Labels: run-nala, commerce, high priority, Ready for Stage

#2577 MWPW-146743 Improve Article Header Performance
  libs/blocks/article-header/article-header.js
  test/blocks/article-header/article-header.test.js
  test/blocks/article-header/mocks/body.html
  test/blocks/article-header/mocks/placeholders.json
Labels: verified, run-nala, Ready for Stage

#2569 MWPW-153586 - [LocUI] Validation and URL Actions state
  libs/blocks/locui/actions/index.js
  libs/blocks/locui/actions/modal.js
  libs/blocks/locui/langs/index.js
  libs/blocks/locui/loc/index.js
  libs/blocks/locui/locui.css
  libs/blocks/locui/url/index.js
  libs/blocks/locui/url/tabs.js
  libs/blocks/locui/url/view.js
Labels: new-feature

#2616 MWPW-154998 [MEP][MILO] Manifests do not execute in the right order when there is a disabled manifest
  libs/features/personalization/personalization.js
  test/utils/utils.test.js
Labels: run-nala

#2612 Revert "[MWPW-152968] mWeb - Passing ECID to Branch.io banner - Implementation"
  libs/blocks/mobile-app-banner/mobile-app-banner.js
  test/blocks/mobile-app-banner/mobile-app-banner.test.js
Labels: verified, critical, Ready for Stage

#2560 Bootstrapper script for milo feds blocks
  libs/blocks/fragment/fragment.js
  libs/blocks/global-footer/global-footer.js
  libs/navigation/bootstrapper.js
  libs/navigation/navigation.css
  libs/navigation/navigation.js
  libs/scripts/scripts.js
  libs/utils/federated.js
  libs/utils/locales.js
  test/blocks/fragment/mocks/body.html
  test/blocks/fragment/mocks/federal/fragments/frag-a.plain.html
  test/navigation/bootstrapper.test.js
  test/navigation/mocks/body.html
  test/navigation/navigation.test.js
Labels: verified, run-nala, Ready for Stage

#2619 Fix for errors in dynamically loaded scripts in test cases
  libs/navigation/navigation.js
  test/navigation/bootstrapper.test.js
  test/navigation/navigation.test.js
Labels: Ready for Stage

#2615 MWPW-128600 Locale Tool: Langstore points to langstore/en
  libs/blocks/locale-nav/locale-nav.js
Labels: Ready for Stage

#2610 MWPW-153245 [merch][analytics] dispatch wcomp events, and let default lh
  libs/deps/merch-card-collection.js
  libs/deps/merch-card.js
  libs/deps/merch-sidenav.js
  libs/martech/attributes.js
Labels: verified, run-nala, commerce, Ready for Stage

#2618 mwpw-154965: Fetch federal stage content from hlx.page instead of stage.adobe.com
  libs/utils/federated.js
  test/blocks/global-navigation/global-navigation.test.js
  test/blocks/global-navigation/test-utilities.js
  test/blocks/global-navigation/utilities/utilities.test.js
  test/utils/federated.test.js
Labels: Ready for Stage

#2632 MWPW-154998 [MEP][MILO] Manifests do not execute in the right order when there is a disabled manifest
  libs/features/personalization/personalization.js
  test/utils/utils.test.js
Labels: Ready for Stage

#2538 [MWPW-151517] - Remove condition for promobar hidden on mobile from gnav
  libs/blocks/global-navigation/global-navigation.css
  libs/blocks/global-navigation/global-navigation.js
  libs/blocks/mobile-app-banner/mobile-app-banner.js
  libs/styles/styles.css
  test/blocks/global-navigation/gnav-promo.test.js
Labels: verified, Ready for Stage

#2613 Mwpw 147034: Custom border color + badge/border color decoupling [merch card]
  libs/deps/merch-card.js
Labels: verified, run-nala, commerce, merch card, Ready for Stage

#2636 MWPW-150557 - Split Marquee CLS issues on consuming sites
  libs/blocks/marquee/marquee.css
Labels: verified, Ready for Stage

#2628 [MWPW-154335] [callout] Spacing issue encountered when the call-out section is added
  libs/blocks/merch-card/merch-card.js
  libs/deps/merch-card.js
  test/blocks/merch-card/merch-card.test.js
Labels: verified, run-nala, merch card, Ready for Stage

#2625 MWPW-153580: Add Opt-In Feature for CaaS Badge Display
  libs/blocks/caas-config/caas-config.js
  libs/blocks/caas/utils.js
  test/blocks/caas-config/caas-config.test.html
  test/blocks/caas-config/expectedConfigs/defaultConfig.js
  test/blocks/caas/utils.test.js
Labels: new-feature, caas-configurator, Ready for Stage

#2622 [MWPW-153611] [Gray Box] environment aware links
  libs/blocks/graybox/graybox.js
Labels: verified, Ready for Stage

#2603 Mwpw 154887: Making gnav visible in base.css
  libs/blocks/global-navigation/base.css
  libs/blocks/global-navigation/global-navigation.css
  libs/blocks/global-navigation/global-navigation.js
Labels: verified, Ready for Stage

#2645 MWPW-127793: Add Query Parameters for Chimera Stage/Prod Environment Override
  libs/blocks/caas/caas.js
Labels: new-feature, CaaS, Ready for Stage

#2600 [MWPW-145131] Send locale and language code to analytics
  libs/martech/martech.js
Labels: verified, Ready for Stage

#2643 MWPW-155293 Remove Bulk Publish V1
  libs/blocks/bulk-publish/README.md
  libs/blocks/bulk-publish/bulk-publish-utils.js
  libs/blocks/bulk-publish/bulk-publish.css
  libs/blocks/bulk-publish/bulk-publish.js
  libs/blocks/bulk-publish/img/arrow-group.svg
  libs/blocks/bulk-publish/img/dots.svg
  libs/blocks/bulk-publish/img/emphasis-shape.svg
  libs/blocks/bulk-publish/img/mesh.svg
  test/blocks/bulk-publish/bulk-publish-utils.test.js
Labels: Ready for Stage

#2631 MWPW-154891 - [LocUI] Check if media in URL Validation
  libs/blocks/locui/actions/index.js
  libs/blocks/locui/loc/index.js
  libs/blocks/locui/utils/url.js
Labels: bug

#2640 MWPW-147867 - [marquee] support RTL for loc
  libs/blocks/marquee/marquee.css
Labels: run-nala, @marquee, needs-verification, Ready for Stage

#2655 MWPW-145389 Push sync for floodgate
  .github/workflows/fg-sync-repos.yml
Labels: zero-impact

#2657 MWPW-146030 and MWPW-143704 Add fresco-any and cc-paid-no-stock
  libs/features/personalization/entitlements.js
  libs/features/personalization/stage-entitlements.js
Labels: Ready for Stage

#2660 Attaching loadblock to window to provide alternative way of loading the script
  libs/navigation/navigation.js
Labels: verified, trivial, Ready for Stage

#2637 [MWPW-153267] Expand table to parent grid size
  libs/blocks/table/table.css
Labels: verified, Ready for Stage

#2639 MWPW-155316 - Fixing Pill Notification edge cases
  libs/blocks/notification/notification.css
  libs/blocks/notification/notification.js
  test/blocks/notification/mocks/body.html
Labels: bug, needs-verification, Ready for Stage

#2651 Correctly pass on the dataset
  libs/blocks/adobetv/adobetv.js
Labels: verified, Ready for Stage

#2653 MWPW-155289: Fixed filtering and sorting in catalog sidenav
  libs/deps/mas/merch-card-collection.js
  libs/deps/mas/merch-sidenav.js
  libs/features/mas/web-components/src/deeplink.js
  libs/features/mas/web-components/test/deeplink.test.js
Labels: verified, run-nala, commerce, Ready for Stage

#2654 MWPW-154124: use preview index
  libs/blocks/merch-card-collection/merch-card-collection.js
  test/blocks/merch-card-collection/merch-card-collection.test.js
  test/blocks/merch-card-collection/mocks/merch-card-collection.html
Labels: verified, run-nala, commerce, Ready for Stage
