Repository adobecom/milo, pull requests merged in 2024-02, with the labels that each got.

#1797 MWPW-141691: Merch card: align footer rows
  libs/blocks/merch-card/merch-card.js
  libs/deps/merch-card.js
  test/blocks/merch-card/merch-card.test.js
  test/blocks/merch-card/mocks/mini-compare-chart.html
Labels: verified, run-nala, commerce, needs-verification

#1775 MWPW-139379 Improve Tab Scrolling for Mobile
  libs/blocks/tabs/tabs.css
  libs/blocks/tabs/tabs.js
  libs/features/georoutingv2/georoutingv2.css
  test/blocks/tabs/mocks/body.html
  test/blocks/tabs/tabs.test.js
Labels: verified, run-nala

#1768 Implemented option to add more links to qr-code media block variant, …
  libs/blocks/media/media.css
  libs/blocks/media/media.js
  test/blocks/media/media.test.js
Labels: bug, verified

#1807 MWPW-141131 - Updating checkmark-circle icon. Adding lock icon.
  libs/img/icons/icons.svg
Labels: trivial, needs-verification

#1806 MWPW-141594 Move georouting to post LCP
  libs/utils/utils.js
Labels: verified, run-nala

#1813 MWPW-140884| Increase z index of sticky bottom section
  libs/blocks/section-metadata/section-metadata.css
Labels: verified, trivial, run-nala

#1812 MWPW-142072 | Making full width brick foreground image have full height
  libs/blocks/brick/brick.css
Labels: verified, trivial, run-nala

#1819 MWPW-142089 - Quiz background markup cleanup
  libs/blocks/quiz/quiz.css
  libs/blocks/quiz/quizcontainer.js
Labels: verified

#1820 MWPW-142157: Set background size to cover in quiz cards
  libs/blocks/quiz/quiz.css
  libs/blocks/quiz/quizoption.js
Labels: bug, verified, run-nala

#1825 MWPW-140867: remove conflicting padding
  libs/blocks/merch-card/merch-card.css
Labels: trivial

#1824 MWPW-141691: Footer rows of merch-cards in fragments
  libs/blocks/merch-card/merch-card.js
  test/blocks/merch-card/mocks/mini-compare-chart.html
Labels: trivial

#1826 improve redirect message for edit manifest button in sidekick
  libs/features/personalization/preview.js
Labels: trivial

#1814 MWPW-142125: fix CLS issue on mnemonic list
  CODEOWNERS
  libs/blocks/marquee/marquee.js
  libs/blocks/mnemonic-list/mnemonic-list.css
  libs/blocks/mnemonic-list/mnemonic-list.js
Labels: verified, trivial

#1822 MWPW-142224 [MILO][MEP] useBlockCode action improvements
  experiments/test001/blocks/quote/quote.css
  experiments/test001/blocks/quote/quote.js
  libs/features/personalization/personalization.js
  libs/mep/mwpw-142224/marquee/marquee.css
  libs/mep/mwpw-142224/marquee/marquee.js
  libs/mep/readme.md
  libs/utils/utils.js
  test/features/personalization/mocks/manifestUseBlockCode.json
  test/features/personalization/mocks/manifestUseBlockCode2.json
  test/features/personalization/mocks/promo/promo.css
  test/features/personalization/mocks/promo/promo.js
  test/features/personalization/personalization.test.js
Labels: trivial, run-nala

#1786 [MWPW-139079][MWPW-139078] Link Farms - Adjustable spacing between breakpoints and enabling spacing tokens
  libs/blocks/text/link-farms.css
  libs/blocks/text/text.css
  libs/blocks/text/text.js
Labels: verified, trivial, run-nala

#1811 MWPW-142053: Fix CLS issues in merch-cards block
  libs/blocks/merch-card/merch-card.css
  libs/blocks/merch-cards/merch-cards.css
  libs/blocks/merch-cards/merch-cards.js
  libs/deps/merch-cards.js
  test/blocks/merch-cards/mocks/merch-cards.html
Labels: verified, commerce

#1815 MWPW-141290 | Icon stack text content to contain link and plain text
  libs/blocks/brick/brick.css
  libs/blocks/brick/brick.js
  test/blocks/brick/mocks/body.html
Labels: verified, trivial, run-nala

#1765 MWPW-138716 - Tablist is overlaying gnav when the page has a table block
  libs/blocks/tabs/tabs.css
Labels: verified, run-nala

#1782 MWPW-141392: Tooltip On Focus & Aria-checked
  libs/blocks/review/components/review/RatingInput.js
  libs/blocks/review/components/review/Ratings.js
  test/blocks/form/form.test.js
  test/blocks/review/components/review/Ratings.test.js
Labels: run-nala, needs-verification

#1828 Ignore ficodes with low correlation and new apis
  libs/blocks/quiz-dynamic-tutorials/quiz-dynamic-tutorials-utils.js
  libs/blocks/quiz-dynamic-tutorials/quiz-dynamic-tutorials.js
  libs/blocks/quiz/quiz.js
  libs/blocks/quiz/utils.js
Labels: trivial, run-nala

#1834 MWPW-142027 - Unit tests for quiz-results tagging
  test/blocks/quiz-results/mocks/body.html
  test/blocks/quiz-results/mocks/fragments/basic-frag.plain.html
  test/blocks/quiz-results/quiz-results.test.js
Labels: verified

#1832 [MWPW-142314] Send correct analytics values
  libs/blocks/global-navigation/global-navigation.js
Labels: verified, trivial

#1714 GNAV & Footer content centralisation
  libs/blocks/global-footer/global-footer.js
  libs/blocks/global-navigation/features/breadcrumbs/breadcrumbs.js
  libs/blocks/global-navigation/features/profile/dropdown.js
  libs/blocks/global-navigation/features/search/gnav-search.js
  libs/blocks/global-navigation/global-navigation.js
  libs/blocks/global-navigation/utilities/menu/menu.js
  libs/blocks/global-navigation/utilities/utilities.js
  test/blocks/global-navigation/global-navigation.test.js
  test/blocks/global-navigation/mocks/global-navigation.plain.js
  test/blocks/global-navigation/test-utilities.js
  test/blocks/global-navigation/utilities/utilities.test.js
Labels: verified, run-nala, new-feature

#1829 MWPW-140071 - CaaS Marquee Metadata Block
  libs/blocks/caas-marquee-metadata/caas-marquee-metadata.css
  libs/blocks/caas-marquee-metadata/caas-marquee-metadata.js
  tools/send-to-caas/send-utils.js
Labels: verified, CaaS

#1821 MWPW-141650 - [Icon Block] full-width alignment
  libs/blocks/icon-block/icon-block.css
  test/blocks/icon-block/icon-block.test.js
  test/blocks/icon-block/mocks/body.html
Labels: bug, verified, run-nala, @icon-block

#1831 MWPW-136891: Introduce Switch Modal feature
  libs/blocks/merch/README.md
  libs/blocks/merch/merch.css
  libs/blocks/merch/merch.js
  libs/blocks/merch/upgrade.js
  libs/blocks/modal/modal.css
  test/blocks/merch/merch.test.js
  test/blocks/merch/mocks/body.html
  test/blocks/merch/mocks/offers.json
  test/blocks/merch/upgrade.test.js
Labels: verified, run-nala, commerce

#1844 Quiz / question background fixes and quiz result analytics tagging
  libs/blocks/quiz-results/quiz-results.js
  libs/blocks/quiz/quiz.css
  libs/blocks/quiz/quizcontainer.js
  libs/blocks/quiz/quizoption.js
  test/blocks/quiz-results/mocks/body.html
  test/blocks/quiz-results/mocks/fragments/basic-frag.plain.html
  test/blocks/quiz-results/quiz-results.test.js
Labels: verified, run-nala

#1845 MWPW-142399-Fix for TwP modal not displaying in tablet viewports or smaller on Safari
  libs/blocks/modal/modal.css
Labels: run-nala, needs-verification

#1850 MWPW-142499-Fix link farm text block failing to load when no heading is added
  libs/blocks/text/text.js
Labels: verified

#1835 MWPW-142200 ability to add strikethrough fro price for Special offer
  libs/blocks/merch-card/merch-card.css
Labels: verified, trivial, commerce, merch card

#1852 MWPW-138460 Update entitlements and add support for stage and consumer entitlements
  libs/features/personalization/entitlements.js
  libs/features/personalization/personalization.js
  libs/features/personalization/stage-entitlements.js
  libs/utils/utils.js
  test/features/personalization/entitlements.test.js
  test/features/personalization/pageFilter.test.js
  test/features/personalization/personalization.test.js
  test/features/personalization/replacePage.test.js
Labels: trivial

#1851 Mwpw 140539: merch card outline CTA hover state
  libs/blocks/merch-card/merch-card.css
Labels: trivial

#1858 Mwpw 142568: OST-generated Merch CTA text not displaying
  libs/blocks/merch/merch.css
Labels: bug, verified, commerce

#1836 MWPW-141291 - Icon-block (inline) - Icon and title should `align-items: center`
  libs/blocks/icon-block/icon-block.css
  libs/blocks/icon-block/icon-block.js
Labels: verified

#1840 MWPW-142003: Mini Compare Chart Merch Card UX observations
  libs/blocks/merch-card/merch-card.js
  libs/blocks/merch-card/merch-offer-select.js
  libs/deps/merch-card.js
Labels: run-nala, commerce, needs-verification, merch card

#1841 MWPW-141560: unav unit tests
  libs/blocks/global-navigation/global-navigation.js
  test/blocks/global-navigation/global-navigation.test.js
  test/blocks/global-navigation/test-utilities.js
Labels: needs-verification

#1862 Correctly decorate SVGs in central navs
  libs/blocks/global-navigation/utilities/utilities.js
Labels: verified, run-nala-on-feds

#1818 MWPW-139296-Promo Aside Enhancement - Time Delay
  libs/blocks/section-metadata/section-metadata.js
  libs/blocks/section-metadata/sticky-section.js
  test/blocks/section-metadata/mocks/body.html
  test/blocks/section-metadata/section-meta.test.js
Labels: verified, run-nala, new-feature

#1781 MWPW-141638: Fix for commerce modals event listeners
  Icon 
  libs/blocks/merch-card/merch-card.js
  libs/blocks/modal/modal.css
  libs/blocks/modal/modal.js
  test/blocks/modals/modals.test.js
Labels: verified, run-nala, @modal

#1869 Mwpw 142003: Mini compare chart edge case scenario
  libs/blocks/merch-card/merch-card.js
Labels: bug, run-nala, commerce, needs-verification, merch card

#1863 MWPW-142249: checkout-link flows
  libs/blocks/global-navigation/utilities/getUserEntitlements.js
  libs/blocks/merch-offers/merch-offers.js
  libs/blocks/merch/merch.css
  libs/blocks/merch/merch.js
  libs/blocks/merch/upgrade.js
  libs/deps/commerce.js
  test/blocks/merch/merch.test.js
  test/blocks/merch/mocks/body.html
  test/blocks/merch/mocks/fetch.js
  test/blocks/merch/mocks/named-offers.json
  test/blocks/merch/upgrade.test.js
Labels: verified, run-nala, commerce, new-feature

#1865 MWPW-141314 - Make split marquee foreground img optional
  libs/blocks/marquee/marquee.js
Labels: trivial, run-nala, @marquee

#1859 MWPW-141539 update deps
  libs/deps/merch-card.js
  libs/deps/merch-offer-select.js
  libs/deps/merch-quantity-select.js
Labels: bug, verified, run-nala, commerce

#1868 MWPW-140438 - Add martech metadata tool to Preflight
  libs/blocks/preflight/panels/martech.js
  libs/blocks/preflight/preflight.css
  libs/blocks/preflight/preflight.js
Labels: verified, new-feature

#1886 MWPW-142249: disable entitlements by default
  libs/blocks/merch/merch.js
  libs/deps/commerce.js
  test/blocks/merch/mocks/body.html
Labels: bug, verified, run-nala, commerce

#1885 MWPW-142738 Force ims prod when sending to CaaS
  tools/send-to-caas/send-to-caas.js
Labels: trivial

#1867 MWPW-142630 - [Marquee] media style CLS
  libs/blocks/marquee/marquee.css
  libs/blocks/marquee/marquee.js
Labels: bug, verified, run-nala, @marquee

#1773 MWPW-141413 - JP - wbr tags are causing too many gaps in Firefox
  libs/features/japanese-word-wrap.js
Labels: verified, trivial

#1888 MWPW-142786: skip Download flow if url is empty
  libs/blocks/merch/merch.js
  test/blocks/merch/merch.test.js
Labels: trivial, run-nala, commerce

#1884 Change the adobe logo color in the GNAV
  libs/blocks/global-navigation/base.css
  libs/blocks/global-navigation/global-navigation.js
Labels: verified

#1882 MWPW-142617: Microsoft Edge & Chrome Win - progress bar not completely loaded
  libs/features/webapp-prompt/webapp-prompt.css
  libs/features/webapp-prompt/webapp-prompt.js
Labels: needs-verification

#1843 MWPW-142070 Performance improvements for target
  head.html
  libs/martech/martech.js
  libs/utils/utils.js
Labels: bug, trivial, run-nala

#1891 MWPW-142070 MEP Target Performance Improvements
  head.html
  libs/martech/martech.js
  libs/utils/utils.js
Labels: trivial

#1870 MWPW-142681 [MILO][MEP] Manifest replaceFragment selectors don't localize
  libs/blocks/fragment/fragment.js
  libs/features/personalization/personalization.js
  test/features/personalization/personalization.test.js
Labels: high-impact, verified, run-nala

#1846 MWPW-142433: Fixes various bugs in CaaS Marquee Metadata block
  libs/blocks/caas-marquee-metadata/caas-marquee-metadata.js
  tools/send-to-caas/send-utils.js
Labels: verified, run-nala, CaaS

#1876 MWPW-142250: Progress Circle for Switch Modal
  libs/blocks/merch/merch.css
  libs/blocks/merch/merch.js
  libs/blocks/merch/upgrade.js
  libs/features/spectrum-web-components/README.md
  libs/features/spectrum-web-components/dist/progress-circle.js
  libs/features/spectrum-web-components/src/progress-circle.js
  libs/utils/utils.js
  test/blocks/merch/merch.test.html
  test/blocks/merch/mocks/embed-utils.js
  test/blocks/merch/upgrade.test.html
  test/blocks/merch/upgrade.test.js
  test/features/spectrum-web-components/progress-circle.test.html
Labels: run-nala, commerce, needs-verification

#1894 MWPW-142630 - [Marquee] media CLS
  libs/blocks/marquee/marquee.css
  libs/blocks/marquee/marquee.js
Labels: bug, run-nala, @marquee, needs-verification

#1903 MWPW-142937-Fix spacing between share icons for RTL pages
  libs/blocks/share/share.css
Labels: verified

#1896 MWPW-141127: Create CaaS Marquee block for viewing component
  libs/blocks/caas-marquee/caas-marquee.css
  libs/blocks/caas-marquee/caas-marquee.js
Labels: new-feature, needs-verification, CaaS

#1905 Update martech.main.standard.qa.min.js
  libs/deps/martech.main.standard.qa.min.js
Labels: trivial

#1892 Verify that target content has manifest info
  libs/martech/martech.js
Labels: trivial

#1909 Adding caas-marquee and caas-marquee-medata to MILO BLOCKS
  libs/utils/utils.js
Labels: trivial

#1904 MWPW-142010 Fix capitalization and space in contextual search
  libs/blocks/gnav/gnav-contextual-search.js
  libs/blocks/gnav/gnav.js
  test/blocks/gnav/gnav-contextual-search.test.js
Labels: verified, run-nala

#1854 Mwpw 142278: Thumbnail icons are not aligned vertically on iPad- fix
  libs/blocks/icon-block/icon-block.css
Labels: bug, verified

#1899 [MWPW-142899] Add additional IMS scopes for Universal Navigation integration
  libs/scripts/scripts.js
  libs/utils/utils.js
Labels: high-impact, verified, run-nala

#1907 MWPW-142830-Play video only on hoverplay and not on page load
  libs/utils/decorate.js
  test/blocks/video/video.test.js
Labels: verified, new-feature

#1906 MWPW-142699 allowing empty defined value for PH
  libs/features/placeholders.js
  test/features/placeholders/placeholders.json
  test/features/placeholders/placeholders.test.js
Labels: verified, run-nala, needs-verification

#1912 MWPW-142782: prevent commerce overrides on PROD (adobe.com)
  libs/deps/commerce.js
Labels: verified, run-nala, commerce, needs-verification

#1791 MWPW-136885: More SEO-friendly, improved accessibility in merch cards
  libs/blocks/merch-card/merch-card.js
  test/blocks/merch-card/merch-card.test.js
  test/blocks/merch-card/mocks/special-offers.html
Labels: do not merge, run-nala, commerce, needs-verification, merch card

#1917 MWPW-143183: CaaS Marquee Performance Improvements
  libs/blocks/caas-marquee/caas-marquee.js
  libs/utils/utils.js
Labels: verified, CaaS

#1883 MWPW-142130: update the source of merch card name
  libs/blocks/merch-card/merch-card.js
  libs/blocks/merch-cards/merch-cards.js
  libs/deps/merch-card.js
  test/blocks/merch-card/merch-card.test.js
  test/blocks/merch-card/mocks/catalog.html
  test/blocks/merch-cards/mocks/merch-cards.html
Labels: verified, run-nala, commerce

#1927 Revert "MWPW-142130: update the source of merch card name"
  libs/blocks/merch-card/merch-card.js
  libs/blocks/merch-cards/merch-cards.js
  libs/deps/merch-card.js
  test/blocks/merch-card/merch-card.test.js
  test/blocks/merch-card/mocks/catalog.html
  test/blocks/merch-cards/mocks/merch-cards.html
Labels: trivial, run-nala
