Repository adobecom/milo, pull requests merged in 2024-11, with the labels that each got.

#3111 MWPW-161076 and 158127 MEP replace not working as expected
  libs/blocks/global-navigation/utilities/utilities.js
  libs/features/personalization/personalization.js
Labels: verified, high priority, Ready for Stage

#3115 MWPW-156940 AU price display
  libs/blocks/merch/au-merch.css
  libs/blocks/merch/merch.js
  libs/deps/mas/commerce.js
  libs/features/mas/commerce/internal/tacocat-consonant-templates-1.13.0.tgz
  libs/features/mas/commerce/internal/tacocat-consonant-templates-1.14.0.tgz
  libs/features/mas/commerce/package.json
  libs/features/mas/commerce/src/external.js
  libs/features/mas/commerce/src/price.js
  libs/features/mas/commerce/test/price.test.js
  libs/features/mas/mocks/snapshots.js
  test/blocks/merch/merch.test.js
Labels: verified, commerce, high priority, Ready for Stage

#3134 Adding support for clients to add their own stage domain maps
  libs/navigation/navigation.js
Labels: verified, high priority, Ready for Stage

#3016 MWPW-159032: Defaults to empty alt tag on the svg - Accessibility requirement
  libs/utils/utils.js
Labels: verified, Ready for Stage

#3090 MWPW-160239 [MEP] Support searching for placeholders in URLs
  libs/features/placeholders.js
  test/features/placeholders/placeholders.test.js
Labels: verified, Ready for Stage

#3094 MWPW-160511: badge & switch to AEM Prod
  libs/deps/mas/mas.js
  libs/deps/mas/merch-card.js
  libs/features/mas/build-docs.mjs
  libs/features/mas/docs/ccd.html
  libs/features/mas/docs/checkout-link.html
  libs/features/mas/docs/inline-price.html
  libs/features/mas/docs/mas.html
  libs/features/mas/docs/mas.js.html
  libs/features/mas/docs/merch-card.html
  libs/features/mas/docs/styles.css
  libs/features/mas/mas/dist/mas.js
  libs/features/mas/package-lock.json
  libs/features/mas/web-components/merch-card.md
  libs/features/mas/web-components/src/aem-fragment.js
  libs/features/mas/web-components/src/global.css.js
  libs/features/mas/web-components/src/merch-card.css.js
  libs/features/mas/web-components/src/merch-card.js
  libs/features/mas/web-components/src/variants/ccd-suggested.js
  test/blocks/notification/notification.test.js
Labels: verified, run-nala, commerce, Ready for Stage

#3098 MWPW-160058: Fixes tag matching case logic
  tools/send-to-caas/send-utils.js
Labels: trivial, caas-configurator, CaaS, Ready for Stage

#3104 MWPW-160094 - Set editorial card's footer Text CTA size
  libs/blocks/editorial-card/editorial-card.css
Labels: Ready for Stage

#3110 MWPW-159381: Removes 'body' overrides from caas.css
  libs/deps/caas.css
Labels: trivial, CaaS, Ready for Stage

#3112 [MWPW-160730] - Project Red logo update for adobecom and bacom
  libs/blocks/global-navigation/global-navigation.css
  libs/blocks/global-navigation/global-navigation.js
  libs/blocks/global-navigation/utilities/utilities.js
Labels: verified, high priority, Ready for Stage

#3139 Revert "MWPW-159381: Removes 'body' overrides from caas.css"
  libs/deps/caas.css
Labels: verified, Ready for Stage

#3141 Temporary workflow to watch for any feds files being changed
  .github/workflows/check-feds-files.js
  .github/workflows/check-feds-files.yaml
Labels: zero-impact

#3100 MWPW-161130 - [Table] Handle dynamic pricing in addon labels
  libs/blocks/table/table.css
  libs/blocks/table/table.js
  test/blocks/table/mocks/body.html
Labels: bug, verified, high priority, Ready for Stage

#3080 MWPW-157100: Merch card headers as p tags for Accessibility
  libs/blocks/merch-card/merch-card.css
  libs/blocks/merch-card/merch-card.js
  libs/blocks/merch-card/merch-offer-select.js
  libs/deps/mas/mas.js
  libs/deps/mas/merch-card.js
  libs/features/mas/mas/dist/mas.js
  libs/features/mas/package-lock.json
  libs/features/mas/web-components/src/global.css.js
  nala/blocks/merchcard/merchcard.pages.js
  nala/blocks/merchcard/merchcard.test.js
  test/blocks/merch-card/merch-card.test.js
  test/blocks/merch-card/mocks/catalog.html
  test/blocks/merch-card/mocks/plans-card.html
Labels: verified, commerce, merch card, Ready for Stage

#3095 MWPW-161101 load sidekick button css faster if already open
  libs/utils/sidekick-decorate.js
  libs/utils/utils.js
Labels: verified, Ready for Stage

#3128 MWPW-161174 fixed library query param
  libs/blocks/library-config/library-config.js
Labels: Ready for Stage

#3130 [MWPW-148000] [ANALYTICS] Add analytics to Modals
  libs/blocks/modal/modal.js
  libs/martech/attributes.js
  test/blocks/modals/modals.test.js
Labels: verified, Ready for Stage

#3133 MWPW-161025: Gnav is not loading in mobile for cc/all-apps AEM page
  libs/styles/styles.css
Labels: verified, Ready for Stage

#3145 Adding client's search component class to exclude from getting it clicked on keydown
  libs/blocks/global-navigation/utilities/keyboard/index.js
Labels: verified, high priority, Ready for Stage

#3149 [Nala] Fix failing promo code in Nala tests
  nala/features/commerce/commerce.spec.js
Labels: zero-impact

#3125 Carousel mWeb Enhancements
  libs/blocks/carousel/carousel.css
  libs/blocks/carousel/carousel.js
Labels: verified, new-feature, high priority, Ready for Stage

#3060 MWPW-160360 - Decorate standalone text with body default styles
  libs/blocks/marquee-anchors/marquee-anchors.js
  libs/utils/decorate.js
  test/blocks/text/mocks/body.html
Labels: bug, verified, Ready for Stage

#3101 [MWPW-154662] [Accessibility] Visual list is not marked up as list: section
  libs/blocks/merch-card/merch-card.js
  libs/deps/mas/mas.js
  libs/deps/mas/merch-card.js
  libs/features/mas/mas/dist/mas.js
  libs/features/mas/web-components/src/variants/mini-compare-chart.css.js
Labels: bug, verified, run-nala, commerce, Ready for Stage

#3120 [MWPW-161098] Links conversion localization support
  libs/scripts/scripts.js
  libs/utils/utils.js
  test/utils/utils.test.js
Labels: Ready for Stage

#3126 MWPW-160966 Fix next-gen sidekick preflight
  libs/blocks/preflight/panels/seo.js
Labels: verified, Ready for Stage

#3137 MWPW-159032: Accessibility requirements floating label
  libs/blocks/review/components/review/Comments.js
  libs/blocks/review/review.css
Labels: verified, Ready for Stage, DC SOT 👌

#3144 [MWPW-160719] - Support media only in Editorial-Card
  libs/blocks/editorial-card/editorial-card.css
  libs/blocks/editorial-card/editorial-card.js
  test/blocks/editorial-card/editorial-card.test.js
  test/blocks/editorial-card/mocks/body.html
Labels: Ready for Stage

#2986 MWPW-140452 - Icon authoring in milo using the federal repo and individual SVG assets
  libs/blocks/text/text.css
  libs/features/georoutingv2/georoutingv2.css
  libs/features/georoutingv2/georoutingv2.js
  libs/features/icons/icons.js
  libs/styles/styles.css
  libs/utils/utils.js
  test/features/icons/icons.test.js
  test/features/icons/mocks/body.html
Labels: high-impact, Ready for Stage

#3117 MWPW-159374: Support MAS switch to Prosemirror RTE
  libs/deps/mas/commerce.js
  libs/deps/mas/mas.js
  libs/deps/mas/merch-card.js
  libs/features/mas/commerce/src/checkout-link.js
  libs/features/mas/commerce/src/inline-price.js
  libs/features/mas/commerce/test/checkout.test.js
  libs/features/mas/commerce/test/price.test.js
  libs/features/mas/mas/dist/mas.js
  libs/features/mas/package-lock.json
  libs/features/mas/web-components/src/global.css.js
  libs/features/mas/web-components/src/hydrate.js
  libs/features/mas/web-components/src/variants/catalog.js
  libs/features/mas/web-components/src/variants/ccd-action.js
  libs/features/mas/web-components/src/variants/ccd-slice.js
  libs/features/mas/web-components/src/variants/ccd-suggested.js
  libs/features/mas/web-components/src/variants/special-offer.js
  libs/features/mas/web-components/test/hydrate.test.js
  libs/features/mas/web-components/test/mas.js
Labels: verified, commerce, Ready for Stage

#3169 MWPW-161176: restructure ccd gallery
  libs/features/mas/docs/ccd.html
Labels: commerce

#3019 [MWPW-160011] - GNAV light mode color changes
  libs/blocks/global-navigation/base.css
  libs/blocks/global-navigation/dark-nav.css
  libs/blocks/global-navigation/global-navigation.css
  libs/blocks/global-navigation/utilities/menu/menu.css
  libs/navigation/navigation.css
Labels: verified, high priority, Ready for Stage

#3142 MWPW-161590, 161606, 161871, 161987 [MEP] Update placeholders before updating href
  libs/blocks/fragment/fragment.js
  libs/features/personalization/personalization.js
  test/features/personalization/actions.test.js
  test/features/personalization/mocks/actions/manifestUpdate.json
  test/features/personalization/parseNestedPlaceholders.test.js
Labels: verified, high priority, Ready for Stage

#3162 [MWPW-161782] - Added logo changes for older GNAV experience
  libs/blocks/gnav/gnav.css
  libs/blocks/gnav/gnav.js
Labels: verified, high priority, Ready for Stage

#3168 [MWPW-161563] CDT Overlap in Global and APAC Promotion file
  libs/features/cdt/cdt.js
  libs/features/personalization/promo-utils.js
  test/features/cdt/cdt.test.js
  test/features/personalization/mocks/head-schedule.html
  test/features/personalization/promo-utils.test.js
Labels: verified, run-nala, commerce, high priority, critical, Ready for Stage

#3103 [MWPW-157451] [Accessibility] Merch cards | Focus is lost on comparing plans section
  libs/blocks/tabs/tabs.js
  libs/deps/mas/commerce.js
  libs/deps/mas/mas.js
  libs/deps/mas/merch-card.js
  libs/features/mas/mas/dist/mas.js
  libs/features/mas/web-components/src/merch-card.js
Labels: bug, verified, run-nala, commerce, merch card, Ready for Stage

#3152 MWPW-159381: Replaces CSS 'body *' with '.consonant-Wrapper *'
  libs/deps/caas.css
Labels: verified, trivial, CaaS, Ready for Stage

#3159 [MWPW-160948] Remove blockquote default spacing
  libs/styles/styles.css
Labels: Ready for Stage

#3165 [MWPW-161098] Environment-aware links support for CaaS
  libs/blocks/caas/utils.js
  test/blocks/caas/utils.test.js
Labels: Ready for Stage

#3180 [MWPW-162059] - Fix for vertical alignment of logo on AH
  libs/navigation/navigation.css
Labels: verified, Ready for Stage

#3166 Global links underlined by default
  libs/blocks/card-horizontal/card-horizontal.css
  libs/blocks/global-footer/global-footer.css
  libs/blocks/marquee-anchors/marquee-anchors.css
  libs/blocks/text/link-farms.css
  libs/styles/iconography.css
  libs/styles/styles.css
Labels: high-impact, high priority, Ready for Stage

#3136 MWPW-161289 Catalog CTA IMS country used in commerce calls
  libs/deps/mas/commerce.js
  libs/deps/mas/mas.js
  libs/features/mas/commerce/src/checkout-link.js
  libs/features/mas/mas/dist/mas.js
Labels: verified, commerce, Ready for Stage

#3140 Helix 5 support for milo blocks and features
  .github/PULL_REQUEST_TEMPLATE/gnav.md
  .github/pull_request_template.md
  .github/workflows/merge-to-stage.js
  .github/workflows/update-script.js
  CONTRIBUTING.md
  README.md
  codecov.yaml
  helix-query.yaml
  libs/blocks/bulk-publish-v2/utils.js
  libs/blocks/caas-marquee/caas-marquee.js
  libs/blocks/caas/caas.js
  libs/blocks/library-config/library-config.js
  libs/blocks/marketo/marketo.js
  libs/blocks/merch/merch.js
  libs/blocks/ost/README.md
  libs/blocks/pdf-viewer/README.md
  libs/blocks/pdf-viewer/pdf-viewer.js
  libs/blocks/preflight/panels/seo.js
  libs/blocks/quiz-entry/quiz-entry.css
  libs/blocks/section-metadata/README.md
  libs/blocks/version-history/index.js
  libs/features/personalization/personalization.js
  libs/features/title-append/README.md
  libs/mep/ace0861/section-metadata/README.md
  libs/navigation/navigation.js
  libs/scripts/delayed.js
  libs/scripts/scripts.js
  libs/utils/federated.js
  libs/utils/service-config.js
  libs/utils/utils.js
  nala/blocks/video/video.spec.js
  nala/utils/global.setup.js
  nala/utils/nala.run.js
  nala/utils/pr.run.sh
  playwright.config.js
  test/blocks/aside/mocks/body.html
  test/blocks/bulk-publish-v2/bulk-publish-v2.test.js
  test/blocks/bulk-publish-v2/mocks/response/retry.json
  test/blocks/caas/mocks/utils.js
  test/blocks/global-navigation/global-navigation.test.js
  test/blocks/global-navigation/test-utilities.js
  test/blocks/global-navigation/utilities/utilities.test.js
  test/blocks/marketo/mocks/marketo-utils.js
  test/blocks/merch/mocks/embed-utils.js
  test/blocks/ost/mocks/ost-utils.js
  test/features/personalization/actions.test.js
  test/navigation/mocks/gnav.html
  test/utils/federated.test.js
  test/utils/mocks/body-gnav.html
  tools/loc/utils.js
  tools/send-to-caas/bulk-publish-to-caas.js
  tools/send-to-caas/send-utils.js
  tools/sidekick/config.json
Labels: Ready for Stage

#3107 MWPW-160292 Next gen sidekick publish button
  libs/utils/sidekick-decorate.js
  libs/utils/sidekick.js
  libs/utils/utils.js
  tools/sidekick/config.json
Labels: verified, Ready for Stage

#3097 MWPW-161243 [MEP] add nala-test folder to mep folder
  libs/mep/nala-test/insertscript-test.js
Labels: verified, zero-impact, Ready for Stage

#3170 [MWPW-161698] - Add two up in mobile for Editorial Card
  libs/blocks/editorial-card/editorial-card.css
Labels: high priority, Ready for Stage

#3105 MWPW-156089: See what's included modal additional white space issue
  libs/blocks/modal/modal.css
  libs/blocks/modal/modal.js
  libs/blocks/modal/modal.merch.js
Labels: verified, run-nala, commerce, Ready for Stage

#3131 MWPW-161170: Multiple UI CCD Slice/suggested merch card fixes
  libs/deps/mas/commerce.js
  libs/deps/mas/mas.js
  libs/deps/mas/merch-card.js
  libs/features/mas/docs/ccd.html
  libs/features/mas/mas/dist/mas.js
  libs/features/mas/web-components/src/global.css.js
  libs/features/mas/web-components/src/hydrate.js
  libs/features/mas/web-components/src/merch-card.css.js
  libs/features/mas/web-components/src/variants/ccd-slice.css.js
  libs/features/mas/web-components/src/variants/ccd-slice.js
  libs/features/mas/web-components/src/variants/ccd-suggested.css.js
  libs/features/mas/web-components/src/variants/ccd-suggested.js
  libs/features/mas/web-components/src/variants/variant-layout.js
Labels: verified, commerce, merch card, Ready for Stage

#3176 MWPW-160237: Caas Bulk Publisher v2 (Beta)
  tools/send-to-caas/bulk-publish-to-caas.beta.js
  tools/send-to-caas/bulkpublish.beta.css
  tools/send-to-caas/bulkpublisher.beta.html
Labels: trivial, CaaS, Ready for Stage

#3193 [MWPW-140627] [MEP] Replace MEP placeholders when loading fragments
  libs/blocks/fragment/fragment.js
  test/blocks/fragment/fragment.test.js
  test/blocks/fragment/mocks/fragments/fragment.plain.html
Labels: verified, Ready for Stage

#3194 MWPW-141870: Update seotech-video-url API endpoint
  libs/features/seotech/README.md
  libs/features/seotech/seotech.js
  test/features/seotech/seotech.test.js
  test/utils/utils.test.js
Labels: Ready for Stage

#3167 MWPW-160926: [Loc] Core Components for LocUI
  libs/blocks/locui-create/components/stepControls.js
  libs/blocks/locui-create/components/stepTracker.js
  libs/blocks/locui-create/fragments/index.js
  libs/blocks/locui-create/fragments/modal.js
  libs/blocks/locui-create/fragments/view.js
  libs/blocks/locui-create/img/analytics-icon.svg
  libs/blocks/locui-create/img/home-icon.svg
  libs/blocks/locui-create/img/logo.svg
  libs/blocks/locui-create/img/plugins-icon.svg
  libs/blocks/locui-create/input-actions/index.js
  libs/blocks/locui-create/input-actions/modal.js
  libs/blocks/locui-create/input-actions/view.js
  libs/blocks/locui-create/input-locale/index.js
  libs/blocks/locui-create/input-locale/view.js
  libs/blocks/locui-create/input-urls/index.js
  libs/blocks/locui-create/input-urls/view.js
  libs/blocks/locui-create/locui-create.css
  libs/blocks/locui-create/locui-create.js
  libs/blocks/locui-create/store.js
  libs/blocks/locui/actions/index.js
  libs/blocks/milostudio-header/header.js
  libs/blocks/milostudio-sidenav/sidenav.js
Labels: trivial, zero-impact

#3207 [LOC] MWPW-161619 - Handled validation when no fragment is there
  libs/blocks/locui-create/fragments/view.js
  libs/blocks/locui-create/input-urls/index.js
  libs/blocks/locui-create/input-urls/view.js
Labels: trivial, zero-impact

#3219 MWPW-160919: [Loc] CSS updation for the language selection screen.
  libs/blocks/locui-create/locui-create.css
Labels: trivial

#3206 MWPW-161845: basic analytics on mas cards
  libs/deps/mas/commerce.js
  libs/deps/mas/mas.js
  libs/deps/mas/merch-card.js
  libs/features/mas/mas/dist/mas.js
  libs/features/mas/web-components/src/hydrate.js
  libs/features/mas/web-components/src/merch-card.js
  libs/features/mas/web-components/test/hydrate.test.js
Labels: verified, commerce

#3227 [Loc][MWPW-162545] Moved stepper to the bottom and minor css fixes
  libs/blocks/locui-create/components/stepControls.js
  libs/blocks/locui-create/img/check-mark.svg
  libs/blocks/locui-create/img/logo-4f4133ca.svg
  libs/blocks/locui-create/img/logo.svg
  libs/blocks/locui-create/input-actions/modal.js
  libs/blocks/locui-create/input-actions/view.js
  libs/blocks/locui-create/input-locale/view.js
  libs/blocks/locui-create/input-urls/view.js
  libs/blocks/locui-create/locui-create.css
  libs/blocks/locui-create/locui-create.js
Labels: trivial, zero-impact

#3228 [Loc] MWPW-161619 - minor html and css fixes
  libs/blocks/locui-create/fragments/view.js
  libs/blocks/locui-create/input-urls/view.js
  libs/blocks/locui-create/locui-create.css
Labels: trivial, zero-impact

#3209 MWPW-159191: MAS Freyja support
  libs/deps/mas/commerce.js
  libs/deps/mas/mas.js
  libs/deps/mas/merch-card.js
  libs/features/mas/docs/ccd.html
  libs/features/mas/mas/dist/mas.js
  libs/features/mas/mas/package.json
  libs/features/mas/mocks/aem.js
  libs/features/mas/mocks/sites/cf/fragments/fragment-cc-all-apps-badge.json
  libs/features/mas/mocks/sites/cf/fragments/fragment-cc-all-apps.json
  libs/features/mas/mocks/sites/cf/fragments/fragment-photoshop.json
  libs/features/mas/mocks/sites/cf/fragments/search/authorPayload.json
  libs/features/mas/mocks/sites/fragments/fragment-cc-all-apps-badge.json
  libs/features/mas/mocks/sites/fragments/fragment-cc-all-apps.json
  libs/features/mas/mocks/sites/fragments/fragment-photoshop.json
  libs/features/mas/web-components/src/aem-fragment.js
  libs/features/mas/web-components/src/getFragmentById.js
  libs/features/mas/web-components/src/global.css.js
  libs/features/mas/web-components/src/hydrate.js
  libs/features/mas/web-components/test/aem-fragment.test.html
  libs/features/mas/web-components/test/aem-fragment.test.html.js
  libs/features/mas/web-components/test/getFragmentById.test.js
  libs/features/mas/web-components/test/hydrate.test.js
Labels: verified, commerce

#3216 MWPW-161804: Merch card style auditing
  libs/deps/mas/mas.js
  libs/deps/mas/merch-card.js
  libs/features/mas/mas/dist/mas.js
  libs/features/mas/web-components/src/global.css.js
Labels: verified, commerce, merch card

#3196 Added space after price recurrence label for display-per-unit prices
  libs/deps/mas/mas.js
  libs/deps/mas/merch-card.js
  libs/features/mas/mas/dist/mas.js
  libs/features/mas/web-components/src/global.css.js
Labels: verified, commerce

#3246 [Loc][MWPW-162813] Fixed action screen ui, added validation
  libs/blocks/locui-create/input-actions/index.js
  libs/blocks/locui-create/input-actions/modal.js
  libs/blocks/locui-create/input-actions/view.js
  libs/blocks/locui-create/locui-create.css
Labels: trivial, zero-impact

#3260 [LOC] MWPW 162874: Removing duplicate urls from enter urls textarea
  libs/blocks/locui-create/input-urls/view.js
Labels: trivial, zero-impact

#3256 MWPW-160755 - add tests for CCD cards
  nala/features/masccd/masccd.page.js
  nala/features/masccd/masccd.spec.js
  nala/features/masccd/masccd.test.js
Labels: zero-impact

#3269 [LOC] MWPW-163183 - fixed cta issue when no fragments is selected
  libs/blocks/locui-create/fragments/view.js
  libs/blocks/locui-create/input-urls/index.js
  libs/blocks/locui-create/input-urls/view.js
Labels: trivial, zero-impact

#3270 [LOC] MWPW-163209 - Removed Fragment sections when invalid or empty urls
  libs/blocks/locui-create/input-urls/view.js
Labels: trivial, zero-impact

#3203 MWPW-162385 add wcsApiKey attribute
  libs/deps/mas/commerce.js
  libs/deps/mas/mas.js
  libs/deps/mas/merch-card-collection.js
  libs/deps/mas/merch-card.js
  libs/deps/mas/merch-icon.js
  libs/deps/mas/merch-mnemonic-list.js
  libs/deps/mas/merch-offer-select.js
  libs/deps/mas/merch-secure-transaction.js
  libs/deps/mas/merch-sidenav.js
  libs/deps/mas/merch-stock.js
  libs/deps/mas/merch-subscription-panel.js
  libs/deps/mas/merch-twp-d2p.js
  libs/deps/mas/merch-whats-included.js
  libs/features/mas/dist/mas.js
  libs/features/mas/docs/mas.js.html
  libs/features/mas/docs/src/mas.js.md
  libs/features/mas/src/mas-commerce-service.js
  libs/features/mas/test/mas-commerce-service.test.js
Labels: verified, commerce

#3279 [LOC] Mwpw 162810 issues screen one
  libs/blocks/locui-create/input-urls/view.js
  libs/blocks/locui-create/locui-create.css
  libs/blocks/locui-create/locui-create.js
  libs/blocks/milostudio-header/header.js
  libs/blocks/milostudio-header/img/logo-4f4133ca.svg
  libs/blocks/milostudio-header/milostudio-header.css
  libs/blocks/milostudio-header/milostudio-header.js
Labels: trivial, zero-impact

#3280 [LOC]Mwpw 162810 fixed padding issue
  libs/blocks/locui-create/input-locale/view.js
Labels: trivial, zero-impact

#3257 MWPW-163041: analytics fix
  README.md
  libs/deps/mas/commerce.js
  libs/deps/mas/mas.js
  libs/deps/mas/merch-card-collection.js
  libs/deps/mas/merch-card.js
  libs/deps/mas/merch-icon.js
  libs/deps/mas/merch-mnemonic-list.js
  libs/deps/mas/merch-offer-select.js
  libs/deps/mas/merch-secure-transaction.js
  libs/deps/mas/merch-sidenav.js
  libs/deps/mas/merch-stock.js
  libs/deps/mas/merch-subscription-panel.js
  libs/deps/mas/merch-twp-d2p.js
  libs/deps/mas/merch-whats-included.js
  libs/features/mas/dist/mas.js
  libs/features/mas/docs/checkout-link.html
  libs/features/mas/docs/mas.html
  libs/features/mas/docs/merch-card.html
  libs/features/mas/docs/src/checkout-link.md
  libs/features/mas/docs/src/mas.md
  libs/features/mas/docs/src/merch-card.md
  libs/features/mas/src/hydrate.js
  libs/features/mas/src/variants/ccd-slice.js
  libs/features/mas/test/hydrate.test.js
  nala/features/masccd/masccd.spec.js
  nala/features/masccd/masccd.test.js
Labels: verified, commerce

#3278 Fix overriding of border style on merch cards
  libs/deps/mas/mas.js
  libs/deps/mas/merch-card.js
  libs/features/mas/dist/mas.js
  libs/features/mas/src/merch-card.css.js
  libs/features/mas/src/merch-card.js
  libs/features/mas/src/variants/ccd-slice.js
Labels: verified

#3282 Bump timeout from 2 to 10 sec
  libs/deps/mas/mas.js
  libs/deps/mas/merch-card.js
  libs/features/mas/dist/mas.js
  libs/features/mas/src/merch-card.js
Labels: verified, commerce

#3174 MWPW-162057 [MEP][NALA]add nala test for new features from PR 2683 "allow HTML"
  nala/features/personalization/allowhtml.spec.js
  nala/features/personalization/allowhtml.test.js
Labels: verified, zero-impact, Ready for Stage

#3175 MWPW-162093 [MEP][NALA] add 2 more legacy tests
  nala/features/personalization/personalization.spec.js
  nala/features/personalization/personalization.test.js
Labels: verified, zero-impact, Ready for Stage

#3214 [NALA][MWPW-162670] Enhance Nala Framework and Tests for Execution on DA-BACOM Repository and Branches
  nala/utils/nala.run.js
Labels: zero-impact, Ready for Stage

#3225 MWPW-162777 [MEP] [NALA] add code to marquee.css for CSS change
  libs/mep/sample-block-code/marquee/marquee.css
Labels: verified, zero-impact, Ready for Stage

#3229 MWPW-162833 [nala][MEP] confirm the "any-marquee-section" selector
  nala/features/personalization/any-marquee-section.spec.js
  nala/features/personalization/any-marquee-section.test.js
Labels: verified, zero-impact, Ready for Stage

#3205 MWPW-161587 - Support typed query indexes
  libs/blocks/article-feed/article-helpers.js
  test/blocks/article-feed/article-helpers.test.js
Labels: high priority, Ready for Stage

#3232 New modal option to support tall videos
  libs/blocks/modal-metadata/modal-metadata.js
  libs/blocks/modal/modal.css
  libs/blocks/section-metadata/section-metadata.js
Labels: verified, high priority, Ready for Stage

#3239 MWPW-162905 [Analytics] Analytics for content in tab containers needs improvement
  libs/blocks/martech-metadata/martech-metadata.js
  libs/blocks/tabs/tabs.js
  libs/martech/attributes.js
  test/martech/attributes.test.js
  test/martech/mocks/body.html
Labels: verified, high priority, Ready for Stage

#3243 Poster play button update
  libs/styles/consonant-play-button.css
  libs/utils/image-video-link.js
Labels: verified, high priority, Ready for Stage
