Repository adobecom/milo, pull requests merged in 2024-09, with the labels that each got.

#2683 [MWPW-155566] [MEP] Allow relevant actions in MEP to use text and HTML instead of just fragments
  libs/features/personalization/personalization.js
  libs/features/personalization/preview.js
  test/features/personalization/actions.test.js
  test/features/personalization/actionsTargetManifestId.test.js
  test/features/personalization/mocks/actions/manifestInsertAfter.json
  test/features/personalization/mocks/actions/manifestInsertBefore.json
  test/features/personalization/mocks/actions/manifestTargetUpdate.json
  test/features/personalization/mocks/actions/manifestUpdate.json
  test/features/personalization/mocks/manifestSectionBlock.json
  test/features/personalization/mocks/personalization.html
  test/features/personalization/modifyNonFragmentSelector.test.js
  test/features/personalization/personalization-params.test.js
  test/features/personalization/personalization.test.js
Labels: verified, run-nala, high priority, Ready for Stage

#2765 MWPW-156793 [MILO][Analytics] Change char limit for headers based on MD
  libs/martech/attributes.js
  test/martech/attributes.test.js
  test/martech/mocks/body.html
Labels: verified, run-nala, high priority, Ready for Stage

#2806 MWPW-157540: fix external modals
  libs/blocks/merch/merch.js
Labels: verified, run-nala, commerce, high priority, Ready for Stage

#2674 Mwpw 142267: What's included style fixes
  libs/deps/mas/merch-mnemonic-list.js
  libs/deps/mas/merch-whats-included.js
  libs/features/mas/web-components/src/merch-mnemonic-list.js
  libs/features/mas/web-components/src/merch-whats-included.js
Labels: verified, run-nala, commerce, merch card, Ready for Stage

#2707 MWPW-156810: adding caas config change for live CTAs
  libs/blocks/caas-config/caas-config.js
  libs/blocks/caas/utils.js
  test/blocks/caas-config/caas-config.test.html
  test/blocks/caas-config/expectedConfigs/defaultConfig.js
  test/blocks/caas/utils.test.js
Labels: verified, caas-configurator, CaaS, Ready for Stage

#2723 MWPW-156672: refactor commerce & optimize pandora dependencies
  libs/deps/commerce.js
  libs/deps/mas/commerce.js
  libs/deps/mas/mas.js
  libs/features/mas/commerce/internal/data-source-wcs-0.2.8.tgz
  libs/features/mas/commerce/internal/eslint-config-tacocat-1.1.2.tgz
  libs/features/mas/commerce/internal/react-auth-provider-1.2.1.tgz
  libs/features/mas/commerce/internal/react-env-provider-1.2.2.tgz
  libs/features/mas/commerce/internal/react-fetch-provider-1.2.2.tgz
  libs/features/mas/commerce/internal/tacocat-core-1.12.2.tgz
  libs/features/mas/commerce/internal/tacocat-core-1.13.0.tgz
  libs/features/mas/commerce/internal/tacocat-wcs-client-1.17.0.tgz
  libs/features/mas/commerce/libs/commerce.d.ts
  libs/features/mas/commerce/package.json
  libs/features/mas/commerce/src/constants.js
  libs/features/mas/commerce/src/defaults.js
  libs/features/mas/commerce/src/external.js
  libs/features/mas/commerce/src/index.d.ts
  libs/features/mas/commerce/src/index.js
  libs/features/mas/commerce/src/settings.js
  libs/features/mas/commerce/src/wcs.js
  libs/features/mas/commerce/test/settings.test.js
  libs/features/mas/commerce/test/wcs.test.js
  libs/features/mas/package-lock.json
Labels: verified, run-nala, commerce, Ready for Stage

#2727 MWPW-154209 - [hero-marquee] bugs
  libs/blocks/hero-marquee/hero-marquee.css
  libs/blocks/hero-marquee/hero-marquee.js
Labels: needs-verification, Ready for Stage

#2730 Dark nav for standalone Gnav
  libs/blocks/global-footer/global-footer.css
  libs/blocks/global-footer/global-footer.js
  libs/blocks/global-navigation/base.css
  libs/blocks/global-navigation/dark-nav.css
  libs/blocks/global-navigation/features/profile/dropdown.css
  libs/blocks/global-navigation/features/search/gnav-search.css
  libs/blocks/global-navigation/global-navigation.css
  libs/blocks/global-navigation/global-navigation.js
  libs/blocks/global-navigation/utilities/menu/menu.css
  libs/blocks/global-navigation/utilities/utilities.js
  libs/navigation/navigation.css
  libs/navigation/navigation.js
  libs/styles/styles.css
  test/blocks/global-footer/global-footer.test.js
  test/blocks/global-footer/test-utilities.js
  test/blocks/global-navigation/global-navigation.test.js
  test/blocks/global-navigation/mocks/adobe-dark-logo.svg
  test/blocks/global-navigation/mocks/dark-global-navigation.plain.js
Labels: verified, run-nala, Ready for Stage

#2770 MWPW-157034 [MEP] move call for preview from loadPostLCP to loadDeferred
  libs/utils/utils.js
Labels: verified, Ready for Stage

#2772 [MWPW-152968] mWeb - Passing ECID to Branch.io banner - Implementation
  libs/blocks/mobile-app-banner/mobile-app-banner.js
  test/blocks/mobile-app-banner/mobile-app-banner.test.js
Labels: verified, Ready for Stage

#2776 MWPW-153372 - Add ability to further customize buttons
  libs/utils/decorate.js
  test/blocks/text/mocks/body.html
Labels: verified, run-nala, Ready for Stage

#2785 MWPW-156126 - quiz-entry contrast and accessibility
  libs/blocks/quiz-entry/quiz-entry.css
  libs/blocks/quiz-entry/quizoption.js
Labels: verified, uar, Ready for Stage

#2795 MWPW-157346:[NALA] Move Nala tests to Milo repository
  .gitignore
  nala/.nala-snippets/spec-snippet.code-snippets
  nala/blocks/accordion/accordion.page.js
  nala/blocks/accordion/accordion.spec.js
  nala/blocks/accordion/accordion.test.js
  nala/features/georouting/georouting.page.js
  nala/features/georouting/georouting.spec.js
  nala/features/georouting/georouting.test.js
  nala/libs/baseurl.js
  nala/libs/webutil.js
  nala/utils/base-reporter.js
  nala/utils/global.setup.js
  nala/utils/nala.run.js
  nala/utils/slack.js
  package-lock.json
  package.json
  playwright.config.js
Labels: run-nala, Ready for Stage

#2809 [MWPW-157556] Eagerly import lit from merch-card block
  libs/blocks/merch-card/merch-card.js
Labels: commerce, Ready for Stage

#2786 [MWPW-148140] Adjust table strikethrough pricing
  libs/blocks/table/table.css
Labels: Ready for Stage

#2752 Parallelize Placeholder loading for an LCP improvement
  libs/blocks/chart/chart.js
  libs/blocks/fragment/fragment.js
  libs/features/placeholders.js
  libs/utils/helpers.js
  libs/utils/utils.js
  test/blocks/caas/mocks/utils.js
  test/blocks/instagram/mocks/embed-utils.js
  test/blocks/marketo/mocks/marketo-utils.js
  test/blocks/merch/mocks/embed-utils.js
  test/blocks/ost/mocks/ost-utils.js
  test/blocks/slideshare/mocks/utils.js
  test/utils/helpers.test.js
  test/utils/utils.test.js
Labels: run-nala, Ready for Stage

#2800 MWPW-151932 - Section metadata style grid enhancement for tablet VP
  libs/blocks/section-metadata/section-metadata.css
Labels: needs-verification, Ready for Stage

#2667 MWPW-154448: Content should be in a data table but is not
  libs/blocks/table/table.js
Labels: verified, Ready for Stage

#2780 MWPW-156866 [MILO][MEP] Create martech metadata table if placeholders are used in non EN page
  libs/features/personalization/personalization.js
  libs/martech/attributes.js
  test/features/personalization/createMartechMetadata.test.js
  test/features/personalization/mocks/placeholders.js
  test/martech/attributes.test.js
Labels: verified, run-nala, Ready for Stage

#2805 MWPW-157445 Additional Lana LCP data
  libs/utils/logWebVitals.js
  test/utils/logWebVitals.test.js
Labels: Ready for Stage

#2750 Fix video CLS netting +10 lighthouse points
  libs/blocks/adobetv/adobetv.js
  libs/blocks/figure/figure.js
  libs/blocks/video/video.js
  libs/utils/decorate.js
  test/blocks/adobetv/adobetv.test.js
  test/blocks/adobetv/mocks/body.html
  test/blocks/marquee/marquee.test.js
  test/blocks/video/mocks/body.html
  test/blocks/video/video.test.js
Labels: run-nala, Ready for Stage

#2817 MWPW-156265 - [LocUI] Pass loc ui url during create-project to loc service
  libs/blocks/locui/utils/miloc.js
Labels: zero-impact

#2812 [MWPW-156244] Reduce TBT Youtube/Vimeo Videos
  libs/blocks/vimeo/vimeo.css
  libs/blocks/vimeo/vimeo.js
  libs/blocks/youtube/youtube.css
  libs/blocks/youtube/youtube.js
  test/blocks/instagram/mocks/embed-utils.js
  test/blocks/vimeo/mocks/placeholders.js
  test/blocks/vimeo/vimeo.test.html
  test/blocks/youtube/youtube.test.html
Labels: Ready for Stage

#2804 [MWPW-157017] Send a Link Feature - Implementation
  libs/styles/styles.css
  libs/utils/utils.js
  test/utils/mocks/body.html
  test/utils/utils.test.js
Labels: verified, new-feature, high priority, critical, Ready for Stage

#2793 MWPW-146258: [UNav] CTA text alignment is not center in CTA in UNAV for some locales.
  libs/blocks/global-navigation/global-navigation.css
Labels: verified, Ready for Stage

#2828 MWPW-157761: Tab preselect in external modals [catalog]
  libs/blocks/merch/merch.js
Labels: verified, commerce, high priority, Ready for Stage

#2739 MWPW-155720: Dynamic nav ignore values
  libs/features/dynamic-navigation.js
  test/features/dynamic-nav/dynamicNav.test.js
  test/features/dynamic-nav/mocks/on-ignore-does-not-match.html
  test/features/dynamic-nav/mocks/on-ignore-match.html
  test/features/dynamic-nav/mocks/on-ignore-misspelled.html
  test/features/dynamic-nav/mocks/on-ignore-no-content.html
  test/features/dynamic-nav/mocks/on-ignore-some-matches.html
Labels: verified, run-nala, Ready for Stage

#2827 MWPW-157693 [MEP] Action area simplified selector does not work well with hero-marquee block
  libs/features/personalization/personalization.js
  test/features/personalization/modifyNonFragmentSelector.test.js
Labels: verified, Ready for Stage

#2744 fix(MWPW-148801):Added two New sticky header variants.
  libs/blocks/table/table.css
  libs/blocks/table/table.js
Labels: verified, Ready for Stage

#2771 MWPW-156135 - [editorial-card] bugs
  libs/blocks/editorial-card/editorial-card.css
  libs/blocks/editorial-card/editorial-card.js
  libs/blocks/text/text.css
  libs/styles/styles.css
  libs/utils/decorate.js
Labels: needs-verification, Ready for Stage

#2788 MWPW-155694 Dispatch sticky close event for dynamic chat
  libs/blocks/aside/aside.js
  libs/blocks/notification/notification.js
  libs/blocks/section-metadata/section-metadata.css
Labels: verified, Ready for Stage

#2841 MWPW-157292: CC and DC: Phone number links wrong
  libs/features/placeholders.js
  libs/utils/utils.js
  test/utils/mocks/body.html
  test/utils/utils.test.js
Labels: verified, Ready for Stage

#2832 MWPW-157785 [MEP] Create "any-marquee" and "header" simplified selectors
  libs/features/personalization/personalization.js
  test/features/personalization/modifyNonFragmentSelector.test.js
Labels: verified, Ready for Stage

#2801 MWPW-156865 - Hero marquee supports heading element on detail text.
  libs/blocks/hero-marquee/hero-marquee.js
  libs/utils/decorate.js
Labels: needs-verification, Ready for Stage

#2845 [MWPW-157980] Update RCP dates
  .github/workflows/helpers.js
Labels: zero-impact

#2829 MWPW-157701 [Fast-follow] - Add'l Pill updates
  libs/blocks/notification/notification.css
Labels: run-nala, needs-verification, high priority, Ready for Stage

#2826 [MWPW-157334] Table pricing alignment
  libs/blocks/table/table.css
Labels: run-nala, Ready for Stage

#2838 Adding support for getting env config through client env
  libs/navigation/navigation.js
  libs/utils/utils.js
Labels: verified, Ready for Stage

#2843 MWPW-157887 [MEP] HTML elements like body need to be recognized and header simplified selector rename
  libs/features/personalization/personalization.js
  test/features/personalization/modifyNonFragmentSelector.test.js
Labels: verified, Ready for Stage

#2822 MWPW-156365 - Text Block tiger team updates
  libs/blocks/text/text.css
  libs/blocks/text/text.js
  test/blocks/text/mocks/body.html
Labels: high-impact, run-nala, needs-verification, Ready for Stage

#2848 Set expiry of 'international' cookie for 1 year for selection of region from region selector
  libs/blocks/region-nav/region-nav.js
Labels: verified, Ready for Stage

#2854 MWPW-158059 [MEP] PHONE_SIZE limit is too large to exclude smaller tablets
  libs/features/personalization/personalization.js
Labels: verified, high priority, Ready for Stage

#2815 MWPW-156357 Price-literals - fail gracefully
  libs/blocks/merch/merch.js
  libs/deps/mas/commerce.js
  libs/features/mas/commerce/libs/commerce.d.ts
  libs/features/mas/commerce/price-literals.json
  libs/features/mas/commerce/src/index.d.ts
  libs/features/mas/commerce/src/literals.js
  libs/features/mas/commerce/src/service.js
  libs/features/mas/commerce/src/settings.js
  libs/features/mas/commerce/test/checkout.test.js
  libs/features/mas/commerce/test/literals.test.js
  libs/features/mas/commerce/test/placeholder.test.js
  libs/features/mas/commerce/test/price.test.js
  libs/features/mas/commerce/test/service.test.js
  libs/features/mas/commerce/test/settings.test.js
  libs/features/mas/mas/src/mas.js
  libs/features/mas/mocks/config.js
  libs/features/mas/mocks/literals.js
  libs/features/mas/mocks/literals.json
  libs/features/mas/web-components/test/merch-card-collection.test.html.js
  libs/features/mas/web-components/test/merch-card.mini-compare.test.html.js
  libs/features/mas/web-components/test/merch-card.mini-inline-heading.test.html.js
  libs/features/mas/web-components/test/merch-offer-select.test.html.js
  libs/features/mas/web-components/test/merch-quantity-select.test.html.js
  libs/features/mas/web-components/test/merch-subscription-panel.test.html.js
  libs/features/mas/web-components/test/merch-twp-d2p.test.html.js
  libs/features/mas/web-components/test/plans-modal.test.html.js
  test/blocks/merch/merch.test.js
  test/blocks/merch/mocks/fetch.js
  test/blocks/merch/mocks/literals.json
Labels: verified, run-nala, commerce, Ready for Stage

#2758 MWPW-156788: Unable to scroll page with active Sort filter
  libs/deps/mas/merch-sidenav.js
  libs/features/mas/web-components/build.mjs
  libs/features/mas/web-components/src/sidenav/merch-sidenav.js
  libs/features/mas/web-components/test/merch-card-collection.test.html.js
Labels: verified, run-nala, commerce, Ready for Stage

#2837 MWPW-157210 STE Promo card not appearing
  libs/blocks/merch-card-collection/merch-card-collection.js
  libs/utils/helpers.js
  test/utils/helpers.test.js
Labels: verified, run-nala, Ready for Stage

#2851 [MWPW-157740] Table pricing gutter
  libs/blocks/table/table.css
Labels: Ready for Stage

#2864 MWPW-158148 [MEP] Can't use ul, ol or li in MEP selectorsf
  libs/features/personalization/personalization.js
  test/features/personalization/modifyNonFragmentSelector.test.js
Labels: verified, Ready for Stage

#2834 [MWPW-157347] Environment relative URLs
  libs/scripts/scripts.js
  libs/utils/utils.js
  test/utils/utils.test.js
Labels: high-impact, Ready for Stage

#2866 MWPW-151534 [PEP Prompt] Dismissal action on close button of prompt not seen in windows
  libs/features/webapp-prompt/webapp-prompt.css
Labels: verified, Ready for Stage

#2870 REVERT MWPW-157686 [MEP] Cannot spoof an experience that exists in manifest but not in Target #2844
  libs/features/personalization/personalization.js
Labels: verified, high priority, Ready for Stage

#2869 MWPW-155333 - [FloodgateUI] URL validation
  libs/blocks/floodgateui/actions/index.js
  libs/blocks/floodgateui/floodgate/index.js
  libs/blocks/floodgateui/floodgateui.css
  libs/blocks/floodgateui/url/view.js
  libs/blocks/floodgateui/utils/url.js
Labels: new-feature, zero-impact

#2818 fix(MWPW-155964):Lana log error type changed to info.
  libs/blocks/article-feed/article-helpers.js
  libs/blocks/event-rich-results/event-rich-results.js
  libs/blocks/faas/utils.js
  libs/blocks/library-config/lists/templates.js
  libs/blocks/mobile-app-banner/mobile-app-banner.js
  libs/blocks/path-finder/path-finder.js
  libs/blocks/preflight/panels/seo.js
  libs/blocks/quiz-entry/mlField.js
  libs/blocks/quiz-entry/quiz-entry.js
  libs/blocks/quiz-entry/quizPopover.js
  libs/blocks/quiz-results/quiz-results.js
  libs/blocks/tag-selector/tag-selector.js
  libs/blocks/video-metadata/video-metadata.js
  libs/blocks/vimeo/vimeo.js
  libs/features/footer-promo.js
  libs/martech/martech.js
  test/blocks/article-header/article-header.test.js
  test/blocks/global-footer/global-footer.test.js
  test/blocks/quiz-results/mocks/body.html
  test/blocks/quiz-results/quiz-results.test.js
  test/blocks/vimeo/vimeo.test.html
  test/features/webapp-prompt/webapp-prompt.test.js
Labels: verified, run-nala, Ready for Stage

#2846 MWPW-154980 - Milo advanced page publishing
  libs/blocks/bulk-publish-v2/components/bulk-publisher.js
  libs/blocks/bulk-publish-v2/services.js
  libs/tools/utils/publish.js
  libs/utils/sidekick-decorate.js
  test/blocks/bulk-publish-v2/bulk-publish-v2.test.js
  test/blocks/bulk-publish-v2/mocks/authentication.js
  test/blocks/bulk-publish-v2/mocks/fetch.js
  test/blocks/bulk-publish-v2/mocks/response/permissions.json
  tools/utils/utils.js
Labels: new-feature, Ready for Stage

#2856 fix(Mwpw-157971):sticky feature works in landscape mode.
  libs/blocks/table/table.js
Labels: verified, Ready for Stage

#2833 Create a container element for search in standalone gnav
  libs/blocks/global-navigation/global-navigation.js
  libs/navigation/navigation.js
  test/blocks/global-navigation/global-navigation.test.js
Labels: verified, Ready for Stage

#2860 MWPW-157682 Check CLS for photoshop page
  libs/blocks/hero-marquee/hero-marquee.js
Labels: verified, Ready for Stage

#2863 MWPW-144470 Support article header author without link
  libs/blocks/article-header/article-header.js
  test/blocks/article-header/article-header.test.js
  test/blocks/article-header/mocks/body.html
Labels: verified, run-nala, Ready for Stage

#2877 [MWPW-157973] Run Nala checks on all PRs by default
  .github/workflows/run-nala.yml
Labels: zero-impact, Ready for Stage

#2887 MWPW-157686 [MEP] Cannot spoof an experience that exists in manifest but not in Target
  libs/features/personalization/personalization.js
Labels: verified, Ready for Stage

#2849 MWPW-156749: Fix video CLS
  libs/blocks/adobetv/adobetv.js
  libs/blocks/figure/figure.js
  libs/blocks/video/video.js
  libs/utils/decorate.js
  test/blocks/adobetv/adobetv.test.js
  test/blocks/adobetv/mocks/body.html
  test/blocks/figure/figure.test.js
  test/blocks/figure/mocks/body.html
  test/blocks/marquee/marquee.test.js
  test/blocks/video/mocks/body.html
  test/blocks/video/video.test.js
Labels: run-nala, Ready for Stage

#2861 MWPW-157888 - Hero marquee w/ `no-min-height` and no l/r padding when using a `full-width` variant
  libs/blocks/hero-marquee/hero-marquee.css
  libs/blocks/hero-marquee/hero-marquee.js
Labels: Ready for Stage

#2867 MWPW-157965: Upgrade Universal Nav to Version 1.3
  libs/blocks/global-navigation/global-navigation.js
  test/blocks/global-navigation/global-navigation.test.js
  test/blocks/global-navigation/gnav-brand.test.js
  test/blocks/global-navigation/gnav-cross-cloud.test.js
  test/blocks/global-navigation/gnav-main-nav-popup.test.js
  test/blocks/global-navigation/gnav-main-nav.test.js
  test/blocks/global-navigation/gnav-profile.test.js
  test/blocks/global-navigation/gnav-promo.test.js
  test/blocks/global-navigation/gnav-search.test.js
  test/blocks/global-navigation/test-utilities.js
Labels: verified, run-nala, Ready for Stage

#2884 MWPW-158462 [MEP] any-marquee-section simplified selector
  libs/features/personalization/personalization.js
  test/features/personalization/mocks/manifestSectionBlock.json
  test/features/personalization/modifyNonFragmentSelector.test.js
Labels: verified, Ready for Stage

#2888 MWPW-158353: Updates configurator label to Carousel Animation Style
  libs/blocks/caas-config/caas-config.js
Labels: Ready for Stage, run-nala-on-caas

#2853 MWPW-157024 - Editorial card authoring refinement for the 'open' variant.
  libs/blocks/editorial-card/editorial-card.js
  test/blocks/editorial-card/mocks/body.html
Labels: Ready for Stage

#2891 Mwpw 157587 | [Geo-Routing][Page Performance] Removing the georouting modal background image
  libs/features/georoutingv2/georoutingv2.css
  libs/features/georoutingv2/georoutingv2.js
  libs/features/georoutingv2/getMobileBg.js
  libs/features/georoutingv2/img/GeoModal_BG_Map_Desktop.png
  libs/features/georoutingv2/img/GeoModal_BG_Map_Mobile.png
  libs/features/georoutingv2/img/GeoModal_BG_Map_Tablet.png
  test/features/georoutingv2/georoutingv2.test.js
Labels: verified, run-nala, Ready for Stage

#2875 Quiz Entry Accessibility Round 2
  libs/blocks/quiz-entry/quiz-entry.css
  libs/blocks/quiz-entry/quiz-entry.js
  libs/blocks/quiz-entry/quizoption.js
Labels: verified, Ready for Stage

#2889 MWPW-155317: [CaaS] add support for link rewriting
  libs/blocks/caas/utils.js
  test/blocks/caas-config/expectedConfigs/defaultConfig.js
  test/blocks/caas/utils.test.js
Labels: CaaS, Ready for Stage, run-nala-on-caas

#2896 [MWPW-158583] Update old run-nala GitHub action job
  .github/workflows/run-nala.yml
Labels: zero-impact, Ready for Stage, run-nala-on-caas

#2905 Revert "MWPW-157888 - Hero marquee w/ `no-min-height` and no l/r padding when using a `full-width` variant"
  libs/blocks/hero-marquee/hero-marquee.css
  libs/blocks/hero-marquee/hero-marquee.js
Labels: trivial, Ready for Stage

#2892 [MWPW-157924] - Added functionality to disable Active Element Detection
  libs/blocks/global-navigation/global-navigation.js
  libs/blocks/global-navigation/utilities/utilities.js
  test/blocks/global-navigation/global-navigation.test.js
Labels: verified, Ready for Stage

#2894 MWPW-158464: Switch Odin endpoint
  .hlxignore
  libs/deps/mas/mas.js
  libs/deps/mas/merch-datasource.js
  libs/features/mas/docs/plans.html
  libs/features/mas/mocks/aem.js
  libs/features/mas/mocks/sites/cf/fragments/search/authorPayload.json
  libs/features/mas/mocks/sites/cf/fragments/search/default.json
  libs/features/mas/web-components/src/merch-datasource.js
  libs/features/mas/web-components/test/merch-datasource.test.html.js
Labels: verified, Ready for Stage, run-nala-on-caas

#2855 MWPW-154059 - Milo templates library
  libs/blocks/library-config/library-config.css
  libs/blocks/library-config/library-config.js
  libs/blocks/library-config/library-utils.js
  libs/blocks/library-config/lists/blocks.js
  libs/blocks/library-config/lists/templates.js
  libs/blocks/library-metadata/library-metadata.css
  test/blocks/library-config/library-config.test.js
Labels: Ready for Stage

#2913 [MWPW-158756] Enhance stage links conversion for cross-domain localization
  libs/utils/utils.js
Labels: Ready for Stage

#2909 [MWPW-158021] Update Milo README with Nala commands details
  README.md
  nala/utils/nala.run.js
Labels: Ready for Stage

#2916 MWPW-158777 returning proper response in case of error
  libs/martech/martech.js
Labels: verified, Ready for Stage

#2908 MWPW-158674 [MEP] Support nested placholders in MEP placeholders
  libs/features/personalization/personalization.js
  test/features/personalization/parseNestedPlaceholders.test.js
Labels: verified, Ready for Stage

#2904 MWPW-157476 - [LocUI] Ignore OG property in find meta fragments
  libs/blocks/locui/actions/index.js
Labels: zero-impact

#2885 MWPW-154980 - Milo advanced page publishing part 2
  libs/blocks/bulk-publish-v2/components/bulk-publisher.js
  libs/blocks/bulk-publish-v2/services.js
  libs/blocks/preflight/panels/general.js
  libs/blocks/preflight/preflight.css
  libs/tools/utils/publish.js
  libs/utils/sidekick-decorate.js
  test/blocks/bulk-publish-v2/bulk-publish-v2.test.js
  test/blocks/bulk-publish-v2/mocks/authentication.js
  test/blocks/bulk-publish-v2/mocks/fetch.js
  test/blocks/bulk-publish-v2/mocks/response/permissions.json
  tools/utils/utils.js
Labels: new-feature, Ready for Stage

#2928 [MWPW-153363] Countdown Timer implementation based on page metadata
  libs/blocks/hero-marquee/hero-marquee.js
  libs/blocks/marquee/marquee.js
  libs/blocks/media/media.js
  libs/features/cdt/cdt.css
  libs/features/cdt/cdt.js
  libs/utils/decorate.js
  test/blocks/hero-marquee/mocks/body.html
  test/blocks/marquee/mocks/body.html
  test/blocks/media/media.test.js
  test/blocks/media/mocks/body.html
  test/blocks/media/mocks/placeholders.json
  test/features/cdt/cdt.test.js
  test/features/cdt/mocks/body.html
Labels: verified, run-nala, commerce, new-feature, high priority, Ready for Stage

#2926 MWPW-158077 rollout new Timeline block
  libs/blocks/timeline/timeline.css
  libs/blocks/timeline/timeline.js
  libs/utils/utils.js
  test/blocks/timeline/mocks/body.html
  test/blocks/timeline/mocks/switchcolors.html
  test/blocks/timeline/timeline.test.js
Labels: Ready for Stage

#2930 [MWPW-158872 : NALA] Update Nala GitHub Action runs to correctly handle bot-generated PR details.
  nala/utils/global.setup.js
  nala/utils/pr.run.sh
Labels: zero-impact, Ready for Stage

#2911 Add option to configure children for unav's help component
  libs/blocks/global-navigation/global-navigation.js
  libs/navigation/navigation.js
Labels: verified, critical, Ready for Stage

#2921 MWPW-155984 - Brick list showing null value in link label
  libs/utils/decorate.js
Labels: needs-verification, Ready for Stage

#2922 typo fix
  libs/blocks/faas-config/faas-config.js
Labels: trivial, Ready for Stage

#2914 MWPW-158071: Optimize LCP loading times
  libs/utils/utils.js
  test/utils/mocks/marquee.html
  test/utils/utils.test.js
Labels: Ready for Stage

#2934 GNav - Remove Header Display none
  libs/blocks/home/home.css
Labels: verified, Ready for Stage

#2944 MWPW-152411: MAS technical documentation
  libs/features/mas/README.md
  libs/features/mas/build-docs.mjs
  libs/features/mas/build-docs.sh
  libs/features/mas/commerce/checkout-link.md
  libs/features/mas/docs/checkout-link.html
  libs/features/mas/docs/mas.html
  libs/features/mas/docs/mas.js.html
  libs/features/mas/docs/styles.css
  libs/features/mas/mas/build.mjs
  libs/features/mas/mas/mas.js.md
  libs/features/mas/mas/mas.md
  libs/features/mas/mas/package.json
  libs/features/mas/package-lock.json
  libs/features/mas/package.json
Labels: trivial, Ready for Stage

#2878 MWPW-158053: CCD Slice Card [Merch card]
  libs/deps/mas/merch-card.js
  libs/deps/mas/merch-datasource.js
  libs/features/mas/web-components/src/merch-datasource.js
  libs/features/mas/web-components/src/variants/ccd-slice.css.js
  libs/features/mas/web-components/src/variants/ccd-slice.js
  libs/features/mas/web-components/src/variants/variants.js
  libs/features/mas/web-components/test/img/pixel.png
  libs/features/mas/web-components/test/merch-card.ccd-slice.test.html
  libs/features/mas/web-components/test/merch-card.ccd-slice.test.html.js
  libs/features/mas/web-components/test/merch-twp-d2p.test.html
Labels: verified, commerce, merch card, Ready for Stage

#2897 MWPW-158178 - Preflight check for svg's and pdf's
  libs/blocks/pdf-viewer/pdf-viewer.js
  libs/blocks/preflight/panels/general.js
  libs/blocks/preflight/preflight.css
Labels: new-feature, Ready for Stage

#2907 MWPW-158480 Exclude defaults from caas links
  libs/blocks/caas-config/caas-config.js
  test/blocks/caas-config/caas-config.test.html
Labels: verified, run-nala, caas-configurator, CaaS, Ready for Stage, @caas

#2917 MWPW-157450: Localization Enhancements for quiz-entry block needed
  libs/blocks/quiz-entry/quiz-entry.js
  libs/blocks/quiz-entry/quizoption.js
  libs/blocks/quiz-entry/utils.js
Labels: bug, verified, Ready for Stage, run-nala-on-caas

#2957 Fixed MAS unit test related to mini-compare card variation
  libs/features/mas/web-components/test/merch-card.mini-compare.test.html.js
Labels: Ready for Stage

#2950 [MWPW-158314 : NALA] Add nala tests for additional marquee variants
  nala/blocks/marquee-anchors/marquee-anchors.page.js
  nala/blocks/marquee-anchors/marquee-anchors.spec.js
  nala/blocks/marquee-anchors/marquee-anchors.test.js
  nala/blocks/marquee/marquee.page.js
  nala/blocks/marquee/marquee.spec.js
  nala/blocks/marquee/marquee.test.js
Labels: zero-impact, Ready for Stage

#2946 [MWPW-158004] Fix callout & grey line alignment issues in product merch cards
  libs/blocks/merch-card/merch-card.css
  libs/blocks/merch-card/merch-card.js
  libs/deps/mas/mas.js
  libs/deps/mas/merch-card.js
  libs/features/mas/mocks/offers.json
  libs/features/mas/web-components/src/variants/mini-compare-chart.js
  libs/features/mas/web-components/src/variants/product.js
  libs/features/mas/web-components/src/variants/variant-layout.js
  libs/features/mas/web-components/src/variants/variants.js
  libs/features/mas/web-components/test/merch-card-product.test.html
  libs/features/mas/web-components/test/merch-card-product.test.html.js
  test/blocks/merch-card/merch-card.test.js
  test/blocks/merch-card/mocks/product.html
Labels: bug, verified, run-nala, commerce, merch card, high priority, critical, Ready for Stage

#2931 MWPW-155489 [PEP] Add device type as PEP criteria
  libs/blocks/global-navigation/global-navigation.js
Labels: verified, Ready for Stage

#2948 Jarvis stage URL for Acom stage env
  libs/features/jarvis-chat.js
  test/features/jarvis-chat/jarvis-chat.test.js
Labels: verified, Ready for Stage

#2942 [MWPW-158932] - Add support for custom links through link group in parallel to large menu.
  libs/blocks/global-navigation/global-navigation.css
  libs/blocks/global-navigation/global-navigation.js
  libs/navigation/navigation.js
  libs/styles/styles.css
  test/blocks/global-navigation/global-navigation.test.js
  test/blocks/global-navigation/mocks/navigation-with-custom-links.plain.js
  test/blocks/global-navigation/test-utilities.js
Labels: verified, critical, Ready for Stage

#2941 MWPW-158652 [MEP] Only output non fatal errors to internal users and skip rows missing an action value
  libs/features/personalization/personalization.js
  test/features/personalization/mepPreviewSettings.js
  test/features/personalization/mocks/manifestEmptyAction.json
  test/features/personalization/personalization.test.js
Labels: verified, Ready for Stage

#2906 MWPW-157555: Remove useless logic and putting import commerce.js top.
  libs/blocks/merch/merch.js
  test/blocks/merch/merch.test.js
Labels: run-nala, commerce, Ready for Stage

#2956 [MWPW-153616] Update 404 links in region selector
  libs/blocks/region-nav/region-nav.js
  test/blocks/region-nav/mocks/regions.html
  test/blocks/region-nav/region-nav.test.js
Labels: Ready for Stage

#2967 MWPW-144360 Prototype pollution tag selector
  libs/blocks/tag-selector/tag-selector.js
Labels: verified, Ready for Stage

#2968 MWPW-159236 Fix duplicate percent in donut chart tooltip
  libs/blocks/chart/chart.js
Labels: verified, run-nala, @chart, Ready for Stage

#2969 Add support for Jarvis through Unav and make appID of notifications configurable
  libs/blocks/global-navigation/global-navigation.js
  libs/navigation/navigation.js
  test/navigation/bootstrapper.test.js
Labels: verified, Ready for Stage

#2974 [MWPW-159265] Callout text in RTL not properly aligned
  libs/deps/mas/mas.js
  libs/deps/mas/merch-card.js
  libs/deps/mas/plans-modal.js
  libs/features/mas/web-components/src/global.css.js
Labels: bug, verified, run-nala, commerce, merch card, Ready for Stage

#2955 [MWPW-158927] Countdown Timer feedbacks incorporated
  libs/blocks/media/media.js
  libs/blocks/notification/notification.js
  libs/features/cdt/cdt.css
  libs/features/cdt/cdt.js
  libs/utils/decorate.js
  test/blocks/notification/mocks/body.html
  test/blocks/notification/notification.test.js
Labels: bug, verified, run-nala, commerce, high priority, Ready for Stage

#2978 [MWPW-159287 : NALA] Enhance Nala Run Command to Support Feature Branches with with an owner other than 'adobecom'
  nala/utils/nala.run.js
Labels: zero-impact, Ready for Stage

#2987 Reverts MWPW-157555: Causing prices and CTAs to fail in Safari
  libs/blocks/merch/merch.js
  test/blocks/merch/merch.test.js
Labels: verified, commerce, high priority, critical, Ready for Stage
