Repository adobecom/milo, pull requests merged in 2024-01, with the labels that each got.

#1542 MWPW-137938 - Inline video image fallback
  libs/blocks/figure/figure.js
  libs/blocks/media/media.js
  libs/blocks/video/video.js
  libs/utils/decorate.js
  libs/utils/utils.js
  test/blocks/figure/figure.test.js
  test/blocks/figure/mocks/body.html
Labels: verified, run-nala, new-feature, Ready To Merge

#1654 MWPW-137523 - Allow dark quiet marquees
  libs/blocks/marquee/marquee.css
  libs/blocks/marquee/marquee.js
Labels: verified, run-nala, @marquee

#1670 MWPW-140321 - how-to block - Heading area without Image has gap
  libs/blocks/how-to/how-to.css
  libs/blocks/how-to/how-to.js
Labels: bug, verified, trivial, needs-verification

#1672 MWPW-140273 Highlight replace fragment
  libs/features/personalization/personalization.js
  libs/features/personalization/preview.js
  test/features/personalization/mocks/postPersonalization.html
  test/features/personalization/preview.test.js
Labels: verified, trivial, Ready To Merge

#1689 Sync gnav branch from main
  libs/blocks/figure/figure.js
  libs/blocks/how-to/how-to.css
  libs/blocks/how-to/how-to.js
  libs/blocks/marquee/marquee.css
  libs/blocks/marquee/marquee.js
  libs/blocks/media/media.js
  libs/blocks/video/video.js
  libs/features/personalization/personalization.js
  libs/features/personalization/preview.js
  libs/utils/decorate.js
  libs/utils/utils.js
  test/blocks/figure/figure.test.js
  test/blocks/figure/mocks/body.html
  test/features/personalization/mocks/postPersonalization.html
  test/features/personalization/preview.test.js
Labels: trivial

#1668 MWPW-140470: allow OST to overwrite landscape
  libs/blocks/ost/ost.js
  test/blocks/ost/mocks/ost-utils.js
  test/blocks/ost/ost.test.html.js
Labels: verified, run-nala, commerce

#1679 MWPW-131662: consistent global navigation padding on mobile
  libs/blocks/global-navigation/global-navigation.css
  libs/blocks/global-navigation/utilities/menu/menu.css
Labels: run-nala, needs-verification

#1675 MWPW-140052-Word break css for korean
  libs/styles/styles.css
Labels: verified

#1694 [MWPW-140706] Quiz options should use Adobe Clean and [MWPW-140499] fix multiple merch card width issue on result page
  libs/blocks/quiz-results/quiz-results.css
  libs/blocks/quiz/quiz.css
Labels: bug, verified, run-nala

#1691 [MWPW-140788] Ensure correct Gnav Promo element order
  .github/PULL_REQUEST_TEMPLATE/gnav.md
  libs/blocks/global-navigation/utilities/menu/menu.js
  test/blocks/global-navigation/global-navigation.test.js
Labels: bug, verified, trivial

#1699 Fix broken gnav test
  test/blocks/gnav/gnav.test.js
Labels: trivial

#1701 MWPW-140877 - Quiz Marquee style updates
  libs/blocks/quiz-marquee/quiz-marquee.css
  libs/blocks/quiz-results/quiz-results.css
Labels: bug, verified, trivial, run-nala

#1698 [#1641] add parent option to createTag
  libs/utils/utils.js
  test/utils/utils.test.js
Labels: trivial, new-feature

#1658 MWPW-140345-Fix issues in media QR block variant
  libs/blocks/media/media.css
  libs/blocks/media/media.js
  test/blocks/media/media.test.js
Labels: bug, verified, run-nala, @media

#1663 MWPW-139915: Delivery of Spectrum Web Components
  .eslintrc.js
  libs/deps/lit-all.min.js
  libs/features/spectrum-web-components/.gitignore
  libs/features/spectrum-web-components/README.md
  libs/features/spectrum-web-components/build.mjs
  libs/features/spectrum-web-components/dist/alert-dialog.js
  libs/features/spectrum-web-components/dist/base.js
  libs/features/spectrum-web-components/dist/button-group.js
  libs/features/spectrum-web-components/dist/button.js
  libs/features/spectrum-web-components/dist/checkbox.js
  libs/features/spectrum-web-components/dist/dialog.js
  libs/features/spectrum-web-components/dist/divider.js
  libs/features/spectrum-web-components/dist/field-label.js
  libs/features/spectrum-web-components/dist/help-text.js
  libs/features/spectrum-web-components/dist/icon.js
  libs/features/spectrum-web-components/dist/icons-ui.js
  libs/features/spectrum-web-components/dist/icons-workflow.js
  libs/features/spectrum-web-components/dist/icons/asterisk.js
  libs/features/spectrum-web-components/dist/icons/checkmark.js
  libs/features/spectrum-web-components/dist/icons/chevron.js
  libs/features/spectrum-web-components/dist/icons/dash.js
  libs/features/spectrum-web-components/dist/menu.js
  libs/features/spectrum-web-components/dist/overlay.js
  libs/features/spectrum-web-components/dist/popover.js
  libs/features/spectrum-web-components/dist/reactive-controllers.js
  libs/features/spectrum-web-components/dist/search.js
  libs/features/spectrum-web-components/dist/shared.js
  libs/features/spectrum-web-components/dist/sidenav.js
  libs/features/spectrum-web-components/dist/textfield.js
  libs/features/spectrum-web-components/dist/theme.js
  libs/features/spectrum-web-components/dist/underlay.js
  libs/features/spectrum-web-components/package-lock.json
  libs/features/spectrum-web-components/package.json
  libs/features/spectrum-web-components/src/alert-dialog.js
  libs/features/spectrum-web-components/src/base.js
  libs/features/spectrum-web-components/src/button-group.js
  libs/features/spectrum-web-components/src/button.js
  libs/features/spectrum-web-components/src/checkbox.js
  libs/features/spectrum-web-components/src/dialog.js
  libs/features/spectrum-web-components/src/divider.js
  libs/features/spectrum-web-components/src/field-label.js
  libs/features/spectrum-web-components/src/help-text.js
  libs/features/spectrum-web-components/src/icon.js
  libs/features/spectrum-web-components/src/icons-ui.js
  libs/features/spectrum-web-components/src/icons-workflow.js
  libs/features/spectrum-web-components/src/lit.js
  libs/features/spectrum-web-components/src/menu.js
  libs/features/spectrum-web-components/src/overlay.js
  libs/features/spectrum-web-components/src/popover.js
  libs/features/spectrum-web-components/src/reactive-controllers.js
  libs/features/spectrum-web-components/src/search.js
  libs/features/spectrum-web-components/src/shared.js
  libs/features/spectrum-web-components/src/sidenav.js
  libs/features/spectrum-web-components/src/textfield.js
  libs/features/spectrum-web-components/src/theme.js
  libs/features/spectrum-web-components/src/underlay.js
  test/features/spectrum-web-components/alert-dialog.test.html
  test/features/spectrum-web-components/button.test.html
  test/features/spectrum-web-components/search.test.html
Labels: trivial, commerce

#1692 document OST overrides
  libs/blocks/ost/README.md
Labels: trivial

#1707 Create merch block README.md
  libs/blocks/merch/README.md
Labels: trivial

#1687 MWPW-140780 - Remove :has() selector from Aside
  libs/blocks/aside/aside.css
Labels: trivial, run-nala

#1702 MWPW-140660 Fix Marketo Destination Url
  libs/blocks/marketo/marketo.js
  test/blocks/marketo/marketo.test.js
Labels: verified, run-nala, @marketo

#1700 MWPW-140862: Updated twitter logo
  libs/blocks/global-footer/icons.svg
  test/blocks/global-footer/mocks/icons.js
Labels: verified, run-nala

#1676 MWPW-136866: merch-cards block
  CODEOWNERS
  libs/blocks/merch-cards/merch-cards.css
  libs/blocks/merch-cards/merch-cards.js
  libs/deps/merch-card.js
  libs/deps/merch-cards.js
  libs/deps/merch-offer-select.js
  libs/utils/utils.js
  test/blocks/merch-cards/merch-cards.test.js
  test/blocks/merch-cards/mocks/merch-cards.html
Labels: verified, run-nala, commerce, needs-verification

#1688 MWPW-140538 - Icon Block inline margin
  libs/blocks/icon-block/icon-block.css
Labels: bug, trivial, run-nala

#1690 Integrate Universal Navigation
  libs/blocks/global-navigation/global-navigation.css
  libs/blocks/global-navigation/global-navigation.js
Labels: needs-verification

#1709 Update magma codeowners
  CODEOWNERS
Labels: trivial

#1696 MWPW-137523 - Allow dark quiet marquees (redux)
  libs/blocks/marquee/marquee.css
  libs/blocks/marquee/marquee.js
Labels: verified, run-nala, @marquee

#1710 MWPW-140191: Fixes Merch Card custom <hr> color, inline heading variant
  libs/blocks/merch-card/merch-card.js
  libs/deps/merch-card.js
Labels: bug, run-nala, needs-verification, merch card

#1716 faas-env default qa
  libs/blocks/faas/utils.js
  test/blocks/faas/utils.test.js
Labels: trivial

#1720 Add theme
  libs/blocks/global-navigation/global-navigation.js
Labels: trivial

#1705 MWPW-140964 Marquee static links should not be blue on hover
  libs/blocks/marquee/marquee.css
Labels: trivial, run-nala

#1718 MWPW-140738 - Add foreground gap on large marquees
  libs/blocks/marquee/marquee.css
Labels: verified, trivial, run-nala, @marquee

#1624 MWPW-139379 Improve Tab Scrolling for Mobile
  libs/blocks/tabs/tabs.css
  libs/blocks/tabs/tabs.js
  test/blocks/tabs/mocks/body.html
  test/blocks/tabs/tabs.test.js
Labels: verified, run-nala

#1680 MWPW-140403 | Aside promo block button and block size
  libs/blocks/aside/aside.css
  libs/blocks/aside/aside.js
Labels: verified, trivial, run-nala

#1708 MWPW-140836: fix Commerce for several geo's
  libs/deps/commerce.js
  libs/scripts/scripts.js
Labels: verified, run-nala, needs-verification

#1721 MWPW-139915: Delivery of Spectrum Web Components (#1663)
  .eslintrc.js
  libs/deps/lit-all.min.js
  libs/features/spectrum-web-components/.gitignore
  libs/features/spectrum-web-components/README.md
  libs/features/spectrum-web-components/build.mjs
  libs/features/spectrum-web-components/dist/alert-dialog.js
  libs/features/spectrum-web-components/dist/base.js
  libs/features/spectrum-web-components/dist/button-group.js
  libs/features/spectrum-web-components/dist/button.js
  libs/features/spectrum-web-components/dist/checkbox.js
  libs/features/spectrum-web-components/dist/dialog.js
  libs/features/spectrum-web-components/dist/divider.js
  libs/features/spectrum-web-components/dist/field-label.js
  libs/features/spectrum-web-components/dist/help-text.js
  libs/features/spectrum-web-components/dist/icon.js
  libs/features/spectrum-web-components/dist/icons-ui.js
  libs/features/spectrum-web-components/dist/icons-workflow.js
  libs/features/spectrum-web-components/dist/icons/asterisk.js
  libs/features/spectrum-web-components/dist/icons/checkmark.js
  libs/features/spectrum-web-components/dist/icons/chevron.js
  libs/features/spectrum-web-components/dist/icons/dash.js
  libs/features/spectrum-web-components/dist/menu.js
  libs/features/spectrum-web-components/dist/overlay.js
  libs/features/spectrum-web-components/dist/popover.js
  libs/features/spectrum-web-components/dist/reactive-controllers.js
  libs/features/spectrum-web-components/dist/search.js
  libs/features/spectrum-web-components/dist/shared.js
  libs/features/spectrum-web-components/dist/sidenav.js
  libs/features/spectrum-web-components/dist/textfield.js
  libs/features/spectrum-web-components/dist/theme.js
  libs/features/spectrum-web-components/dist/underlay.js
  libs/features/spectrum-web-components/package-lock.json
  libs/features/spectrum-web-components/package.json
  libs/features/spectrum-web-components/src/alert-dialog.js
  libs/features/spectrum-web-components/src/base.js
  libs/features/spectrum-web-components/src/button-group.js
  libs/features/spectrum-web-components/src/button.js
  libs/features/spectrum-web-components/src/checkbox.js
  libs/features/spectrum-web-components/src/dialog.js
  libs/features/spectrum-web-components/src/divider.js
  libs/features/spectrum-web-components/src/field-label.js
  libs/features/spectrum-web-components/src/help-text.js
  libs/features/spectrum-web-components/src/icon.js
  libs/features/spectrum-web-components/src/icons-ui.js
  libs/features/spectrum-web-components/src/icons-workflow.js
  libs/features/spectrum-web-components/src/lit.js
  libs/features/spectrum-web-components/src/menu.js
  libs/features/spectrum-web-components/src/overlay.js
  libs/features/spectrum-web-components/src/popover.js
  libs/features/spectrum-web-components/src/reactive-controllers.js
  libs/features/spectrum-web-components/src/search.js
  libs/features/spectrum-web-components/src/shared.js
  libs/features/spectrum-web-components/src/sidenav.js
  libs/features/spectrum-web-components/src/textfield.js
  libs/features/spectrum-web-components/src/theme.js
  libs/features/spectrum-web-components/src/underlay.js
  test/features/spectrum-web-components/alert-dialog.test.html
  test/features/spectrum-web-components/button.test.html
  test/features/spectrum-web-components/search.test.html
  web-test-runner.config.mjs
Labels: verified, new-feature, needs-verification

#1724 MWPW-140267 Update MEP PZN tags
  libs/features/personalization/personalization.js
Labels: verified

#1725 MWPW-141124: match widths used by standard merch cards
  libs/blocks/quiz-results/quiz-results.css
Labels: bug, verified, run-nala

#1664 MWPW-140467 Integrate round-corners for brick block
  libs/blocks/brick/brick.js
  libs/blocks/media/media.js
  test/blocks/brick/mocks/body.html
Labels: verified, run-nala, new-feature

#1732 MWPW-140953: Updated twitter logo
  libs/blocks/global-footer/icons.svg
  test/blocks/global-footer/mocks/icons.js
Labels: verified, run-nala

#1728 MWPW-140836: Switch Milo Commerce to own country/language mapping
  libs/deps/commerce.js
  test/blocks/ost/mocks/ost-utils.js
Labels: verified, run-nala, commerce, needs-verification

#1733 Revert "MWPW-139379 Improve Tab Scrolling for Mobile"
  libs/blocks/tabs/tabs.css
  libs/blocks/tabs/tabs.js
  test/blocks/tabs/mocks/body.html
  test/blocks/tabs/tabs.test.js
Labels: trivial

#1730 [MWPW-140624] Footer layout with few columns
  libs/blocks/global-footer/global-footer.css
Labels: verified, trivial, run-nala

#1717 MWPW-140916, MWPW-141124: Adding result to quiz analytics; update merch card width
  libs/blocks/quiz-results/quiz-results.css
  libs/blocks/quiz/utils.js
  test/blocks/quiz/quiz.test.js
  test/blocks/quiz/utils.test.js
Labels: verified, run-nala

#1731 MWPW-140268 Icon duplicates if nested in multiple sections
  libs/features/icons/icons.js
  test/features/icons/icons.test.js
Labels: trivial, run-nala

#1726 MWPW-141139 Parameter PZN tags don't match if user uses uppercase characters
  libs/features/personalization/personalization.js
Labels: trivial

#1729 MWPW-136866: merch-cards block
  CODEOWNERS
  libs/blocks/merch-cards/merch-cards.css
  libs/blocks/merch-cards/merch-cards.js
  libs/deps/merch-cards.js
  libs/deps/merch-offer-select.js
  libs/utils/utils.js
  test/blocks/merch-cards/merch-cards.test.js
  test/blocks/merch-cards/mocks/merch-cards.html
Labels: verified, run-nala, commerce, new-feature, needs-verification

#1740 MWPW-141140 MEP throws error if page filter uses single asterisks
  libs/features/personalization/personalization.js
Labels: trivial, run-nala

#1742 [MILOLIBS RUN : MWPW-141223] Provide support to run nala tests on a given milo libs
  .github/workflows/run-nala-milolibs.yaml
Labels: new-feature

#1745 Universal Navigation
  libs/blocks/global-navigation/global-navigation.css
  libs/blocks/global-navigation/global-navigation.js
Labels: trivial

#1746 Add additional IMS scope to allow Profile Menu to render the user avatar
  libs/scripts/scripts.js
Labels: trivial

#1735 MWPW-137932 - Bullet-proof quiz and result metadata keys
  libs/blocks/quiz-results/quiz-results.js
  libs/blocks/quiz/utils.js
Labels: verified, run-nala

#1659 Mwpw 139968: Mnemonic list block
  libs/blocks/marquee/marquee.css
  libs/blocks/marquee/marquee.js
  libs/blocks/mnemonic-list/mnemonic-list.css
  libs/blocks/mnemonic-list/mnemonic-list.js
  libs/utils/utils.js
  test/blocks/marquee/marquee.test.js
  test/blocks/marquee/mocks/body.html
  test/blocks/mnemonic-list/mnemonic-list.test.js
  test/blocks/mnemonic-list/mocks/mnemonic-list.html
Labels: verified, run-nala, @marquee, new-feature

#1719 MWPW-135163 added quantity selection functionality
  libs/blocks/merch-card/merch-card.js
  libs/blocks/merch-card/merch-offer-select.js
  libs/deps/merch-card.js
  libs/deps/merch-offer-select.js
  libs/deps/merch-quantity-select.js
  test/blocks/merch-card/merch-card.test.js
  test/blocks/merch-card/merch-offer-select.test.js
  test/blocks/merch-card/mocks/acrobat-card.html
Labels: run-nala, new-feature, needs-verification, merch card

#1610 MWPW-139177: TWP modal over Milo (Home) page is not auto re-sized
  libs/blocks/modal/modal.css
  libs/blocks/modal/modal.js
  libs/styles/iframe.css
  test/blocks/modals/modals.test.js
Labels: verified, run-nala

#1753 MWPW-141447 Support inline fragments with MEP replaceFragment
  libs/blocks/fragment/fragment.js
  test/features/personalization/mocks/inlineFragReplaced.plain.html
  test/features/personalization/mocks/manifestReplaceFragment.json
  test/features/personalization/mocks/personalization.html
  test/features/personalization/personalization.test.js
Labels: bug, trivial

#1756 fix zh-HK mapping - commerce
  libs/deps/commerce.js
Labels: trivial, run-nala

#1757 Fix cli
  libs/blocks/merch/merch.js
Labels: verified, run-nala, commerce, needs-verification

#1750 MWPW-141446: Remove the locale from the quiz key in the URL; continue to use it in the background; normalize other chars
  libs/blocks/quiz-results/quiz-results.js
  libs/blocks/quiz/utils.js
  test/blocks/quiz/quiz.test.js
  test/blocks/quiz/utils.test.js
Labels: verified, run-nala, uar

#1749 MWPW-1351731 support linked text
  libs/blocks/merch/merch.js
  test/blocks/merch/merch.test.js
  test/blocks/merch/mocks/body.html
Labels: run-nala, needs-verification, merch card

#1766 MWPW-141609: Universal navigation NO localization tag
  libs/blocks/global-navigation/global-navigation.js
Labels: bug, needs-verification

#1761 MWPW-141446, MWPW-137932: Remove locale from quiz key in URLs; Bullet-proof metadata keys
  libs/blocks/quiz-results/quiz-results.js
  libs/blocks/quiz/utils.js
  test/blocks/quiz/quiz.test.js
  test/blocks/quiz/utils.test.js
Labels: verified, run-nala

#1767 Sync gnav branch from main
  libs/blocks/fragment/fragment.js
  libs/blocks/icon-block/icon-block.css
  libs/blocks/marquee/marquee.css
  libs/blocks/marquee/marquee.js
  libs/blocks/merch-card/merch-card.js
  libs/blocks/merch-card/merch-offer-select.js
  libs/blocks/merch/merch.js
  libs/blocks/mnemonic-list/mnemonic-list.css
  libs/blocks/mnemonic-list/mnemonic-list.js
  libs/blocks/modal/modal.css
  libs/blocks/modal/modal.js
  libs/blocks/quiz-results/quiz-results.js
  libs/blocks/quiz/utils.js
  libs/deps/commerce.js
  libs/deps/merch-card.js
  libs/deps/merch-offer-select.js
  libs/deps/merch-quantity-select.js
  libs/features/personalization/preview.css
  libs/features/personalization/preview.js
  libs/styles/iframe.css
  libs/utils/utils.js
  test/blocks/marquee/marquee.test.js
  test/blocks/marquee/mocks/body.html
  test/blocks/merch-card/merch-card.test.js
  test/blocks/merch-card/merch-offer-select.test.js
  test/blocks/merch-card/mocks/acrobat-card.html
  test/blocks/merch/merch.test.js
  test/blocks/merch/mocks/body.html
  test/blocks/merch/mocks/fetch.js
  test/blocks/merch/mocks/named-offers.json
  test/blocks/mnemonic-list/mnemonic-list.test.js
  test/blocks/mnemonic-list/mocks/mnemonic-list.html
  test/blocks/modals/modals.test.js
  test/blocks/quiz/quiz.test.js
  test/blocks/quiz/utils.test.js
  test/features/personalization/mocks/inlineFragReplaced.plain.html
  test/features/personalization/mocks/manifestReplaceFragment.json
  test/features/personalization/mocks/personalization.html
  test/features/personalization/mocks/postPersonalization.html
  test/features/personalization/personalization.test.js
  test/features/personalization/preview.test.js
Labels: trivial

#1760 MWPW-135540 - Enable a new section-metadata style: reverse-mobile
  libs/blocks/accordion/accordion.css
  libs/blocks/section-metadata/section-metadata.css
Labels: verified

#1727 MWPW-141151: Adding bacom-blog tag to Milo Tool Configurator
  libs/blocks/caas-config/caas-config.js
Labels: verified

#1776 MWPW-141639 Quick follow to do an early return if mep=off
  libs/utils/utils.js
Labels: trivial

#1777 MWPW-141653 Update martech to use QA script
  libs/deps/martech.main.standard.qa.min.js
  libs/martech/martech.js
  test/scripts/scripts.test.js
Labels: trivial, run-nala

#1764 MWPW-138103: Mini Compare Chart Card [Merch Card]
  libs/blocks/merch-card/merch-card.js
  libs/deps/merch-card.js
  test/blocks/merch-card/merch-card.test.js
  test/blocks/merch-card/mocks/mini-compare-chart.html
Labels: verified, run-nala, commerce, new-feature, merch card

#1783 MWPW-141771 fix tests to run synchronously.
  test/blocks/merch-card/merch-offer-select.test.js
Labels: bug

#1770 MWPW-141526 Removed Content no longer highlights
  libs/blocks/merch-card/merch-card.css
  libs/blocks/merch-card/merch-card.js
  libs/features/personalization/personalization.js
  libs/features/personalization/preview.css
  test/blocks/merch-card/merch-card.test.js
  test/blocks/merch-card/mocks/mep.html
  test/features/personalization/personalization.test.js
Labels: trivial, run-nala

#1787 replaced dev env with stage for unav
  libs/blocks/global-navigation/global-navigation.js
Labels: trivial

#1759 Mwpw 139968: Mnemonic list block comments
  CODEOWNERS
  libs/blocks/marquee/marquee.css
  libs/blocks/mnemonic-list/mnemonic-list.css
  libs/blocks/mnemonic-list/mnemonic-list.js
Labels: run-nala, @marquee

#1788 MWPW-141771 fix tests.
  test/blocks/merch-card/merch-offer-select.test.js
Labels: bug, verified, trivial, commerce

#1772 MWPW-141387 Marquee background colors bug
  libs/blocks/marquee/marquee.css
  libs/utils/decorate.js
Labels: bug, high-impact, verified, run-nala

#1784 left option enabled.
  libs/blocks/table/table.css
Labels: trivial, run-nala

#1778 MWPW-140917 - Quiz result link tagging
  libs/blocks/quiz-results/quiz-results.js
Labels: verified, run-nala

#1793 Sync gnav branch from main
  CODEOWNERS
  libs/blocks/accordion/accordion.css
  libs/blocks/caas-config/caas-config.js
  libs/blocks/marquee/marquee.css
  libs/blocks/merch-card/merch-card.css
  libs/blocks/merch-card/merch-card.js
  libs/blocks/mnemonic-list/mnemonic-list.css
  libs/blocks/mnemonic-list/mnemonic-list.js
  libs/blocks/section-metadata/section-metadata.css
  libs/blocks/table/table.css
  libs/deps/martech.main.standard.qa.min.js
  libs/deps/merch-card.js
  libs/features/personalization/personalization.js
  libs/features/personalization/preview.css
  libs/martech/martech.js
  libs/utils/decorate.js
  libs/utils/utils.js
  test/blocks/merch-card/merch-card.test.js
  test/blocks/merch-card/merch-offer-select.test.js
  test/blocks/merch-card/mocks/mep.html
  test/blocks/merch-card/mocks/mini-compare-chart.html
  test/features/personalization/personalization.test.js
  test/scripts/scripts.test.js
Labels: trivial

#1738 fix(MWPW-138316):scrolling inside an iframe is disabled.
  libs/blocks/modal/modal.css
Labels: run-nala, needs-verification

#1739 MWPW-136892: Entitlement aware checkout links
  libs/blocks/global-navigation/utilities/getUserEntitlements.js
  libs/blocks/merch/merch.css
  libs/blocks/merch/merch.js
  libs/deps/commerce.js
  test/blocks/merch/merch.test.js
  test/blocks/merch/mocks/body.html
  test/blocks/merch/mocks/fetch.js
  test/blocks/merch/mocks/ims.js
  web-test-runner.config.mjs
Labels: verified, run-nala, commerce, new-feature, needs-verification

#1790 MWPW-141827: Update code for all APIs to support STAGE and PROD
  CODEOWNERS
  libs/blocks/caas-config/caas-config.js
  libs/blocks/marquee/marquee.css
  libs/blocks/merch-card/merch-card.css
  libs/blocks/merch-card/merch-card.js
  libs/blocks/mnemonic-list/mnemonic-list.css
  libs/blocks/mnemonic-list/mnemonic-list.js
  libs/blocks/quiz-dynamic-tutorials/quiz-dynamic-tutorials-utils.js
  libs/blocks/quiz/utils.js
  libs/blocks/table/table.css
  libs/deps/martech.main.standard.qa.min.js
  libs/deps/merch-card.js
  libs/features/personalization/personalization.js
  libs/features/personalization/preview.css
  libs/martech/martech.js
  libs/utils/decorate.js
  libs/utils/utils.js
  test/blocks/merch-card/merch-card.test.js
  test/blocks/merch-card/merch-offer-select.test.js
  test/blocks/merch-card/mocks/mep.html
  test/blocks/merch-card/mocks/mini-compare-chart.html
  test/features/personalization/personalization.test.js
  test/scripts/scripts.test.js
Labels: trivial, run-nala

#1588 MWPW-137905 Integrate Heartbeat Video Tracking on YouTube Videos
  libs/blocks/youtube/youtube.js
Labels: verified

#1795 MWPW-141810: updated custom ietf locale logic for unav
  libs/blocks/global-navigation/global-navigation.js
Labels: needs-verification

#1801 Mwpw 138103: Quantity selector in mini compare chart card
  libs/blocks/merch-card/merch-card.js
  test/blocks/merch-card/merch-card.test.js
  test/blocks/merch-card/mocks/mini-compare-chart.html
Labels: run-nala, commerce, needs-verification, merch card

#1785 MWPW-141781 [MEP][Analytics] Remove personalization info from analytics with no pzn manifests
  libs/blocks/global-footer/global-footer.js
  libs/blocks/global-navigation/global-navigation.js
  libs/features/personalization/personalization.js
  libs/martech/attributes.js
  libs/martech/martech.js
  libs/utils/utils.js
  test/blocks/table/mocks/body.html
  test/features/personalization/personalization.test.js
  test/martech/attributes.test.js
  test/martech/mocks/body.html
Labels: trivial, run-nala

#1673 MWPW-138958 - media-block: enable spacing tokens
  libs/blocks/media/media.css
  libs/styles/styles.css
Labels: verified, @media

#1796 MWPW-138544 [merch-card] storage options
  libs/blocks/merch-card/merch-card.js
  libs/blocks/merch-card/merch-offer-select.js
  libs/deps/merch-offer-select.js
  test/blocks/merch-card/merch-card.test.js
  test/blocks/merch-card/merch-offer-select.test.js
  test/blocks/merch-card/mocks/selection-cards.html
Labels: verified, run-nala, commerce, needs-verification

#1805 MWPW-140539: Outline CTA merch card styles in dark section
  libs/blocks/merch-card/merch-card.css
  libs/deps/merch-card.js
Labels: bug, run-nala, needs-verification, merch card

#1804 Allow Profile Menu to show a local section
  libs/blocks/global-navigation/global-navigation.js
Labels: trivial

#1803 MWPW-140229: Sync Universal Nav analytics from Dunamis to AA
  libs/blocks/global-navigation/global-navigation.js
Labels: needs-verification

#1808 [MWPW-142055] Ensure UNav dropdowns are visible on Safari
  libs/blocks/global-navigation/global-navigation.css
Labels: bug, trivial

#1809 MWPW-142058 Localize fragment preload
  libs/features/personalization/personalization.js
Labels: bug, trivial

#1810 [MWPW-141779] Make sure Jarvis chat gets loaded regardless of alloy response / errors
  libs/features/jarvis-chat.js
Labels: trivial

#1723 MWPW-140456 - [Aside] fix notification static links color
  libs/blocks/aside/aside.css
Labels: bug, verified, run-nala
