Repository adobecom/milo, pull requests merged in 2024-05, with the labels that each got.

#2199 MWPW-146878 [LocUI] - Actions polling state management
  libs/blocks/locui/actions/index.js
  libs/blocks/locui/langs/index.js
  libs/blocks/locui/langs/view.js
  libs/blocks/locui/utils/miloc.js
Labels: trivial, zero-impact

#2242 MWPW-147482 - ML Input Bulletproofing
  libs/blocks/quiz-entry/mlField.js
  libs/blocks/quiz-entry/quiz-entry.js
  libs/blocks/quiz-entry/utils.js
Labels: trivial

#2238 [Release] Stage to Main
  libs/blocks/merch-card/merch-card.js
  libs/blocks/mnemonic-list/mnemonic-list.css
  libs/blocks/mnemonic-list/mnemonic-list.js
  libs/deps/merch-card.js
  libs/features/jarvis-chat.js
  libs/features/personalization/personalization.js
  libs/scripts/delayed.js
  test/blocks/merch-card/merch-card.test.js
  test/blocks/merch-card/mocks/plans-card.html
  test/features/jarvis-chat/jarvis-chat.test.js
Labels: run-nala, Ready for Main, BAcom SOT 👌, DC SOT 👌, Homepage SOT 👌, MIQ SOT👌

#2217 MWPW-147027: CTA flowing out of mini compare card (due to long strings)
  libs/deps/merch-card.js
Labels: verified, run-nala, commerce, merch card, Ready for Stage

#2226 MWPW-147149: Prevent multiple download/upgrade CTAs
  libs/blocks/marquee/marquee.css
  libs/blocks/merch-card/merch-card.css
  libs/blocks/merch/merch.js
  libs/blocks/merch/upgrade.js
  libs/deps/commerce.js
  test/blocks/merch/merch.test.js
Labels: verified, run-nala, commerce, Ready for Stage

#2236 MWPW-146845 Setup Footer Promo for Localization
  libs/features/footer-promo.js
  libs/utils/utils.js
  test/utils/utils.test.js
Labels: trivial, run-nala, Ready for Stage

#2158 MWPW-146263 - [Bulk Publish v2] Job Info UI
  libs/blocks/bulk-publish-v2/components/bulk-publisher.css
  libs/blocks/bulk-publish-v2/components/bulk-publisher.js
  libs/blocks/bulk-publish-v2/components/job-info.js
  libs/blocks/bulk-publish-v2/components/job-process.css
  libs/blocks/bulk-publish-v2/components/job-process.js
  libs/blocks/bulk-publish-v2/img/checked.svg
  libs/blocks/bulk-publish-v2/img/close.svg
  libs/blocks/bulk-publish-v2/img/copy.svg
  libs/blocks/bulk-publish-v2/img/crossed.svg
  libs/blocks/bulk-publish-v2/img/indicator.svg
  libs/blocks/bulk-publish-v2/img/rework.svg
  libs/blocks/bulk-publish-v2/services.js
  libs/blocks/bulk-publish-v2/utils.js
  test/blocks/bulk-publish-v2/bulk-publish-v2.test.js
  test/blocks/tabs/tabs.test.js
  web-test-runner.config.mjs
Labels: verified, new-feature, zero-impact, Ready for Stage

#2249 Adding additional IMS Scope for A.com Client IDs
  libs/utils/utils.js
Labels: verified, run-nala, high priority, Ready for Stage

#2250 MWPW-146070: Upgrade Universal Nav to Version 1.1 in Milo
  libs/blocks/global-navigation/global-navigation.js
  test/blocks/global-navigation/global-navigation.test.js
Labels: verified, run-nala, high priority, Ready for Stage

#2166 MWPW-146370: Enable dynamic comment threshold via metadata
  libs/blocks/review/review.js
  test/blocks/review/components/review/Review.test.js
  test/blocks/review/mocks/body.html
  test/blocks/review/review.test.js
Labels: verified, run-nala, @marquee, needs-verification, Ready for Stage

#2231 MWPW-147284: discard default params in merch link
  libs/blocks/ost/ost.js
  test/blocks/ost/mocks/ost-utils.js
  test/blocks/ost/ost.test.html.js
  test/blocks/ost/ost.test.js
Labels: verified, commerce, Ready for Stage

#2241 MWPW-147002-Fix spacing issue between button on table header left variation in RTL
  libs/blocks/table/table.css
Labels: verified, run-nala, high priority, Ready for Stage

#2247 MWPW-146845 - [LocUI] Find Footer Promo Fragments
  libs/blocks/locui/actions/index.js
Labels: bug, zero-impact

#2245 MWPW-147523 - [LocUI] Excel Service Error Handling
  libs/tools/sharepoint/excel.js
Labels: bug, zero-impact

#2235 Project pep
  libs/blocks/global-navigation/global-navigation.css
  libs/blocks/global-navigation/global-navigation.js
  libs/blocks/global-navigation/utilities/menu/menu.js
  libs/blocks/global-navigation/utilities/utilities.js
  libs/features/personalization/entitlements.js
  libs/features/personalization/stage-entitlements.js
  libs/features/webapp-prompt/webapp-prompt.css
  libs/features/webapp-prompt/webapp-prompt.js
  libs/scripts/delayed.js
  test/blocks/global-navigation/global-navigation.test.js
  test/features/webapp-prompt/mocks/media-icon.png
  test/features/webapp-prompt/mocks/pep-prompt-content.js
  test/features/webapp-prompt/test-utilities.js
  test/features/webapp-prompt/webapp-prompt.test.js
Labels: verified, run-nala, new-feature, high priority, Ready for Stage

#2262 MWPW-146796 Fix Marketo unit test
  test/blocks/marketo/mocks/marketo-utils.js
Labels: zero-impact, Ready for Stage

#2265 [MWPW-147848] Remove e-mail notifications for PRs
  .github/workflows/email-release.yaml
Labels: zero-impact, Ready for Stage

#2263 MWPW-147808 - Create README.md for mobile app banner
  libs/blocks/mobile-app-banner/README.md
Labels: zero-impact

#2260 [Release] Stage to Main
  .github/workflows/email-release.yaml
  libs/blocks/global-navigation/global-navigation.css
  libs/blocks/global-navigation/global-navigation.js
  libs/blocks/global-navigation/utilities/menu/menu.js
  libs/blocks/global-navigation/utilities/utilities.js
  libs/blocks/marketo/marketo.js
  libs/blocks/mobile-app-banner/README.md
  libs/blocks/ost/ost.js
  libs/blocks/review/review.js
  libs/blocks/table/table.css
  libs/features/personalization/entitlements.js
  libs/features/personalization/stage-entitlements.js
  libs/features/webapp-prompt/webapp-prompt.css
  libs/features/webapp-prompt/webapp-prompt.js
  libs/scripts/delayed.js
  libs/utils/sidekick-decorate.js
  libs/utils/sidekick.js
  test/blocks/global-navigation/global-navigation.test.js
  test/blocks/marketo/marketo.test.js
  test/blocks/marketo/mocks/marketo-utils.js
  test/blocks/ost/mocks/ost-utils.js
  test/blocks/ost/ost.test.html.js
  test/blocks/ost/ost.test.js
  test/blocks/review/components/review/Review.test.js
  test/blocks/review/mocks/body.html
  test/blocks/review/review.test.js
  test/features/webapp-prompt/mocks/media-icon.png
  test/features/webapp-prompt/mocks/pep-prompt-content.js
  test/features/webapp-prompt/test-utilities.js
  test/features/webapp-prompt/webapp-prompt.test.js
Labels: run-nala, needs-verification, Ready for Main, BAcom SOT 👌, CC SOT 👌, DC SOT 👌, Homepage SOT 👌, MIQ SOT👌

#2224 [MWPW-147001] Stage initiative automation (Stage-Main sync PRs)
  .github/workflows/helpers.js
  .github/workflows/localWorkflowConfigs.js
  .github/workflows/merge-to-stage.js
  .github/workflows/merge-to-stage.yaml
  .github/workflows/pr-reminders.js
  .github/workflows/update-script.js
Labels: verified, Ready for Stage

#2269 Squash merges
  .github/workflows/merge-to-stage.js
Labels: zero-impact, Ready for Stage

#2252 MWPW-146703 [MILO][MEP][GNAV2.0] Apply MEP actions to the contents of the gnav file
  libs/blocks/fragment/fragment.js
  libs/blocks/global-navigation/global-navigation.js
  libs/blocks/global-navigation/utilities/menu/menu.js
  libs/blocks/global-navigation/utilities/utilities.js
  libs/blocks/merch-card-collection/merch-card-collection.js
  libs/features/personalization/personalization.js
  libs/features/personalization/preview.css
  test/blocks/global-navigation/mocks/mep-config.js
  test/blocks/global-navigation/mocks/mep-global-navigation.plain.html
  test/blocks/global-navigation/mocks/mep-large-menu-table
  test/blocks/global-navigation/utilities/utilities.test.js
  test/blocks/merch-card-collection/merch-card-collection.test.js
  test/features/personalization/actions.test.js
  test/features/personalization/mocks/actions/manifestCustomAction.json
  test/features/personalization/mocks/actions/manifestUpdateMetadata.json
  test/features/personalization/mocks/manifestInvalid.json
  test/features/personalization/normalizePath.test.js
  test/features/personalization/personalization.test.js
Labels: high-impact, verified, run-nala, high priority, Ready for Stage

#2209 MWPW-144549 CTA alignment for Text, Icon, and Media Blocks
  libs/blocks/icon-block/icon-block.css
  libs/blocks/icon-block/icon-block.js
  libs/blocks/media/media.css
  libs/blocks/media/media.js
  libs/blocks/text/text.css
  libs/blocks/text/text.js
  test/blocks/icon-block/icon-block.test.js
  test/blocks/icon-block/mocks/body.html
  test/blocks/media/media.test.js
  test/blocks/media/mocks/body.html
  test/blocks/text/mocks/body.html
  test/blocks/text/text.test.js
Labels: high-impact, verified, run-nala, Ready for Stage

#2216 MWPW-144238: refactor(video-metadata) more flexible createVideoObject
  libs/blocks/video-metadata/video-metadata.js
Labels: trivial, zero-impact, Ready for Stage

#2264 MWPW-145721 UNav Analytics Enhancements
  libs/blocks/global-navigation/global-navigation.js
  test/blocks/global-navigation/test-utilities.js
Labels: verified, run-nala, Ready for Stage

#2240 MWPW-142590 - [Share] enhancement (resubmit) - ability to edit text above icons
  libs/blocks/share/share.js
  libs/blocks/share/share.svg
  test/blocks/share/mocks/body.html
  test/blocks/share/share.test.js
Labels: verified, run-nala, Ready for Stage

#2271 Use a github app token for the auto merge to stage workflow
  .github/workflows/merge-to-stage.js
  .github/workflows/merge-to-stage.yaml
Labels: zero-impact, Ready for Stage

#2273 Update github permissions to use the env token
  .github/workflows/merge-to-stage.js
  .github/workflows/merge-to-stage.yaml
Labels: zero-impact, Ready for Stage

#2192 MWPW-143783 - [Marquee] block enhancement - Support for logo | label 'lockup'
  libs/blocks/marquee/marquee.css
  libs/blocks/marquee/marquee.js
  test/blocks/marquee/marquee.test.js
  test/blocks/marquee/mocks/multiple-icons.html
Labels: verified, run-nala, Ready for Stage

#2274 Milo PR merge bot - add the correct permissions
  .github/workflows/merge-to-stage.js
  .github/workflows/merge-to-stage.yaml
Labels: zero-impact, Ready for Stage

#2272 Test the stage automation workflow
  README.md
Labels: zero-impact, Ready for Stage

#2278 [merge to stage automation] Remove superfluent slacks to the changelog
  .github/workflows/merge-to-stage.js
  .github/workflows/merge-to-stage.yaml
Labels: zero-impact, Ready for Stage

#2259 MWPW-147735 - [LocUI] Catch fetch errors in fragment search
  libs/blocks/locui/actions/index.js
Labels: bug, zero-impact

#2267 MWPW-147683 - CSS Cleanup
  libs/blocks/quiz-entry/mlField.js
  libs/blocks/quiz-entry/quiz-entry.css
  libs/blocks/quiz-entry/quiz-entry.js
  libs/blocks/quiz-entry/quizPopover.js
  libs/blocks/quiz-entry/quizoption.js
Labels: trivial

#2255 MWPW-147173 - Add gap below Aside notification headings
  libs/blocks/aside/aside.css
Labels: trivial, run-nala, Ready for Stage

#2185 MWPW-147127 Scrolling on the gnav in mobile portrait and landscape view is not working as expected ,navigation menu when opened is not seen rendered completely in MILO Pages
  libs/blocks/global-navigation/global-navigation.js
Labels: bug, verified, high priority, critical, Ready for Stage

#2218 Fix(MWPW-144755):Highlight of a single columned table is visible.
  libs/blocks/table/table.css
Labels: verified, run-nala, Ready for Stage

#2237 MWPW-137282 - [Action Items] Centered in the grid/scroller
  libs/blocks/action-item/action-item.css
  libs/blocks/action-scroller/action-scroller.css
  libs/blocks/action-scroller/action-scroller.js
  libs/blocks/icon-block/icon-block.css
  libs/blocks/section-metadata/section-metadata.css
  test/blocks/action-scroller/action-scroller.test.js
  test/blocks/action-scroller/mocks/body.html
Labels: high-impact, verified, new-feature, Ready for Stage

#2286 Revert "MWPW-137282 - [Action Items] Centered in the grid/scroller"
  libs/blocks/action-item/action-item.css
  libs/blocks/action-scroller/action-scroller.css
  libs/blocks/action-scroller/action-scroller.js
  libs/blocks/icon-block/icon-block.css
  libs/blocks/section-metadata/section-metadata.css
  test/blocks/action-scroller/action-scroller.test.js
  test/blocks/action-scroller/mocks/body.html
Labels: verified

#2292 MWPW-147245 Quiz entry block Tests
  libs/blocks/quiz-entry/quiz-entry.js
  libs/blocks/quiz-entry/quizoption.js
  test/blocks/quiz-entry/mocks/index.html
  test/blocks/quiz-entry/mocks/invalid-user-selection.json
  test/blocks/quiz-entry/mocks/mock-data.js
  test/blocks/quiz-entry/mocks/mock-states.js
  test/blocks/quiz-entry/mocks/questions.json
  test/blocks/quiz-entry/mocks/quiz.html
  test/blocks/quiz-entry/mocks/result-resources.json
  test/blocks/quiz-entry/mocks/strings.json
  test/blocks/quiz-entry/quiz-entry.test.js
Labels: trivial

#2293 MWPW-148094 - LocUI Error Status style
  libs/blocks/locui/locui.css
  libs/blocks/locui/status/view.js
Labels: bug, zero-impact

#2295 MWPW-146681 - [LocUI] Language card polling check
  libs/blocks/locui/utils/miloc.js
Labels: bug, zero-impact

#2248 MWPW-147599: CaaS Bulk Publisher not working after MS authentication change
  tools/send-to-caas/bulk-publish-to-caas.js
Labels: verified, CaaS, Ready for Stage

#2254 Preflight Accessibility tab update
  libs/blocks/preflight/panels/accessibility.js
  libs/blocks/preflight/preflight.css
Labels: trivial, run-nala, new-feature, Ready for Stage

#2279 MWPW-146407: add new card style to caas configurator
  libs/blocks/caas-config/caas-config.js
Labels: trivial, new-feature, caas-configurator, CaaS, Ready for Stage

#2276 MWPW-141780 - Clean up Accordion block attributes
  libs/blocks/accordion/accordion.js
Labels: verified, trivial, run-nala, Ready for Stage

#2198 MWPW-147158: adds support for footer divider at the collection level
  libs/blocks/caas-config/caas-config.js
  libs/blocks/caas/utils.js
  test/blocks/caas-config/caas-config.test.html
  test/blocks/caas-config/expectedConfigs/defaultConfig.js
  test/blocks/caas/utils.test.js
Labels: trivial, run-nala, caas-configurator, CaaS, Ready for Stage

#2244 MWPW-147594: Consumers mappings for origin not being sent when using sidekick
  tools/send-to-caas/send-utils.js
Labels: trivial, CaaS, Ready for Stage

#2289 Stage automation, update the body after merging another PR in
  .github/workflows/merge-to-stage.js
Labels: zero-impact, Ready for Stage

#2251 MWPW-147472: auto adjust commerce iframe
  libs/blocks/merch/merch.css
  libs/blocks/merch/merch.js
  libs/blocks/modal/modal.merch.js
  test/blocks/modals/mocks/iframe.plain.html
  test/blocks/modals/modal.merch.test.js
Labels: verified, run-nala, commerce, Ready for Stage

#2282 MWPW-141725 Graybox Block
  libs/blocks/graybox/graybox.css
  libs/blocks/graybox/graybox.js
  libs/blocks/graybox/mobileFrames.js
  libs/styles/styles.css
  libs/utils/utils.js
  test/blocks/graybox/graybox.test.js
  test/blocks/graybox/mocks/graybox.html
Labels: new-feature, zero-impact, Ready for Stage

#2305 MWPW-148253 Quiz Entry Coverage
  libs/blocks/quiz-entry/quiz-entry.js
  libs/blocks/quiz-entry/quizoption.js
  libs/blocks/quiz-entry/utils.js
  test/blocks/quiz-entry/mocks/mock-data.js
  test/blocks/quiz-entry/quiz-entry.test.js
  test/blocks/quiz-entry/utils.test.js
Labels: verified, new-feature, Ready for Stage

#2306 MWPW-148257 - [LocUI] Retry Language status badge style
  libs/blocks/locui/locui.css
Labels: bug, zero-impact

#2297 MWPW-148084 - [LocUI] No languages messaging
  libs/blocks/locui/actions/view.js
Labels: new-feature, zero-impact

#2298 OPT-26580 DC0994_US | Frictionless | Add sticky banner Upload CTA
  libs/mep/dc0994/aside/aside.css
  libs/mep/dc0994/aside/aside.js
Labels: verified, run-nala, zero-impact, high priority, Ready for Stage

#2268 MWPW-147527 Fix JP text issue in Review component
  libs/blocks/review/components/review/RatingSummary.js
  test/blocks/review/mocks/body_jp.html
  test/blocks/review/mocks/head.html
  test/blocks/review/review_jp.test.js
Labels: run-nala, needs-verification, Ready for Stage

#2275 [MWPW-147480] Fix: Badge overlapping title
  libs/blocks/merch-card/merch-card.css
  libs/blocks/merch-card/merch-card.js
  libs/deps/merch-card.js
  test/blocks/merch-card/merch-card.test.js
Labels: bug, verified, Ready for Stage

#2243 MWPW-143912 New Media Variant: Medium Compact
  libs/blocks/media/media.css
  libs/blocks/media/media.js
  libs/utils/decorate.js
  test/blocks/media/media.test.js
  test/blocks/media/mocks/body.html
Labels: verified, run-nala, new-feature, @media, Ready for Stage

#2314 MWPW-138032: added tags to LANA logs
  libs/blocks/article-feed/article-helpers.js
  libs/blocks/event-rich-results/event-rich-results.js
  libs/blocks/faas/utils.js
  libs/blocks/preflight/panels/seo.js
  libs/blocks/quiz-entry/mlField.js
  libs/blocks/quiz-entry/quiz-entry.js
  libs/blocks/quiz-entry/quizPopover.js
  libs/blocks/quiz-results/quiz-results.js
  libs/blocks/tag-selector/tag-selector.js
  libs/blocks/video-metadata/video-metadata.js
  libs/features/footer-promo.js
  libs/martech/martech.js
Labels: Ready for Stage

#2316 MWPW-147472: auto adjust commerce iframe
  libs/blocks/merch/merch.css
  libs/blocks/merch/merch.js
  libs/blocks/modal/modal.merch.js
  test/blocks/modals/mocks/iframe.plain.html
  test/blocks/modals/modal.merch.test.js
Labels: verified, commerce, Ready for Stage

#2287 fix(MWPW-148021):Table min width set to screen size.
  libs/blocks/table/table.css
Labels: verified, Ready for Stage

#2304 MWPW-148252: auto label zero impact PRs
  .github/workflows/label-zero-impact.js
  .github/workflows/label-zero-impact.yaml
Labels: Ready for Stage

#2313 MWPW-148418 - Share default placeholder text not displaying in some cases
  libs/blocks/share/share.js
Labels: bug, verified, Ready for Stage

#2331 MWPW-148426 [MEP] Request for New Personalization Tag: Free users, individuals, US and CA
  libs/features/personalization/entitlements.js
Labels: verified, run-nala, zero-impact, high priority, Ready for Stage

#2337 [Release] Stage to Main
  libs/features/personalization/entitlements.js
Labels: verified, Ready for Main, zero-impact

#2336 MWPW-149113: UAR Interactive Front Door click event not registering
  libs/blocks/quiz-entry/quiz-entry.js
Labels: verified, new-feature, uar, high priority, Ready for Stage

#2257 fix(MWPW-147387):Table colours are loaded in Mweb screens.
  libs/blocks/table/table.js
Labels: Ready for Stage

#2333 MWPW-148640: Add Jarvis africa to ZA mapping
  libs/features/jarvis-chat.js
  test/features/jarvis-chat/jarvis-chat.test.js
Labels: verified, run-nala, Ready for Stage

#2348 quiz entry block - fix for content disappearing before redirect
  libs/blocks/quiz-entry/quiz-entry.js
  libs/blocks/quiz-entry/utils.js
Labels: verified, new-feature, uar, high priority, Ready for Stage

#2334 MWPW-147601: sending ML field text to Analytics
  libs/blocks/quiz-entry/quiz-entry.js
Labels: verified, new-feature, uar, high priority, Ready for Stage

#2351 fast follow for MWPW-146214 [MILO][MEP] Option to have gnav but not main wait for Target (preserve targetEnabled in config under more circumstances)
  libs/features/personalization/personalization.js
  libs/utils/utils.js
Labels: verified, run-nala, high priority, Ready for Stage

#2258 MWPW-147351: Added styles for delayed modal and media block inside
  libs/blocks/media/media.css
  libs/blocks/modal/modal.css
  libs/blocks/modal/modal.js
  test/blocks/modals/modals.test.js
Labels: verified, run-nala, Ready for Stage

#2061 [MWPW-139963] Table style fixes
  libs/blocks/table/table.css
Labels: bug, verified, run-nala, Ready for Stage

#2358 MWPW-150614 [MEP] Stage - Request for New Personalization Tag: Free users, individuals, US and CA
  libs/features/personalization/stage-entitlements.js
Labels: zero-impact, high priority, Ready for Stage

#2180 MWPW-145574 - Dynamic Nav Gnav Implementation
  libs/blocks/global-navigation/global-navigation.js
  libs/features/dynamic-navigation.js
  test/blocks/global-navigation/global-navigation.test.js
  test/features/dynamic-nav/dynamicNav.test.js
  test/features/dynamic-nav/mocks/entry.html
  test/features/dynamic-nav/mocks/off.html
  test/features/dynamic-nav/mocks/on.html
Labels: verified, run-nala, Ready for Stage

#2281 MWPW-147175 Support Extending window.adobeid
  libs/utils/utils.js
Labels: verified, trivial, run-nala, Ready for Stage

#2339 MWPW-148609 [Project PEP] Optionally Bypass xLG for Testing
  libs/features/webapp-prompt/webapp-prompt.js
Labels: verified, Ready for Stage

#2346 High Impact Alert Workflow
  .github/workflows/high-impact-alert.js
  .github/workflows/high-impact-alert.yml
  .github/workflows/mark-stale-prs.yaml
  .github/workflows/merge-to-stage.js
  .github/workflows/merge-to-stage.yaml
  .github/workflows/pr-reminders.yaml
Labels: zero-impact, Ready for Stage

#2326 MWPW-148298 - [LocUI] Validation status toast
  libs/blocks/locui/status/view.js
  libs/blocks/locui/utils/miloc.js
Labels: new-feature, zero-impact

#2347 Various catalog fixes + SWC updates
  libs/blocks/merch-card-collection/merch-card-collection.css
  libs/blocks/merch-card-collection/merch-card-collection.js
  libs/blocks/merch-card/merch-card.css
  libs/blocks/merch-card/merch-card.js
  libs/blocks/merch/merch.css
  libs/deps/merch-card-collection.js
  libs/deps/merch-card.js
  libs/deps/merch-offer-select.js
  libs/deps/merch-quantity-select.js
  libs/features/spectrum-web-components/build.mjs
  libs/features/spectrum-web-components/dist/action-button.js
  libs/features/spectrum-web-components/dist/action-menu.js
  libs/features/spectrum-web-components/dist/base.js
  libs/features/spectrum-web-components/dist/button.js
  libs/features/spectrum-web-components/dist/dialog.js
  libs/features/spectrum-web-components/dist/divider.js
  libs/features/spectrum-web-components/dist/field-label.js
  libs/features/spectrum-web-components/dist/icon.js
  libs/features/spectrum-web-components/dist/icons/asterisk.js
  libs/features/spectrum-web-components/dist/icons/checkmark.js
  libs/features/spectrum-web-components/dist/icons/chevron.js
  libs/features/spectrum-web-components/dist/icons/corner-triangle.js
  libs/features/spectrum-web-components/dist/icons/cross.js
  libs/features/spectrum-web-components/dist/icons/dash.js
  libs/features/spectrum-web-components/dist/link.js
  libs/features/spectrum-web-components/dist/menu.js
  libs/features/spectrum-web-components/dist/overlay.js
  libs/features/spectrum-web-components/dist/picker.js
  libs/features/spectrum-web-components/dist/popover.js
  libs/features/spectrum-web-components/dist/progress-circle.js
  libs/features/spectrum-web-components/dist/reactive-controllers.js
  libs/features/spectrum-web-components/dist/shared.js
  libs/features/spectrum-web-components/dist/theme.js
  libs/features/spectrum-web-components/dist/tray.js
  libs/features/spectrum-web-components/dist/underlay.js
  libs/features/spectrum-web-components/package-lock.json
  libs/features/spectrum-web-components/package.json
  libs/features/spectrum-web-components/src/action-button.js
  libs/features/spectrum-web-components/src/action-menu.js
  libs/features/spectrum-web-components/src/base.js
  libs/features/spectrum-web-components/src/button.js
  libs/features/spectrum-web-components/src/dialog.js
  libs/features/spectrum-web-components/src/link.js
  libs/features/spectrum-web-components/src/overlay.js
  libs/features/spectrum-web-components/src/picker.js
  libs/features/spectrum-web-components/src/polyfills/array.prototype.at.js
  libs/features/spectrum-web-components/src/reactive-controllers.js
  libs/features/spectrum-web-components/src/tray.js
  libs/utils/utils.js
  test/blocks/merch-card/merch-card.test.js
  test/blocks/merch-card/merch-offer-select.test.js
  test/blocks/merch-card/mocks/catalog.html
  test/blocks/merch-card/mocks/photoshop.svg
  test/blocks/merch-card/mocks/selection-cards.html
  test/blocks/merch/merch.test.js
  test/blocks/merch/mocks/fetch.js
  test/blocks/merch/mocks/named-offers.json
Labels: high-impact, run-nala, commerce

#2383 MWPW-151189 [MILO][MEP] Skip Martech timeout if blocked by ad blocker
  libs/martech/martech.js
Labels: run-nala
