Repository adobecom/milo, pull requests merged in 2024-08, with the labels that each got.

#2664 Query Parms update & sendTargetResponse function update
  libs/martech/martech.js
  libs/utils/utils.js
Labels: needs-verification

#2681 MWPW-155676 - [LocUI] Find duplicate fragments by pathname
  libs/blocks/locui/actions/index.js
Labels: bug

#2678 MWPW-153586 - [LocUI] Get url status on sync to langstore
  libs/blocks/locui/url/tabs.js
  libs/blocks/locui/url/view.js
  libs/blocks/locui/utils/miloc.js
Labels: bug

#2650 [MWPW-152181] Tabbing gets "stuck" after second instance of merch-card CTAs, within a segment blade
  libs/deps/mas/merch-card-all.js
  libs/deps/mas/merch-card.js
  libs/features/mas/package-lock.json
  libs/features/mas/web-components/README.md
  libs/features/mas/web-components/src/merch-card.js
Labels: run-nala, commerce, Ready for Stage

#2670 [MWPW-145131] Send locale and language code to analytics
  libs/martech/martech.js
Labels: verified, Ready for Stage

#2676 MWPW-147867 - [marquee] support RTL for loc - RePost
  libs/blocks/marquee/marquee.css
Labels: needs-verification, Ready for Stage

#2680 MWPW-155691 [MILO][MEP] Also use region in placeholders decision
  libs/features/personalization/personalization.js
  libs/features/personalization/preview.js
Labels: Ready for Stage

#2624 MWPW-154901 Set debug=true on categories container
  libs/blocks/caas/utils.js
Labels: verified, caas-configurator, CaaS, Ready for Stage

#2652 [MWPW-136406] Tabs block enhancement: deep linking
  libs/blocks/tabs/tabs.js
Labels: verified, run-nala, Ready for Stage

#2638 MWPW-155314 [MEP] Enable Entitlements + Operator
  libs/features/personalization/personalization.js
  libs/utils/utils.js
  test/features/personalization/personalization.test.js
Labels: bug, Ready for Stage, @personalization

#2685 MWPW-154981: adds a new Created Date option to details text
  libs/blocks/caas-config/caas-config.js
Labels: trivial, caas-configurator, CaaS, Ready for Stage

#2694 MWPW-155781 [MILO] Geo Modal Tracking on BACOM - Missing custom link
  libs/blocks/modal/modal.js
Labels: run-nala, Ready for Stage

#2663 MWPW-154191: Ability to have green promo text on merch-card to bottom of the card (under description)
  libs/deps/mas/merch-card-all.js
  libs/deps/mas/merch-card.js
  libs/features/mas/web-components/src/merch-card.js
Labels: verified, run-nala, commerce, Ready for Stage

#2691 MWPW-155654 Open TWP modal with preselected tab
  libs/blocks/merch/merch.js
  test/blocks/merch/merch.test.js
  test/blocks/merch/mocks/body.html
Labels: verified, run-nala, commerce, Ready for Stage

#2656 MWPW-154893 - [editorial-card] bugs
  libs/blocks/editorial-card/editorial-card.css
  libs/blocks/editorial-card/editorial-card.js
  libs/styles/styles.css
  test/blocks/editorial-card/editorial-card.test.js
  test/blocks/editorial-card/mocks/body.html
Labels: needs-verification, Ready for Stage

#2682 ENB-6995 Query Params update & sendTargetResponse function update Resubmit for #2664
  libs/martech/martech.js
  libs/utils/utils.js
Labels: Ready for Stage

#2647 MWPW-153810 media image is seen loaded twice in product page urls in desktop
  libs/utils/utils.js
Labels: verified, run-nala, critical, Ready for Stage

#2679 [MWPW-155627] Merch Callout feature: Missing font cascade
  libs/deps/mas/merch-card-all.js
  libs/deps/mas/merch-card.js
  libs/deps/mas/plans-modal.js
  libs/features/mas/web-components/src/global.css.js
Labels: run-nala, Ready for Stage

#2687 MWPW-153955 [PEP ] dismiss tool tip text is seen chopped in RTL locale in ipad and iphone in landscape mode
  libs/features/webapp-prompt/webapp-prompt.css
Labels: verified, Ready for Stage

#2686 MWPW-154969 Log LCP and key user attributes
  libs/utils/logWebVitals.js
  libs/utils/utils.js
  test/utils/logWebVitals.test.js
  test/utils/logWebVitalsUtils.test.js
Labels: verified, Ready for Stage

#2696 [MWPW-150579] Update supported browser list
  .browserslistrc
  .github/workflows/label-zero-impact.js
Labels: verified, Ready for Stage

#2545 MWPW-152952 Allow message for Marketo form success
  libs/blocks/marketo/marketo.js
  test/blocks/marketo/marketo.test.js
Labels: verified, run-nala, Ready for Stage

#2578 MWPW-146237: Repurpose seotech-structured-data feature for arbitrary JSON-LD
  libs/features/seotech/README.md
  libs/features/seotech/seotech.js
  test/features/seotech/seotech.test.js
Labels: Ready for Stage

#2709 revert PR of placeholder function as placeholder value is seen displayed with additional nbsp text in locale product pages in stage
  libs/utils/utils.js
Labels: verified

#2669 Standalone GNav for Non-Milo Consumers
  libs/navigation/bootstrapper.js
  libs/navigation/navigation.css
  libs/navigation/navigation.js
  test/navigation/bootstrapper.test.js
  test/navigation/navigation.test.js
Labels: verified, run-nala, Ready for Stage

#2689 Making new GNAV experience default
  libs/utils/utils.js
Labels: verified, Ready for Stage

#2700 Fix: Load gnav search files only if it is authored
  libs/blocks/global-navigation/global-navigation.js
Labels: verified, run-nala, critical, Ready for Stage

#2704 [MWPW-154102] Accordion RTL alignment
  libs/blocks/accordion/accordion.css
Labels: Ready for Stage

#2713 [MWPW-156163] Send additional Slack notifications for high impact PRs
  .github/workflows/high-impact-alert.js
  .github/workflows/high-impact-alert.yml
Labels: zero-impact, Ready for Stage

#2712 MWPW-156220: Support pa code and product code for
  libs/blocks/merch/merch.js
  test/blocks/merch/merch.test.js
Labels: verified, run-nala, commerce, Ready for Stage

#2595 Added download and open-in spectrum icons
  libs/features/spectrum-web-components/dist/icons-workflow.js
  libs/features/spectrum-web-components/src/icons-workflow.js
Labels: verified, Ready for Stage

#2673 MWPW-142166 One Page Gated
  libs/blocks/marketo/marketo.js
  test/blocks/marketo/marketo.test.html
Labels: verified, run-nala, @marketo, Ready for Stage

#2714 [MWPW-154969] Performance consent
  libs/utils/logWebVitals.js
  libs/utils/utils.js
  test/utils/logWebVitals.test.js
  test/utils/logWebVitalsUtils.test.js
Labels: Ready for Stage

#2642 MWPW-132156: close (old) footer block modal when click outside
  libs/blocks/footer/footer.js
  test/blocks/footer/footer.test.js
  test/blocks/footer/mocks/region-selector.html
Labels: verified, run-nala, Ready for Stage

#2692 Feat(MWPW:151162):nofollow a individual link.
  libs/utils/utils.js
  test/utils/mocks/body.html
  test/utils/utils.test.js
Labels: verified, Ready for Stage

#2718 MWPW-156094: clean up LTRM in URLs
  libs/blocks/quiz/quizcontainer.js
  libs/blocks/quiz/quizoption.js
  libs/blocks/quiz/utils.js
Labels: bug, verified, uar, Ready for Stage

#2725 MWPW-152283: Commerce endpoint update
  libs/deps/mas/commerce.js
  libs/deps/mas/mas.js
  libs/features/mas/commerce/src/wcs.js
Labels: high-impact, verified, run-nala, commerce, Ready for Stage

#2731 Adding test case for federated modal
  test/blocks/modals/mocks/body.html
  test/blocks/modals/mocks/federal/geo.plain.html
  test/blocks/modals/modals.test.js
Labels: trivial, Ready for Stage

#2729 MWPW-156545 [MILO][MEP] Info in MEP button panel is incorrect
  libs/features/personalization/personalization.js
  libs/features/personalization/preview.js
Labels: Ready for Stage

#2706 [MWPW-154970] allow authoring hash value delay=0 for promo modals
  libs/blocks/modal/modal.js
  test/blocks/modals/modals.test.js
Labels: verified, Ready for Stage

#2715 MWPW-153810 media image is seen loaded twice in product page urls in desktop
  libs/utils/utils.js
  test/utils/mocks/body.html
  test/utils/utils.test.js
Labels: verified, Ready for Stage

#2736 MWPW-156624 [MILO][MEP] Add locale prefix as an option for placeholder feature
  libs/features/personalization/personalization.js
  libs/features/personalization/preview.js
Labels: verified, Ready for Stage

#2724 MWPW-155412: Fix video CLS netting +10 lighthouse points
  libs/blocks/adobetv/adobetv.js
  libs/blocks/video/video.js
  libs/utils/decorate.js
  test/blocks/adobetv/adobetv.test.js
  test/blocks/adobetv/mocks/body.html
  test/blocks/marquee/marquee.test.js
  test/blocks/video/mocks/body.html
  test/blocks/video/video.test.js
Labels: verified, Ready for Stage

#2747 [MWPW-156638] Table row header items wrap
  libs/blocks/table/table.css
Labels: Ready for Stage

#2738 MWPW-151456: Demo page accordion & hover state bug fixes
  libs/blocks/accordion/accordion.css
  libs/blocks/region-nav/region-nav.css
Labels: Ready for Stage

#2675 MWPW-153629: [Mini compare] Stack cards on mobile
  libs/deps/mas/merch-card-all.js
  libs/deps/mas/merch-card-collection.js
  libs/deps/mas/merch-card.js
  libs/deps/mas/merch-sidenav.js
  libs/deps/mas/plans-modal.js
  libs/features/mas/web-components/src/global.css.js
  libs/features/mas/web-components/src/merch-card.css.js
  libs/features/mas/web-components/src/merch-card.js
  libs/features/mas/web-components/src/utils.js
Labels: verified, run-nala, commerce, merch card, Ready for Stage

#2726 MWPW-155529 - Notification design parity
  libs/blocks/notification/notification.css
  libs/blocks/notification/notification.js
  libs/utils/decorate.js
  test/blocks/notification/mocks/body.html
  test/blocks/notification/notification.test.js
Labels: run-nala, needs-verification, Ready for Stage

#2745 MWPW-147759 - quiz option contrast fixes
  libs/blocks/quiz/quiz.css
Labels: verified, uar, Ready for Stage

#2746 MWPW-156262 use standard tab browsing in collection
  libs/deps/mas/merch-card-all.js
  libs/deps/mas/merch-card-collection.js
  libs/deps/mas/merch-card.js
  libs/features/mas/web-components/src/merch-card-collection.js
  libs/features/mas/web-components/src/merch-card.js
  libs/features/mas/web-components/test/merch-card-collection.test.html.js
Labels: verified, run-nala, commerce, Ready for Stage

#2737 MWPW-155687
  libs/features/placeholders.js
Labels: trivial, Ready for Stage

#2755 MWPW-156872 - Add `no borders` variant to Accordion block
  libs/blocks/accordion/accordion.css
Labels: run-nala, needs-verification, Ready for Stage

#2762 MWPW-147803 [MEP] Request for Logged in Free users tag
  libs/features/personalization/entitlements.js
Labels: Ready for Stage

#2763 Revert "MWPW-151936 Aside Tiger Team Enhancements"
  libs/blocks/aside/aside.css
  libs/blocks/aside/aside.js
  libs/styles/iconography.css
  test/blocks/aside/aside-legacy.test.js
  test/blocks/aside/aside.test.js
  test/blocks/aside/mocks/body.html
  test/blocks/aside/mocks/split.html
  test/blocks/aside/mocks/standard.html
Labels: trivial, high priority

#2698 MWPW-153629: Removal of merch-card-all dep
  libs/deps/mas/merch-card-all.js
  libs/features/mas/mas/src/mas.js
  libs/features/mas/mocks/mas.js
  libs/features/mas/web-components/build.mjs
  libs/features/mas/web-components/src/merch-card-all.js
  libs/features/mas/web-components/src/merch-datasource.js
Labels: verified, commerce, merch card, high priority, Ready for Stage

#2703 MWPW-155943 Use correct image source for video when using poster Image
  libs/utils/decorate.js
  libs/utils/utils.js
  test/blocks/figure/mocks/body.html
  test/utils/mocks/body.html
  test/utils/utils.test.js
Labels: verified, run-nala, Ready for Stage

#2751 Prevent a line break before 'ー U+2013', '〜 U+301C', and etc in Japanese
  libs/styles/styles.css
Labels: Ready for Stage

#2717 MWPW-155057: Lets authors add "starting at" to merch cards
  libs/blocks/merch-card/merch-card.js
  libs/deps/mas/merch-card.js
  libs/deps/mas/plans-modal.js
  libs/features/mas/web-components/src/global.css.js
  libs/features/mas/web-components/src/merch-card.js
  libs/features/mas/web-components/test/merch-card.test.html
  test/blocks/merch-card/mocks/plans-card.html
  test/blocks/merch-card/mocks/segment-card.html
Labels: verified, run-nala, commerce, merch card, Ready for Stage

#2769 MWPW-155604 - [FloodgateUI] Find nested fragments
  libs/blocks/floodgateui/actions/index.js
  libs/blocks/floodgateui/floodgateui.css
Labels: new-feature

#2753 MWPW-155770 - [LocUI] AEM URL Validation
  libs/blocks/locui/actions/index.js
  libs/blocks/locui/loc/index.js
  libs/blocks/locui/utils/url.js
Labels: bug, zero-impact

#2767 MWPW-151936 - Aside Tiger Team Enhancements (redux)
  libs/blocks/aside/aside.css
  libs/blocks/aside/aside.js
  libs/styles/iconography.css
  test/blocks/aside/aside-legacy.test.js
  test/blocks/aside/aside.test.js
  test/blocks/aside/mocks/body.html
  test/blocks/aside/mocks/split.html
  test/blocks/aside/mocks/standard.html
Labels: verified, run-nala, high priority, Ready for Stage

#2668 MWPW-152792: Adjust CSS in Catalog card for promo treatment
  libs/blocks/merch-card/merch-card.js
  libs/deps/mas/merch-card.js
  libs/deps/mas/plans-modal.js
  libs/features/mas/web-components/src/global.css.js
  libs/features/mas/web-components/src/merch-card.css.js
  libs/features/mas/web-components/test/merch-card.test.html
Labels: verified, run-nala, commerce, Ready for Stage

#2690 MWPW-151392: Sorting button/menu issues on Mobile
  .gitignore
  libs/blocks/merch-card-collection/merch-card-collection.js
  libs/blocks/merch/merch.js
  libs/features/mas/package-lock.json
  libs/features/mas/package.json
  libs/features/mas/web-components/package-lock.json
  libs/features/spectrum-web-components/README.md
  libs/features/spectrum-web-components/dist/action-button.js
  libs/features/spectrum-web-components/dist/action-menu.js
  libs/features/spectrum-web-components/dist/alert-dialog.js
  libs/features/spectrum-web-components/dist/base.js
  libs/features/spectrum-web-components/dist/button.js
  libs/features/spectrum-web-components/dist/checkbox.js
  libs/features/spectrum-web-components/dist/dialog.js
  libs/features/spectrum-web-components/dist/divider.js
  libs/features/spectrum-web-components/dist/icon.js
  libs/features/spectrum-web-components/dist/icons/asterisk.js
  libs/features/spectrum-web-components/dist/icons/checkmark.js
  libs/features/spectrum-web-components/dist/icons/chevron.js
  libs/features/spectrum-web-components/dist/icons/corner-triangle.js
  libs/features/spectrum-web-components/dist/icons/cross.js
  libs/features/spectrum-web-components/dist/icons/dash.js
  libs/features/spectrum-web-components/dist/link.js
  libs/features/spectrum-web-components/dist/menu.js
  libs/features/spectrum-web-components/dist/overlay.js
  libs/features/spectrum-web-components/dist/picker.js
  libs/features/spectrum-web-components/dist/popover.js
  libs/features/spectrum-web-components/dist/progress-circle.js
  libs/features/spectrum-web-components/dist/reactive-controllers.js
  libs/features/spectrum-web-components/dist/search.js
  libs/features/spectrum-web-components/dist/shared.js
  libs/features/spectrum-web-components/dist/sidenav.js
  libs/features/spectrum-web-components/dist/tabs.js
  libs/features/spectrum-web-components/dist/textfield.js
  libs/features/spectrum-web-components/dist/theme.js
  libs/features/spectrum-web-components/dist/toast.js
  libs/features/spectrum-web-components/dist/tooltip.js
  libs/features/spectrum-web-components/dist/tray.js
  libs/features/spectrum-web-components/dist/underlay.js
  libs/features/spectrum-web-components/package-lock.json
  libs/features/spectrum-web-components/package.json
  libs/features/spectrum-web-components/src/overlay.js
Labels: verified, run-nala, commerce, Ready for Stage

#2721 Table review
  libs/blocks/table/table.css
  libs/blocks/table/table.js
  libs/img/icons/icons.svg
  test/blocks/table/table.test.js
Labels: Ready for Stage

#2754 MWPW-156898 [MEP] Add setting to use XLG segments in MEP while logged out
  libs/features/personalization/entitlements.js
  libs/martech/martech.js
  libs/utils/utils.js
  test/utils/mocks/mep/head-xlg.html
  test/utils/utils-mep.test.js
Labels: verified, Ready for Stage

#2759 MWPW-156265 - [LocUI] Pass user information to loc service calls
  libs/blocks/locui/utils/miloc.js
Labels: zero-impact

#2777 Revert "MWPW-151936 - Aside Tiger Team Enhancements (redux)"
  libs/blocks/aside/aside.css
  libs/blocks/aside/aside.js
  libs/styles/iconography.css
  test/blocks/aside/aside-legacy.test.js
  test/blocks/aside/aside.test.js
  test/blocks/aside/mocks/body.html
  test/blocks/aside/mocks/split.html
  test/blocks/aside/mocks/standard.html
Labels: trivial, high priority

#2782 MWPW-151936 - Aside Tiger Team Enhancements (a new hope)
  libs/blocks/aside/aside.css
  libs/blocks/aside/aside.js
  libs/styles/iconography.css
  test/blocks/aside/aside-legacy.test.js
  test/blocks/aside/aside.test.js
  test/blocks/aside/mocks/body.html
  test/blocks/aside/mocks/split.html
  test/blocks/aside/mocks/standard.html
Labels: run-nala, needs-verification, high priority, Ready for Stage

#2783 MWPW-155621 - Adding functionality to the Pill Notification
  libs/blocks/notification/notification.css
  libs/blocks/notification/notification.js
  libs/blocks/section-metadata/section-metadata.css
  libs/blocks/section-metadata/sticky-section.js
  libs/utils/decorate.js
  test/blocks/notification/mocks/body.html
Labels: verified, run-nala, high priority, Ready for Stage
