Repository adobecom/milo, pull requests merged in 2024-06, with the labels that each got.

#2400 MWPW-151476 and MWPW-151189 Post RCP consolidated MEP PR
  libs/features/personalization/personalization.js
  libs/martech/martech.js
  libs/utils/utils.js
Labels: high priority, Ready for Stage

#2230 MWPW-144756 Table - Responsive breakpoints - Text wraps under icon in Content cell
  libs/blocks/table/table.css
  libs/blocks/table/table.js
Labels: bug, verified, run-nala, Ready for Stage

#2327 MWPW-143562 - Add "radio" variant to Tabs block
  libs/blocks/tabs/tabs.css
  libs/blocks/tabs/tabs.js
Labels: high-impact, verified, run-nala, Ready for Stage

#2357 MWPW-147760: Color contrast fix
  libs/blocks/quiz/quiz.css
Labels: verified, Ready for Stage

#2364 Quiz option card accessibility fixes
  libs/blocks/quiz-entry/quizoption.js
  libs/blocks/quiz/quizoption.js
Labels: verified, Ready for Stage

#2367 MWPW-137401 - Sidekick path feature
  libs/blocks/path-finder/img/link-out.svg
  libs/blocks/path-finder/path-finder.css
  libs/blocks/path-finder/path-finder.js
  tools/sidekick/config.json
Labels: trivial, new-feature, Ready for Stage

#2372 Build a query parameter to make unav version configurable
  libs/blocks/global-navigation/global-navigation.js
Labels: verified, run-nala, Ready for Stage

#2374 [MWPW-148268] Adjust high impact workflow
  .github/workflows/high-impact-alert.yml
Labels: zero-impact, Ready for Stage

#2368 Only comment reminders on PRs against stage
  .github/workflows/pr-reminders.js
Labels: zero-impact, Ready for Stage

#2323 MWPW-143143: Improvements for Upgrade modal
  libs/blocks/merch/merch.js
  libs/blocks/merch/upgrade.js
  libs/deps/commerce.js
  test/blocks/merch/mocks/body.html
  test/blocks/merch/upgrade.test.js
Labels: verified, run-nala, commerce, Ready for Stage

#2393 MWPW-147718: [T3 MVP][MIlo] Update Milo configurator
  libs/blocks/caas-config/caas-config.js
  libs/blocks/caas/utils.js
  test/blocks/caas-config/expectedConfigs/defaultConfig.js
  test/blocks/caas/caas.test.html
  test/blocks/caas/mocks/utils.js
  test/blocks/caas/utils.test.js
Labels: caas-configurator, CaaS, Ready for Stage

#2366 MWPW-148227: added newsroom/news to caas-config
  libs/blocks/caas-config/caas-config.js
Labels: trivial, caas-configurator, CaaS, Ready for Stage

#2381 MWPW-148208 - [LocUI] Render links in error messages
  libs/blocks/locui/actions/view.js
  libs/blocks/locui/langs/modal.js
  libs/blocks/locui/loc/index.js
  libs/blocks/locui/status/view.js
  libs/blocks/locui/url/tabs.js
  libs/blocks/locui/utils/miloc.js
Labels: zero-impact

#2401 MWPW-151430 [MILO][MEP] not in front of a segment does not work
  libs/features/personalization/entitlements.js
  libs/features/personalization/stage-entitlements.js
Labels: Ready for Stage

#2324 [MWPW-141785] Implement custom link actions
  libs/blocks/card/cardUtils.js
  libs/utils/utils.js
  test/utils/mocks/body.html
  test/utils/utils.test.js
Labels: verified, Ready for Stage

#2356 MWPW-147770 Mobile Touch
  libs/blocks/quiz-entry/quizoption.js
Labels: verified, new-feature, uar, Ready for Stage

#2360 fix(MWPW-148021):Table min width set to screen size.
  libs/blocks/table/table.css
Labels: verified, Ready for Stage

#2389 MWPW-130601-Add typekit for adobe clean thai
  libs/scripts/scripts.js
  libs/styles/styles.css
Labels: verified, Ready for Stage

#2398 MWPW-142084 - Accessibility: ARIA attribute needed on "Play" button for Image video links
  libs/utils/image-video-link.js
Labels: verified, Ready for Stage

#2385 MWPW-148232 - [LocUI] Retry Queue Label
  libs/blocks/locui/langs/view.js
  libs/blocks/locui/locui.css
Labels: zero-impact

#2361 [MWPW-146056] Links are not converted to their stage counterparts
  libs/scripts/scripts.js
  libs/utils/utils.js
  test/utils/utils.test.js
Labels: verified, Ready for Stage

#2384 MWPW-146577: [Kodiak]: Cross-site Scripting (XSS) in JavaScript in [github.com/adobecom/milo]
  libs/features/personalization/preview.js
Labels: Ready for Stage

#2426 Fixed failing unit tests
  test/utils/utils.test.js
Labels: Ready for Stage

#2373 Start the RCP for stage earlier
  .github/workflows/helpers.js
  .github/workflows/merge-to-stage.js
Labels: zero-impact, Ready for Stage

#2399 MWPW-147741 [Geo-Routing] Need to load modal after bootstrap in order to ensure Analytics fires
  libs/blocks/modal/modal.js
  libs/features/georoutingv2/georoutingv2.js
  libs/utils/utils.js
  test/blocks/modals/modals.test.js
Labels: high priority, Ready for Stage

#2320 MWPW-147267: Mini Compare Chart Card UX Feedback
  libs/blocks/merch-card/merch-card.js
Labels: verified, run-nala, Ready for Stage

#2430 MWPW-151911 - [LocUI] URL validation enhancement
  libs/blocks/locui/actions/index.js
  libs/blocks/locui/actions/modal.js
  libs/blocks/locui/actions/view.js
  libs/blocks/locui/loc/index.js
  libs/blocks/locui/locui.css
  libs/blocks/locui/status/view.js
Labels: zero-impact

#2415 MWPW-150627 - [LocUI] Skipped files UI
  libs/blocks/locui/img/warnings-icon.svg
  libs/blocks/locui/langs/index.js
  libs/blocks/locui/langs/modal.js
  libs/blocks/locui/langs/view.js
  libs/blocks/locui/locui.css
Labels: new-feature, zero-impact

#2416 MWPW-147989 and MWPW-151786: handle localized path for quiz spreadsheets and doc files
  libs/blocks/quiz-results/quiz-results.js
  libs/blocks/quiz/quiz.js
  libs/blocks/quiz/utils.js
  test/blocks/quiz/utils.test.js
Labels: high-impact, verified, uar, high priority, Ready for Stage

#2375 Add news.adobe.com as known federal origin
  libs/blocks/global-navigation/utilities/utilities.js
Labels: run-nala, Ready for Stage

#2376 [MWPW-150668] Get utils ready for Helix 5
  libs/utils/utils.js
Labels: verified, Ready for Stage

#2421 MWPW-151281-Fix overflow causing horizontal scroll
  libs/blocks/section-metadata/section-metadata.css
Labels: verified, run-nala, Ready for Stage

#2427 [MWPW-151474] Ensure carousel navigation is displayed after everything has been loaded
  libs/blocks/carousel/carousel.css
  libs/blocks/carousel/carousel.js
Labels: verified, run-nala, Ready for Stage

#2431 MWPW-146963: OST to support Annual template
  libs/blocks/merch/merch.js
  libs/blocks/ost/ost.js
  libs/deps/commerce.js
  test/blocks/merch/merch.test.js
  test/blocks/merch/mocks/body.html
Labels: verified, run-nala, commerce, Ready for Stage

#2444 MWPW-146254 make merch quantity input a textfield for ff
  libs/deps/merch-quantity-select.js
Labels: run-nala, commerce, Ready for Stage

#2428 MWPW-150665: [POC] Spectrum 2 Styles and Spectrum CSS Tokens Integration Script
  libs/deps/spectrum2-styles.css
  libs/features/spectrum2-styles/.gitignore
  libs/features/spectrum2-styles/README.md
  libs/features/spectrum2-styles/build.mjs
  libs/features/spectrum2-styles/package-lock.json
  libs/features/spectrum2-styles/package.json
  package.json
Labels: needs-verification

#2451 mwpw-150087: bump action dependencies
  .github/workflows/code-compatibility.yaml
  .github/workflows/codeql.yml
  .github/workflows/dispatch.yml
  .github/workflows/fg-sync-repos.yml
  .github/workflows/high-impact-alert.yml
  .github/workflows/label-zero-impact.yaml
  .github/workflows/merge-to-main.yaml
  .github/workflows/merge-to-stage.yaml
  .github/workflows/pr-reminders.yaml
  .github/workflows/run-lint.yaml
  .github/workflows/run-nala-milolibs.yaml
  .github/workflows/run-nala.yml
  .github/workflows/run-tests.yaml
  .github/workflows/skms.yaml
  .github/workflows/update-dependencies.yaml
Labels: zero-impact

#2411 MWPW-147299 How-to MP4 Videos
  libs/blocks/how-to/how-to.css
  libs/blocks/how-to/how-to.js
  test/blocks/how-to/how-to.test.js
  test/blocks/how-to/mocks/body.html
Labels: verified, run-nala, Ready for Stage

#2441 MWPW-151561 [MILO][MEP] MEP button does not appear if Target is on but there are no pzn manifests
  .github/workflows/code-compatibility.yaml
  .github/workflows/codeql.yml
  .github/workflows/dispatch.yml
  .github/workflows/fg-sync-repos.yml
  .github/workflows/high-impact-alert.yml
  .github/workflows/label-zero-impact.yaml
  .github/workflows/merge-to-main.yaml
  .github/workflows/merge-to-stage.js
  .github/workflows/merge-to-stage.yaml
  .github/workflows/pr-reminders.yaml
  .github/workflows/run-lint.yaml
  .github/workflows/run-nala-milolibs.yaml
  .github/workflows/run-nala.yml
  .github/workflows/run-tests.yaml
  .github/workflows/skms.yaml
  .github/workflows/update-dependencies.yaml
  libs/blocks/carousel/carousel.css
  libs/blocks/carousel/carousel.js
  libs/blocks/global-navigation/utilities/utilities.js
  libs/blocks/how-to/how-to.css
  libs/blocks/how-to/how-to.js
  libs/blocks/merch/merch.js
  libs/blocks/ost/ost.js
  libs/blocks/quiz-results/quiz-results.js
  libs/blocks/quiz/quiz.js
  libs/blocks/quiz/utils.js
  libs/blocks/section-metadata/section-metadata.css
  libs/deps/commerce.js
  libs/deps/merch-quantity-select.js
  libs/features/personalization/personalization.js
  libs/utils/utils.js
  test/blocks/how-to/how-to.test.js
  test/blocks/how-to/mocks/body.html
  test/blocks/merch/merch.test.js
  test/blocks/merch/mocks/body.html
  test/blocks/quiz/utils.test.js
Labels: Ready for Stage

#2446 MWPW-152041[MEP][MILO] Add support for using MEP placeholders in gnav
  libs/blocks/global-navigation/utilities/utilities.js
Labels: high priority, Ready for Stage

#2380 MWPW-148278: Dynamic-Nav hide breadcrumbs
  libs/utils/utils.js
  test/blocks/global-navigation/global-navigation.test.js
Labels: verified, run-nala, Ready for Stage

#2413 MWPW-147594: Consumers mappings for origin not being sent when using sidekick
  test/blocks/caas/send-to-caas.test.js
  tools/send-to-caas/send-utils.js
Labels: caas-configurator, CaaS, Ready for Stage

#2439 MWPW-148437 [MILO][MEP] Placeholders don't work if you qualify for default and override with mep=
  libs/features/personalization/personalization.js
Labels: Ready for Stage

#2417 MWPW-146681 - [LocUI] sidekick integration
  libs/blocks/locui/loc/index.js
  libs/blocks/locui/loc/view.js
  libs/utils/sidekick.js
Labels: new-feature, zero-impact

#2469 MWPW-152456 [MILO][MEP] using the `not-q-always-on-promo` entitlement is selected when it should not be
  libs/features/personalization/personalization.js
Labels: Ready for Stage

#2454 MWPW-151790[MILO][MEP] Organize getPersConfig function in personalization.js
  libs/features/personalization/personalization.js
Labels: Ready for Stage

#2455 [MWPW-151673] Library templates
  libs/blocks/library-config/library-config.css
  libs/blocks/library-config/library-config.js
  libs/blocks/library-config/lists/blocks.js
  libs/blocks/library-config/lists/templates.js
  test/blocks/library-config/mocks/blocks/chart/docx.html
  test/blocks/library-config/mocks/blocks/container/docx-container.html
  test/blocks/library-config/mocks/blocks/container/docx-single-block.html
  test/blocks/library-config/mocks/blocks/marquee/docx.html
  test/blocks/library-config/mocks/blocks/text/docx.html
Labels: new-feature, Ready for Stage

#2463 MWPW-151885 - [LocUI] messaging for auth redirect
  libs/blocks/locui/locui.css
  libs/blocks/locui/locui.js
  libs/utils/utils.js
Labels: trivial, Ready for Stage

#2229 MWPW-146856: Left/right padding missing on segment cards on mobile
  libs/deps/merch-card.js
Labels: verified, run-nala, commerce, merch card, Ready for Stage

#2403 MWPW-142935 [Project PEP] PEP <> Geo Routing Modal Interactions
  libs/features/webapp-prompt/webapp-prompt.js
  test/features/webapp-prompt/webapp-prompt.test.js
Labels: verified, Ready for Stage

#2438 MWPW-147206 making promo schedule geo aware
  libs/features/personalization/promo-utils.js
  libs/utils/utils.js
  test/features/personalization/mocks/head-schedule.html
  test/features/personalization/promo-utils.test.js
  test/utils/mocks/mep/head-promo.html
  test/utils/utils-mep.test.js
Labels: verified, run-nala, commerce, Ready for Stage

#2467 [MWPW-151172][Kodiak] Package updates
  .github/workflows/label-zero-impact.js
  package-lock.json
Labels: Ready for Stage

#2474 mwpw-152624: improve stage PR communication
  .github/workflows/merge-to-stage.js
Labels: zero-impact, Ready for Stage

#2407 Container PR for initial TWP features
  libs/blocks/merch-card/merch-card.css
  libs/blocks/merch-card/merch-card.js
  libs/blocks/merch-card/merch-offer-select.js
  libs/blocks/merch-offers/merch-offers.js
  libs/blocks/merch-twp/merch-twp.css
  libs/blocks/merch-twp/merch-twp.js
  libs/deps/merch-icon.js
  libs/deps/merch-secure-transaction.js
  libs/deps/merch-sidenav.js
  libs/deps/merch-stock.js
  libs/deps/merch-subscription-panel.js
  libs/deps/merch-twp-d2p.js
  libs/features/spectrum-web-components/dist/alert-dialog.js
  libs/features/spectrum-web-components/dist/base.js
  libs/features/spectrum-web-components/dist/button-group.js
  libs/features/spectrum-web-components/dist/checkbox.js
  libs/features/spectrum-web-components/dist/dialog.js
  libs/features/spectrum-web-components/dist/help-text.js
  libs/features/spectrum-web-components/dist/icons-workflow.js
  libs/features/spectrum-web-components/dist/icons/asterisk.js
  libs/features/spectrum-web-components/dist/icons/checkmark.js
  libs/features/spectrum-web-components/dist/icons/chevron.js
  libs/features/spectrum-web-components/dist/icons/corner-triangle.js
  libs/features/spectrum-web-components/dist/icons/cross.js
  libs/features/spectrum-web-components/dist/icons/dash.js
  libs/features/spectrum-web-components/dist/link.js
  libs/features/spectrum-web-components/dist/overlay.js
  libs/features/spectrum-web-components/dist/search.js
  libs/features/spectrum-web-components/dist/sidenav.js
  libs/features/spectrum-web-components/dist/tabs.js
  libs/features/spectrum-web-components/dist/textfield.js
  libs/features/spectrum-web-components/dist/theme.js
  libs/features/spectrum-web-components/dist/tooltip.js
  libs/features/spectrum-web-components/package-lock.json
  libs/features/spectrum-web-components/package.json
  libs/features/spectrum-web-components/src/icons-workflow.js
  libs/features/spectrum-web-components/src/tabs.js
  libs/features/spectrum-web-components/src/theme.js
  libs/features/spectrum-web-components/src/tooltip.js
  test/blocks/merch-card/merch-card.test.js
  test/blocks/merch-card/merch-offer-select.test.js
  test/blocks/merch-card/mocks/selection-cards.html
  test/blocks/merch-card/mocks/twp.html
  test/blocks/merch-twp/assets/creative-cloud.svg
  test/blocks/merch-twp/assets/illustrator.svg
  test/blocks/merch-twp/assets/lightroom.svg
  test/blocks/merch-twp/assets/photoshop.svg
  test/blocks/merch-twp/assets/premiere-pro.svg
  test/blocks/merch-twp/merch-twp.2cards.test.html
  test/blocks/merch-twp/merch-twp.3cards.test.html
  test/blocks/merch/merch.test.js
  test/blocks/merch/mocks/body.html
  test/blocks/merch/mocks/named-offers.json
Labels: verified, run-nala, commerce, Ready for Stage

#2468 MWPW-151816 - [LocUI] Link to error matrix documentation
  libs/blocks/locui/langs/modal.js
  libs/blocks/locui/locui.css
  libs/blocks/locui/status/index.js
  libs/blocks/locui/status/view.js
Labels: zero-impact

#2412 MWPW-144801 - [Hero-Marquee] 🆕 block
  libs/blocks/adobetv/adobetv.js
  libs/blocks/brick/brick.js
  libs/blocks/hero-marquee/hero-marquee.css
  libs/blocks/hero-marquee/hero-marquee.js
  libs/styles/breakpoint-theme.css
  libs/utils/decorate.js
  libs/utils/utils.js
  test/blocks/hero-marquee/hero-marquee.test.js
  test/blocks/hero-marquee/mocks/body.html
Labels: verified, new-feature, Ready for Stage

#2478 MWPW-152659 [MILO][MODAL][ANALYTICS] Analytic on modal load is missing
  libs/blocks/modal/modal.js
Labels: high priority, Ready for Stage

#2405 MWPW-148054: Mnemonics list in a text block
  libs/blocks/text/text.js
  test/blocks/text/mocks/body.html
  test/blocks/text/text.test.js
Labels: verified, run-nala, Ready for Stage

#2494 MWPW-152912 - [LocUI] Fix duplicate fragments in search
  libs/blocks/locui/actions/index.js
Labels: bug

#2488 [MWPW-152676] Ensure all Graybox URLs use STAGE environment
  libs/utils/utils.js
Labels: run-nala, Ready for Stage

#2402 MWPW-140523: Update existing LANA logs to capture potential client errors
  libs/blocks/global-footer/global-footer.js
  libs/blocks/global-navigation/global-navigation.js
  libs/blocks/global-navigation/utilities/menu/menu.js
  libs/blocks/global-navigation/utilities/utilities.js
  test/blocks/global-footer/global-footer.test.js
  test/blocks/global-navigation/global-navigation.test.js
Labels: verified, Ready for Stage

#2459 MWPW-148002: Adjust Strike-through price font size for: merch-card (all variations)
  libs/blocks/merch/merch.css
Labels: verified, run-nala, Ready for Stage

#2485 MWPW-152759 - [LocUI] update skipped message
  libs/blocks/locui/langs/modal.js
  libs/blocks/locui/status/view.js
Labels: zero-impact

#2449 MWPW-151588: fix geo modal is not closed on ESC
  libs/features/georoutingv2/georoutingv2.js
Labels: verified, run-nala, Ready for Stage

#2473 MWPW-139487 - Fix for Gnav scroll issue with Landscape Orientation on devices
  libs/blocks/global-navigation/global-navigation.css
Labels: verified, Ready for Stage

#2497 [MWPW-129964] Fix accessibility issues for georouting language selector
  libs/features/georoutingv2/georoutingv2.js
Labels: run-nala, Ready for Stage

#2506 MWPW-143637 [Milo]Component Enhancements for ACE0861 Prioritized Placements HP Test
  libs/mep/ace0861/brick/brick.css
  libs/mep/ace0861/brick/brick.js
  libs/mep/ace0861/section-metadata/README.md
  libs/mep/ace0861/section-metadata/section-metadata.css
  libs/mep/ace0861/section-metadata/section-metadata.js
  libs/mep/ace0861/section-metadata/sticky-section.js
Labels: zero-impact, Ready for Stage

#2477 MWPW-152627 [MILO][MARTECH] add Target propositionDisplay call
  libs/martech/martech.js
Labels: Ready for Stage

#2481 MWPW-150705: De-couple Result Spreadsheet for Interactive Front Door Experience
  libs/blocks/quiz-entry/quiz-entry.js
  libs/blocks/quiz-entry/utils.js
  libs/blocks/quiz/quiz.js
  libs/blocks/quiz/utils.js
  test/blocks/quiz-entry/mocks/mock-data.js
  test/blocks/quiz-entry/mocks/results.json
  test/blocks/quiz-entry/quiz-entry.test.js
  test/blocks/quiz-entry/utils.test.js
  test/blocks/quiz/quiz.test.js
Labels: verified, uar, Ready for Stage

#2483 MWPW-146326 introduce promo text for all cards
  libs/blocks/merch-card/merch-card.js
  libs/deps/merch-card.js
  test/blocks/merch-card/merch-card.test.js
  test/blocks/merch-card/mocks/catalog.html
  test/blocks/merch-card/mocks/intro-pricing.html
  test/blocks/merch-card/mocks/mini-compare-chart.html
  test/blocks/merch-card/mocks/plans-card.html
  test/blocks/merch-card/mocks/segment-card.html
Labels: high-impact, verified, run-nala, commerce, Ready for Stage

#2505 MWPW-146782: Add Description to Article richresults
  libs/features/richresults.js
  test/utils/mocks/head-rich-results-article.html
  test/utils/mocks/head-rich-results.html
  test/utils/richresults.test.js
Labels: trivial, Ready for Stage

#2502 MWPW-153068: fix missing 'P3Y' in ost
  libs/blocks/ost/ost.js
Labels: verified, run-nala, commerce, Ready for Stage

#2504 MWPW-152283: [TEST] switch WCS to acom domain
  libs/deps/commerce.js
Labels: run-nala, commerce, Ready for Stage

#2517 MWPW-153129 - [LocUI] Index pathname conditions in find fragments
  libs/blocks/locui/actions/index.js
Labels: bug, zero-impact

#2526 Support pills
  libs/blocks/caas/utils.js
Labels: testing

#2511 Integrating spectrum Toast in milo required by Event creation console.
  libs/features/spectrum-web-components/dist/icons-ui.js
  libs/features/spectrum-web-components/dist/toast.js
  libs/features/spectrum-web-components/package-lock.json
  libs/features/spectrum-web-components/package.json
  libs/features/spectrum-web-components/src/icons-ui.js
  libs/features/spectrum-web-components/src/toast.js
  test/features/spectrum-web-components/toast.test.html
Labels: run-nala, Ready for Stage

#2529 Revert "MWPW-148002: Adjust Strike-through price font size for: merch-card (all variations)"
  libs/blocks/merch/merch.css
Labels: verified, Ready for Stage
