Repository adobecom/milo, pull requests merged in 2024-12, with the labels that each got.

#3233 MWPW-162717: Media locks above the Nav post scroll
  libs/blocks/table/table.css
Labels: verified, high priority, Ready for Stage

#3153 Aside spacing issue when using AdobeTV urls
  libs/blocks/aside/aside.js
Labels: bug, verified, Ready for Stage

#3177 MWPW-157506: Localized Placeholder Texts on English Pages
  libs/features/placeholders.js
  test/features/placeholders/bg/placeholders.json
  test/features/placeholders/placeholders.json
  test/features/placeholders/placeholders.test.js
Labels: verified, Ready for Stage

#3178 [MWPW-162258][NALA] Increase GitHub Test Execution Worker Count for Nala to Improve Execution Speed
  playwright.config.js
Labels: Ready for Stage

#3199 DOTCOM-140152 - Update helix-query for Blog usage
  helix-query.yaml
Labels: Ready for Stage

#3213 quiz button and indicator accessibility
  libs/blocks/quiz/quizoption.js
  libs/blocks/quiz/stepIndicator.js
Labels: verified, uar, Ready for Stage

#3226 MWPW-162668: makes tags in collection request non-case-sensitive
  libs/blocks/caas/utils.js
Labels: verified, caas-configurator, Ready for Stage

#3245 MWPW-162669: Adds useHtml default setting to Presets configuration
  tools/send-to-caas/bulk-publish-to-caas.beta.js
Labels: verified, CaaS, Ready for Stage

#3250 MWPW-162990 [MEP] Exclude MEP button from rtl formatting
  libs/features/personalization/preview.css
Labels: verified, Ready for Stage

#3271 MWPW-161645: lana logging for CCD
  .github/workflows/run-tests.yaml
  libs/deps/mas/commerce.js
  libs/deps/mas/mas.js
  libs/features/mas/dist/mas.js
  libs/features/mas/docs/ccd.html
  libs/features/mas/docs/mas.html
  libs/features/mas/docs/mas.js.html
  libs/features/mas/docs/src/mas.js.md
  libs/features/mas/docs/src/mas.md
  libs/features/mas/src/defaults.js
  libs/features/mas/src/img/checkmark-white-small.svg
  libs/features/mas/src/img/ellipsis.svg
  libs/features/mas/src/img/secure-transaction.svg
  libs/features/mas/src/lana.js
  libs/features/mas/src/log.js
  libs/features/mas/src/mas-commerce-service.js
  libs/features/mas/src/mas-element.js
  libs/features/mas/src/mas.js
  libs/features/mas/src/price/template.js
  libs/features/mas/src/settings.js
  libs/features/mas/src/wcs.js
  libs/features/mas/test/checkout.test.js
  libs/features/mas/test/lana.test.js
  libs/features/mas/test/mas-commerce-service.test.js
  libs/features/mas/test/price.test.js
  libs/features/mas/test/wcs.test.js
  libs/utils/lana.js
  test/utils/lana.test.js
  test/utils/lanaDefaultOptions.test.js
Labels: verified, commerce

#3132 MWPW-161273 Standalone Gnav needs a release cycle [Bundle]
  .eslintrc-code-compatibility.js
  .eslintrc.js
  .github/workflows/release-standalone-feds.yml
  .gitignore
  libs/blocks/global-footer/global-footer.css
  libs/blocks/global-footer/global-footer.js
  libs/blocks/global-navigation/base.css
  libs/blocks/global-navigation/global-navigation.js
  libs/blocks/global-navigation/utilities/getUserEntitlements.js
  libs/blocks/global-navigation/utilities/getUserEventHistory.js
  libs/blocks/global-navigation/utilities/utilities.js
  libs/blocks/region-nav/region-nav.css
  libs/navigation/base.css
  libs/navigation/bootstrapper.js
  libs/navigation/build.mjs
  libs/navigation/dark-nav.css
  libs/navigation/footer.css
  libs/navigation/navigation.css
  libs/navigation/navigation.js
  libs/navigation/package-lock.json
  libs/navigation/package.json
  libs/utils/utils.js
  test/blocks/global-footer/global-footer.test.js
  test/blocks/global-navigation/keyboard/mocks/global-nav-mobile.html
  test/blocks/global-navigation/keyboard/mocks/global-nav.html
  test/navigation/bootstrapper.test.js
  test/navigation/navigation.test.js
Labels: verified, high priority, Ready for Stage

#3124 MWPW-155723 - Adds group metadata to ensure dyanmic nav continuity
  libs/features/dynamic-navigation/dynamic-navigation.js
  libs/features/dynamic-navigation/status.js
  test/features/dynamic-nav/dynamicNav.test.js
  test/features/dynamic-nav/status.test.js
Labels: verified, run-nala, Ready for Stage, Stale

#3204 MWPW-160774 - [Table] top variant
  libs/blocks/table/table.css
Labels: new-feature, needs-verification, Ready for Stage

#3251 MWPW-163002-proxy marketing scripts for newsroom
  libs/martech/martech.js
Labels: Ready for Stage

#3053 Feat(MWPW-146367):Added accessibility player controls (NON MPC)
  libs/blocks/adobetv/adobetv.css
  libs/blocks/aside/aside.css
  libs/blocks/aside/aside.js
  libs/blocks/brick/brick.css
  libs/blocks/carousel/carousel.css
  libs/blocks/carousel/carousel.js
  libs/blocks/figure/figure.js
  libs/blocks/global-footer/global-footer.js
  libs/blocks/global-navigation/features/profile/dropdown.js
  libs/blocks/global-navigation/features/search/gnav-search.js
  libs/blocks/global-navigation/global-navigation.js
  libs/blocks/global-navigation/utilities/utilities.js
  libs/blocks/hero-marquee/hero-marquee.js
  libs/blocks/how-to/how-to.js
  libs/blocks/marquee/marquee.js
  libs/blocks/video/video.css
  libs/features/webapp-prompt/webapp-prompt.js
  libs/utils/decorate.js
  libs/utils/federated.js
  nala/blocks/marquee/marquee.test.js
  test/blocks/adobetv/adobetv.test.js
  test/blocks/figure/figure.test.js
  test/blocks/global-navigation/utilities/utilities.test.js
  test/blocks/how-to/how-to.test.js
  test/blocks/how-to/mocks/body.html
  test/blocks/video/mocks/body.html
  test/blocks/video/video.test.js
Labels: verified, high priority, Ready for Stage

#3287 Add Express SOTs
  .github/workflows/merge-to-stage.js
Labels: zero-impact, Ready for Stage

#3302 MWPW-163606 removed the /dist/ from the css paths where it's incorrect
  libs/navigation/navigation.js
  test/navigation/navigation.test.js
Labels: verified, high priority, Ready for Stage

#3258 [MWPW-158749] Enhance Interact call efficiency and defer non-essentia…
  libs/features/personalization/personalization.js
  libs/martech/helpers.js
  libs/martech/martech.js
  libs/utils/utils.js
  test/martech/helpers.test.js
  test/utils/utils-enable-perf.test.js
  test/utils/utils.test.js
Labels: verified, high priority, Ready for Stage

#3286 [MWPW-161403] Remove default alt from media block
  libs/blocks/media/media.js
Labels: Ready for Stage

#3307 MWPW-161575: Unit tests for FG and GB
  test/tools/floodbox/floodgate/fg-copy.test.js
  test/tools/floodbox/floodgate/utils.test.js
  test/tools/floodbox/graybox/utils.test.js
  test/tools/floodbox/references.test.js
Labels: zero-impact

#3310 Adding prodDomains and allowed origin for standalone gnav
  libs/navigation/navigation.js
Labels: verified, high priority, Ready for Stage

#3238 MWPW-162847 [MEP][nala] add ul-li selector test
  nala/features/personalization/ul-ol-li.spec.js
  nala/features/personalization/ul-ol-li.test.js
Labels: verified, zero-impact, Ready for Stage

#3267 [MWPW-162711][NALA] Update Table block tests to validate tooltip information
  nala/blocks/table/table.page.js
  nala/blocks/table/table.spec.js
  nala/blocks/table/table.test.js
Labels: zero-impact, Ready for Stage, Stale

#3247 [MWPW-161570] Ensure hardcoded decorative SVGs have aria-hidden="true"
  libs/blocks/article-feed/article-feed.js
  libs/blocks/aside/aside.js
  libs/blocks/chart/chart.js
  libs/blocks/footer/footer.js
  libs/blocks/global-footer/global-footer.js
  libs/blocks/global-navigation/utilities/utilities.js
  libs/blocks/gnav/gnav-appLauncher.js
  libs/blocks/gnav/gnav.js
  libs/blocks/modal/modal.js
  libs/blocks/notification/notification.js
  libs/blocks/tabs/tabs.js
  libs/deps/mas/plans-modal.js
  libs/features/personalization/preview.js
  libs/features/spectrum-web-components/dist/popover.js
  libs/mep/dc0994/aside/aside.js
Labels: Ready for Stage

#3255 Allow setting of aria label text for links
  libs/utils/utils.js
  nala/blocks/video/video.spec.js
  test/utils/mocks/body.html
  test/utils/utils.test.js
Labels: Ready for Stage

#3221 MWPW-160380 [Milo]Update A.com CTA color to Spectrum 2 Blue for all A.com CTAs
  libs/deps/mas/mas.js
  libs/deps/mas/merch-card.js
  libs/styles/styles.css
  nala/blocks/aside/aside.test.js
  nala/blocks/marquee/marquee.test.js
Labels: verified, high priority, Ready for Stage

#3322 MWPW-161273 Standalone Gnav needs a release cycle [Bundle]
  libs/blocks/global-footer/global-footer.js
Labels: verified, Ready for Stage

#3323 [MWPW-160919]:- LocV3 Rollout-Translate flow Language selection UI flow.
  libs/blocks/locui-create/input-actions/index.js
  libs/blocks/locui-create/input-actions/view.js
  libs/blocks/locui-create/input-locale/index.js
  libs/blocks/locui-create/input-locale/view.js
  libs/blocks/locui-create/locui-create.css
  libs/blocks/locui-create/store.js
  libs/blocks/locui-create/utils/utils.js
Labels: trivial

#3303 MWPW-163463: Added project type switcher and bifurcated 1st step
  libs/blocks/locui-create/input-urls/index.js
  libs/blocks/locui-create/input-urls/view.js
  libs/blocks/locui-create/locui-create.css
Labels: trivial, zero-impact

#3327 [LOC]Mwpw 163467 action rollout translate
  libs/blocks/locui-create/input-actions/index.js
  libs/blocks/locui-create/input-actions/view.js
  libs/blocks/locui-create/input-locale/index.js
  libs/blocks/locui-create/input-locale/view.js
  libs/blocks/locui-create/locui-create.css
  libs/blocks/locui-create/utils/constant.js
Labels: trivial, zero-impact

#3329 Adding Standalone gnav's default allowed origins
  libs/navigation/navigation.js
Labels: verified, high priority, Ready for Stage

#3259 MWPW-140452 - Icon authoring in milo using the federal repo and individual SVG assets
  libs/blocks/table/table.css
  libs/blocks/text/text.css
  libs/features/georoutingv2/georoutingv2.css
  libs/features/georoutingv2/georoutingv2.js
  libs/features/icons/icons.css
  libs/features/icons/icons.js
  libs/styles/styles.css
  libs/utils/utils.js
  test/features/icons/icons.test.js
  test/features/icons/mocks/body.html
Labels: high-impact, Ready for Stage

#3296 [MWPW-163539] Update RCP workflow
  .github/workflows/helpers.js
  .github/workflows/merge-to-main.js
  .github/workflows/merge-to-main.yaml
  .github/workflows/merge-to-stage.js
  .github/workflows/rcp-notifier.js
Labels: zero-impact, Ready for Stage

#3290 MWPW-156157 use OST v1.19.1
  libs/blocks/ost/ost.js
Labels: verified, commerce, Ready for Stage

#3317 [MWPW-163723] [NALA] Update Nala CircleCI Job to Manual Trigger
  .github/workflows/run-nala-circleci.yml
Labels: zero-impact, Ready for Stage

#3264 MWPW-154147: add spectrum switch component
  libs/features/spectrum-web-components/dist/checkbox.js
  libs/features/spectrum-web-components/dist/switch.js
  libs/features/spectrum-web-components/package.json
  libs/features/spectrum-web-components/src/checkbox.js
  libs/features/spectrum-web-components/src/switch.js
  test/features/spectrum-web-components/switch.test.html
Labels: Ready for Stage

#3335 [NALA][Table-Tooltip] Update tooltip locator
  nala/blocks/table/table.page.js
Labels: zero-impact, Ready for Stage

#3343 [LOC]MWPW-163466: Integrate Project Update API with "publish" flag when user clicks "Create Project" in Actions Screen
  libs/blocks/locui-create/components/toast.js
  libs/blocks/locui-create/create/view.js
  libs/blocks/locui-create/img/s2_icon_close.svg
  libs/blocks/locui-create/input-actions/index.js
  libs/blocks/locui-create/input-actions/modal.js
  libs/blocks/locui-create/input-actions/view.js
  libs/blocks/locui-create/input-locale/index.js
  libs/blocks/locui-create/input-locale/view.js
  libs/blocks/locui-create/input-urls/index.js
  libs/blocks/locui-create/input-urls/view.js
  libs/blocks/locui-create/locui-create.css
  libs/blocks/locui-create/locui-create.js
  libs/blocks/locui-create/store.js
  libs/blocks/locui-create/utils/utils.js
Labels: trivial, zero-impact

#3332 [Locv3] MWPW-63465 create api integration
  libs/blocks/locui-create/components/toast.js
  libs/blocks/locui-create/create/view.js
  libs/blocks/locui-create/img/s2_icon_close.svg
  libs/blocks/locui-create/input-urls/view.js
  libs/blocks/locui-create/locui-create.css
  libs/blocks/locui-create/locui-create.js
  libs/blocks/locui-create/store.js
  libs/blocks/locui-create/utils/constant.js
  libs/blocks/locui-create/utils/utils.js
Labels: trivial

#3324 [ENB-7566] Change domain names for stage, remove personalization logic for not signed in
  libs/martech/helpers.js
  libs/utils/utils.js
Labels: verified, high priority, Ready for Stage

#3201 [MWPW-161870] Fixing the issue that sidenav can't be collapsed.
  libs/blocks/merch-card-collection/merch-card-collection.js
  libs/deps/mas/merch-sidenav.js
  libs/features/mas/web-components/src/sidenav/merch-sidenav-list.js
  libs/features/mas/web-components/test/sidenav/catalog-sidenav.test.html.js
  test/blocks/merch-card-collection/mocks/merch-card-collection.html
Labels: bug, verified, run-nala, Ready for Stage

#3347 [ENB-7567] Remove ee from the link
  libs/martech/helpers.js
Labels: verified, high priority, Ready for Stage

#3336 chore: Ignore tmp folders
  .gitignore
Labels: zero-impact, Ready for Stage

#3344 MWPW-159180 [MILO][MEP] MEP Manifest Manager
  libs/blocks/mmm/mmm.css
  libs/blocks/mmm/mmm.js
  libs/features/personalization/personalization.js
  libs/features/personalization/preview.css
  libs/features/personalization/preview.js
  libs/features/personalization/promo-utils.js
  libs/utils/utils.js
  test/blocks/mmm/mmm.test.js
  test/blocks/mmm/mocks/body.html
  test/blocks/mmm/mocks/get-page.json
  test/blocks/mmm/mocks/get-pages.json
  test/features/personalization/mocks/manifestLists/two-duplicate-manifests-one-from-target.json
  test/features/personalization/mocks/manifestLists/two-duplicate-manifests-other-one-from-target.json
  test/features/personalization/mocks/preview.js
  test/features/personalization/preview.test.js
  test/features/personalization/promo-utils.test.js
Labels: verified, high priority, Ready for Stage

#3318 MWPW-155723 - Adds group metadata to ensure dynamic nav continuity - fix
  libs/features/dynamic-navigation/dynamic-navigation.js
  libs/features/dynamic-navigation/status.js
  test/features/dynamic-nav/dynamicNav.test.js
  test/features/dynamic-nav/status.test.js
Labels: verified, run-nala, Ready for Stage

#3330 MWPW-163754 Color difference is seen in the milo pages
  libs/styles/styles.css
Labels: verified, Ready for Stage

#3349 Fix optional profile page detail in the sidekick
  libs/utils/sidekick-decorate.js
Labels: Ready for Stage

#3277 MWPW-157864 [Catalog] Localise external modals
  libs/blocks/merch/merch.js
  test/blocks/merch/merch.test.js
Labels: verified, Ready for Stage

#3356 Revert "MWPW-140452 - Icon authoring in milo using the federal repo and individual SVG assets"
  libs/blocks/table/table.css
  libs/blocks/text/text.css
  libs/features/georoutingv2/georoutingv2.css
  libs/features/georoutingv2/georoutingv2.js
  libs/features/icons/icons.css
  libs/features/icons/icons.js
  libs/styles/styles.css
  libs/utils/utils.js
  test/features/icons/icons.test.js
  test/features/icons/mocks/body.html
Labels: Ready for Stage

#3357 Revert "MWPW-140452 - Icon authoring in milo using the federal repo a…
  libs/blocks/table/table.css
  libs/blocks/text/text.css
  libs/features/georoutingv2/georoutingv2.css
  libs/features/georoutingv2/georoutingv2.js
  libs/features/icons/icons.css
  libs/features/icons/icons.js
  libs/styles/styles.css
  libs/utils/utils.js
  test/features/icons/icons.test.js
  test/features/icons/mocks/body.html
Labels: verified

#3265 Carousel update for SharePoint video sizing
  libs/blocks/carousel/carousel.css
Labels: bug, verified, Ready for Stage

#3215 MWPW-161872: Self host marketo's forms2.min.js
  .github/workflows/update-dependencies.yaml
  .github/workflows/update-script.js
  libs/blocks/marketo/marketo.js
  libs/deps/forms2.min.js
  test/blocks/marketo/marketo.test.html
  test/blocks/marketo/mocks/marketo-utils.js
Labels: verified, run-nala, Ready for Stage

#3365 Revert "MWPW-163754 Color difference is seen in the milo pages"
  libs/styles/styles.css
Labels: verified, Ready for Stage

#3371 [MWPW-164170] Update RCP dates for 2025
  .github/workflows/helpers.js
Labels: zero-impact

#3366 [Loc] MWPW-164054: added env for edit and create flows
  libs/blocks/locui-create/utils/utils.js
Labels: trivial, zero-impact

#3376 MWPW-164169: Fixed value from override to overwrite
  libs/blocks/locui-create/input-urls/view.js
Labels: trivial

#3361 [Loc]Mwpw-163903: fixes for design feedback on loc create screen
  libs/blocks/locui-create/input-locale/index.js
  libs/blocks/locui-create/input-urls/view.js
  libs/blocks/locui-create/locui-create.css
  libs/blocks/locui-create/utils/constant.js
  libs/blocks/locui-create/utils/utils.js
Labels: trivial, zero-impact

#3353 [Loc] MWPW-163947: Added confirmation modal
  libs/blocks/locui-create/img/alert-icon.svg
  libs/blocks/locui-create/input-actions/confirmationModal.js
  libs/blocks/locui-create/input-actions/index.js
  libs/blocks/locui-create/input-actions/modal.js
  libs/blocks/locui-create/input-actions/view.js
  libs/blocks/locui-create/input-urls/view.js
  libs/blocks/locui-create/locui-create.css
  libs/blocks/locui-create/store.js
Labels: trivial, zero-impact

#3358 [LOC UI] MWPW-164043 - Changes for supporting langstore urls
  libs/blocks/locui/actions/index.js
  libs/blocks/locui/langs/modal.js
  libs/blocks/locui/loc/index.js
  libs/blocks/locui/url/view.js
  libs/blocks/locui/utils/miloc.js
  libs/utils/utils.js
Labels: trivial, zero-impact

#3391 [Loc] MWPW-163949: Project creation success message is not wrapping properly
  libs/blocks/locui-create/locui-create.css
Labels: trivial

#3393 [Loc]MWPW-164350 - Fragments are getting added multiple times in the Enter urls
  libs/blocks/locui-create/input-urls/index.js
Labels: trivial, zero-impact

#3396 Mwpw 164318 edit flow lang
  libs/blocks/locui-create/input-actions/view.js
  libs/blocks/locui-create/locui-create.js
  libs/blocks/locui-create/store.js
  libs/blocks/locui-create/utils/utils.js
Labels: trivial, zero-impact
