Repository adobecom/milo, pull requests merged in 2024-03, with the labels that each got.

#1944 Caas mashup final cm
  libs/blocks/caas-marquee-metadata/caas-marquee-metadata.js
  libs/blocks/caas-marquee/caas-marquee.js
Labels: trivial

#1929 Adobe logo not showing up as expected when retrieved from the federal project
  libs/blocks/global-navigation/utilities/utilities.js
  test/blocks/global-navigation/utilities/utilities.test.js
Labels: verified, run-nala, blocker

#1924 MWPW-143460: Add support for "Mash-Up" marquee
  libs/blocks/caas-marquee-metadata/caas-marquee-metadata.js
  libs/blocks/caas-marquee/caas-marquee.css
  libs/blocks/caas-marquee/caas-marquee.js
Labels: CaaS

#1960 Revert "MWPW-143460: Add support for "Mash-Up" marquee"
  libs/blocks/caas-marquee-metadata/caas-marquee-metadata.js
  libs/blocks/caas-marquee/caas-marquee.css
  libs/blocks/caas-marquee/caas-marquee.js
Labels: trivial

#1954 [Release] Stage to Main
  libs/blocks/global-navigation/utilities/utilities.js
  libs/blocks/region-nav/region-nav.js
  libs/features/georoutingv2/georoutingv2.js
  test/blocks/global-navigation/utilities/utilities.test.js
Labels: run-nala, needs-verification, Ready for Main

#1941 MWPW-140268 [MILO][MEP] Overhaul MEP Action List
  libs/blocks/fragment/fragment.js
  libs/features/personalization/personalization.js
  libs/mep/mepmoreactions/insertScript.js
  libs/mep/mepmoreactions/quote/quote.css
  libs/mep/mepmoreactions/quote/quote.js
  test/features/personalization/actions.test.js
  test/features/personalization/deprecatedActions.test.js
  test/features/personalization/mocks/actions/manifestAppendToSection.json
  test/features/personalization/mocks/actions/manifestInsertAfter.json
  test/features/personalization/mocks/actions/manifestInsertBefore.json
  test/features/personalization/mocks/actions/manifestPrependToSection.json
  test/features/personalization/mocks/actions/manifestRemove.json
  test/features/personalization/mocks/actions/manifestReplace.json
  test/features/personalization/mocks/actions/manifestReplacePage.json
  test/features/personalization/mocks/actions/manifestUpdateMetadata.json
  test/features/personalization/mocks/actions/manifestUseBlockCode.json
  test/features/personalization/mocks/actions/manifestUseBlockCode2.json
  test/features/personalization/mocks/deprecatedActions/manifestInsertContentAfter.json
  test/features/personalization/mocks/deprecatedActions/manifestInsertContentBefore.json
  test/features/personalization/mocks/deprecatedActions/manifestRemoveContent.json
  test/features/personalization/mocks/deprecatedActions/manifestReplaceContent.json
  test/features/personalization/mocks/deprecatedActions/manifestReplaceFragment.json
  test/features/personalization/mocks/fragments/appendToSection.plain.html
  test/features/personalization/mocks/fragments/fragmentReplaced.plain.html
  test/features/personalization/mocks/fragments/inlineFragReplaced.plain.html
  test/features/personalization/mocks/fragments/insertafter.plain.html
  test/features/personalization/mocks/fragments/insertafterfragment.plain.html
  test/features/personalization/mocks/fragments/insertbefore.plain.html
  test/features/personalization/mocks/fragments/insertbeforefragment.plain.html
  test/features/personalization/mocks/fragments/milo-replace-content-chrome-howto-h2.plain.html
  test/features/personalization/mocks/fragments/prependToSection.plain.html
  test/features/personalization/mocks/fragments/replacePage.plain.html
  test/features/personalization/mocks/media_1.jpg
  test/features/personalization/mocks/personalization.html
  test/features/personalization/mocks/postPersonalization.html
  test/features/personalization/normalizePath.test.js
  test/features/personalization/pageFilter.test.js
  test/features/personalization/personalization.test.js
  test/features/personalization/replacePage.test.js
Labels: high-impact, verified, run-nala, Ready To Merge, critical, Ready for Stage

#1963 UnRevert MWPW-143460: Add support for Mash-Up marquee 1924
  libs/blocks/caas-marquee-metadata/caas-marquee-metadata.js
  libs/blocks/caas-marquee/caas-marquee.css
  libs/blocks/caas-marquee/caas-marquee.js
Labels: do not merge, verified, new-feature, CaaS, zero impact, blocker

#1965 [Release] Stage to Main
  libs/blocks/caas-marquee-metadata/caas-marquee-metadata.js
  libs/blocks/caas-marquee/caas-marquee.css
  libs/blocks/caas-marquee/caas-marquee.js
Labels: run-nala, needs-verification, Ready for Main

#1910 MWPW-142894: Global navigation unit tests
  libs/blocks/global-navigation/global-navigation.js
  test/blocks/global-navigation/global-navigation.test.js
  test/blocks/global-navigation/test-utilities.js
Labels: verified, run-nala, Ready for Stage

#1928 MWPW-143135: mep page filter to auto match optional .html extension
  libs/features/personalization/personalization.js
  test/features/personalization/personalization.test.js
Labels: verified, run-nala, Ready for Stage

#1956 MWPW-139939 - Support for quiz state in local storage
  libs/blocks/quiz/quiz.js
  test/blocks/quiz/mocks/mock-states.js
  test/blocks/quiz/quiz.test.js
Labels: verified, run-nala, new-feature

#1948 MWPW-141132 - [Milo Loc V2] urls preview
  libs/blocks/locui/locui.css
  libs/blocks/locui/url/index.js
  libs/blocks/locui/url/tabs.js
Labels: trivial, new-feature

#1978 MWPW-130939 - [Milo Loc v2] Find Nested Fragments
  libs/blocks/locui/actions/index.js
Labels: new-feature, needs-verification

#1887 MWPW-142003: Mini Compare Chart Mobile styling
  libs/blocks/merch-card/merch-card.js
  libs/blocks/merch-card/merch-offer-select.js
  libs/deps/merch-card.js
  libs/deps/merch-offer-select.js
  libs/deps/merch-quantity-select.js
Labels: bug, run-nala, commerce, needs-verification, merch card

#1971 [Release] Stage to Main
  libs/blocks/global-navigation/global-navigation.js
  libs/blocks/media/media.css
  libs/features/georoutingv2/georoutingv2.css
  libs/features/georoutingv2/georoutingv2.js
  libs/features/georoutingv2/getMobileBg.js
  libs/features/personalization/personalization.js
  test/blocks/global-navigation/global-navigation.test.js
  test/blocks/global-navigation/test-utilities.js
  test/features/georoutingv2/georoutingv2.test.js
  test/features/personalization/personalization.test.js
Labels: verified, Ready for Main, BAcom SOT 👌, CC SOT 👌, DC SOT 👌, Homepage SOT 👌, MIQ SOT👌

#1931 MWPW-142069 - Cache control via URL parameter
  libs/blocks/chart/chart.js
  libs/blocks/fragment/fragment.js
  libs/features/icons/icons.js
  libs/features/placeholders.js
  libs/utils/helpers.js
  test/blocks/chart/chart.test.js
  test/blocks/fragment/fragment.test.js
  test/blocks/fragment/mocks/body.html
  test/blocks/fragment/mocks/fragments/frag-cache.plain.html
  test/features/icons/icons.test.js
  test/features/placeholders/placeholders.json
  test/features/placeholders/placeholders.test.js
  test/utils/helpers.test.js
Labels: run-nala, new-feature, @icon-block, needs-verification, @chart, high priority

#1968 MWPW-143825 - Block library block grouping
  libs/blocks/library-container-end/library-container-end.css
  libs/blocks/library-container-start/library-container-start.css
  libs/blocks/library-metadata/library-metadata.css
  libs/blocks/library-metadata/library-metadata.js
Labels: trivial

#1977 MWPW-143936: SEGMENT_MAP is undefined in PROD
  libs/blocks/caas-marquee/caas-marquee.js
Labels: bug, trivial, new-feature, CaaS, zero impact, high priority

#1970 daa-ll not present when using footer-promo-tag in metadata.xlsx
  libs/features/footer-promo.js
Labels: high-impact, verified, run-nala, Ready for Stage

#1973 Setup the federal stage environment
  libs/blocks/global-navigation/utilities/utilities.js
  test/blocks/global-navigation/global-navigation.test.js
  test/blocks/global-navigation/test-utilities.js
  test/blocks/global-navigation/utilities/utilities.test.js
Labels: verified, run-nala-on-feds, zero impact, Ready for Stage

#1985 [Release] Stage to Main
  libs/blocks/caas-marquee/caas-marquee.js
  libs/blocks/chart/chart.js
  libs/blocks/fragment/fragment.js
  libs/blocks/global-navigation/utilities/utilities.js
  libs/blocks/library-container-end/library-container-end.css
  libs/blocks/library-container-start/library-container-start.css
  libs/blocks/library-metadata/library-metadata.css
  libs/blocks/library-metadata/library-metadata.js
  libs/features/footer-promo.js
  libs/features/icons/icons.js
  libs/features/placeholders.js
  libs/utils/helpers.js
  test/blocks/chart/chart.test.js
  test/blocks/fragment/fragment.test.js
  test/blocks/fragment/mocks/body.html
  test/blocks/fragment/mocks/fragments/frag-cache.plain.html
  test/blocks/global-navigation/global-navigation.test.js
  test/blocks/global-navigation/test-utilities.js
  test/blocks/global-navigation/utilities/utilities.test.js
  test/features/icons/icons.test.js
  test/features/placeholders/placeholders.json
  test/features/placeholders/placeholders.test.js
  test/utils/helpers.test.js
Labels: run-nala, needs-verification, Ready for Main, BAcom SOT 👌, DC SOT 👌, Homepage SOT 👌, MIQ SOT👌

#1947 [MWPW-143313] IMS scopes based on UNav enablement
  libs/scripts/scripts.js
  libs/utils/utils.js
Labels: verified, Ready for Stage

#1934 MWPW-142781: add draft param to checkout url
  libs/deps/commerce.js
Labels: verified, run-nala, Ready for Stage

#1930 MWPW-142278: Thumbnail icons are not aligned vertically on iPad- fix
  libs/blocks/icon-block/icon-block.css
Labels: bug, verified, Ready for Stage

#1991 MWPW-143314: [Universal Navigation][Milo] Add support for Notifications analytics
  libs/blocks/global-navigation/global-navigation.js
  test/blocks/global-navigation/global-navigation.test.js
  test/blocks/global-navigation/test-utilities.js
Labels: verified, run-nala, high priority, Ready for Stage

#1987 mwpw-144020: federal/media paths for federal items
  libs/blocks/global-navigation/utilities/utilities.js
  test/blocks/global-navigation/utilities/utilities.test.js
Labels: bug, verified, high priority, Ready for Stage

#1952 MWPW-142130: Update the source of merch-card
  libs/blocks/merch-card/merch-card.js
  libs/blocks/merch-cards/merch-cards.js
  libs/deps/merch-card.js
  test/blocks/merch-card/merch-card.test.js
  test/blocks/merch-card/mocks/catalog.html
  test/blocks/merch-cards/mocks/merch-cards.html
Labels: verified, run-nala, commerce, Ready for Stage

#1994 [Release] Stage to Main
  libs/blocks/global-navigation/global-navigation.js
  libs/blocks/global-navigation/utilities/utilities.js
  libs/blocks/icon-block/icon-block.css
  libs/blocks/merch-card/merch-card.js
  libs/blocks/merch-cards/merch-cards.js
  libs/deps/commerce.js
  libs/deps/merch-card.js
  libs/scripts/scripts.js
  libs/utils/utils.js
  test/blocks/global-navigation/global-navigation.test.js
  test/blocks/global-navigation/test-utilities.js
  test/blocks/global-navigation/utilities/utilities.test.js
  test/blocks/merch-card/merch-card.test.js
  test/blocks/merch-card/mocks/catalog.html
  test/blocks/merch-cards/mocks/merch-cards.html
Labels: run-nala, needs-verification, Ready for Main, BAcom SOT 👌, CC SOT 👌, DC SOT 👌, Homepage SOT 👌, MIQ SOT👌

#2000 MWPW-144237 - [Loc v2] Fix find deep fragments
  libs/blocks/locui/actions/index.js
Labels: bug, trivial

#2002 MWPW-143708 and MWPW-143712 add kodiak auto-ticketing
  .kodiak/config.yaml
Labels: trivial, zero impact, security

#1990 MWPW-143591 Fix Contextual Search Duplicates
  libs/blocks/article-feed/article-feed.js
  libs/blocks/gnav/gnav-contextual-search.js
  libs/blocks/gnav/gnav.js
Labels: bug, verified, run-nala, high priority, critical, Ready for Stage

#1972 MWPW-143673: Load Milo fragment modals from co links
  libs/blocks/merch/merch.css
  libs/blocks/merch/merch.js
  libs/blocks/modal/modal.css
  libs/deps/commerce.js
  test/blocks/merch/merch.test.js
  test/blocks/merch/mocks/body.html
  test/blocks/merch/mocks/embed-utils.js
  test/blocks/merch/mocks/fetch.js
  test/blocks/merch/mocks/fragments/twp-url.plain.html
  test/blocks/merch/mocks/fragments/twp.plain.html
  test/blocks/merch/mocks/named-offers.json
Labels: verified, run-nala, commerce, Ready for Stage

#1937 MWPW-142894: fragments can lead to invalid html
  libs/blocks/fragment/fragment.js
  libs/blocks/global-navigation/utilities/utilities.js
  test/blocks/fragment/fragment.test.js
  test/blocks/fragment/mocks/body.html
  test/blocks/fragment/mocks/fragments/frag-p.plain.html
  test/utils/utils.test.js
Labels: verified, run-nala, Ready for Stage

#2003 Caas-Marquee: Fixes integration with martech.js issues
  libs/blocks/caas-marquee/caas-marquee.js
Labels: bug, verified, trivial, run-nala, CaaS, zero impact, high priority, Ready for Stage

#2004 MWPW-143799 - Quiz Accessibility Refinement
  libs/blocks/quiz/quizcontainer.js
  libs/blocks/quiz/quizoption.js
Labels: run-nala, needs-verification

#2005 [Release] Stage to Main
  .kodiak/config.yaml
  libs/blocks/article-feed/article-feed.js
  libs/blocks/caas-marquee/caas-marquee.js
  libs/blocks/fragment/fragment.js
  libs/blocks/global-navigation/utilities/utilities.js
  libs/blocks/gnav/gnav-contextual-search.js
  libs/blocks/gnav/gnav.js
  libs/blocks/merch/merch.css
  libs/blocks/merch/merch.js
  libs/blocks/modal/modal.css
  libs/deps/commerce.js
  test/blocks/fragment/fragment.test.js
  test/blocks/fragment/mocks/body.html
  test/blocks/fragment/mocks/fragments/frag-p.plain.html
  test/blocks/merch/merch.test.js
  test/blocks/merch/mocks/body.html
  test/blocks/merch/mocks/embed-utils.js
  test/blocks/merch/mocks/fetch.js
  test/blocks/merch/mocks/fragments/twp-url.plain.html
  test/blocks/merch/mocks/fragments/twp.plain.html
  test/blocks/merch/mocks/named-offers.json
  test/utils/utils.test.js
Labels: run-nala, needs-verification, Ready for Main, BAcom SOT 👌, CC SOT 👌, DC SOT 👌, Homepage SOT 👌, MIQ SOT👌

#2008 Update martech.main.standard.min.js
  libs/deps/martech.main.standard.min.js
Labels: trivial, high priority, Ready for Stage

#2009 Caas marquee: adds some additional error handlin
  libs/blocks/caas-marquee/caas-marquee.js
Labels: bug, trivial, new-feature, CaaS, zero impact, high priority, Ready for Stage

#1957 MWPW-143648 - [Action Item] Fix float icon position
  libs/blocks/action-item/action-item.css
Labels: bug, verified, Ready for Stage

#1946 MWPW-142798 + MWPW-142872: Made the height-fit-content class to be set automatically
  libs/blocks/modal/modal.css
  libs/blocks/modal/modal.js
  libs/blocks/modal/modal.merch.js
  test/blocks/modals/mocks/iframe.plain.html
  test/blocks/modals/modal.merch.test.js
  test/blocks/modals/modals.test.js
Labels: verified, @modal, Ready for Stage

#1992 [MILO][MEP] MEP parameter spoof breaks if chosen experience has a comma
  libs/features/personalization/personalization.js
  libs/features/personalization/preview.js
  test/features/personalization/preview.test.js
Labels: trivial

#1980 [MILO][MEP] Update Manifest Type and Manifest Ordering v2
  libs/features/personalization/personalization.js
  libs/features/personalization/preview.js
  test/features/personalization/actions.test.js
  test/features/personalization/cleanAndSortManifestList.test.js
  test/features/personalization/deprecatedActions.test.js
  test/features/personalization/mocks/manifestLists/three-manifest-types-all-normal.json
  test/features/personalization/mocks/manifestLists/three-manifest-types-one-first.json
  test/features/personalization/mocks/manifestLists/three-manifest-types-one-last.json
  test/features/personalization/mocks/manifestLists/three-manifest-types-one-no-type.json
  test/features/personalization/mocks/manifestLists/three-manifest-types-one-test-or-promo.json
  test/features/personalization/mocks/manifestLists/two-duplicate-manifests-one-from-target.json
  test/features/personalization/mocks/manifestLists/two-duplicate-manifests-other-one-from-target.json
  test/features/personalization/mocks/manifestLists/two-manifests-one-from-target.json
  test/features/personalization/preview.test.js
  test/utils/utils.test.js
Labels: high-impact, verified

#1959 Deconflicting for MWPW-136727 MEP: Support for simplified selectors
  libs/features/personalization/personalization.js
  test/features/personalization/mocks/deprecatedActions/manifestReplaceContent.json
  test/features/personalization/mocks/manifestBlockNumber.json
  test/features/personalization/mocks/manifestInvalidSelector.json
  test/features/personalization/mocks/manifestSectionBlock.json
  test/features/personalization/mocks/personalization.html
  test/features/personalization/personalization.test.js
Labels: high-impact, verified, run-nala

#2006 [MWPW-144516] Handle cross cloud menu block error
  libs/blocks/fallback/fallback.js
Labels: trivial, Ready for Stage

#1901 fix(MWPW-142248): Accessibility for carousels containing focusable elements.
  libs/blocks/carousel/carousel.js
  test/blocks/carousel/carousel.test.js
Labels: verified, run-nala, Ready for Stage

#2021 MWPW-144575: fix for the modal duplication
  libs/blocks/modal/modal.js
Labels: bug, verified, @modal, Ready for Stage

#2019 [Release] Stage to Main
  libs/blocks/action-item/action-item.css
  libs/blocks/caas-marquee/caas-marquee.js
  libs/blocks/carousel/carousel.js
  libs/blocks/fallback/fallback.js
  libs/blocks/merch/merch.css
  libs/blocks/modal/modal.css
  libs/blocks/modal/modal.js
  libs/blocks/modal/modal.merch.js
  test/blocks/carousel/carousel.test.js
  test/blocks/modals/mocks/iframe.plain.html
  test/blocks/modals/modal.merch.test.js
  test/blocks/modals/modals.test.js
Labels: run-nala, needs-verification, BAcom SOT 👌, CC SOT 👌, DC SOT 👌, Homepage SOT 👌, MIQ SOT👌

#1996 [MWPW-137148] [PERFORMANCE] Load IMS from the same domain
  .github/workflows/localWorkflowConfigs.js
  .github/workflows/update-dependencies.yaml
  .github/workflows/update-script.js
  .gitignore
  libs/deps/imslib.min.js
  libs/utils/utils.js
  package-lock.json
  package.json
Labels: verified, Ready for Stage

#1989 MWPW-142003: Mini Compare Chart Mobile styling
  libs/blocks/merch-card/merch-card.js
  libs/blocks/merch-card/merch-offer-select.js
  libs/deps/merch-card.js
  test/blocks/merch-card/merch-card.test.js
  test/blocks/merch-card/mocks/mini-compare-chart.html
Labels: bug, verified, run-nala, commerce, merch card, Ready for Stage

#1969 MWPW-143202 firefox gnav not appearing bug
  libs/features/georoutingv2/georoutingv2.js
Labels: bug, verified, critical, Ready for Stage

#2023 MWPW-141134 - [Loc v2] Sync to Langstore Confirm Dialog
  libs/blocks/locui/actions/index.js
  libs/blocks/locui/actions/modal.js
  libs/blocks/locui/actions/view.js
  libs/blocks/locui/loc/index.js
  libs/blocks/locui/locui.css
  libs/blocks/locui/utils/state.js
Labels: trivial, new-feature

#2033 MWPW-140540 - [Loc V2] Language Error Dialog
  libs/blocks/locui/langs/index.js
  libs/blocks/locui/langs/modal.js
  libs/blocks/locui/langs/view.js
  libs/blocks/locui/locui.css
Labels: trivial, new-feature

#1942 Excluding modals from Active link check
  libs/blocks/global-navigation/utilities/utilities.js
Labels: verified, run-nala, high priority, Ready for Stage

#2020 [MWPW-144602] Ensure DNT functionality in top nav
  libs/blocks/global-navigation/global-navigation.js
  libs/blocks/global-navigation/utilities/menu/menu.js
Labels: bug, verified, Ready for Stage

#2030 MWPW-144026 Update Twitter Icon to X
  libs/img/icons/icons.svg
Labels: verified, run-nala, Ready for Stage

#1997 Add support for bold as header if no header
  libs/martech/attributes.js
  test/martech/attributes.test.js
  test/martech/mocks/body.html
Labels: high-impact, verified, run-nala, Ready for Stage

#1995 [MWPW-144112] send-to-caas: point to prod end-point
  tools/send-to-caas/send-utils.js
Labels: verified, CaaS, Ready for Stage

#1951 MWPW-141020: [Project PEP] Implement Analytics Enablement
  libs/features/webapp-prompt/webapp-prompt.js
Labels: verified, Ready for Stage

#1966 [MILO] Allow svg or media files to be located in a fragments folder
  libs/utils/utils.js
  test/utils/mocks/svg.html
  test/utils/svg.test.js
Labels: high-impact, verified, run-nala, Ready for Stage

#2032 UAR integration - Quiz Sync for state in local storage and accessibility
  libs/blocks/quiz/quiz.js
  libs/blocks/quiz/quizcontainer.js
  libs/blocks/quiz/quizoption.js
  test/blocks/quiz/mocks/mock-states.js
  test/blocks/quiz/quiz.test.js
Labels: verified, run-nala, uar, Ready for Stage

#2046 MWPW-141134 - [Loc v2] Remove find fragments
  libs/blocks/locui/actions/index.js
  libs/blocks/locui/actions/view.js
  libs/blocks/locui/loc/index.js
  libs/blocks/locui/utils/miloc.js
  libs/blocks/locui/utils/state.js
Labels: trivial

#2049 Adobe logo not showing up as expected when retrieved from the federal project
  libs/blocks/global-footer/global-footer.js
  libs/blocks/global-navigation/global-navigation.js
  libs/blocks/global-navigation/utilities/utilities.js
Labels: verified, high priority, Ready for Stage

#2051 MWPW-143067 split mep param to ---
  libs/features/personalization/add-preview-to-config.js
Labels: verified, trivial, critical, Ready for Stage

#2017 MWPW-144588: decorate placeholders of inline fragments
  libs/utils/utils.js
Labels: verified, run-nala, Ready for Stage

#1939 MWPW-140481: Delayed modal
  libs/blocks/modal/modal.js
  test/blocks/modals/modals.test.js
  test/features/personalization/mocks/deprecatedActions/manifestInsertContentAfter.json
Labels: verified, run-nala, @modal, Ready for Stage

#2045 MWPW-145115 CaaS Configurator: Load latest tags
  libs/blocks/caas-config/caas-config.js
  libs/blocks/caas-config/caas-tags.js
Labels: trivial, high priority, Ready for Stage

#1988 MWPW-143262: offer preview removed as auto-block
  libs/utils/utils.js
Labels: verified, run-nala, commerce, zero impact, Ready for Stage

#2058 MWPW-145171: mep fix for replace action
  libs/features/personalization/personalization.js
Labels: verified, trivial, run-nala, critical, Ready for Stage

#2055 [Release] Stage to Main
  libs/blocks/caas-config/caas-config.js
  libs/blocks/caas-config/caas-tags.js
  libs/blocks/global-footer/global-footer.js
  libs/blocks/global-navigation/global-navigation.js
  libs/blocks/global-navigation/utilities/utilities.js
  libs/blocks/modal/modal.js
  libs/features/personalization/add-preview-to-config.js
  libs/features/personalization/personalization.js
  libs/utils/utils.js
  test/blocks/modals/modals.test.js
  test/features/personalization/mocks/deprecatedActions/manifestInsertContentAfter.json
Labels: run-nala, Ready for Main, BAcom SOT 👌, CC SOT 👌, DC SOT 👌, Homepage SOT 👌, MIQ SOT👌

#2034 MWPW-143822 Dispatch DC workflow for Milo stage PR
  .github/workflows/dispatch.yml
Labels: trivial, testing, zero impact

#2050 Bulk Publish Performance Enhancements
  libs/blocks/bulk-publish-v2/components/bulk-publisher.css
  libs/blocks/bulk-publish-v2/components/bulk-publisher.js
  libs/blocks/bulk-publish-v2/components/job-process.css
  libs/blocks/bulk-publish-v2/components/job-process.js
  libs/blocks/bulk-publish-v2/services.js
  libs/blocks/bulk-publish-v2/utils.js
Labels: verified, new-feature, zero impact, high priority, Ready for Stage

#2056 better check for duplicates when from Target
  libs/features/personalization/personalization.js
Labels: trivial, run-nala, new-feature, zero impact, Ready for Stage

#2060 [Release][Zero Impact] Stage to Main
  .github/workflows/dispatch.yml
  libs/blocks/bulk-publish-v2/components/bulk-publisher.css
  libs/blocks/bulk-publish-v2/components/bulk-publisher.js
  libs/blocks/bulk-publish-v2/components/job-process.css
  libs/blocks/bulk-publish-v2/components/job-process.js
  libs/blocks/bulk-publish-v2/services.js
  libs/blocks/bulk-publish-v2/utils.js
  libs/features/personalization/personalization.js
Labels: Ready for Main, zero impact

#2064 MWPW-144236 - [locui] Fix inconsistency with total count
  libs/blocks/locui/langs/view.js
Labels: trivial, zero impact

#2075 MWPW-144236 - Correct rollout total
  libs/blocks/locui/langs/view.js
Labels: trivial, zero impact

#2082 MWPW-137053 - [LocUI v2] Display create project errors
  libs/blocks/locui/actions/index.js
  libs/blocks/locui/utils/miloc.js
Labels: trivial, new-feature

#2089 MWPW-145783 - Show correct complete label for action type
  libs/blocks/locui/langs/view.js
Labels: trivial, zero-impact
