Repository adobecom/milo, pull requests merged in 2024-10, with the labels that each got.

#2975 MWPW-159157: Update modal to account for new image size
  libs/blocks/media/media.css
Labels: verified, high priority, Ready for Stage

#2963 MWPW-159197 Invoke onReady of standalone gnav when it is rendered #2962
  libs/blocks/global-navigation/global-navigation.js
  test/blocks/global-navigation/test-utilities.js
Labels: verified, Ready for Stage

#2915 MWPW-158776 Fix video CLS
  libs/blocks/adobetv/adobetv.js
  libs/blocks/figure/figure.js
  libs/blocks/marquee/marquee.js
  libs/blocks/video/video.js
  libs/utils/decorate.js
  test/blocks/adobetv/adobetv.test.js
  test/blocks/adobetv/mocks/body.html
  test/blocks/figure/figure.test.js
  test/blocks/figure/mocks/body.html
  test/blocks/marquee/marquee.test.js
  test/blocks/video/mocks/body.html
  test/blocks/video/video.test.js
Labels: Ready for Stage

#2952 MWPW-159028: MAS more technical documents + refactored aem related code
  libs/deps/mas/mas.js
  libs/deps/mas/merch-card.js
  libs/deps/mas/merch-datasource.js
  libs/features/mas/build-docs.mjs
  libs/features/mas/build-docs.sh
  libs/features/mas/commerce/checkout-link.md
  libs/features/mas/commerce/inline-price.md
  libs/features/mas/commerce/src/inline-price.js
  libs/features/mas/docs/checkout-link.html
  libs/features/mas/docs/inline-price.html
  libs/features/mas/docs/mas.html
  libs/features/mas/docs/mas.js.html
  libs/features/mas/docs/merch-card.html
  libs/features/mas/docs/styles.css
  libs/features/mas/mas.md
  libs/features/mas/mas/mas.js.md
  libs/features/mas/mas/mas.md
  libs/features/mas/mas/src/mas.js
  libs/features/mas/mocks/aem.js
  libs/features/mas/web-components/build.mjs
  libs/features/mas/web-components/merch-card.md
  libs/features/mas/web-components/src/aem-datasource.js
  libs/features/mas/web-components/src/aem-fragment.js
  libs/features/mas/web-components/src/aem.js
  libs/features/mas/web-components/src/constants.js
  libs/features/mas/web-components/src/getFragmentById.js
  libs/features/mas/web-components/src/global.css.js
  libs/features/mas/web-components/src/hydrate.js
  libs/features/mas/web-components/src/merch-card.css.js
  libs/features/mas/web-components/src/merch-card.js
  libs/features/mas/web-components/src/merch-datasource.js
  libs/features/mas/web-components/src/variants/catalog.js
  libs/features/mas/web-components/src/variants/ccd-action.js
  libs/features/mas/web-components/src/variants/ccd-slice.js
  libs/features/mas/web-components/src/variants/special-offer.js
  libs/features/mas/web-components/src/variants/variant-layout.js
  libs/features/mas/web-components/test/aem-fragment.test.html
  libs/features/mas/web-components/test/aem-fragment.test.html.js
  libs/features/mas/web-components/test/getFragmentById.test.js
  libs/features/mas/web-components/test/mas.js
Labels: verified, commerce, Ready for Stage

#2977 MWPW-158886: update the way we send arbitrary fields to caas
  test/blocks/caas/mocks/body.html
  test/blocks/caas/send-to-caas.test.js
  tools/send-to-caas/send-utils.js
Labels: Ready for Stage

#2923 MWPW-157888 - Hero marquee w/ no-min-height and no l/r padding when using a full-width variant in masonry(repost)
  libs/blocks/hero-marquee/hero-marquee.css
  libs/blocks/hero-marquee/hero-marquee.js
  test/blocks/hero-marquee/mocks/body.html
Labels: needs-verification, Ready for Stage

#2924 MWPW-158407, 158404, 158406, 158408, 158461: Ignoring decorateMeta if the metadata is from promo.
  libs/utils/utils.js
Labels: run-nala, Ready for Stage

#2939 MWPW-146262 - [Bulk Publish v2] Additional job tools
  libs/blocks/bulk-publish-v2/components/bulk-publisher.css
  libs/blocks/bulk-publish-v2/components/bulk-publisher.js
  libs/blocks/bulk-publish-v2/components/job-info.js
  libs/blocks/bulk-publish-v2/components/job-process.css
  libs/blocks/bulk-publish-v2/components/job-process.js
  libs/blocks/bulk-publish-v2/img/cancel.svg
  libs/blocks/bulk-publish-v2/img/share.svg
  libs/blocks/bulk-publish-v2/services.js
  libs/blocks/bulk-publish-v2/utils.js
  test/blocks/bulk-publish-v2/bulk-publish-v2.test.js
  test/blocks/bulk-publish-v2/mocks/fetch.js
  test/blocks/bulk-publish-v2/mocks/response/sharestatus.json
Labels: new-feature, Ready for Stage

#2971 [MWPW-159181] - links conversion should handle extensions
  libs/scripts/scripts.js
  libs/utils/utils.js
  test/utils/utils.test.js
Labels: Ready for Stage

#2973 Fixed review comments of previous PR of custom Links setup for GNAV
  libs/blocks/global-navigation/global-navigation.js
Labels: verified, Ready for Stage

#2976 MWPW-146211 [MILO][MEP] Option to select all elements
  libs/blocks/fragment/fragment.js
  libs/blocks/global-navigation/utilities/utilities.js
  libs/blocks/merch-card-collection/merch-card-collection.js
  libs/features/personalization/personalization.js
  test/blocks/fragment/fragment.test.js
  test/blocks/merch-card-collection/merch-card-collection.test.js
  test/features/personalization/actions.test.js
  test/features/personalization/actionsTargetManifestId.test.js
  test/features/personalization/parseNestedPlaceholders.test.js
  test/features/personalization/personalization.test.js
Labels: verified, Ready for Stage

#2982 [MWPW-159265] AI callout icon alignment fix in rtl and mobile
  libs/deps/mas/mas.js
  libs/deps/mas/merch-card.js
  libs/deps/mas/plans-modal.js
  libs/features/mas/web-components/src/global.css.js
Labels: bug, verified, run-nala, commerce, merch card, Ready for Stage

#3000 [MWPW-159129] - Add full width GNAV css for adobe home
  libs/navigation/navigation.css
Labels: verified, critical, Ready for Stage

#2998 [MWPW-159328] handle a case where there are not placeholders available
  libs/features/personalization/personalization.js
  test/features/personalization/parseNestedPlaceholders.test.js
Labels: verified, Ready for Stage

#3009 [MWPW-159903] Fix quiz video marquees
  libs/utils/decorate.js
Labels: Ready for Stage

#2991 MWPW-158455: Promobar overlays with localnav elements in devices
  libs/blocks/section-metadata/section-metadata.css
Labels: verified, Ready for Stage

#3033 MWPW-158455: Promobar overlays with localnav elements in devices (#2991)
  libs/blocks/section-metadata/section-metadata.css
Labels: verified, Ready for Main

#3061 Remove @adobecom/admins from codeowners
  CODEOWNERS
Labels: zero-impact

#3062 Limit maximum number of PRs per batch
  .github/workflows/merge-to-stage.js
  .github/workflows/merge-to-stage.yaml
Labels: zero-impact

#3068 Fix the merge to stage process
  .github/workflows/merge-to-stage.js
Labels: zero-impact

#3028 MWPW-157999 - [Table] Add-on content
  libs/blocks/table/table.css
  libs/blocks/table/table.js
  test/blocks/table/mocks/body.html
Labels: new-feature, needs-verification, high priority, Ready for Stage

#3035 Adding support for environment aware link feature to standalone Gnav
  libs/navigation/navigation.js
Labels: verified, high priority, Ready for Stage

#2781 MWPW-154098: Retain Modal param while traversing back from Commerce to Page
  libs/blocks/merch/merch.js
  libs/blocks/merch/upgrade.js
  libs/deps/mas/commerce.js
  libs/features/mas/commerce/src/checkout-link.js
  libs/features/mas/commerce/src/checkout.js
  test/blocks/merch/merch.test.js
  test/blocks/merch/upgrade.test.js
Labels: verified, run-nala, Ready for Stage

#2850 [MWPW-152549] BYO SUSI Options to pass in adobeIMS.signIn()
  libs/blocks/global-navigation/global-navigation.js
  libs/blocks/gnav/gnav.js
  libs/features/jarvis-chat.js
  libs/utils/utils.js
  test/blocks/global-navigation/global-navigation.test.js
  test/blocks/global-navigation/mocks/global-navigation-no-dropdown.plain.js
  tools/send-to-caas/bulk-publish-to-caas.js
  tools/send-to-caas/send-to-caas.js
Labels: run-nala, Ready for Stage

#2984 MWPW-159356: Merch Card grid misalignment fix
  libs/deps/mas/merch-card.js
  libs/features/mas/web-components/src/global.css.js
Labels: verified, commerce, merch card, Ready for Stage

#2996 MWPW-158014 - [Notification] bugs
  libs/blocks/section-metadata/sticky-section.js
  libs/utils/decorate.js
Labels: bug, verified, Ready for Stage

#2997 MWPW-159291 Fix fragment recursive check algo
  libs/blocks/fragment/fragment.js
  test/blocks/fragment/mocks/fragments/frag-b.plain.html
  test/blocks/fragment/mocks/fragments/frag-c.plain.html
  test/blocks/fragment/tree.test.js
Labels: Ready for Stage

#3006 MWPW-146211 add code coverage
  libs/blocks/global-navigation/utilities/utilities.js
  test/blocks/global-navigation/mocks/mep-config.js
Labels: verified, Ready for Stage

#3049 MWPW-160014 : Search container for Standalone Gnav on devices
  libs/blocks/global-navigation/global-navigation.js
  libs/navigation/navigation.css
  test/blocks/global-navigation/global-navigation.test.js
  test/blocks/global-navigation/test-utilities.js
Labels: verified, high priority, Ready for Stage

#3069 [Release] Stage to Main
  .github/workflows/merge-to-stage.js
  libs/blocks/fragment/fragment.js
  libs/blocks/global-navigation/global-navigation.js
  libs/blocks/global-navigation/utilities/utilities.js
  libs/blocks/gnav/gnav.js
  libs/blocks/merch/merch.js
  libs/blocks/merch/upgrade.js
  libs/blocks/section-metadata/sticky-section.js
  libs/blocks/table/table.css
  libs/blocks/table/table.js
  libs/deps/mas/commerce.js
  libs/deps/mas/merch-card.js
  libs/deps/mas/merch-sidenav.js
  libs/features/jarvis-chat.js
  libs/features/mas/commerce/src/checkout-link.js
  libs/features/mas/commerce/src/checkout.js
  libs/features/mas/web-components/src/global.css.js
  libs/features/mas/web-components/src/sidenav/merch-sidenav.js
  libs/features/mas/web-components/test/merch-card-collection.test.html.js
  libs/navigation/navigation.css
  libs/navigation/navigation.js
  libs/utils/decorate.js
  libs/utils/utils.js
  test/blocks/fragment/mocks/fragments/frag-b.plain.html
  test/blocks/fragment/mocks/fragments/frag-c.plain.html
  test/blocks/fragment/tree.test.js
  test/blocks/global-navigation/global-navigation.test.js
  test/blocks/global-navigation/mocks/global-navigation-no-dropdown.plain.js
  test/blocks/global-navigation/mocks/mep-config.js
  test/blocks/global-navigation/test-utilities.js
  test/blocks/merch/merch.test.js
  test/blocks/merch/upgrade.test.js
  test/blocks/table/mocks/body.html
  tools/send-to-caas/bulk-publish-to-caas.js
  tools/send-to-caas/send-to-caas.js
Labels: BAcom SOT 👌, CC SOT 👌, Homepage SOT 👌, MIQ SOT👌, run-nala-on-caas

#3029 MWPW-157618: How-to block video support for mp4 and adobetv
  libs/blocks/how-to/how-to.css
  libs/blocks/how-to/how-to.js
  libs/styles/styles.css
  libs/utils/decorate.js
  test/blocks/how-to/how-to.test.js
  test/blocks/how-to/mocks/body.html
Labels: needs-verification, high priority, Ready for Stage, DC SOT 👌

#2881 MWPW-158182 add callback of URL for google yolo
  libs/features/google-login.js
  libs/scripts/delayed.js
  libs/utils/utils.js
  test/features/google-login/google-login.test.js
  test/scripts/delayed.test.js
Labels: run-nala, Ready for Stage

#3007 MWPW-152455 added handling of "no placeholders" case for parsePlaceholders()
  libs/features/personalization/personalization.js
  test/features/personalization/parseNestedPlaceholders.test.js
Labels: verified, Ready for Stage

#3008 graybox no-click fix
  libs/blocks/graybox/graybox.css
Labels: verified, Ready for Stage

#3010 MWPW-150610: implement partial load options in configurator
  libs/blocks/caas-config/caas-config.js
  libs/blocks/caas/utils.js
  test/blocks/caas-config/expectedConfigs/defaultConfig.js
  test/blocks/caas/caas.test.html
  test/blocks/caas/utils.test.js
Labels: CaaS, Ready for Stage, run-nala-on-caas

#3020 [MWPW-159905] - Add config for full width and no border along with jarvis fix for standalone GNAV
  libs/blocks/global-navigation/global-navigation.js
  libs/blocks/global-navigation/utilities/utilities.js
  libs/navigation/bootstrapper.js
  libs/navigation/navigation.css
  libs/navigation/navigation.js
  test/blocks/global-navigation/global-navigation.test.js
  test/blocks/global-navigation/mocks/navigation-with-custom-links.plain.js
  test/navigation/bootstrapper.test.js
  test/navigation/mocks/gnav.html
Labels: verified, Ready for Stage

#3021 MWPW-160061: Clickable App and Playstore links
  libs/blocks/media/media.js
Labels: Ready for Stage

#3030 MWPW-148185 [MILO][MEP] Promo modal suppression mechanism
  libs/blocks/modal/modal.js
  test/blocks/modals/modals.test.js
Labels: verified, Ready for Stage

#3059 MWPW-158736: [Black Friday] CRM modal not opening when promo_id attached
  libs/blocks/merch/merch.js
  test/blocks/merch/merch.test.js
Labels: verified, run-nala, high priority, Ready for Stage

#3084 Adding creative cloud stage link to stageDomainsMap
  libs/navigation/navigation.js
Labels: verified, high priority, Ready for Stage

#2992 [MWPW-155061] Secure transaction label is not center aligned with CTA
  libs/deps/mas/mas.js
  libs/deps/mas/merch-card.js
  libs/features/mas/web-components/src/merch-card.css.js
Labels: verified, run-nala, commerce, merch card, Ready for Stage

#2994 MWPW-159427: Milo Catalog: Ipad specific issues
  libs/deps/mas/merch-card-collection.js
  libs/deps/mas/merch-sidenav.js
  libs/deps/mas/merch-subscription-panel.js
  libs/features/mas/web-components/src/sidenav/merch-sidenav.js
Labels: verified, Ready for Stage

#3011 [MWPW-159901] Removed testing code
  libs/scripts/scripts.js
Labels: Ready for Stage

#3031 MWPW-160200: clean up sort options for caas
  libs/blocks/caas-config/caas-config.js
  libs/blocks/caas/utils.js
Labels: verified, caas-configurator, CaaS, Ready for Stage

#3040 MWPW-153237: Test content for CCD validation
  libs/features/mas/docs/ccd.html
  libs/features/mas/docs/mas.js.html
  libs/features/mas/docs/styles.css
  libs/features/mas/mas/mas.js.md
  libs/features/spectrum-web-components/build.mjs
  libs/features/spectrum-web-components/dist/themes/dark.js
  libs/features/spectrum-web-components/dist/themes/light.js
  libs/features/spectrum-web-components/src/themes/dark.js
  libs/features/spectrum-web-components/src/themes/light.js
Labels: verified, run-nala, commerce, Ready for Stage

#3042 Opt-out class to prevent automatic addition of daa-ll
  libs/martech/attributes.js
  libs/martech/attributes.md
Labels: verified, Ready for Stage

#3070 Improve RCP communication by sending out reminders
  .github/workflows/helpers.js
  .github/workflows/merge-to-stage.js
  .github/workflows/merge-to-stage.yaml
  .github/workflows/rcp-notifier.js
  .github/workflows/rcp-notifier.yml
Labels: zero-impact

#3081 [MWPW-160735][NALA] Add Nala-specific user-agent
  playwright.config.js
Labels: Ready for Stage

#3086 [MWPW-160958][NALA] Increase Nala test execution worker count in GitHub
  nala/utils/pr.run.sh
  playwright.config.js
Labels: Ready for Stage

#3087 [MWPW-160961][NALA]Move and Update Nala Personalization feature automation tests to Milo repo
  nala/features/personalization/personalization.spec.js
  nala/features/personalization/personalization.test.js
Labels: zero-impact, Ready for Stage

#3079 [MWPW-158315][NALA][Accessibility] Add Accessibility automation tests scripts for milo blocks
  nala/blocks/accordion/accordion.test.js
  nala/blocks/actionitem/actionitem.test.js
  nala/blocks/aside/aside.test.js
  nala/blocks/card/card.test.js
  nala/blocks/carousel/carousel.test.js
  nala/blocks/chart/chart.test.js
  nala/blocks/columns/columns.test.js
  nala/blocks/figure/figure.spec.js
  nala/blocks/figure/figure.test.js
  nala/blocks/howto/howto.spec.js
  nala/blocks/howto/howto.test.js
  nala/blocks/icon/icon.test.js
  nala/libs/accessibility.js
  nala/libs/customerrors.js
  package-lock.json
  package.json
Labels: zero-impact, Ready for Stage

#3088 [MWPW-160862] [Milo OST] Add 'Save now' to dropdown of CTA text options
  libs/blocks/ost/ctaTextOption.js
  test/blocks/ost/textOption.test.js
Labels: verified, run-nala, commerce, high priority, Ready for Stage

#2920 MWPW-157147: Dynamic Nav Status Button
  libs/blocks/global-navigation/global-navigation.js
  libs/features/dynamic-navigation/dynamic-navigation.js
  libs/features/dynamic-navigation/status.css
  libs/features/dynamic-navigation/status.js
  libs/utils/utils.js
  test/features/dynamic-nav/dynamicNav.test.js
  test/features/dynamic-nav/mocks/status.html
  test/features/dynamic-nav/status.test.js
Labels: verified, run-nala, Ready for Stage

#3045 MWPW-159555 Add support for lana-sample query param
  libs/utils/lana.js
  libs/utils/lana.md
  test/utils/lana.test.js
Labels: Ready for Stage

#3046 MWPW-159651 && MWPW-160196 - [Hero marquee] bug fixes
  libs/blocks/hero-marquee/hero-marquee.css
  libs/blocks/hero-marquee/hero-marquee.js
  libs/styles/breakpoint-theme.css
  libs/styles/styles.css
  test/blocks/hero-marquee/mocks/body.html
Labels: needs-verification, Ready for Stage

#3050 MWPW-156242 | [Performance] Georouting modal creating cls
  libs/blocks/modal/modal.css
  libs/features/georoutingv2/georoutingv2.css
  libs/features/georoutingv2/georoutingv2.js
Labels: verified, run-nala, Ready for Stage

#3051 Graybox display specificity fix
  libs/blocks/graybox/graybox.css
Labels: trivial, Ready for Stage

#3078 MWPW-160233: Adding tabindex to social share icons
  libs/blocks/article-header/article-header.js
Labels: verified, run-nala, Ready for Stage

#3091 [MWPW-161069][NALA][A11Y] Add accessibility automation test for Milo blocks
  nala/blocks/marquee-anchors/marquee-anchors.test.js
  nala/blocks/marquee/marquee.test.js
  nala/blocks/media/media.test.js
  nala/blocks/merchcard/merchcard.test.js
  nala/blocks/modal/modal.test.js
  nala/blocks/quote/quote.test.js
  nala/blocks/review/review.test.js
  nala/blocks/table/table.test.js
  nala/blocks/tabs/tabs.test.js
  nala/blocks/text/text.test.js
  nala/blocks/video/video.test.js
  nala/blocks/zpattern/zpattern.test.js
  nala/libs/accessibility.js
Labels: zero-impact, Ready for Stage

#3025 MWPW-159791 Support Next-Gen Sidekick
  libs/blocks/bulk-publish-v2/services.js
  libs/blocks/preflight/panels/general.js
  libs/blocks/preflight/panels/seo.js
  libs/features/personalization/preview.js
  libs/utils/sidekick.js
  libs/utils/utils.js
Labels: verified, Ready for Stage

#3036 MWPW-152228: refactor georouting promises call
  libs/features/georoutingv2/georoutingv2.js
Labels: verified, Ready for Stage

#3063 CCD Merch Card Combined changes
  libs/deps/mas/mas.js
  libs/deps/mas/merch-card-collection.js
  libs/deps/mas/merch-card.js
  libs/deps/mas/merch-icon.js
  libs/deps/mas/merch-sidenav.js
  libs/deps/mas/merch-subscription-panel.js
  libs/features/mas/docs/ccd.html
  libs/features/mas/docs/merch-card.html
  libs/features/mas/docs/styles.css
  libs/features/mas/mas/dist/mas.js
  libs/features/mas/mocks/sites/cf/fragments/search/authorPayload.json
  libs/features/mas/web-components/merch-card.md
  libs/features/mas/web-components/src/global.css.js
  libs/features/mas/web-components/src/hydrate.js
  libs/features/mas/web-components/src/merch-card.js
  libs/features/mas/web-components/src/merch-icon.js
  libs/features/mas/web-components/src/variants/ccd-slice.css.js
  libs/features/mas/web-components/src/variants/ccd-slice.js
  libs/features/mas/web-components/src/variants/ccd-suggested.css.js
  libs/features/mas/web-components/src/variants/ccd-suggested.js
  libs/features/mas/web-components/src/variants/variant-layout.js
  libs/features/mas/web-components/test/aem-fragment.test.html
  libs/features/mas/web-components/test/aem-fragment.test.html.js
  libs/features/mas/web-components/test/merch-card.ccd-slice.test.html
  libs/features/mas/web-components/test/merch-card.ccd-slice.test.html.js
  libs/features/mas/web-components/test/merch-card.ccd-suggested.test.html
  libs/features/mas/web-components/test/merch-card.ccd-suggested.test.html.js
  libs/features/spectrum-web-components/.npmrc
  libs/features/spectrum-web-components/build.mjs
  libs/features/spectrum-web-components/src/themes/dark.js
  libs/features/spectrum-web-components/src/themes/light.js
Labels: verified, run-nala, commerce, merch card, Ready for Stage

#3074 MWPW-160834: Clickable App and Playstore links
  libs/blocks/media/media.css
  libs/blocks/media/media.js
Labels: Ready for Stage

#3037 MWPW-159605 Allow consumer apps set IMS timeout value
  libs/utils/utils.js
Labels: run-nala, Ready for Stage

#3076 Upgrade to RUM V2.7.0
  libs/blocks/article-feed/article-feed.js
  libs/blocks/library-config/library-config.js
  libs/blocks/library-config/lists/blocks.js
  libs/blocks/library-config/lists/icons.js
  libs/blocks/library-config/lists/personalization.js
  libs/blocks/library-config/lists/placeholders.js
  libs/scripts/delayed.js
  libs/templates/404/404.js
  libs/utils/samplerum.js
  libs/utils/utils.js
  test/utils/samplerum.test.js
Labels: Ready for Stage

#3056 Added performance tab to the Preflight tool (#2773)
  libs/blocks/preflight/panels/performance.js
  libs/blocks/preflight/panels/seo.js
  libs/blocks/preflight/preflight.css
  libs/blocks/preflight/preflight.js
  libs/utils/utils.js
  test/blocks/preflight/panels/performance/mocks/marquee.html
  test/blocks/preflight/panels/performance/performance.test.js
  test/helpers/generalHelpers.js
  web-test-runner.config.mjs
Labels: Ready for Stage

#3067 [MWPW-159595] - support same domain consumers in the links conversion feature
  libs/scripts/scripts.js
  libs/utils/utils.js
  test/utils/utils.test.js
Labels: Ready for Stage

#3099 MWPW-161235 [MEP] add nala test for timeline block
  nala/blocks/timeline/timeline.page.js
  nala/blocks/timeline/timeline.spec.js
  nala/blocks/timeline/timeline.test.js
Labels: verified, zero-impact, Ready for Stage

#3109 [MWPW-161236][NALA] Nala Accessibility Test Bot (A11y Bot)
  .gitignore
  nala/utils/a11y-bot.js
  nala/utils/a11y-report.js
  nala/utils/nala.cli.js
  package-lock.json
  package.json
Labels: zero-impact, Ready for Stage

#3082 [MWPW-156187][Milo Catalog Accessibility] "more actions" on catalog cards not accessible
  libs/blocks/merch-card/merch-card.js
  libs/deps/mas/merch-card.js
  libs/features/mas/web-components/src/merch-card.css.js
  libs/features/mas/web-components/src/variants/catalog.js
  libs/features/mas/web-components/test/merch-card.catalog.test.html.js
Labels: verified, run-nala, high priority, Ready for Stage

#3108 MWPW-161191: Checkout cli parameter does not get rendered correctly
  libs/blocks/merch/merch.js
  libs/features/mas/commerce/test/settings.test.js
  test/blocks/merch/merch.test.js
Labels: verified, run-nala, commerce, high priority, Ready for Stage

#3039 MWPW-153998, 148129, 149504 [MILO][MEP] Change Target gnav setting to be useable for any post LCP updates
  libs/blocks/library-config/library-config.js
  libs/blocks/library-config/lists/personalization.js
  libs/features/personalization/entitlements.js
  libs/features/personalization/personalization.js
  libs/features/personalization/preview.js
  libs/martech/martech.js
  libs/utils/utils.js
  test/features/personalization/actions.test.js
  test/features/personalization/entitlements.test.js
  test/features/personalization/mocks/actions/manifestCustomAction.json
  test/features/personalization/mocks/targetIntegration.html
  test/features/personalization/mocks/targetResponse.json
  test/features/personalization/pageFilter.test.js
  test/features/personalization/replacePage.test.js
  test/features/personalization/targetIntegration.test.js
  test/utils/mocks/mep/head-target-postlcp.html
  test/utils/utils-mep-gnav.test.js
  test/utils/utils-mep-with-params.test.js
  test/utils/utils-mep.test.js
Labels: verified, Ready for Stage

#3071 MWPW-157460 Allow Ungated Marketo One Page Experience
  libs/blocks/marketo/marketo.js
  test/blocks/marketo/marketo.test.js
  test/blocks/marketo/mocks/one-page-experience.html
Labels: verified, run-nala, @marketo, Ready for Stage

#3075 MWPW-160015: M@S: support for mnemonic multifield
  libs/deps/mas/mas.js
  libs/features/mas/mas/dist/mas.js
  libs/features/mas/web-components/src/aem-fragment.js
  libs/features/mas/web-components/test/aem-fragment.test.html.js
Labels: verified, commerce, Ready for Stage

#3044 MWPW-159561 Add lcpSectionOne metric to web vitals
  libs/utils/logWebVitals.js
  test/utils/logWebVitalsUtils.test.js
Labels: Ready for Stage

#3119 MWPW-158127 MEP Add support for identifying iPad on Safari as a mobile device and as iOS
  libs/features/personalization/personalization.js
Labels: verified, Ready for Stage

#3077 MWPW-161293 [MEP] add some selectors for the text blocks
  nala/blocks/text/text.page.js
Labels: verified, zero-impact, Ready for Stage
