Repository adobecom/milo, pull requests merged in 2025-01, with the labels that each got.

#3400 MWPW-163901: Fixed check when setting htmlFlow in UI
  libs/blocks/locui-create/input-urls/view.js
Labels: trivial, zero-impact

#3401 [LOC] MWPW-164482 - close view modal on button click
  libs/blocks/locui-create/input-actions/modal.js
Labels: trivial, zero-impact

#3292 MWPW-163490[MEP][NALA] add basic mep-actions test
  nala/features/personalization/mep-actions.spec.js
  nala/features/personalization/mep-actions.test.js
Labels: verified, zero-impact, Ready for Stage

#3147 [MWPW-158015] [Mini Compare Merch Card] Redesign mini compare card for testing
  libs/blocks/merch-card/img/chevron.js
  libs/blocks/merch-card/merch-card.js
  libs/deps/mas/commerce.js
  libs/deps/mas/mas.js
  libs/deps/mas/merch-card-collection.js
  libs/deps/mas/merch-card.js
  libs/deps/mas/merch-icon.js
  libs/deps/mas/merch-mnemonic-list.js
  libs/deps/mas/merch-offer-select.js
  libs/deps/mas/merch-secure-transaction.js
  libs/deps/mas/merch-sidenav.js
  libs/deps/mas/merch-stock.js
  libs/deps/mas/merch-subscription-panel.js
  libs/deps/mas/merch-twp-d2p.js
  libs/deps/mas/merch-whats-included.js
  libs/features/mas/dist/mas.js
  libs/features/mas/src/global.css.js
  libs/features/mas/src/variants/mini-compare-chart.css.js
  libs/features/mas/src/variants/mini-compare-chart.js
  libs/features/mas/test/merch-card.mini-compare.test.html
  test/blocks/merch-card/merch-card.test.js
  test/blocks/merch-card/mocks/mini-compare-chart-featured-list.html
Labels: verified, run-nala, commerce, merch card, Ready for Stage

#3295 [LOC]MWPW-163380 - Missing project details locui create
  libs/blocks/locui-create/locui-create.css
  libs/blocks/locui-create/locui-create.js
  libs/utils/utils.js
  test/blocks/locui-create/locui-create.test.js
  test/blocks/locui-create/mocks/body.html
Labels: trivial, Ready for Stage, Stale

#3314 MWPW-163379: Fix edit url from Helix admin API for DA
  libs/blocks/preflight/img/document-authoring.svg
  libs/blocks/preflight/panels/general.js
  libs/blocks/preflight/preflight.css
Labels: Ready for Stage

#3363 MWPW-163892 Fix Chat Icon Cut Off
  libs/img/icons/icons.svg
Labels: verified, Ready for Stage

#3364 MWPW-159180 & 164118 [MMM] MEP Manifest Manager Fast Follow
  libs/features/personalization/personalization.js
  libs/features/personalization/preview.js
  libs/features/personalization/promo-utils.js
  test/features/personalization/preview.test.js
  test/features/personalization/promo-utils.test.js
Labels: verified, Ready for Stage

#3398 [MWPW-160864] Adapt action item focus state
  libs/blocks/action-item/action-item.css
  libs/blocks/action-scroller/action-scroller.css
Labels: Ready for Stage

#3380 MWPW-163515: add daa-ll attributes for new mobile gnav elements
  libs/blocks/global-navigation/global-navigation.js
  libs/blocks/global-navigation/utilities/utilities.js
  libs/utils/federated.js
Labels: Stale

#3341 MWPW-162839: Move title-append to loadArea
  libs/features/title-append/README.md
  libs/features/title-append/title-append.js
  libs/utils/utils.js
  test/features/title-append/mocks/head-social.html
  test/features/title-append/mocks/head.html
  test/features/title-append/title-append.test.js
  test/utils/mocks/head-title-append.html
  test/utils/utils.test.js
Labels: Ready for Stage

#3362 [MWPW-164097] Allow special chars in aria-label definition
  libs/utils/utils.js
  test/utils/mocks/body.html
  test/utils/utils.test.js
Labels: Ready for Stage

#3409 [LOC] MWPW-164481 - For English language only "Rollout" action option should be available when author creates translation project.
  libs/blocks/locui-create/input-locale/index.js
  libs/blocks/locui-create/input-locale/view.js
  libs/blocks/locui-create/store.js
  libs/blocks/locui-create/utils/constant.js
Labels: trivial, zero-impact

#3392 ServiceNow CMR integration
  .github/workflows/servicenow.py
  .github/workflows/servicenow.yaml
  .github/workflows/skms.yaml
Labels: zero-impact, Ready for Stage

#3414 [LOC] MWPW-164574 - For English altlang in Translation flow should allow either "Translate" or "Rollout"
  libs/blocks/locui-create/input-actions/view.js
  libs/blocks/locui-create/utils/constant.js
Labels: trivial, zero-impact

#3386 Add unc activity feed support for standalone gnav
  libs/blocks/global-navigation/global-navigation.js
Labels: verified, high priority, Ready for Stage

#3351 MWPW-162046 Tabs - Stacked Mobile
  libs/blocks/tabs/tabs.css
  libs/blocks/tabs/tabs.js
  test/blocks/tabs/mocks/body.html
  test/blocks/tabs/tabs.test.js
Labels: verified, Ready for Stage

#3375 MWPW-164084 [Catalog] Page position not preserved after closing the modal
  libs/blocks/merch/merch.js
  test/blocks/merch/merch.test.js
Labels: verified, Ready for Stage

#3402 [MWPW-161858] Remove sticky section when footer is visible
  libs/blocks/section-metadata/sticky-section.js
Labels: Ready for Stage

#3404 MWPW-159299 Add chart role and dynamic aria labels
  libs/blocks/chart/chart.js
  libs/deps/echarts.common.min.js
  package-lock.json
  package.json
  test/blocks/chart/chart.test.js
Labels: verified, @chart, Ready for Stage

#3413 MWPW-156410: add daa-lh/ll values for gnav promo
  libs/blocks/global-navigation/utilities/menu/menu.js
Labels: verified, Ready for Stage

#3415 MWPW-162760 [MEP] Issues with inline fragments
  libs/blocks/fragment/fragment.js
  libs/features/personalization/personalization.js
Labels: verified, Ready for Stage

#3433 Mobile gnav tests
  test/blocks/global-navigation/global-navigation.test.js
  test/blocks/global-navigation/gnav-promo.test.js
  test/blocks/global-navigation/keyboard/keyboard.test.js
  test/blocks/global-navigation/test-utilities.js
Labels: zero-impact

#3418 [LOC UI] MWPW-164043 - Changes for supporting langstore urls
  libs/blocks/locui/actions/index.js
  libs/blocks/locui/langs/modal.js
  libs/blocks/locui/loc/index.js
  libs/blocks/locui/url/view.js
  libs/blocks/locui/utils/miloc.js
Labels: trivial

#3434 Making gnav promo sticky
  libs/blocks/global-navigation/features/aside/aside.js
  libs/blocks/global-navigation/global-navigation.css
  libs/blocks/global-navigation/global-navigation.js
  libs/styles/styles.css
  libs/utils/utils.js
  test/blocks/global-navigation/gnav-promo.test.js
  test/blocks/global-navigation/test-utilities.js
Labels: verified

#3428 [LOC] MWPW-164734 - single rollout for loc
  libs/blocks/locui-create/input-locale/index.js
  libs/blocks/locui-create/input-locale/view.js
  libs/blocks/locui-create/input-urls/view.js
  libs/blocks/locui-create/locui-create.css
  libs/blocks/locui-create/locui-create.js
  libs/blocks/locui-create/store.js
  libs/blocks/locui-create/utils/constant.js
  libs/blocks/locui-create/utils/utils.js
Labels: trivial, zero-impact

#3354 MWPW-162795: Complimentary/Product Entry CTAs
  libs/blocks/fallback/fallback.js
  libs/blocks/global-navigation/global-navigation.css
  libs/blocks/global-navigation/global-navigation.js
  test/blocks/global-navigation/global-navigation.test.js
  test/blocks/global-navigation/mocks/global-navigation-product-entry-cta.plain.js
Labels: verified, high priority, Ready for Stage

#3397 MWPW-164227 add checkmark animation on successful form submit
  libs/blocks/faas/faas.css
  libs/blocks/faas/utils.js
  libs/ui/img/checkmark-green.svg
  test/blocks/faas/faas.test.js
Labels: high priority, Ready for Stage

#3263 MWPW-162722: Sticky promo banner loading issue
  libs/blocks/section-metadata/sticky-section.js
  test/blocks/section-metadata/mocks/body.html
  test/blocks/section-metadata/section-meta.test.js
Labels: verified, Ready for Stage

#3360 MWPW-161865: adds alt text attribute to background images of merch cards
  libs/features/mas/src/hydrate.js
  libs/features/mas/src/variants/ccd-suggested.js
  libs/features/mas/test/hydrate.test.js
Labels: verified, commerce, Ready for Stage

#3370 MWPW-164094 Fix algorithm for calculation of PUF optical
  libs/deps/mas/commerce.js
  libs/deps/mas/mas.js
  libs/features/mas/dist/mas.js
  libs/features/mas/src/price/utilities.js
  libs/features/mas/test/price/__snapshots__/index.test.js.snap
  libs/features/mas/test/price/utilities.test.js
Labels: verified, Ready for Stage

#3379 [MWPW-164327] BulkPublisher BETA does not detect non-US lang & locale
  tools/send-to-caas/send-utils.js
Labels: trivial, CaaS, Ready for Stage

#3381 fix(Mwpw-163747):fix for accessibility bugs.
  libs/blocks/aside/aside.css
  libs/blocks/carousel/carousel.js
  libs/blocks/video/video.css
Labels: verified, Ready for Stage

#3416 MWPW-164638 and 164805 MMM refine values for save and add manifest count
  libs/blocks/mmm/mmm.css
  libs/blocks/mmm/mmm.js
  libs/features/personalization/preview.js
  test/blocks/mmm/mmm.test.js
  test/blocks/mmm/mocks/get-pages.json
  test/features/personalization/preview.test.js
Labels: verified, Ready for Stage

#3425 language based region nav config
  libs/blocks/region-nav/region-nav.js
  test/blocks/region-nav/region-nav.test.js
Labels: high priority, Ready for Stage

#3429 Fix(MWPW-164736):Table header cell height fix.
  libs/blocks/table/table.js
Labels: verified, high priority, Ready for Stage

#3444 [LOC]MWPW-164734 - minor css changes for input urls screen
  libs/blocks/locui-create/input-urls/view.js
  libs/blocks/locui-create/locui-create.css
Labels: trivial, zero-impact

#3377 MWPW-163603 benchmark card rendering time in PR
  README.md
  libs/deps/mas/commerce.js
  libs/deps/mas/mas.js
  libs/deps/mas/merch-card-collection.js
  libs/deps/mas/merch-card.js
  libs/features/mas/README.md
  libs/features/mas/dist/mas.js
  libs/features/mas/docs/benchmarks.html
  libs/features/mas/docs/ccd.html
  libs/features/mas/docs/checkout-link.html
  libs/features/mas/docs/common.js
  libs/features/mas/docs/inline-price.html
  libs/features/mas/docs/mas.html
  libs/features/mas/docs/mas.js.html
  libs/features/mas/docs/merch-card.html
  libs/features/mas/docs/src/build-docs.mjs
  libs/features/mas/docs/styles.css
  libs/features/mas/src/aem-fragment.js
  libs/features/mas/src/hydrate.js
  libs/features/mas/src/mas-commerce-service.js
  libs/features/mas/src/merch-card.js
  nala/features/mas/benchmark/benchmark.page.js
  nala/features/mas/benchmark/benchmark.spec.js
  nala/features/mas/benchmark/benchmark.test.js
  nala/features/mas/ccd/masccd.page.js
  nala/features/mas/ccd/masccd.spec.js
  nala/features/mas/ccd/masccd.test.js
Labels: verified, commerce, Ready for Stage

#3423 Updating package version for bundled standalone gnav
  libs/navigation/package.json
Labels: trivial, Ready for Stage

#3427 MWPW-162308 Update focus to convey state
  libs/blocks/marketo/marketo.css
Labels: verified, run-nala, @marketo, Ready for Stage

#3437 MWPW-163166: Enables scroll to on ungated forms
  libs/blocks/marketo/marketo.js
Labels: verified, Ready for Stage

#3445 Notification pill variant needs 16px spacing below it
  libs/blocks/section-metadata/section-metadata.css
Labels: verified, Ready for Stage

#3458 Adding save today to ctaTextOption
  libs/blocks/ost/ctaTextOption.js
  test/blocks/ost/textOption.test.js
Labels: verified, trivial, Ready for Stage

#3467 MWPW-165391 [Mobile-GNav] when the page is opened and navigated till center and clicked on tabs the screen is taken up
  libs/blocks/tabs/tabs.js
Labels: verified, high priority

#3417 [MWPW-163381] : Removed lorem ipsum text check from preflight modal
  libs/blocks/preflight/panels/seo.js
Labels: Ready for Stage

#3389 Setting aria-live to shadowRoot element instead to the slot.
  libs/blocks/merch-card-collection/merch-card-collection.js
  libs/deps/mas/merch-card-collection.js
  libs/features/mas/src/merch-card-collection.js
  test/blocks/merch-card-collection/mocks/merch-card-collection.html
Labels: bug, verified, run-nala, Ready for Stage

#3480 fixing unit test
  test/blocks/merch-card-collection/mocks/merch-card-collection.html
Labels: zero-impact

#3372 MWPW-164107: Mnemonic list fixed
  libs/blocks/merch-card/merch-card.js
Labels: bug, verified, commerce, merch card, Ready for Stage

#3374 New Mobile gnav 1.2 redesign
  libs/blocks/fallback/fallback.js
  libs/blocks/global-navigation/base.css
  libs/blocks/global-navigation/dark-nav.css
  libs/blocks/global-navigation/features/aside/aside.js
  libs/blocks/global-navigation/global-navigation.css
  libs/blocks/global-navigation/global-navigation.js
  libs/blocks/global-navigation/utilities/keyboard/index.js
  libs/blocks/global-navigation/utilities/keyboard/localNav.js
  libs/blocks/global-navigation/utilities/keyboard/mainNav.js
  libs/blocks/global-navigation/utilities/keyboard/mobilePopup.js
  libs/blocks/global-navigation/utilities/keyboard/utils.js
  libs/blocks/global-navigation/utilities/menu/menu.css
  libs/blocks/global-navigation/utilities/menu/menu.js
  libs/blocks/global-navigation/utilities/utilities.js
  libs/blocks/section-metadata/sticky-section.js
  libs/blocks/tabs/tabs.js
  libs/mep/ace0861/section-metadata/sticky-section.js
  libs/navigation/bootstrapper.js
  libs/navigation/navigation.css
  libs/navigation/navigation.js
  libs/styles/styles.css
  libs/utils/federated.js
  libs/utils/utils.js
  test/blocks/global-navigation/global-navigation.test.js
  test/blocks/global-navigation/gnav-cross-cloud.test.js
  test/blocks/global-navigation/gnav-main-nav-popup.test.js
  test/blocks/global-navigation/gnav-main-nav.test.js
  test/blocks/global-navigation/gnav-promo.test.js
  test/blocks/global-navigation/keyboard/keyboard.test.js
  test/blocks/global-navigation/keyboard/mocks/global-new-nav-mobile-localnav.html
  test/blocks/global-navigation/keyboard/mocks/global-new-nav-mobile.html
  test/blocks/global-navigation/keyboard/mocks/localnav-mock.html
  test/blocks/global-navigation/mocks/gnav-with-localnav.plain.js
  test/blocks/global-navigation/mocks/mock-cc-column-1.plain.js
  test/blocks/global-navigation/mocks/mock-cc-column-2.plain.js
  test/blocks/global-navigation/mocks/mock-megamenu.plain.js
  test/blocks/global-navigation/test-utilities.js
  test/blocks/global-navigation/utilities/utilities.test.js
  test/navigation/bootstrapper.test.js
Labels: high-impact, verified, Ready for Stage

#3490 mas: update failing Nala test on stage
  nala/features/mas/ccd/masccd.spec.js
Labels: zero-impact, Ready for Stage

#3489 [ENB-7645] Add page-view send event, fix window.satellite empty issue
  libs/features/personalization/personalization.js
Labels: verified, high priority, Ready for Stage

#3469 fixed the flaky test for logWebVitals.test.js & logWebVitalsUtils.test.js
  README.md
  test/utils/logWebVitals.test.js
  test/utils/logWebVitalsUtils.test.js
Labels: Ready for Stage

#3495 MWPW-165774 [Mobile-GNAV] page is not scrollable in live page
  libs/blocks/global-navigation/utilities/utilities.js
Labels: verified, high priority, Ready for Stage

#3476 MWPW-165523: Fixes BETA Caas bulkpublisher auto-detect
  tools/send-to-caas/bulk-publish-to-caas.beta.js
  tools/send-to-caas/bulkpublish.beta.css
  tools/send-to-caas/bulkpublisher.beta.html
Labels: CaaS, Ready for Stage

#3491 [LOC]MWPW-164699 - Changed css of select all and reset all
  libs/blocks/locui-create/input-actions/modal.js
  libs/blocks/locui-create/input-locale/view.js
  libs/blocks/locui-create/locui-create.css
  libs/blocks/locui-create/store.js
Labels: trivial, zero-impact

#3424 [MWPW-164132] Implementing Branch Quick Links with ECID Integration
  libs/features/branch-quick-links/branch-quick-links.css
  libs/features/branch-quick-links/branch-quick-links.js
  libs/utils/utils.js
  test/features/branch-quick-links/branch-quick-links.test.js
  test/utils/mocks/body.html
  test/utils/mocks/head.html
Labels: verified, new-feature, high priority, Ready for Stage

#3388 MWPW-161625: fix mas:pending event on requestUpdate
  libs/deps/mas/commerce.js
  libs/deps/mas/mas.js
  libs/deps/mas/merch-card-collection.js
  libs/deps/mas/merch-card.js
  libs/deps/mas/merch-sidenav.js
  libs/deps/mas/merch-subscription-panel.js
  libs/features/mas/dist/mas.js
  libs/features/mas/src/constants.js
  libs/features/mas/src/mas-element.js
  nala/features/mas/docs/masdocs.spec.js
  nala/features/mas/docs/masdocs.test.js
Labels: verified, commerce, Ready for Stage

#3477 [ENB-7642] Remove Console logs
  libs/features/personalization/personalization.js
  libs/martech/helpers.js
  test/martech/helpers.test.js
Labels: verified, Ready for Stage

#3501 [MWPW-165782] - Hamburger icon issue fix
  libs/blocks/global-navigation/base.css
  libs/blocks/global-navigation/global-navigation.css
  libs/blocks/global-navigation/global-navigation.js
  libs/styles/styles.css
  libs/utils/utils.js
  test/utils/mocks/head-localNav.html
  test/utils/utils.test.js
Labels: verified, high priority, Ready for Stage

#3481 Don't merge PRs with running tests
  .github/workflows/merge-to-stage.js
Labels: zero-impact

#3486 MWPW-164735 - States/Properties: The element has missing or incorrect states or properties - Change Region
  libs/blocks/global-footer/global-footer.js
Labels: verified, Ready for Stage

#3463 MWPW-146930 - Rollout tool plugin
  libs/blocks/rollout/rollout.css
  libs/blocks/rollout/rollout.js
  test/blocks/rollout/mocks/body.html
  test/blocks/rollout/rollout.test.js
  tools/sidekick/config.json
Labels: verified, new-feature, Ready for Stage

#3502 [MWPW-165790] accordion aria-expanded fix
  libs/blocks/accordion/accordion.js
Labels: Ready for Stage

#3483 [LOC]MWPW-165580: locui css updates
  libs/blocks/locui/img/bg.png
  libs/blocks/locui/locui.css
Labels: trivial, zero-impact

#3522 [LOC] MWPW-166032: fix for project name on locale selection screen
  libs/blocks/locui-create/input-locale/view.js
Labels: trivial, zero-impact

#3523 [LOC] Milostudio stage to milostudio
  libs/blocks/locui-create/fragments/view.js
  libs/blocks/locui-create/input-actions/modal.js
  libs/blocks/locui-create/input-locale/view.js
  libs/blocks/locui-create/input-urls/index.js
  libs/blocks/locui-create/locui-create.css
  libs/blocks/locui-create/store.js
Labels: trivial, zero-impact

#3525 MWPW-165580 - LocUi Details Screen - Styling Updates
  libs/blocks/locui/img/bg.png
  libs/blocks/locui/locui.css
Labels: trivial, zero-impact

#3515 Fixing unit tests for branch-quick-links.js
  test/features/branch-quick-links/branch-quick-links.test.js
Labels: verified, zero-impact, Ready for Stage

#3494 MWPW-165767 Apply ContentSquare data masking attribute to BACOM Account Menu fields
  libs/blocks/global-navigation/features/profile/dropdown.js
  libs/blocks/global-navigation/global-navigation.js
Labels: verified, high priority, Ready for Stage

#3516 MWPW-146930 - Rollout Tool Plugin - environment specific miloLibs
  libs/blocks/rollout/rollout.js
  test/blocks/rollout/rollout.test.js
  tools/sidekick/config.json
Labels: verified, new-feature, high priority, Ready for Stage

#3382 MWPW-152160 and MWPW-152155 card widths and gray divider
  libs/deps/mas/mas.js
  libs/deps/mas/merch-card.js
  libs/features/mas/dist/mas.js
  libs/features/mas/src/global.css.js
  libs/features/mas/src/merch-card.css.js
  libs/features/mas/src/merch-card.js
  libs/features/mas/src/variants/image.css.js
  libs/features/mas/src/variants/product.css.js
  libs/features/mas/test/merch-card-product.test.html
Labels: verified, Ready for Stage

#3407 [MWPW-161923] tab nested focus
  libs/blocks/tabs/tabs.css
  libs/blocks/tabs/tabs.js
  libs/features/georoutingv2/georoutingv2.css
  nala/blocks/tabs/tabs.page.js
  test/blocks/tabs/tabs.test.js
Labels: Ready for Stage

#3431 Tooltip icon to be tabbed and showing the tooltip
  libs/features/icons/icons.css
  libs/features/icons/icons.js
Labels: verified, run-nala, Ready for Stage

#3459 MWPW-164871 Milo Products Catalog - A11Y - Elements must meet minimum…
  libs/deps/mas/merch-sidenav.js
  libs/features/mas/src/sidenav/merch-sidenav-heading.css.js
Labels: verified, Ready for Stage

#3493 MWPW-165303: Fixed potential repetative API calls
  libs/blocks/mmm/mmm.js
Labels: verified, Ready for Stage

#3499 MWPW-164458: Fix - Breadcrumb has capital I in iPhone
  libs/blocks/global-navigation/features/breadcrumbs/breadcrumbs.js
  libs/blocks/global-navigation/global-navigation.css
  test/blocks/global-navigation/features/breadcrumbs.test.js
Labels: verified, Ready for Stage

#3519 [Merge-to-stage worfklow] Increase Github APIs listReview per_page limit
  .github/workflows/helpers.js
Labels: zero-impact

#3507 MWPW-156181: a11y merch-card-collection fix - cards reordering
  libs/deps/mas/merch-card-collection.js
  libs/features/mas/src/merch-card-collection.js
Labels: verified, commerce, Ready for Stage

#3492 MWPW-165302: Calculate promo prices with duration
  libs/deps/mas/commerce.js
  libs/deps/mas/mas.js
  libs/deps/mas/merch-card.js
  libs/features/mas/dist/mas.js
  libs/features/mas/src/price/index.js
  libs/features/mas/src/price/template.js
  libs/features/mas/src/price/utilities.js
  libs/features/mas/test/mocks/snapshots.js
  libs/features/mas/test/price.test.js
  libs/features/mas/test/price/__snapshots__/index.snapshot.js
  libs/features/mas/test/price/__snapshots__/index.test.js.snap
  libs/features/mas/test/price/__snapshots__/template.snapshots.js
  libs/features/mas/test/price/__snapshots__/template.test.js.snap
  libs/features/mas/test/price/index.test.js
  libs/features/mas/test/price/template.test.js
  libs/features/mas/test/price/utilities.test.js
  libs/features/mas/test/utilities.js
Labels: verified, commerce, Ready for Stage

#3534 MWPW-165749 Updated label for custom merge
  libs/blocks/locui-create/input-urls/view.js
Labels: trivial, zero-impact

#3533 MWPW-165573 - limit for project name
  libs/blocks/locui-create/input-urls/view.js
  libs/blocks/locui-create/locui-create.css
Labels: trivial, zero-impact

#3535 [LOC] MWPW-165575: Url validation in url input screen
  libs/blocks/locui-create/input-urls/index.js
Labels: trivial, zero-impact

#3541 MWPW-166355 [MEP] Number and symbols are very small in MEP button on RTL pages
  libs/features/personalization/preview.css
Labels: verified, Ready for Stage

#3527 MWPW-166002 | [MEP] Use Target served version of manifest in prod when Target experience is chosen
  libs/features/personalization/personalization.js
  test/features/personalization/mocks/manifestLists/two-manifests-one-from-target.json
  test/features/personalization/personalization.test.js
Labels: verified, Ready for Stage

#3475 MWPW-159369 [cc][LANA] Error reported: target response time: 0.5
  libs/features/personalization/personalization.js
  libs/martech/martech.js
Labels: verified, Ready for Stage, Stale

#3510 MWPW-156867 [MILO][MEP][ANALYTICS] Support Column nicknames
  libs/features/personalization/personalization.js
  test/features/personalization/mocks/manifestWithAmpersand.json
  test/features/personalization/mocks/manifestWithNicknames.json
  test/features/personalization/personalization.test.js
Labels: verified, Ready for Stage

#3514 [MWPW-165793] aside temporary double background check added
  nala/blocks/aside/aside.test.js
  test/blocks/aside/aside.test.js
Labels: zero-impact, Ready for Stage

#3498 [ENB-7652] Refactor flags and methods
  libs/features/personalization/personalization.js
  libs/martech/helpers.js
  libs/utils/utils.js
  test/features/personalization/personalization.test.js
  test/martech/helpers.test.js
  test/utils/utils-enable-perf.test.js
  test/utils/utils.test.js
Labels: verified, high priority, Ready for Stage

#3408 MWPW-161354: MAS: export variant metadata
  libs/deps/mas/mas.js
  libs/deps/mas/merch-card.js
  libs/deps/mas/merch-icon.js
  libs/features/mas/dist/mas.js
  libs/features/mas/docs/benchmarks.html
  libs/features/mas/docs/ccd.html
  libs/features/mas/docs/mas.js.html
  libs/features/mas/docs/merch-card.html
  libs/features/mas/docs/src/mas.js.md
  libs/features/mas/docs/src/merch-card.md
  libs/features/mas/docs/styles.css
  libs/features/mas/src/hydrate.js
  libs/features/mas/src/merch-card.js
  libs/features/mas/src/merch-icon.js
  libs/features/mas/src/variants/catalog.js
  libs/features/mas/src/variants/ccd-slice.js
  libs/features/mas/src/variants/ccd-suggested.js
  libs/features/mas/src/variants/special-offer.js
  libs/features/mas/src/variants/variants.js
  libs/features/mas/test/hydrate.test.js
  libs/features/mas/test/merch-card-collection.test.html.js
  libs/features/mas/test/merch-card.ccd-suggested.test.html.js
Labels: verified, commerce, Ready for Stage

#3482 MWPW-162519: Nav List - Link to external page
  libs/blocks/tabs/tabs.js
  nala/blocks/tabs/tabs.spec.js
  nala/blocks/tabs/tabs.test.js
  test/blocks/tabs/tabs.test.js
Labels: verified, Ready for Stage

#3517 [MWPW-162043] Bolded last link in Media block
  libs/blocks/media/media.css
Labels: Ready for Stage

#3457 [MWPW-164529] [MWPW-164530] Sticky section a11y issues
  libs/blocks/section-metadata/section-metadata.css
  libs/blocks/section-metadata/sticky-section.js
  test/blocks/section-metadata/section-meta.test.js
Labels: Ready for Stage

#3529 [MWPW-166151] Mobile gnav links transformations
  libs/utils/utils.js
Labels: Ready for Stage

#3485 [MWPW-157116] - Add feature for pause animation on hover for PEP
  libs/features/webapp-prompt/webapp-prompt.css
  libs/features/webapp-prompt/webapp-prompt.js
  test/features/webapp-prompt/mocks/pep-prompt-content.js
  test/features/webapp-prompt/webapp-prompt.test.js
Labels: verified, Ready for Stage

#3550 MWPW-166465 Checking language details after lowercasing
  libs/blocks/locui-create/utils/utils.js
Labels: trivial

#3473 MWPW-162027 Catalog action menu A11Y collapsed expanded
  libs/deps/mas/mas.js
  libs/deps/mas/merch-card.js
  libs/features/mas/dist/mas.js
  libs/features/mas/src/variants/catalog.js
Labels: verified, commerce, Ready for Stage

#3552 [MWPW-166480] - Active Element Detection fix for the Express Milo
  libs/blocks/global-navigation/global-navigation.js
  libs/blocks/global-navigation/utilities/menu/menu.js
  libs/blocks/global-navigation/utilities/utilities.js
Labels: verified, high priority, Ready for Stage

#3565 [MWPW-166427] Increase limit for publishing configuration object
  libs/tools/utils/publish.js
  test/blocks/bulk-publish-v2/mocks/fetch.js
Labels: high priority, Ready for Stage

#3438 MWPW-161867: Add http check to preflight
  libs/blocks/preflight/panels/seo.js
  libs/utils/utils.js
  test/utils/mocks/body.html
  test/utils/utils.test.js
Labels: verified, Ready for Stage

#3455 fix(mwpw-163900):Z-index of play/pause adjusted for interactive marquee.
  libs/blocks/video/video.css
Labels: verified, Ready for Stage

#3518 MWPW-162026 [Milo][Sev2][Catalog] Group of checkboxes is missing FIELDSET …
  libs/deps/mas/mas.js
  libs/deps/mas/merch-card.js
  libs/deps/mas/merch-sidenav.js
  libs/features/mas/dist/mas.js
  libs/features/mas/src/global.css.js
  libs/features/mas/src/sidenav/merch-sidenav-checkbox-group.js
Labels: verified, commerce, Ready for Stage

#3521 MWPW-165969 : Breadcrumb region is missing appropriate roles and/or attributes - Gnav
  libs/blocks/global-navigation/features/breadcrumbs/breadcrumbs.js
  libs/blocks/global-navigation/global-navigation.css
  test/blocks/global-navigation/features/breadcrumbs.test.js
Labels: verified, Ready for Stage

#3539 MWPW-161948: Added .heading-xxs selector
  libs/styles/styles.css
Labels: Ready for Stage

#3542 MWPW-166355, 166002, 159369, 156867 [MEP] Batch PR
  libs/features/personalization/personalization.js
  libs/features/personalization/preview.css
  libs/martech/martech.js
  test/features/personalization/mocks/manifestLists/two-manifests-one-from-target.json
  test/features/personalization/mocks/manifestWithAmpersand.json
  test/features/personalization/mocks/manifestWithNicknames.json
  test/features/personalization/personalization.test.js
Labels: verified, Ready for Stage

#3554 [Milo] BulkPublisher BETA Preview content should point to stage
  tools/send-to-caas/bulk-publish-to-caas.beta.js
  tools/send-to-caas/bulkpublisher.beta.html
Labels: caas-configurator, Ready for Stage

#3573 [LOC] Milostudio stage to milostudio
  libs/blocks/locui-create/input-urls/index.js
  libs/blocks/locui-create/input-urls/view.js
  libs/blocks/locui-create/locui-create.css
  libs/blocks/locui-create/utils/utils.js
Labels: trivial

#3575 MWPW-166662 LocUI hlx5 changes to MS branch
  libs/blocks/locui/actions/index.js
  libs/blocks/locui/loc/index.js
  libs/blocks/locui/utils/franklin.js
  libs/tools/sharepoint/shared.js
  libs/utils/sidekick.js
Labels: trivial

#3576 [LOC] Milostudio stage to milostudio
  libs/blocks/locui/actions/index.js
  libs/blocks/locui/loc/index.js
  libs/blocks/locui/utils/franklin.js
  libs/tools/sharepoint/shared.js
  libs/utils/sidekick.js
Labels: trivial

#3578 [LOC] MWPW-166758: Support for hlx and aem urls for fragments and url validations
  libs/blocks/locui-create/input-urls/index.js
  libs/blocks/locui-create/utils/utils.js
  libs/blocks/locui/loc/index.js
Labels: trivial, zero-impact

#3571 Add arrow icon
  libs/blocks/carousel/img/arrow.svg
Labels: verified, high priority, Ready for Stage

#3520 MWPW-166012: [CCD - Suggested Cards] Enable ABM text under price
  libs/deps/mas/mas.js
  libs/deps/mas/merch-card.js
  libs/features/mas/dist/mas.js
  libs/features/mas/src/variants/ccd-suggested.css.js
  libs/features/mas/src/variants/ccd-suggested.js
Labels: verified, commerce, high priority, Ready for Stage

#3471 MWPW-160808: fassform is seen displayed without the #id and not able to close
  libs/blocks/modal/modal.js
Labels: verified, Ready for Stage

#3505 MWPW-164131: Adding aria label for CTA using placeholder on name attributes of merch card
  libs/blocks/merch/merch.js
Labels: verified, commerce, Ready for Stage

#3528 [MWPW-166027] - Add empty space if the logo is undefined
  libs/blocks/global-navigation/utilities/utilities.js
Labels: verified, Ready for Stage

#3537 MWPW-162061 Fix Lock Icon Cut Off
  libs/img/icons/icons.svg
Labels: Ready for Stage

#3569 Locui hlx5 upgrade
  libs/blocks/locui/actions/index.js
  libs/blocks/locui/loc/index.js
  libs/blocks/locui/utils/franklin.js
  libs/tools/sharepoint/shared.js
  libs/utils/sidekick.js
Labels: trivial

#3563 [LOC]MWPW-165589 - Deselect languages when there are no respective locales selected
  libs/blocks/locui-create/input-locale/index.js
  libs/blocks/locui-create/utils/utils.js
Labels: trivial, zero-impact

#3585 [LOC]MWPW-166822 - Disabled next button on validation error
  libs/blocks/locui-create/components/stepControls.js
Labels: trivial, zero-impact

#3586 [LOC]MWPW-166758 - fragment validations
  libs/blocks/locui/actions/index.js
  libs/blocks/locui/loc/index.js
Labels: trivial, zero-impact

#3367 MWPW-158537 : Upgrade Universal Nav to version 1.4
  libs/blocks/global-navigation/global-navigation.css
  libs/blocks/global-navigation/global-navigation.js
  libs/utils/utils.js
  test/blocks/global-navigation/global-navigation.test.js
  test/blocks/global-navigation/test-utilities.js
Labels: verified, high priority, Ready for Stage

#3540 [MWPW-166134] MMM: added last seen manifest search
  libs/blocks/mmm/mmm.js
  test/blocks/mmm/mmm.test.js
Labels: verified, Ready for Stage

#3567 MWPW-163512: Fix masonry full-width for tablet
  libs/blocks/section-metadata/section-metadata.css
Labels: Ready for Stage

#3568 [MWPW-156760] Table caret position
  libs/blocks/table/table.css
  libs/blocks/table/table.js
Labels: Ready for Stage

#3574 [MWPW-166092] Fix for modal with vimeo video not showing
  libs/blocks/modal/modal.css
Labels: Ready for Stage

#3577 MWPW-166684 Rollout plugin support for hlx5
  libs/blocks/rollout/rollout.js
  test/blocks/rollout/rollout.test.js
Labels: verified, trivial, Ready for Stage

#3579 Bulk publish sidekick v7 support
  libs/blocks/bulk-publish-v2/services.js
  libs/blocks/preflight/panels/general.js
Labels: Ready for Stage

#3587 MWPW-166838 fixed referential time
  libs/features/mas/docs/benchmarks.html
Labels: verified, trivial, commerce, Ready for Stage

#3589 MWPW-166758 Cross domain fragment validation in locui
  libs/blocks/locui/actions/index.js
  libs/blocks/locui/loc/index.js
Labels: trivial

#3598 MWPW-161576: Floodbox
  test/tools/floodbox/bulk-action.test.js
  test/tools/floodbox/crawl-tree.test.js
  test/tools/floodbox/floodgate/fg-copy.test.js
  test/tools/floodbox/floodgate/floodgate-config.test.js
  test/tools/floodbox/floodgate/utils.test.js
  test/tools/floodbox/graybox/graybox-config.test.js
  test/tools/floodbox/graybox/promote-paths.test.js
  test/tools/floodbox/graybox/utils.test.js
  test/tools/floodbox/promote.test.js
  test/tools/floodbox/references.test.js
  test/tools/floodbox/request-handler.test.js
  test/tools/floodbox/search-replace.test.js
  test/tools/floodbox/utils.test.js
  tools/floodbox/bulk-action.js
  tools/floodbox/constants.js
  tools/floodbox/crawl-tree.js
  tools/floodbox/floodbox.css
  tools/floodbox/floodbox.js
  tools/floodbox/floodgate/fg-copy.js
  tools/floodbox/floodgate/floodgate-config.js
  tools/floodbox/floodgate/floodgate.css
  tools/floodbox/floodgate/floodgate.js
  tools/floodbox/floodgate/utils.js
  tools/floodbox/graybox/graybox-config.js
  tools/floodbox/graybox/graybox.css
  tools/floodbox/graybox/graybox.js
  tools/floodbox/graybox/promote-paths.js
  tools/floodbox/graybox/utils.js
  tools/floodbox/promote.js
  tools/floodbox/references.js
  tools/floodbox/request-handler.js
  tools/floodbox/search-replace.js
  tools/floodbox/utils.js
  tools/floodgate.html
  tools/graybox.html
Labels: verified, Ready for Stage

#3600 MWPW-161576: eslint fix
  tools/floodbox/floodgate/floodgate.js
  tools/floodbox/graybox/graybox.js
Labels: trivial

#3597 MWPW-166855 - Express fragment Validation
  libs/blocks/locui/actions/index.js
Labels: trivial, zero-impact

#3602 MWPW-166762 [Loc][Create Project] Updated styles for Express tenant
  libs/blocks/locui-create/locui-create.css
Labels: trivial

#3603 [LOC] MWPW-166855 - handled when fragment url comes undefined
  libs/blocks/locui/actions/index.js
Labels: trivial, zero-impact
