Repository adobecom/milo, pull requests merged in 2025-03, with the labels that each got.

#3714 [MWPW-159511] Create anchor (ID) elements
  libs/blocks/section-metadata/section-metadata.js
  libs/styles/styles.css
  test/blocks/section-metadata/mocks/body.html
  test/blocks/section-metadata/section-meta.test.js
Labels: new-feature, high priority, Ready for Stage

#3618 [MWPW-167031] top tooltip rtl fix
  libs/blocks/table/table.css
  libs/blocks/table/table.js
Labels: Ready for Stage

#3649 MWPW-164492: Plans Card via MAS
  libs/deps/mas/mas.js
  libs/deps/mas/merch-card.js
  libs/features/mas/dist/mas.js
  libs/features/mas/docs/ccd.html
  libs/features/mas/docs/checkout-button.html
  libs/features/mas/docs/checkout-link.html
  libs/features/mas/docs/inline-price.html
  libs/features/mas/docs/mas.html
  libs/features/mas/docs/mas.js.html
  libs/features/mas/docs/merch-card.html
  libs/features/mas/docs/plans.html
  libs/features/mas/docs/src/build-docs.mjs
  libs/features/mas/docs/src/build-docs.sh
  libs/features/mas/docs/src/plans.md
  libs/features/mas/docs/styles.css
  libs/features/mas/src/aem-fragment.js
  libs/features/mas/src/global.css.js
  libs/features/mas/src/hydrate.js
  libs/features/mas/src/merch-card.js
  libs/features/mas/src/variants/plans.css.js
  libs/features/mas/src/variants/plans.js
  libs/features/mas/src/variants/variants.js
  libs/features/mas/test/hydrate.test.js
  nala/features/mas/acom/masacom.page.js
  nala/features/mas/acom/masacom.spec.js
  nala/features/mas/acom/masacom.test.js
  nala/features/mas/ccd/masccd.spec.js
  nala/features/mas/ccd/masccd.test.js
Labels: verified, commerce, Ready for Stage

#3671 MWPW-160954 Marketo Multi-step
  libs/blocks/marketo/marketo-multi.js
  libs/blocks/marketo/marketo.css
  libs/blocks/marketo/marketo.js
  test/blocks/marketo/marketo-multi.test.js
  test/blocks/marketo/mocks/multi-step-2.html
Labels: verified, run-nala, @marketo, Ready for Stage

#3693 Adding support for first localnav menu being a dropdown
  libs/blocks/global-navigation/global-navigation.js
  test/navigation/bootstrapper.test.js
  test/navigation/mocks/gnav-with-localnav.plain.js
Labels: verified, Ready for Stage

#3703 [MWPW-162639] youtube block a tag fix
  libs/utils/utils.js
Labels: Ready for Stage

#3710 Fix(mwpw-163031): Typo fix long-form
  libs/blocks/adobetv/adobetv.js
Labels: verified, Ready for Stage

#3712 Upgrading standalone gnav version to 0.0.5
  libs/navigation/package.json
Labels: trivial, Ready for Stage

#3715 MWPW-167455: Remove node cloning
  libs/blocks/figure/figure.js
  test/blocks/figure/figure.test.js
  test/blocks/figure/mocks/body.html
Labels: Ready for Stage

#3728 [MWPW-167349] - Added a default logo for the 'A' icon displayed on the right side of GNAV.
  libs/blocks/global-navigation/utilities/utilities.js
Labels: verified, high priority, Ready for Stage

#3702 MWPW-167928 Override Marketo POI
  libs/blocks/marketo/marketo.js
Labels: verified, run-nala, @marketo, Ready for Stage

#3706 replace overflow x with contain layout
  libs/blocks/global-navigation/global-navigation.css
Labels: verified, Ready for Stage

#3719 [MWPW-168309] 2 small MEP button updates
  libs/features/personalization/preview.css
  libs/features/personalization/preview.js
Labels: verified, Ready for Stage

#3720 MWPW-168334 Load georoutingv2.json and georoutingv2.js in parallel
  libs/features/georoutingv2/georoutingv2.js
  libs/utils/utils.js
  test/features/georoutingv2/georoutingv2.test.js
Labels: verified, Ready for Stage

#3721 [MWPW-167309] - Table h tags replace
  libs/blocks/table/table.js
Labels: Ready for Stage

#3726 MWPW-166176 - Stop initial tabs click propagation
  libs/blocks/tabs/tabs.js
Labels: verified, Ready for Stage

#3730 Fix(mwpw-168006): Viewport bug fix.
  libs/utils/decorate.js
Labels: verified, Ready for Stage

#3768 [DA] Update build: Merge develop into da-apps
  tools/da-apps/dist/assets/index.js
  tools/da-apps/dist/assets/vendor.js
Labels: trivial

#3736 Remove file overlap condition from merge to stage workflow
  .github/workflows/merge-to-stage.js
Labels: zero-impact, Ready for Stage

#3778 [DA] Update build with session storage hook modifications
  tools/da-apps/auth.js
  tools/da-apps/dist/assets/index.js
Labels: trivial

#3761 [Loc][MWPW-168684] Single Language Rollout
  libs/blocks/locui-create/input-locale/index.js
  libs/blocks/locui-create/store.js
  libs/blocks/locui-create/utils/constant.js
  libs/blocks/locui-create/utils/utils.js
Labels: trivial

#3769 Adding a class to convert group link title to a simple header instead of a link
  libs/blocks/global-navigation/base.css
Labels: verified, high priority, Ready for Stage

#3716 [MWPW-167752] Loop focus in modals containing iframes
  libs/blocks/adobetv/adobetv.js
  libs/blocks/modal/modal.css
  libs/blocks/modal/modal.js
  test/blocks/modals/modals.test.js
Labels: Ready for Stage

#3725 MWPW-163228: Preflight svg issue
  libs/blocks/preflight/panels/general.js
Labels: verified, Ready for Stage

#3731 Updating tags and errortype for PEP lana logs
  libs/features/webapp-prompt/webapp-prompt.js
Labels: verified, Ready for Stage

#3733 MWPW-151376: Check sharepoint url
  tools/floodgate/js/config.js
  tools/loc/config.js
  tools/loc/utils.js
Labels: Ready for Stage

#3735 [MWPW-167759] Hero marquee bg-bottom-tablet fix
  libs/blocks/hero-marquee/hero-marquee.css
Labels: Ready for Stage

#3737 MWPW-166689 Add video support to Article Header
  libs/blocks/article-header/article-header.css
  libs/blocks/article-header/article-header.js
  test/blocks/article-header/article-header.test.js
  test/blocks/article-header/mocks/body-video.html
Labels: verified, Ready for Stage

#3739 MWPW-163320 Gnav Promo CTA overflowing issue - BACOM Global Nav
  libs/blocks/global-navigation/global-navigation.css
Labels: verified, Ready for Stage

#3783 [MWPW-169281] Bug fix for edit workflow
  libs/blocks/locui-create/utils/utils.js
Labels: trivial

#3760 MWPW-167217, MWPW-166638, MWPW-169117 [MEP] Batch PR
  libs/features/personalization/personalization.js
  libs/martech/martech.js
  libs/utils/utils.js
  test/features/personalization/normalizePath.test.js
  test/utils/mocks/mep/head-ajo-off.html
  test/utils/mocks/mep/head-ajo-on.html
  test/utils/mocks/mep/head-ajo-postlcp.html
  test/utils/utils-mep-with-params.test.js
  test/utils/utils-mep.test.js
Labels: verified, high priority, Ready for Stage

#3412 [MWPW-162495] : Temporary fix to handle the extra <p> generated in HTML from Helix
  libs/blocks/aside/aside.js
  libs/blocks/brick/brick.js
  libs/blocks/merch-card/merch-card.js
  libs/blocks/merch-card/merch-offer-select.js
  test/blocks/aside/mocks/standard.html
  test/blocks/brick/mocks/body.html
Labels: Ready for Stage

#3506 Including promo and localnav height to sticky blocks top when it is present
  libs/blocks/global-navigation/global-navigation.js
  libs/blocks/global-navigation/utilities/utilities.js
  libs/blocks/section-metadata/sticky-section.js
  libs/blocks/table/table.js
  libs/mep/ace0861/section-metadata/sticky-section.js
  libs/utils/utils.js
  test/blocks/global-navigation/utilities/utilities.test.js
Labels: verified, Ready for Stage

#3536 [MWPW-158773] : Aside notification CLS performance improvements
  libs/blocks/aside/aside.js
  test/blocks/aside/aside.test.js
  test/blocks/aside/mocks/body.html
Labels: Ready for Stage

#3696 MWPW-167856: Update merch sidenav component to reflect hash changes
  libs/deps/mas/merch-card-collection.js
  libs/deps/mas/merch-sidenav.js
  libs/features/mas/src/merch-card-collection.js
  libs/features/mas/src/sidenav/merch-sidenav-checkbox-group.js
  libs/features/mas/src/sidenav/merch-sidenav-list.js
  libs/features/mas/test/sidenav/catalog-sidenav.test.html.js
Labels: verified, commerce, Ready for Stage

#3742 MWPW-165992 Chart inherit font
  libs/blocks/chart/chartLightTheme.js
Labels: verified, Ready for Stage

#3743 MWPW-167326: CaaS BulkPublisher v2 release
  tools/send-to-caas/bulk-publish-to-caas.beta.js
  tools/send-to-caas/bulk-publish-to-caas.classic.js
  tools/send-to-caas/bulk-publish-to-caas.js
  tools/send-to-caas/bulkpublish.beta.css
  tools/send-to-caas/bulkpublish.classic.css
  tools/send-to-caas/bulkpublish.css
  tools/send-to-caas/bulkpublisher.beta.html
  tools/send-to-caas/bulkpublisher.classic.html
  tools/send-to-caas/bulkpublisher.html
Labels: verified, caas-configurator, CaaS, Ready for Stage

#3747 [MWPW-168637] paramaters appended to ecid value - bug fix
  libs/features/branch-quick-links/branch-quick-links.js
Labels: bug, verified, Ready for Stage

#3750 Fix(MWPW-167810): Sidekick preflight - Lorem ipsum bug.
  libs/utils/sidekick.js
Labels: verified, Ready for Stage

#3795 Moving getGnavSource back to utils
  libs/blocks/global-navigation/global-navigation.js
  libs/utils/utils.js
Labels: verified, high priority, Ready for Stage

#3244 MWPW-162914 [nala][MEP]Nested placeholder issues
  nala/features/personalization/nested-placeholders.spec.js
  nala/features/personalization/nested-placeholders.test.js
Labels: verified, zero-impact, Ready for Stage

#3544 MWPW-166356 [MEP][NALA] Fragment autoload according to Geo
  nala/features/personalization/fragment-autoload.spec.js
  nala/features/personalization/fragment-autoload.test.js
Labels: verified, zero-impact, Ready for Stage

#3767 Profile menu complex config for standalone Gnav
  libs/blocks/global-navigation/global-navigation.js
Labels: verified, high priority, Ready for Stage

#3752 [MWPW-166184] - Pill tab color change
  libs/blocks/tabs/tabs.css
Labels: Ready for Stage

#3753 feat(MWPW-168628): Add support for loading CaaS alpha releases via query parameter
  libs/blocks/caas/utils.js
Labels: verified, Ready for Stage

#3754 MWPW-166497 [Accordion] Improve Expand All Button Accessibility
  libs/blocks/accordion/accordion.css
  libs/blocks/accordion/accordion.js
Labels: verified, Ready for Stage

#3757 [MWPW-167137] LI alignment in Media block
  libs/blocks/media/media.css
Labels: Ready for Stage

#3773 Fix(MWPW-169096): Aside split no longer has 1/3 as default with images.
  libs/blocks/aside/aside.css
Labels: verified, Ready for Stage

#3779 MWPW-164462 [MEP] Add ability for MEP to select sections by section-metadata anchor value
  libs/blocks/section-metadata/section-metadata.js
  libs/features/personalization/personalization.js
  test/features/personalization/mocks/personalization.html
  test/features/personalization/personalization.test.js
Labels: verified, Ready for Stage

#3771 [LOC UI] MWPW-166940 - Sync to LocUI Stage
  libs/blocks/locui/loc/index.js
  libs/blocks/locui/utils/franklin.js
Labels: trivial, Stale

#3792 [Release] [Loc UI] Stage to Main
  libs/blocks/locui/actions/index.js
  libs/blocks/locui/actions/view.js
  libs/blocks/locui/langs/index.js
  libs/blocks/locui/langs/view.js
  libs/blocks/locui/loc/index.js
  libs/blocks/locui/utils/franklin.js
  libs/blocks/locui/utils/miloc.js
  libs/blocks/locui/utils/state.js
Labels: verified

#3802 MWPW-169629 [MEP] DNT hash should not be preserved like other hashes
  libs/features/personalization/personalization.js
  test/features/personalization/normalizePath.test.js
Labels: verified, high priority, Ready for Stage

#3732 Adding onReady and onError callback for standalone footer
  libs/blocks/global-footer/global-footer.js
  libs/navigation/bootstrapper.js
  libs/navigation/navigation.js
Labels: verified, Ready for Stage

#3759 MWPW-167748 Fix focus in georouting modal with tabs
  libs/blocks/modal/modal.js
Labels: verified, Ready for Stage

#3774 MWPW-167306 [Plans] Quantity Selector & Badge
  libs/blocks/mas-autoblock/mas-autoblock.js
  libs/deps/mas/mas.js
  libs/deps/mas/merch-card.js
  libs/deps/mas/merch-quantity-select.js
  libs/features/mas/dist/mas.js
  libs/features/mas/docs/plans.html
  libs/features/mas/docs/src/plans.md
  libs/features/mas/src/global.css.js
  libs/features/mas/src/hydrate.js
  libs/features/mas/src/mas.js
  libs/features/mas/src/merch-quantity-select.js
  libs/features/mas/src/variants/plans.js
  libs/features/mas/test/merch-card.test.html.js
  libs/features/mas/test/merch-quantity-select.test.html.js
Labels: verified, commerce, Ready for Stage

#3800 MWPW-169163 Re-enable broken psnlz tab preselecting function on US …
  libs/blocks/merch/merch.js
  test/blocks/merch/merch.test.js
Labels: verified, Ready for Stage

#3801 MWPW-169452 [DA] Add support for da-bacom-blog tenant to access MS DA Apps
  tools/da-apps/auth.js
Labels: trivial

#3812 [LOC][DA] Milostudio stage to milostudio
  libs/blocks/locui-create/input-locale/index.js
  libs/blocks/locui-create/input-locale/view.js
  libs/blocks/locui-create/input-urls/index.js
  libs/blocks/locui-create/input-urls/view.js
  libs/blocks/locui-create/locui-create.js
  libs/blocks/locui-create/store.js
  libs/blocks/locui-create/utils/constant.js
  libs/blocks/locui-create/utils/utils.js
  tools/da-apps/auth.js
  tools/da-apps/dist/assets/index.js
  tools/da-apps/dist/assets/vendor.js
Labels: trivial

#3793 MWPW-169371 : Adding countryCode config to UNav
  libs/blocks/global-navigation/global-navigation.js
Labels: verified, high priority, Ready for Stage

#3680 MWPW-167716 Remove await from both gnav and georouting
  libs/utils/utils.js
Labels: high-impact, verified, Ready for Stage

#3781 Lnav title and headline text overflow support
  libs/blocks/global-navigation/global-navigation.css
  libs/blocks/global-navigation/global-navigation.js
  libs/blocks/global-navigation/utilities/menu/menu.css
Labels: verified, Ready for Stage

#3803 [MWPW-169500] SEO- Links check failing breaks Preflight
  libs/blocks/preflight/panels/seo.js
Labels: Ready for Stage

#3813 MWPW-169732 Fetch resources from adobe.com/federal instead of https://main--federal--adobecom.aem.live/federal
  libs/navigation/navigation.js
Labels: needs-verification, high priority

#3789 MWPW-169416 [MEP] stop treating remove action differently in preview
  libs/features/personalization/personalization.js
  nala/features/personalization/mep-actions.test.js
  test/blocks/merch-card-collection/merch-card-collection.test.js
  test/features/personalization/actions.test.js
Labels: verified, high priority, Ready for Stage

#3811 MWPW-169194: adds new detailText option for staticDate
  libs/blocks/caas-config/caas-config.js
Labels: caas-configurator, CaaS, Ready for Stage

#3630 MWPW-167191 Removed an unnecessary css url() that was causing a console error
  libs/blocks/global-navigation/global-navigation.css
Labels: high priority

#3825 [DA][MWPW-169445][MWPW-169448] Update build with Bulk Ops bug fixes & Bulk Content Update API integration
  tools/da-apps/dist/assets/index.css
  tools/da-apps/dist/assets/index.js
  tools/da-apps/dist/assets/vendor.js
  tools/da-apps/dist/static/json/bcu.json
Labels: trivial

#3426 MWPW-164732 [MEP][NALA] create a nala test for PR 2976, ability to select all elements
  nala/features/personalization/all-elements.spec.js
  nala/features/personalization/all-elements.test.js
Labels: verified, zero-impact, Ready for Stage

#3723 MWPW-166076 and MWPW-168450 business/education plans page URLs to point to CME-1 M7
  libs/blocks/m7/m7.js
  libs/blocks/mas-autoblock/mas-autoblock.css
  libs/utils/utils.js
  test/blocks/m7/m7.test.js
Labels: verified, commerce, high priority, Ready for Stage

#3816 MWPW-169072: Handle messages from iframe
  libs/blocks/iframe/iframe.js
  libs/blocks/modal/modal.css
  libs/blocks/modal/modal.js
  test/blocks/iframe/iframe.test.js
Labels: high priority, Ready for Stage

#3810 MWPW-165253 Update invalid lana tag
  libs/blocks/article-header/article-header.js
Labels: verified, Ready for Stage

#3818 Adding support to allow standalone Gnav client to Integrate their own Unav
  libs/blocks/global-navigation/global-navigation.js
  libs/navigation/navigation.js
Labels: verified, Ready for Stage

#3820 [MWPW-169501] SEO- Fixed Lorem ipsum check on Preflight
  libs/blocks/preflight/panels/seo.js
Labels: Ready for Stage

#3830 Harden Github Action security by pinning to commit SHAs (versions)
  .github/workflows/README.md
  .github/workflows/code-compatibility.yaml
  .github/workflows/codeql.yml
  .github/workflows/dispatch.yml
  .github/workflows/fg-sync-repos.yml
  .github/workflows/high-impact-alert.yml
  .github/workflows/label-zero-impact.yaml
  .github/workflows/mark-stale-prs.yaml
  .github/workflows/merge-to-main.yaml
  .github/workflows/merge-to-stage.yaml
  .github/workflows/pr-reminders.yaml
  .github/workflows/rcp-notifier.yml
  .github/workflows/release-standalone-feds.yml
  .github/workflows/run-lint.yaml
  .github/workflows/run-mas-tests.yaml
  .github/workflows/run-nala-default.yml
  .github/workflows/run-nala-milolibs.yaml
  .github/workflows/run-nala.yml
  .github/workflows/run-tests.yaml
  .github/workflows/servicenow.yaml
  .github/workflows/update-dependencies.yaml
Labels: zero-impact

#3856 Revert "Tooltips are hidden while hovering over top four icons on Safari browser."
  libs/blocks/global-navigation/global-navigation.css
Labels: verified, high priority, Ready for Stage

#3762 [MWPW-166746] Branch Links not opening in separate Tab
  libs/features/branch-quick-links/branch-quick-links.js
Labels: verified, Ready for Stage

#3822 MWPW-169786: fixes label capitalization
  libs/blocks/caas-config/caas-config.js
  libs/blocks/caas/utils.js
  test/blocks/caas-config/expectedConfigs/defaultConfig.js
  test/blocks/caas/utils.test.js
Labels: verified, trivial, caas-configurator, Ready for Stage

#3823 Nests Show Pagination Quantity inside Pagination option
  libs/blocks/caas-config/caas-config.js
Labels: verified, caas-configurator, CaaS, Ready for Stage

#3849 MWPW-170114: Fix nested radion btn text color
  libs/blocks/tabs/tabs.css
Labels: Ready for Stage

#3866 [DA] Milostudio stage to milostudio
  tools/da-apps/dist/assets/index.css
  tools/da-apps/dist/assets/index.js
  tools/da-apps/dist/assets/vendor.js
  tools/da-apps/dist/static/files/reference.xlsx
Labels: trivial

#3826 MWPW-169166: Check autoblock source
  libs/utils/utils.js
  test/utils/utils.test.js
Labels: Ready for Stage

#3871 [MEP][NALA] add mep tag to all personalization nala tests
  nala/features/personalization/all-elements.spec.js
  nala/features/personalization/allowhtml.spec.js
  nala/features/personalization/any-marquee-section.spec.js
  nala/features/personalization/fragment-autoload.spec.js
  nala/features/personalization/mep-actions.spec.js
  nala/features/personalization/nested-placeholders.spec.js
  nala/features/personalization/personalization.spec.js
  nala/features/personalization/ul-ol-li.spec.js
Labels: zero-impact, Ready for Stage

#3878 [OPT-31058] Test block support for EMEA-1435
  libs/mep/emea1435/susi-light/susi-light.css
  libs/mep/emea1435/susi-light/susi-light.js
Labels: zero-impact, high priority, Ready for Stage

#3738 MWPW-162956: Setting accessibleLabel as sr-only
  libs/blocks/merch/merch.js
  libs/deps/mas/commerce.js
  libs/deps/mas/mas.js
  libs/deps/mas/merch-card.js
  libs/features/mas/dist/mas.js
  libs/features/mas/src/defaults.js
  libs/features/mas/src/external.js
  libs/features/mas/src/global.css.js
  libs/features/mas/src/inline-price.js
  libs/features/mas/src/price.js
  libs/features/mas/src/price/index.js
  libs/features/mas/src/price/template.js
  libs/features/mas/src/settings.js
  libs/features/mas/test/mas-commerce-service.test.js
  libs/features/mas/test/price.test.js
  libs/styles/styles.css
Labels: verified, commerce, Ready for Stage

#3831 MWPW-168302: [3-in-1] Modal Error message - if commerce times out
  libs/blocks/merch/merch.css
  libs/blocks/merch/merch.js
  libs/blocks/merch/three-in-one.js
  test/blocks/merch/three-in-one.test.js
Labels: verified, Ready for Stage

#3835 [MWPW-168529] New Assets tab in Preflight
  libs/blocks/preflight/panels/accessibility.js
  libs/blocks/preflight/panels/assets.js
  libs/blocks/preflight/panels/seo.js
  libs/blocks/preflight/preflight.css
  libs/blocks/preflight/preflight.js
Labels: Ready for Stage

#3836 MWPW-168447: Enable to override aria-label on checkout link via word doc
  libs/blocks/merch/merch.js
Labels: verified, commerce, Ready for Stage

#3858 MWPW-169294: Update ar locale
  libs/utils/locales.js
Labels: Ready for Stage

#3859 MWPW-160751 - Preflight - Adjust section height limit
  libs/blocks/preflight/preflight.css
Labels: Ready for Stage

#3867 MWPW-169775: Add classes for removing borders
  libs/blocks/tabs/tabs.css
Labels: Ready for Stage
