Repository adobecom/milo, pull requests merged in 2025-09, with the labels that each got.

#4603 MWPW-174413: DC 3in1 Fallback - refactor, move to merch, cover with Nala
  libs/blocks/merch/merch.js
  libs/features/mas/src/checkout.js
  nala/blocks/merch/three-in-one.spec.js
  nala/blocks/merch/three-in-one.test.js
  test/blocks/merch/merch.test.js
Labels: verified, commerce, Ready for Stage

#4632 MWPW-177190: Hardening aem-fragment ref caching
  libs/deps/mas/merch-card.js
  libs/features/mas/dist/mas.js
  libs/features/mas/src/aem-fragment.js
  libs/features/mas/test/aem-fragment.test.html.js
Labels: verified, commerce, Ready for Stage

#4691 MWPW-177660: More lenient regex to support - and not
  libs/blocks/caas/utils.js
Labels: Ready for Stage

#4719 MWPW-178287: Fix horizontal scroll in plans collection
  libs/deps/mas/merch-card.js
  libs/features/mas/dist/mas.js
  libs/features/mas/src/variants/plans.css.js
Labels: verified, Ready for Stage, Stale

#4749 MWPW-176776: Slot adjustment fix for plans super-wide
  libs/deps/mas/merch-card.js
  libs/features/mas/dist/mas.js
  libs/features/mas/src/variants/plans.js
Labels: verified, Ready for Stage

#4641 [MWPW-177278] [Preflight] ASO Preflight conditioned by federal config
  libs/blocks/preflight/checks/asoApi.js
  libs/blocks/preflight/checks/assets.js
  libs/blocks/preflight/checks/constants.js
  libs/blocks/preflight/checks/preflightApi.js
  libs/blocks/preflight/checks/seo.js
  libs/blocks/preflight/panels/assets.js
  libs/blocks/preflight/panels/seo.js
  libs/blocks/preflight/preflight.css
  libs/utils/utils.js
Labels: Ready for Stage

#4646 MWPW-176967 pass along country to mas/io if different
  libs/deps/mas/merch-card.js
  libs/features/mas/dist/mas.js
  libs/features/mas/src/aem-fragment.js
  libs/features/mas/test/aem-fragment.test.html.js
Labels: verified, commerce, Ready for Stage

#4755 intermittently seen the issue of multiple slash (/) in gnav links in news US page
  libs/utils/utils.js
Labels: verified, Ready for Stage

#4760 MWPW-178730: add fallback for structuredClone for older safari versions
  libs/blocks/merch/merch.js
  libs/deps/mas/commerce.js
  libs/features/mas/dist/mas.js
  libs/features/mas/src/price.js
Labels: verified, Ready for Stage

#4778 MWPW-179447-179462-179464 Brand Concierge Bug Fixes
  libs/blocks/brand-concierge/brand-concierge.css
  libs/blocks/brand-concierge/brand-concierge.js
  libs/blocks/brand-concierge/chat-ui-config.js
  test/blocks/brand-concierge/brand-concierge.test.js
Labels: verified, Ready for Stage

#4791 Removing iphone landscape font increase default behavior
  libs/blocks/global-footer/global-footer.css
Labels: verified, Ready for Stage

#4795 [DA Express Migration] Exclude Complex Sheets from Sync
  .github/workflows/import/index.js
Labels: zero-impact, Ready for Stage

#4654 MWPW-177223: apply displayPerUnit = true to
  libs/blocks/merch/merch.js
  libs/deps/mas/commerce.js
  libs/features/mas/dist/mas.js
  libs/features/mas/docs/mas.js.html
  libs/features/mas/docs/src/mas.js.md
  libs/features/mas/docs/styles.css
  libs/features/mas/src/defaults.js
  libs/features/mas/src/inline-price.js
  libs/features/mas/src/settings.js
  libs/features/mas/src/utilities.js
  libs/features/mas/test/mas-commerce-service.test.js
  libs/features/mas/test/price.test.js
  libs/features/mas/test/price/__snapshots__/price.snapshots.js
  libs/features/mas/test/settings.test.js
  nala/blocks/merch/default-flags.page.js
  nala/blocks/merch/default-flags.spec.js
Labels: verified, commerce, Ready for Stage

#4716 MWPW-178057 Tab state is not retained when navigating back
  libs/blocks/tabs/tabs.js
  test/blocks/tabs/mocks/body.html
  test/blocks/tabs/tabs.test.js
Labels: verified, Ready for Stage

#4725 MWPW-174159: M@S compatibility with lang-first sites
  libs/blocks/merch/merch.js
  test/blocks/merch/merch.test.js
Labels: verified, commerce, Ready for Stage

#4790 Mwpw 178576 link farm list
  libs/blocks/text/text.js
  test/blocks/text/text.test.js
Labels: Ready for Stage

#4796 MWPW-178626 Brand Concierge - add consent check
  libs/blocks/brand-concierge/brand-concierge.js
  test/blocks/brand-concierge/brand-concierge.test.js
Labels: verified, Ready for Stage

#4702 MWPW-177471: Plans page alignment fixes
  libs/deps/mas/merch-card.js
  libs/deps/mas/merch-sidenav.js
  libs/features/mas/dist/mas.js
  libs/features/mas/src/sidenav/merch-sidenav.js
  libs/features/mas/src/variants/plans.css.js
  nala/features/mas/acom/plans/plans.page.js
Labels: verified, Ready for Stage

#4766 MWPW-178718: Fix geo and normal modal
  libs/blocks/modal/modal.js
  libs/features/georoutingv2/georoutingv2.css
Labels: Ready for Stage

#4787 [MWPW-178444] #_dnt within deeply nested inline fragments still gets localized
  libs/utils/utils.js
  test/utils/utils.test.js
Labels: verified, Ready for Stage

#4802 MWPW-179461 Brand Concierge - Fix duplicate analytics
  libs/blocks/brand-concierge/brand-concierge.js
Labels: verified, Ready for Stage

#4743 MWPW-178111 [Plans] Quantity selector - accessibility issue
  libs/deps/mas/merch-quantity-select.js
  libs/features/mas/dist/mas.js
  libs/features/mas/src/merch-quantity-select.css.js
  libs/features/mas/src/merch-quantity-select.js
Labels: verified, Ready for Stage

#4814 MWPW-180119 shielding country detection in merch.js
  libs/blocks/merch/merch.js
Labels: verified, Ready for Stage

#4800 Share a11y improvement
  libs/blocks/share/share.css
  libs/blocks/share/share.js
Labels: Ready for Stage

#4810 MWPW-179644 [3-in-1] Create fallback for new Photoshop/Firefly modal
  libs/blocks/merch/merch.js
  test/blocks/merch/merch.test.js
Labels: verified, commerce, Ready for Stage

#4815 MWPW-167998 when the different app banner height is present the primary cta will not be visible in landscape mode completely
  libs/blocks/global-navigation/global-navigation.js
Labels: verified, Ready for Stage

#4793 [MWPW-179487] mWeb Rollout Ps | Updated Typography Values
  libs/styles/styles.css
Labels: verified, Ready for Stage

#4851 Fix(mwpw-178158): Bug fix for faas tool.
  libs/blocks/faas-config/faas-config.js
Labels: verified, Ready for Stage

#4835 MWPW-179632 [NALA]: enable maslibs usage in commerce tests
  nala/blocks/merch/default-flags.test.js
  nala/blocks/merch/three-in-one.test.js
  nala/blocks/merchcard/merchcard.test.js
  nala/blocks/tabs/tabs.test.js
  nala/features/commerce/commerce.test.js
  nala/features/mas/acom/plans/plans.test.js
  nala/features/mas/acom/plans/plansdocs.test.js
  nala/features/mas/benchmark/benchmark.test.js
  nala/features/mas/ccd/masccd.test.js
  nala/features/mas/docs/masdocs.test.js
  nala/features/mas/express/express.spec.js
  nala/features/mas/express/express.test.js
  nala/features/promotions/promotions.test.js
  nala/libs/commerce.js
Labels: verified, commerce, zero-impact, Ready for Stage

#4786 [MWPW-177653] Mobile carousel desktop ups
  libs/blocks/carousel/carousel.css
  libs/blocks/carousel/carousel.js
  libs/blocks/editorial-card/editorial-card.css
  libs/blocks/editorial-card/editorial-card.js
Labels: Ready for Stage

#4845 MWPW-180646 Brand Concierge - Update prompt button hover
  libs/blocks/brand-concierge/chat-ui-config.js
Labels: verified, Ready for Stage

#4857 MWPW-180866: Excludes iOS Safari from inline preloading 3-in-1
  libs/blocks/merch/three-in-one.js
Labels: verified, Ready for Stage

#4807 Refactor icon library to adhere to the DA standard
  libs/blocks/library-config/lists/icons.js
  libs/features/icons/icons.js
Labels: Ready for Stage

#4813 [MWPW-179922] mWeb Rollout Ps Test | Responsive Lockups
  libs/blocks/hero-marquee/hero-marquee.css
  libs/blocks/icon-block/icon-block.css
  libs/blocks/text/text.css
Labels: verified, Ready for Stage

#4822 Treat aem.reviews as stage environment
  libs/utils/utils.js
Labels: Ready for Stage

#4864 MWPW-180928 Brand Concierge - Update Chat label
  libs/blocks/brand-concierge/brand-concierge.js
  libs/blocks/brand-concierge/chat-ui-config.js
Labels: verified, Ready for Stage

#4855 Mwpw 180742: Adobe Home Go-live blockers
  libs/deps/mas/merch-card.js
  libs/features/mas/dist/mas.js
  libs/features/mas/src/global.css.js
  libs/features/mas/src/variants/ah-try-buy-widget.css.js
  libs/features/mas/src/variants/ah-try-buy-widget.js
  libs/features/mas/src/variants/ccd-slice.css.js
  libs/features/mas/test/merch-card.ah-try-buy-widget.test.html
  nala/features/mas/adobehome/masadobehome.page.js
  nala/features/mas/adobehome/masadobehome.spec.js
  nala/features/mas/adobehome/masadobehome.test.js
Labels: verified, high priority, Ready for Stage

#4825 MWPW-178197: SUSI Light Layouts
  libs/blocks/susi-light-login/susi-light-login.css
  libs/blocks/susi-light-login/susi-light-login.js
Labels: verified, Ready for Stage

#4866 MWPW-180601 Brand Concierge - Fix mobile zoom
  libs/blocks/brand-concierge/brand-concierge.css
Labels: verified, Ready for Stage

#4868 MWPW-180376 Brand Concierge - Fix prompt suggestion
  libs/blocks/brand-concierge/chat-ui-config.js
Labels: verified, Ready for Stage

#4877 MWPW-181021 Brand Concierge - Disclaimer text styles
  libs/blocks/brand-concierge/brand-concierge.css
  libs/blocks/brand-concierge/chat-ui-config.js
Labels: verified

#4880 [DA Importer] Fix hlx vs aem domains
  .github/workflows/import/index.js
Labels: zero-impact, Ready for Stage

#4881 MWPW-181071 Brand Concierge - Remove image carousel
  libs/blocks/brand-concierge/chat-ui-config.js
Labels: verified, Ready for Stage

#4739 mWeb Ps Journey | Section Metdata - Expand functionality
  libs/blocks/section-metadata/section-metadata.css
  libs/blocks/section-metadata/section-metadata.js
Labels: verified, high priority, Ready for Stage

#4824 MWPW-179486 mWeb Ps Journey | Carousel block updates
  libs/blocks/carousel/carousel.css
  libs/blocks/carousel/carousel.js
  libs/blocks/editorial-card/editorial-card.css
Labels: verified, high priority, Ready for Stage

#4883 [MWPW-181107] - Remove UNAV analytics call from GNAV
  libs/blocks/global-navigation/global-navigation.js
  test/blocks/global-navigation/global-navigation.test.js
  test/blocks/global-navigation/test-utilities.js
Labels: verified, high priority, Ready for Stage

#4887 MWPW-181155 mWeb icon block fragment double margin
  libs/blocks/icon-block/icon-block.css
Labels: verified, high priority, Ready for Stage

#4886 MWPW-181095 Brand Concierge - Sources spacing
  libs/blocks/brand-concierge/brand-concierge.css
  libs/blocks/brand-concierge/chat-ui-config.js
Labels: verified, Ready for Stage

#4885 MWPW-180356 Brand Concierge - Modal Header Border
  libs/blocks/brand-concierge/brand-concierge.css
Labels: verified, Ready for Stage

#4908 [REVERT] MWPW-178681: Plans Students reflow fix & heading alignments
  libs/deps/mas/merch-card-collection.js
  libs/deps/mas/merch-card.js
  libs/features/mas/dist/mas.js
  libs/features/mas/src/variants/plans.css.js
  nala/features/mas/acom/plans/plans.page.js
Labels: verified, Ready for Stage

#4900 [NALA][MWPW-179073]Fix flaky tests
  nala/blocks/actionitem/actionitem.test.js
  nala/blocks/tabs/tabs.test.js
  nala/features/personalization/mep-actions.test.js
  nala/features/personalization/mep-button.test.js
Labels: zero-impact, Ready for Stage

#4917 MWPW-181320-181372 Brand Concierge M1 Bugs2
  libs/blocks/brand-concierge/brand-concierge.css
  libs/blocks/brand-concierge/chat-ui-config.js
Labels: verified, Ready for Stage

#4921 MWPW-172886 [MEP] Support MEP AICS pzn tags recieved from API - cookie fix
  libs/features/mep/addons/lob.js
Labels: verified, Ready for Stage

#4911 Decorating the goto product cta in imsReady to ensure correct cta is shown based on sign in status
  libs/blocks/global-navigation/global-navigation.js
Labels: verified, Ready for Stage

#4931 MWPW-179866-181463 Brand Concierge M1 Bugs3
  libs/blocks/brand-concierge/brand-concierge.css
  libs/blocks/brand-concierge/brand-concierge.js
  libs/blocks/brand-concierge/chat-ui-config.js
  test/blocks/brand-concierge/brand-concierge.test.js
Labels: verified

#4889 Enabling promo scroll if screen size is lesser than 320px for accessibility
  libs/blocks/global-navigation/global-navigation.css
  libs/blocks/global-navigation/global-navigation.js
  libs/blocks/global-navigation/utilities/utilities.js
Labels: verified, Ready for Stage

#4847 MWPW-180250 Support for checkout links/CTAs in the dropdown menu and mega menu
  libs/blocks/global-navigation/base.css
  libs/blocks/global-navigation/global-navigation.css
  libs/blocks/global-navigation/utilities/menu/menu.js
Labels: verified, Ready for Stage

#4933 Added fix to Alloy payload
  libs/martech/alloy-links.js
Labels: verified, Ready for Stage
