Repository adobecom/milo, pull requests merged in 2025-02, with the labels that each got.

#3606 [LOC]MWPW-166771 - fetch tenant specific locales
  libs/blocks/locui-create/store.js
  libs/blocks/locui-create/utils/utils.js
Labels: trivial, zero-impact

#3611 [LOC] Milostudio stage to milostudio
  libs/blocks/locui-create/components/stepControls.js
  libs/blocks/locui-create/input-locale/index.js
  libs/blocks/locui-create/input-urls/index.js
  libs/blocks/locui-create/locui-create.css
  libs/blocks/locui-create/store.js
  libs/blocks/locui-create/utils/utils.js
  libs/blocks/locui/actions/index.js
  libs/blocks/locui/loc/index.js
Labels: trivial

#3211 MWPW-161639 Removed a workflow that's no longer necessary
  .github/workflows/check-feds-files.js
  .github/workflows/check-feds-files.yaml
Labels: zero-impact, Ready for Stage

#3588 [MWPW-165978] Make codecov tests more reliable
  codecov.yaml
Labels: trivial, zero-impact, Ready for Stage

#3557 MWPW-166640: Fixing action-menu focusable in merch-card
  libs/blocks/merch-card/merch-card.js
  libs/deps/mas/mas.js
  libs/deps/mas/merch-card.js
  libs/features/mas/dist/mas.js
  libs/features/mas/src/variants/catalog.js
  libs/features/mas/test/merch-card.catalog.test.html.js
  test/blocks/merch-card/merch-card.test.js
  test/blocks/merch-card/mocks/catalog-action-menu-only.html
Labels: verified, commerce, high priority, Ready for Stage

#3601 [MWPW-166884] - PEP Bug fix
  libs/features/webapp-prompt/webapp-prompt.js
  test/features/webapp-prompt/mocks/pep-prompt-content.js
  test/features/webapp-prompt/test-utilities.js
  test/features/webapp-prompt/webapp-prompt.test.js
Labels: verified, high priority, Ready for Stage

#3604 MWPW-158537 : Upgrade Universal Nav to version 1.4
  libs/blocks/global-navigation/global-navigation.css
  libs/blocks/global-navigation/global-navigation.js
  libs/utils/utils.js
  test/blocks/global-navigation/global-navigation.test.js
  test/blocks/global-navigation/test-utilities.js
Labels: verified, high priority, Ready for Stage

#3456 [MWPW-164362] Table icon focus
  libs/blocks/table/table.css
  libs/features/icons/icons.css
  libs/styles/styles.css
Labels: Ready for Stage

#3513 [MWPW-165791] Table select aria-label and column cell role added
  libs/blocks/table/table.js
  libs/features/icons/icons.js
  nala/blocks/table/table.test.js
  test/blocks/table/mocks/placeholders.json
  test/blocks/table/table.test.js
Labels: Ready for Stage

#3572 MWPW-165428 Fix georouting tab scroll
  libs/blocks/tabs/tabs.css
  libs/blocks/tabs/tabs.js
Labels: verified, Ready for Stage

#3610 MWPW-166896 - all locales not getting selected
  libs/blocks/locui-create/input-locale/index.js
Labels: trivial

#3526 MWPW-164405 Show multiple success sections
  libs/blocks/marketo/marketo.js
  test/blocks/marketo/marketo.test.html
  test/blocks/marketo/marketo.test.js
  test/blocks/marketo/mocks/marketo-utils.js
Labels: run-nala, @marketo, Ready for Stage

#3607 MWPW-166942 Update Kodiak config.yaml
  .kodiak/config.yaml
Labels: zero-impact, Ready for Stage

#3547 [ENB-7656] Hybrid Personalization - Move Page View Call to Milo Api Approach
  libs/features/personalization/personalization.js
  libs/martech/helpers.js
  libs/martech/helpers.md
  libs/utils/utils.js
  test/martech/helpers.test.js
Labels: verified, high priority, Ready for Stage

#3420 MWPW-142145: [Milo Plans Page] Plans page Tab behavior
  libs/blocks/tabs/tabs.css
  libs/blocks/tabs/tabs.js
  libs/deps/mas/commerce.js
  libs/deps/mas/mas.js
  libs/deps/mas/merch-card-collection.js
  libs/deps/mas/merch-card.js
  libs/deps/mas/merch-icon.js
  libs/deps/mas/merch-mnemonic-list.js
  libs/deps/mas/merch-offer-select.js
  libs/deps/mas/merch-secure-transaction.js
  libs/deps/mas/merch-sidenav.js
  libs/deps/mas/merch-stock.js
  libs/deps/mas/merch-subscription-panel.js
  libs/deps/mas/merch-twp-d2p.js
  libs/deps/mas/merch-whats-included.js
  libs/features/mas/dist/mas.js
  libs/features/mas/src/variants/plans.css.js
  test/blocks/tabs/mocks/body.html
  test/blocks/tabs/tabs.test.js
Labels: verified, Ready for Stage

#3553 MWPW-164658: Fix aside icon button
  libs/blocks/aside/aside.css
Labels: Ready for Stage

#3594 [MWPW-166755] table tab navigation stuck fix
  libs/blocks/table/table.js
Labels: Ready for Stage

#3503 MWPW-155425: [CAAS Authoring] ability to add multiple event states
  libs/blocks/caas-config/caas-config.js
  libs/blocks/caas/utils.js
  test/blocks/caas-config/caas-config.test.html
  test/blocks/caas-config/expectedConfigs/defaultConfig.js
  test/blocks/caas/utils.test.js
Labels: verified, caas-configurator, Ready for Stage

#3532 Fix Flaky Keyboard Navigation Tests by Isolating Mobile and Desktop Viewport Settings
  test/blocks/global-navigation/keyboard/keyboard-mobile.test.js
  test/blocks/global-navigation/keyboard/keyboard.test.js
Labels: zero-impact, Ready for Stage

#3530 Fix(mwpw-161843): favicon is loaded fast.
  libs/utils/utils.js
Labels: verified, Ready for Stage

#3566 [MWPW-166631] Tab color contrast
  libs/blocks/tabs/tabs.css
Labels: Ready for Stage

#3605 MWPW-162345: Fix aside video on tablet
  libs/blocks/aside/aside.css
  libs/blocks/video/video.css
Labels: Ready for Stage

#3625 Prevent a console error from the global navigation main menu
  libs/blocks/global-navigation/global-navigation.css
Labels: verified, Ready for Stage

#3629 Revert "Prevent a console error from the global navigation main menu"
  libs/blocks/global-navigation/global-navigation.css
Labels: high-impact, verified, high priority, Ready for Stage

#3635 [LOC]MWPW-166672 - Providing hlx support for all tenants
  libs/blocks/locui-create/utils/utils.js
Labels: trivial

#3633 MWPW-158537 : Upgrade Universal Nav to version 1.4
  libs/blocks/global-navigation/global-navigation.css
  libs/blocks/global-navigation/global-navigation.js
  libs/utils/utils.js
  test/blocks/global-navigation/global-navigation.test.js
  test/blocks/global-navigation/test-utilities.js
Labels: verified, high priority, Ready for Stage

#3638 Datastream Bug
  libs/martech/helpers.js
Labels: verified, high priority, Ready for Stage

#3636 [MWPW-167165] Fix for vimeo video not showing in modal
  libs/blocks/modal/modal.css
Labels: Ready for Stage

#3613 [MWPW-152453] Overriding description elements for accordion
  libs/blocks/accordion/accordion.css
  libs/blocks/accordion/accordion.js
  nala/blocks/accordion/accordion.page.js
  test/blocks/accordion/accordion.test.js
  test/blocks/accordion/editorial-accordion.test.js
Labels: Ready for Stage

#3616 MWPW-165806 Visual heading text reading fix
  libs/blocks/global-footer/global-footer.js
Labels: verified, Ready for Stage

#3631 MWPW-167205: [CAAS Authoring] Config Change for new Newsroom Card Style
  libs/blocks/caas-config/caas-config.js
Labels: verified, caas-configurator, Ready for Stage

#3623 MWPW-167066 [MEP] Add capabilty for merch-card-collection block to run MEP commands
  libs/blocks/merch-card-collection/merch-card-collection.js
  test/blocks/merch-card-collection/merch-card-collection.test.js
Labels: Ready for Stage

#3562 [MWPW-163470] Migrate Search in DA
  tools/search/dist/analytics/vendor/AppMeasurement.js
  tools/search/dist/assets/AdobeCleanUXBold.otf
  tools/search/dist/assets/AdobeCleanUXRegular.otf
  tools/search/dist/assets/aem-sidekick.png
  tools/search/dist/assets/cache_purge.png
  tools/search/dist/assets/document.png
  tools/search/dist/assets/dropToUpload.svg
  tools/search/dist/assets/excel-icon.svg
  tools/search/dist/assets/folder.png
  tools/search/dist/assets/gallery.png
  tools/search/dist/assets/gpt4.png
  tools/search/dist/assets/hawkeye.png
  tools/search/dist/assets/index.css
  tools/search/dist/assets/index.js
  tools/search/dist/assets/magnify-icon.svg
  tools/search/dist/assets/milo-all-in-one.png
  tools/search/dist/assets/nav-cachepurge.svg
  tools/search/dist/assets/nav-checkinout.svg
  tools/search/dist/assets/nav-copy.svg
  tools/search/dist/assets/nav-deactivate.svg
  tools/search/dist/assets/nav-exportlist.svg
  tools/search/dist/assets/nav-fragments.svg
  tools/search/dist/assets/nav-helixlogs.svg
  tools/search/dist/assets/nav-move.svg
  tools/search/dist/assets/nav-pageindexing.svg
  tools/search/dist/assets/nav-preview.svg
  tools/search/dist/assets/nav-publish.svg
  tools/search/dist/assets/nav-status.svg
  tools/search/dist/assets/nav-versioning.svg
  tools/search/dist/assets/performance.png
  tools/search/dist/assets/picture.png
  tools/search/dist/assets/reference_copy_locales.xlsx
  tools/search/dist/assets/reference_copy_move_nolocales.xlsx
  tools/search/dist/assets/reference_move_locales.xlsx
  tools/search/dist/assets/seo.png
  tools/search/dist/assets/sort-asc.svg
  tools/search/dist/assets/sort-desc.svg
  tools/search/dist/assets/translate-doc.png
  tools/search/dist/assets/unsorted.svg
  tools/search/dist/assets/vendor.css
  tools/search/dist/assets/vendor.js
  tools/search/dist/assets/word-icon.svg
  tools/search/dist/assets/workflow.png
  tools/search/dist/icons/adobe.png
  tools/search/dist/icons/redirects.svg
  tools/search/dist/icons/unity.svg
  tools/search/dist/images/B_IlluMiloStudio_Banner_Dark.jpg
  tools/search/dist/images/B_IlluMiloStudio_Banner_Light.jpg
  tools/search/dist/images/B_Redirect.png
  tools/search/dist/images/B_Unity_White.png
  tools/search/dist/images/apple-touch-icon_48x48.png
  tools/search/dist/index.html
  tools/search/dist/static/json/editredirects.json
  tools/search/dist/static/json/redirects.json
  tools/search/dist/static/json/unity.json
  tools/search/ms-search.html
  tools/search/ms-search.js
Labels: trivial, zero-impact

#3608 quiz-entry block removal
  CODEOWNERS
  libs/blocks/quiz-entry/mlField.js
  libs/blocks/quiz-entry/quiz-entry.css
  libs/blocks/quiz-entry/quiz-entry.js
  libs/blocks/quiz-entry/quizPopover.js
  libs/blocks/quiz-entry/quizoption.js
  libs/blocks/quiz-entry/utils.js
  test/blocks/quiz-entry/mocks/index.html
  test/blocks/quiz-entry/mocks/invalid-user-selection.json
  test/blocks/quiz-entry/mocks/mock-data.js
  test/blocks/quiz-entry/mocks/mock-states.js
  test/blocks/quiz-entry/mocks/questions.json
  test/blocks/quiz-entry/mocks/quiz.html
  test/blocks/quiz-entry/mocks/result-resources.json
  test/blocks/quiz-entry/mocks/results.json
  test/blocks/quiz-entry/mocks/strings.json
  test/blocks/quiz-entry/quiz-entry.test.js
  test/blocks/quiz-entry/utils.test.js
Labels: verified, uar, Ready for Stage

#3646 [LOC] Milostudio stage to milostudio
  libs/blocks/locui-create/input-locale/index.js
  libs/blocks/locui-create/utils/utils.js
  tools/search/dist/analytics/vendor/AppMeasurement.js
  tools/search/dist/assets/AdobeCleanUXBold.otf
  tools/search/dist/assets/AdobeCleanUXRegular.otf
  tools/search/dist/assets/aem-sidekick.png
  tools/search/dist/assets/cache_purge.png
  tools/search/dist/assets/document.png
  tools/search/dist/assets/dropToUpload.svg
  tools/search/dist/assets/excel-icon.svg
  tools/search/dist/assets/folder.png
  tools/search/dist/assets/gallery.png
  tools/search/dist/assets/gpt4.png
  tools/search/dist/assets/hawkeye.png
  tools/search/dist/assets/index.css
  tools/search/dist/assets/index.js
  tools/search/dist/assets/magnify-icon.svg
  tools/search/dist/assets/milo-all-in-one.png
  tools/search/dist/assets/nav-cachepurge.svg
  tools/search/dist/assets/nav-checkinout.svg
  tools/search/dist/assets/nav-copy.svg
  tools/search/dist/assets/nav-deactivate.svg
  tools/search/dist/assets/nav-exportlist.svg
  tools/search/dist/assets/nav-fragments.svg
  tools/search/dist/assets/nav-helixlogs.svg
  tools/search/dist/assets/nav-move.svg
  tools/search/dist/assets/nav-pageindexing.svg
  tools/search/dist/assets/nav-preview.svg
  tools/search/dist/assets/nav-publish.svg
  tools/search/dist/assets/nav-status.svg
  tools/search/dist/assets/nav-versioning.svg
  tools/search/dist/assets/performance.png
  tools/search/dist/assets/picture.png
  tools/search/dist/assets/reference_copy_locales.xlsx
  tools/search/dist/assets/reference_copy_move_nolocales.xlsx
  tools/search/dist/assets/reference_move_locales.xlsx
  tools/search/dist/assets/seo.png
  tools/search/dist/assets/sort-asc.svg
  tools/search/dist/assets/sort-desc.svg
  tools/search/dist/assets/translate-doc.png
  tools/search/dist/assets/unsorted.svg
  tools/search/dist/assets/vendor.css
  tools/search/dist/assets/vendor.js
  tools/search/dist/assets/word-icon.svg
  tools/search/dist/assets/workflow.png
  tools/search/dist/icons/adobe.png
  tools/search/dist/icons/redirects.svg
  tools/search/dist/icons/unity.svg
  tools/search/dist/images/B_IlluMiloStudio_Banner_Dark.jpg
  tools/search/dist/images/B_IlluMiloStudio_Banner_Light.jpg
  tools/search/dist/images/B_Redirect.png
  tools/search/dist/images/B_Unity_White.png
  tools/search/dist/images/apple-touch-icon_48x48.png
  tools/search/dist/index.html
  tools/search/dist/static/json/editredirects.json
  tools/search/dist/static/json/redirects.json
  tools/search/dist/static/json/unity.json
  tools/search/ms-search.html
  tools/search/ms-search.js
Labels: trivial

#3593 [MWPW-160510] tooltip enabled on all icons
  libs/blocks/table/table.css
  libs/features/icons/icons.js
  test/features/icons/icons.test.js
Labels: Ready for Stage

#3609 [LOC]Mwpw 166771 - Fixed css for card and header for express
  libs/blocks/locui/locui.css
Labels: trivial

#3661 [LOC]MWPW-167503: select all during edit project
  libs/blocks/locui-create/input-locale/index.js
  libs/blocks/locui/actions/index.js
Labels: trivial, zero-impact

#3662 [MWPW-166432] Integrate Advanced Search API for DA
  .eslintrc-code-compatibility.js
  .eslintrc.js
  tools/search/dist/assets/index.js
  tools/search/ms-search.js
Labels: trivial

#3665 [DA] Milostudio stage to milostudio
  .eslintrc-code-compatibility.js
  .eslintrc.js
  libs/blocks/locui-create/input-locale/index.js
  libs/blocks/locui/actions/index.js
  tools/search/dist/assets/index.js
  tools/search/ms-search.js
Labels: trivial

#3645 Consent Bug
  libs/features/personalization/personalization.js
  libs/martech/helpers.js
Labels: verified, high priority, Ready for Stage

#3659 Upgrading standalone gnav with unav 1.4
  libs/blocks/global-navigation/global-navigation.js
  libs/navigation/build.mjs
  libs/navigation/package.json
Labels: verified, high priority, Ready for Stage

#3555 MWPW-163861 Accordion Expand All Button
  libs/blocks/accordion/accordion.css
  libs/blocks/accordion/accordion.js
  test/blocks/accordion/accordion.test.js
  test/blocks/accordion/editorial-accordion.test.js
  test/blocks/accordion/mocks/body.html
  test/blocks/accordion/mocks/editorial-body.html
Labels: verified, Ready for Stage

#3560 MWPW-165482 milo autoblock feature
  libs/blocks/mas-autoblock/mas-autoblock.css
  libs/blocks/mas-autoblock/mas-autoblock.js
  libs/deps/mas/merch-card.js
  libs/features/mas/src/merch-card.js
  libs/utils/utils.js
  test/blocks/mas-autoblock/mas-autoblock.test.js
Labels: verified, commerce, Ready for Stage

#3626 Mwpw 161700 notification ribbon
  libs/blocks/notification/notification.css
Labels: Ready for Stage

#3637 Mwpw 162888 nested radio btn
  libs/blocks/tabs/tabs.css
Labels: Ready for Stage

#3642 MWPW-166878: Remove the empty A link element left from icon
  libs/blocks/merch-card/merch-card.js
  nala/blocks/merchcard/merchcard.pages.js
Labels: verified, commerce, Ready for Stage

#3648 [MWPW-161562] Auto pause videos
  libs/blocks/adobetv/adobetv.js
  libs/blocks/figure/figure.js
  libs/utils/decorate.js
  nala/blocks/video/video.page.js
Labels: Ready for Stage

#3663 MWPW-167305 [Plans Milo] Callout grey block: authoring improvement
  libs/deps/mas/mas.js
  libs/deps/mas/merch-card.js
  libs/features/mas/dist/mas.js
  libs/features/mas/src/global.css.js
  libs/features/mas/src/hydrate.js
Labels: commerce

#3677 Update build with token expiry check removal for DA integration
  tools/search/dist/assets/index.js
Labels: trivial

#3584 Adding support for secondary CTA for new mobile gnav
  libs/blocks/global-navigation/global-navigation.css
  libs/blocks/global-navigation/utilities/utilities.js
Labels: verified, high priority, Ready for Stage

#3624 [MWPW-166793] MMM subdomain filter + local storage cacheing
  libs/blocks/mmm/mmm.css
  libs/blocks/mmm/mmm.js
  libs/features/personalization/personalization.js
  test/blocks/mmm/mmm.test.js
Labels: verified, Ready for Stage

#3639 MWPW-157733: Fix checkmark with bold text
  libs/blocks/text/text.css
Labels: Ready for Stage

#3643 MWPW-167216 Support AEM PAGE/LIVE for PDF Viewer
  libs/blocks/pdf-viewer/README.md
  libs/blocks/pdf-viewer/pdf-viewer.js
  libs/utils/utils.js
  test/blocks/pdf-viewer/pdf-viewer.test.js
Labels: Ready for Stage

#3650 MWPW-164470: Console error dynamic nav
  libs/features/dynamic-navigation/status.js
  test/features/dynamic-nav/status.test.js
Labels: verified, Ready for Stage

#3652 [MEP] Update mep target message to include postlcp
  libs/features/personalization/preview.js
Labels: verified, Ready for Stage

#3666 MWPW-167643: Corrected the number of grid columns for the plans three cards layout
  libs/deps/mas/mas.js
  libs/deps/mas/merch-card.js
  libs/features/mas/dist/mas.js
  libs/features/mas/src/variants/plans.css.js
Labels: verified, commerce, Ready for Stage

#3682 Update build for "Home" path removal from breadcrumbs for DA
  tools/search/dist/assets/index.js
Labels: trivial

#3657 [MWPW-155282] table tooltip enhancements
  libs/blocks/table/table.css
  libs/features/icons/icons.css
Labels: Ready for Stage

#3690 MWPW-167503 - Removed filter when no locales are there
  libs/blocks/locui-create/input-locale/index.js
Labels: trivial, zero-impact

#3697 [LOC] Milostudio stage to milostudio
  libs/blocks/locui-create/input-locale/index.js
Labels: trivial

#3612 Mwpw 162709 tooltip unit tests
  test/features/icons/icons.test.js
Labels: zero-impact, Ready for Stage

#3687 [MWPW-167874] ?ecid=null query param getting appended to adobesparkspost branch quick link
  libs/blocks/mobile-app-banner/mobile-app-banner.js
  libs/features/branch-quick-links/branch-quick-links.js
Labels: bug, verified, high priority, Ready for Stage

#3655 Added fix for contrast ratio for blue link on grey background
  libs/blocks/global-navigation/base.css
  libs/styles/styles.css
Labels: high-impact, verified, Ready for Stage

#3664 [MWPW-167312] tooltip dismiss escape
  libs/blocks/table/table.js
  libs/features/icons/icons.css
  test/blocks/table/mocks/body.html
  test/blocks/table/table.test.js
Labels: Ready for Stage

#3675 MWPW-167292: Fix aside promobar buttons overflow
  libs/blocks/aside/aside.css
Labels: Ready for Stage

#3684 MWPW-164755:Add <br> when copying multiple blocks
  libs/blocks/library-config/lists/blocks.js
  test/blocks/library-config/mocks/blocks/chart/docx.html
  test/blocks/library-config/mocks/blocks/container/docx-container.html
  test/blocks/library-config/mocks/blocks/container/docx-single-block.html
  test/blocks/library-config/mocks/blocks/marquee/docx.html
  test/blocks/library-config/mocks/blocks/text/docx.html
Labels: Ready for Stage

#3656 Mocked 3rd party script requests
  test/blocks/global-navigation/gnav-brand.test.js
  test/blocks/global-navigation/gnav-cross-cloud.test.js
  test/blocks/global-navigation/gnav-main-nav-popup.test.js
  test/blocks/global-navigation/gnav-main-nav.test.js
  test/blocks/global-navigation/gnav-profile.test.js
  test/blocks/global-navigation/gnav-promo.test.js
  test/blocks/global-navigation/gnav-search.test.js
Labels: zero-impact, Ready for Stage

#3668 [MWPW-165792] - Remove skip a11y flags
  nala/blocks/accordion/accordion.test.js
  nala/blocks/aside/aside.page.js
  nala/blocks/aside/aside.test.js
  nala/blocks/carousel/carousel.test.js
  nala/blocks/chart/chart.test.js
  nala/blocks/columns/columns.test.js
  nala/blocks/figure/figure.test.js
  nala/blocks/howto/howto.test.js
  nala/blocks/marquee-anchors/marquee-anchors.test.js
  nala/blocks/marquee/marquee.page.js
  nala/blocks/marquee/marquee.test.js
  nala/blocks/text/text.test.js
  nala/blocks/zpattern/zpattern.test.js
  test/blocks/aside/aside.test.js
  test/blocks/aside/mocks/standard.html
Labels: zero-impact, Ready for Stage

#3691 [MWPW-165867] - Branch banner fixes
  libs/blocks/global-navigation/global-navigation.css
  libs/blocks/global-navigation/global-navigation.js
  libs/blocks/global-navigation/utilities/utilities.js
  test/blocks/global-navigation/utilities/utilities.test.js
Labels: verified, high priority, Ready for Stage

#3619 Fix(mwpw-160681| MWPW-163031): Video accessibility for text long form.
  libs/blocks/adobetv/adobetv.js
  libs/utils/decorate.js
Labels: verified, Ready for Stage

#3678 Apply width of active gnav element after bolding of text is done
  libs/blocks/global-navigation/utilities/menu/menu.js
Labels: verified, Ready for Stage

#3692 Fix(Mwpw-166943): Hero marquee split feature.
  libs/blocks/video/video.css
Labels: verified, Ready for Stage

#3708 MWPW-168109: do not modify absolute path to a script hosted in DAM when using insertScript action
  libs/features/personalization/personalization.js
  test/features/personalization/personalization.test.js
Labels: verified, Ready for Stage

#3670 [MWPW-166126] Add new "updateAttribute" action to MEP
  libs/features/personalization/personalization.js
  test/features/personalization/actions.test.js
  test/features/personalization/mocks/actions/manifestUpdateAttribute.json
  test/features/personalization/modifyNonFragmentSelector.test.js
Labels: verified, Ready for Stage

#3653 [MWPW-166712] Redesign MEP button and MMM expanded interface
  libs/features/personalization/preview.css
  libs/features/personalization/preview.js
  nala/features/promotions/promotions.page.js
  nala/features/promotions/promotions.spec.js
  nala/features/promotions/promotions.test.js
  test/blocks/mmm/mmm.test.js
  test/features/personalization/preview.test.js
Labels: verified, Ready for Stage

#3709 MWPW-168109, 166126 MEP Stage Batch
  libs/features/personalization/personalization.js
  test/features/personalization/actions.test.js
  test/features/personalization/mocks/actions/manifestUpdateAttribute.json
  test/features/personalization/modifyNonFragmentSelector.test.js
  test/features/personalization/personalization.test.js
Labels: verified, Ready for Stage

#3711 [DA] Updated build with stage credentials
  tools/da-apps/dist/assets/index.js
Labels: trivial

#3713 DA] Milostudio stage to milostudio
  tools/da-apps/dist/assets/index.js
Labels: trivial

#3698 [NALA][MWPW-168075] Purge cache before running NALA tests on PR
  .github/workflows/run-nala-default.yml
  nala/utils/pr.run.sh
Labels: zero-impact, Ready for Stage

#3647 MWPW-158500: Universal promo terms link
  libs/deps/mas/commerce.js
  libs/deps/mas/mas.js
  libs/deps/mas/merch-card-collection.js
  libs/deps/mas/merch-card.js
  libs/deps/mas/merch-icon.js
  libs/deps/mas/merch-mnemonic-list.js
  libs/deps/mas/merch-offer-select.js
  libs/deps/mas/merch-quantity-select.js
  libs/deps/mas/merch-secure-transaction.js
  libs/deps/mas/merch-sidenav.js
  libs/deps/mas/merch-stock.js
  libs/deps/mas/merch-subscription-panel.js
  libs/deps/mas/merch-twp-d2p.js
  libs/deps/mas/merch-whats-included.js
  libs/features/mas/build.mjs
  libs/features/mas/dist/mas.js
  libs/features/mas/docs/ccd.html
  libs/features/mas/src/commerce.js
  libs/features/mas/src/hydrate.js
  libs/features/mas/src/upt-link.js
  nala/features/mas/ccd/masccd.page.js
  nala/features/mas/ccd/masccd.spec.js
  nala/features/mas/ccd/masccd.test.js
Labels: verified, Ready for Stage

#3669 MWPW-164728 [MMM] Improve design of pagination
  libs/blocks/mmm/mmm.css
  libs/blocks/mmm/mmm.js
Labels: verified, Ready for Stage

#3699 [MWPW-168041] pill tab border removal
  libs/blocks/tabs/tabs.css
Labels: Ready for Stage

#3559 DOTCOM-128841, DOTCOM-129276, Group of navigation links missing semantics
  libs/blocks/global-footer/global-footer.css
  libs/blocks/global-footer/global-footer.js
  libs/blocks/global-navigation/global-navigation.js
Labels: verified, Ready for Stage

#3685 MWPW-165992 Fix Chart Font Family
  libs/blocks/chart/chartLightTheme.js
Labels: verified, Ready for Stage

#3591 Move federal code to utils
  libs/blocks/fragment/fragment.js
  libs/blocks/global-footer/global-footer.js
  libs/blocks/global-navigation/features/breadcrumbs/breadcrumbs.js
  libs/blocks/global-navigation/features/profile/dropdown.js
  libs/blocks/global-navigation/features/search/gnav-search.js
  libs/blocks/global-navigation/global-navigation.js
  libs/blocks/global-navigation/utilities/utilities.js
  libs/blocks/modal/modal.js
  libs/features/georoutingv2/georoutingv2.js
  libs/features/personalization/personalization.js
  libs/features/webapp-prompt/webapp-prompt.js
  libs/utils/decorate.js
  libs/utils/federated.js
  libs/utils/utils.js
  test/blocks/global-navigation/utilities/utilities.test.js
  test/features/georoutingv2/georoutingv2.test.js
  test/utils/federated.test.js
Labels: Ready for Stage

#3717 [MWPW-168268] Correct RCP dates in Slack comms
  .github/workflows/rcp-notifier.js
Labels: zero-impact, Ready for Stage

#3727 [MWPW-168395] Add Promote workflow in Miloc
  libs/blocks/locui-create/input-locale/view.js
  libs/blocks/locui-create/input-urls/index.js
  libs/blocks/locui-create/input-urls/view.js
  libs/blocks/locui-create/locui-create.js
  libs/blocks/locui-create/store.js
  libs/blocks/locui-create/utils/constant.js
Labels: trivial, zero-impact

#3729 [MWPW-168422] Fix for broken single rollout functionality
  libs/blocks/locui-create/locui-create.js
Labels: trivial

#3740 [LOC]MWPW-168413 - Promote rollout for translation project
  libs/blocks/locui/actions/index.js
  libs/blocks/locui/actions/view.js
  libs/blocks/locui/loc/index.js
  libs/blocks/locui/utils/franklin.js
  libs/blocks/locui/utils/miloc.js
  libs/blocks/locui/utils/state.js
Labels: trivial, zero-impact

#3748 MWPW 168415 single language rollout v3
  libs/blocks/locui/actions/index.js
  libs/blocks/locui/langs/index.js
  libs/blocks/locui/langs/view.js
Labels: trivial

#3749 [LOC] MWPW-168413 - fixed sync issue
  libs/blocks/locui/utils/miloc.js
Labels: trivial

#3654 [MEP][AJO] POC to integrate AJO with MEP
  libs/features/personalization/personalization.js
  libs/martech/martech.js
  libs/utils/utils.js
  test/utils/mocks/mep/head-ajo-off.html
  test/utils/mocks/mep/head-ajo-on.html
  test/utils/mocks/mep/head-ajo-postlcp.html
  test/utils/utils-mep-with-params.test.js
  test/utils/utils-mep.test.js
Labels: verified, Ready for Stage

#3751 MWPW-167217 [MEP] preserve hash in normalizePath
  libs/features/personalization/personalization.js
  test/features/personalization/normalizePath.test.js
Labels: verified, Ready for Stage
