Repository adobecom/milo, pull requests merged in 2025-08, with the labels that each got.

#4618 [LOC]MWPW-177102 - Deselect region related locales
  libs/blocks/locui-create/input-locale/index.js
Labels: trivial, zero-impact

#4649 Sync geo
  nala/blocks/merch/three-in-one.test.js
  nala/features/commerce/commerce.test.js
  nala/features/mas/acom/plans/plans.spec.js
  nala/features/mas/acom/plans/plans.test.js
  nala/features/mas/acom/plans/plansdocs.spec.js
  nala/features/mas/acom/plans/plansdocs.test.js
  nala/features/mas/ccd/masccd.spec.js
  nala/features/mas/ccd/masccd.test.js
  nala/libs/commerce.js
Labels: zero-impact

#4648 [Loc] | Prod Deployment | Eliminating custom merge option from regional editing
  libs/blocks/locui-create/input-urls/view.js
Labels: trivial

#4588 [MWPW-175663][NALA] Automation test script for Language selector
  nala/blocks/language-selector/language-selector.page.js
  nala/blocks/language-selector/language-selector.spec.js
  nala/blocks/language-selector/language-selector.test.js
Labels: zero-impact, Ready for Stage

#4633 Share block a11y
  libs/blocks/share/share.css
  libs/blocks/share/share.js
  libs/blocks/share/share.svg
  test/blocks/share/mocks/body.html
  test/blocks/share/share.test.js
Labels: Ready for Stage

#4645 [MWPW-177282] Use Akamai header to return user country
  libs/utils/utils.js
Labels: high priority, Ready for Stage

#4671 MWPW-175128 - Edit locales issue on 3rd step
  libs/blocks/locui-create/utils/utils.js
Labels: trivial, zero-impact

#4598 MWPW-176411: Pixel perfect collections
  libs/blocks/merch-card-collection-autoblock/merch-card-collection-autoblock.js
  libs/deps/mas/merch-card-collection-header.js
  libs/deps/mas/merch-card-collection.js
  libs/deps/mas/merch-card.js
  libs/deps/mas/merch-sidenav.js
  libs/features/mas/build.mjs
  libs/features/mas/dist/mas.js
  libs/features/mas/src/global.css.js
  libs/features/mas/src/merch-card-collection-header.js
  libs/features/mas/src/merch-card-collection.js
  libs/features/mas/src/sidenav/merch-sidenav-checkbox-group.js
  libs/features/mas/src/sidenav/merch-sidenav-heading.css.js
  libs/features/mas/src/sidenav/merch-sidenav-list.js
  libs/features/mas/src/sidenav/merch-sidenav.js
  libs/features/mas/src/variants/catalog.css.js
  libs/features/mas/src/variants/plans.css.js
  libs/features/mas/src/variants/plans.js
  libs/features/mas/test/merch-card-collection.test.html.js
  test/blocks/merch-card-collection-autoblock/merch-card-collection-autoblock.test.js
  test/blocks/merch-card-collection/merch-card-collection.test.js
Labels: verified, commerce, Ready for Stage, plans

#4629 Mwpw 175827 accessibility scroll
  libs/deps/mas/merch-sidenav.js
  libs/features/mas/src/sidenav/merch-sidenav.js
  libs/features/spectrum-web-components/dist/action-button.js
  libs/features/spectrum-web-components/dist/action-menu.js
  libs/features/spectrum-web-components/dist/alert-dialog.js
  libs/features/spectrum-web-components/dist/base.js
  libs/features/spectrum-web-components/dist/button-group.js
  libs/features/spectrum-web-components/dist/button.js
  libs/features/spectrum-web-components/dist/checkbox.js
  libs/features/spectrum-web-components/dist/dialog.js
  libs/features/spectrum-web-components/dist/divider.js
  libs/features/spectrum-web-components/dist/field-label.js
  libs/features/spectrum-web-components/dist/help-text.js
  libs/features/spectrum-web-components/dist/icon.js
  libs/features/spectrum-web-components/dist/icons-ui.js
  libs/features/spectrum-web-components/dist/icons-workflow.js
  libs/features/spectrum-web-components/dist/icons/asterisk.js
  libs/features/spectrum-web-components/dist/icons/checkmark.js
  libs/features/spectrum-web-components/dist/icons/chevron.js
  libs/features/spectrum-web-components/dist/icons/corner-triangle.js
  libs/features/spectrum-web-components/dist/icons/cross.js
  libs/features/spectrum-web-components/dist/icons/dash.js
  libs/features/spectrum-web-components/dist/link.js
  libs/features/spectrum-web-components/dist/menu.js
  libs/features/spectrum-web-components/dist/overlay.js
  libs/features/spectrum-web-components/dist/picker.js
  libs/features/spectrum-web-components/dist/popover.js
  libs/features/spectrum-web-components/dist/progress-circle.js
  libs/features/spectrum-web-components/dist/reactive-controllers.js
  libs/features/spectrum-web-components/dist/search.js
  libs/features/spectrum-web-components/dist/shared.js
  libs/features/spectrum-web-components/dist/sidenav.js
  libs/features/spectrum-web-components/dist/switch.js
  libs/features/spectrum-web-components/dist/tabs.js
  libs/features/spectrum-web-components/dist/textfield.js
  libs/features/spectrum-web-components/dist/theme.js
  libs/features/spectrum-web-components/dist/themes/dark.js
  libs/features/spectrum-web-components/dist/themes/light.js
  libs/features/spectrum-web-components/dist/toast.js
  libs/features/spectrum-web-components/dist/tooltip.js
  libs/features/spectrum-web-components/dist/tray.js
  libs/features/spectrum-web-components/dist/underlay.js
  libs/features/spectrum-web-components/package-lock.json
  libs/features/spectrum-web-components/package.json
  libs/features/spectrum-web-components/src/icons-workflow.js
  libs/features/spectrum-web-components/src/overlay.js
  libs/features/spectrum-web-components/src/reactive-controllers.js
  libs/scripts/accessibility.js
  libs/utils/decorate.js
Labels: high-impact, Ready for Stage

#4660 Mobile global footer arrow keyboard navigation fixed
  libs/blocks/global-navigation/global-navigation.js
  libs/blocks/global-navigation/utilities/keyboard/mobilePopup.js
Labels: verified, Ready for Stage

#4678 MWPW-177334: Remove adjustPrices method from MAS Plans variant
  libs/deps/mas/merch-card-collection.js
  libs/deps/mas/merch-card.js
  libs/features/mas/dist/mas.js
  libs/features/mas/src/variants/plans.js
Labels: verified, commerce, Ready for Stage, plans

#4656 [Nala]: fix m@s nala tests flakiness
  nala/blocks/merch/default-flags.test.js
  nala/blocks/merch/three-in-one.page.js
  nala/blocks/merch/three-in-one.test.js
  nala/features/commerce/commerce.test.js
  nala/features/mas/acom/plans/plans.spec.js
  nala/features/mas/acom/plans/plans.test.js
  nala/features/mas/acom/plans/plansdocs.spec.js
  nala/features/mas/acom/plans/plansdocs.test.js
  nala/features/mas/adobehome/masadobehome.spec.js
  nala/features/mas/adobehome/masadobehome.test.js
  nala/features/mas/benchmark/benchmark.spec.js
  nala/features/mas/ccd/masccd.spec.js
  nala/features/mas/ccd/masccd.test.js
  nala/features/mas/ccd/mini/mini.spec.js
  nala/features/mas/ccd/mini/mini.test.js
  nala/features/mas/docs/masdocs.spec.js
  nala/libs/commerce.js
Labels: zero-impact, Ready for Stage

#4689 MWPW-177328 rework postProcessAutoblock
  libs/blocks/merch-card-autoblock/merch-card-autoblock.js
  libs/blocks/merch-card-collection-autoblock/merch-card-collection-autoblock.js
  libs/blocks/merch/autoblock.js
  test/blocks/merch-card-collection-autoblock/merch-card-collection-autoblock.test.js
  test/blocks/merch/autoblock.test.js
Labels: verified, commerce, high priority, Ready for Stage, plans

#4586 MWPW-176370: [Promos] Suppress promo modal on mobile + tablet devices
  libs/blocks/modal/modal.js
  test/blocks/modals/modals.test.js
Labels: verified, commerce, Ready for Stage

#4596 MWPW-175973 [Accessibility] Filter component accessibility issue on Blog page
  libs/blocks/article-feed/article-feed.css
  libs/blocks/article-feed/article-feed.js
Labels: Ready for Stage

#4688 Fix memory issues when fetching nested circular fragments
  .github/workflows/import/index.js
Labels: zero-impact

#4701 [MWPW-177991][NALA]Disable Marketo block ui tests till we fix the delay issues
  nala/blocks/actionitem/actionitem.test.js
  nala/blocks/marketo/marketo.test.js
Labels: zero-impact, Ready for Stage

#4692 MWPW-177302[Milo] Add support for Frictionless Sticky CTA
  libs/mep/dc1059/notification/notification.css
  libs/mep/dc1059/notification/notification.js
  libs/mep/dc1059/section-metadata/section-metadata.css
  libs/mep/dc1059/section-metadata/section-metadata.js
  libs/mep/dc1059/section-metadata/sticky-section.js
Labels: verified, zero-impact, Ready for Stage

#4695 [MWPW-177703] Load Privacy consistently
  libs/utils/utils.js
Labels: Ready for Stage

#4552 MWPW-174582: retrying to fix id lookup
  tools/send-to-caas/send-utils.js
Labels: CaaS, Ready for Stage

#4674 MWPW-168315 Auto set close captions for videos
  libs/blocks/adobetv/adobetv.js
  test/blocks/adobetv/adobetv.test.js
  test/blocks/adobetv/mocks/body.html
Labels: verified, Ready for Stage

#4675 [MWPW-176965] - faas form error announcement order
  libs/blocks/faas/faas.js
Labels: Ready for Stage

#4705 [MWPW-175711] Optimize network calls for langauge selector on language based sites
  libs/blocks/language-selector/language-selector.js
  libs/utils/utils.js
  test/utils/utils.test.js
Labels: verified, Ready for Stage

#4709 Picking valid privacyEnv from allowed list
  libs/scripts/delayed.js
Labels: verified, Ready for Stage

#4658 [MWPW-177333] Exclude loading icons.js and css for certain blocks
  libs/features/icons/icons.js
  libs/utils/utils.js
  test/utils/utils.test.js
Labels: verified, Ready for Stage

#4670 [MWPW-177019] mWeb Rollout Ps Test | Notifications Block
  libs/blocks/notification/notification.css
  libs/blocks/section-metadata/section-metadata.css
  libs/blocks/section-metadata/sticky-section.js
Labels: verified, Ready for Stage

#4711 [MWPW-177247] Adapt card if text extension is active
  libs/blocks/card/card.css
  libs/blocks/card/card.js
Labels: Ready for Stage

#4697 Section up to list
  libs/blocks/action-scroller/action-scroller.js
  libs/blocks/section-metadata/section-metadata.js
  test/blocks/section-metadata/mocks/body.html
  test/blocks/section-metadata/section-meta.test.js
Labels: Ready for Stage

#4694 [MWPW-177018][MWPW-177170] Mweb changes for feature flag, font-weight and hero marquee
  libs/blocks/hero-marquee/hero-marquee.css
  libs/blocks/hero-marquee/hero-marquee.js
  libs/styles/styles.css
  libs/utils/utils.js
Labels: verified, Ready for Stage

#4642 MWPW-177280: Add new Blade Card option to caas configurator
  libs/blocks/caas-config/caas-config.css
  libs/blocks/caas-config/caas-config.js
  libs/blocks/caas/utils.js
Labels: caas-configurator, CaaS, Ready for Stage

#4683 MWPW-176885 [MEP] Add special handling for suppressing TWP links
  libs/blocks/global-navigation/utilities/utilities.js
  libs/features/personalization/personalization.js
  test/features/personalization/mocks/manifest-remove-twp.json
  test/features/personalization/mocks/personalization-twp.html
  test/features/personalization/personalization.test.js
Labels: verified, high priority, Ready for Stage

#4622 MWPW-175124 Configurable Multi-Step
  libs/blocks/marketo-config/context.js
  libs/blocks/marketo-config/marketo-config.css
  libs/blocks/marketo-config/marketo-config.js
  libs/blocks/marketo-config/step-panel.js
  libs/blocks/marketo/marketo-multi.js
  libs/blocks/marketo/marketo.js
  test/blocks/marketo-config/marketo-config.test.js
Labels: verified, run-nala, @marketo, Ready for Stage

#4693 fix(merch): extract button styling classes from URL hash parameters
  libs/blocks/merch/merch.js
  test/blocks/merch/merch.test.js
  test/blocks/merch/mocks/body.html
Labels: verified, Ready for Stage

#4631 MWPW-169932 adding font-display:swap for iphone safari to stopping fl…
  libs/utils/fonts.js
Labels: Ready for Stage

#4717 [MWPW-177996] Use heading for share block title
  libs/blocks/share/share.css
  libs/blocks/share/share.js
  test/blocks/share/share.test.js
Labels: Ready for Stage

#4699 MWPW-171611 - Block notifications
  libs/scripts/delayed.js
  libs/styles/block-notifications.css
  libs/utils/block-notifications.js
Labels: Ready for Stage

#4732 when more than 2 secondary cta is present alignment issue is seen in mobile
  libs/blocks/global-navigation/global-navigation.css
Labels: verified, Ready for Stage

#4762 MWPW-179126 [MEP] Add marketing actions to manifest info - to stage
  libs/features/mep/addons/lob.js
  libs/features/personalization/personalization.js
  libs/martech/helpers.js
  libs/utils/utils.js
  test/features/personalization/canServeManifest.test.js
  test/features/personalization/mepGeolocation.test.js
  test/features/personalization/mocks/manifestWithNicknames.json
Labels: verified, high priority, Ready for Stage

#4753 MWPW-177450 MWPW-177001 Brand Concierge Chat
  libs/blocks/brand-concierge/brand-concierge.css
  libs/blocks/brand-concierge/brand-concierge.js
  libs/blocks/brand-concierge/chat-ui-config.js
  test/blocks/brand-concierge/brand-concierge.test.js
Labels: verified, Ready for Stage, Blog SOT 👌

#4763 MWPW-177450 MWPW-177001 Brand Concierge Chat
  libs/blocks/brand-concierge/brand-concierge.css
  libs/blocks/brand-concierge/brand-concierge.js
  libs/blocks/brand-concierge/chat-ui-config.js
  test/blocks/brand-concierge/brand-concierge.test.js
Labels: verified, Ready for Main, BAcom SOT 👌, MIQ SOT👌
