Repository adobecom/milo, pull requests merged in 2025-05, with the labels that each got.

#4074 [DA] Refresh dev build with breadcrumb fixes
  tools/da-apps/dist/assets/index.js
Labels: trivial

#3982 MWPW-167550 [Plans] Swap places for strikethrough price
  libs/deps/mas/commerce.js
  libs/deps/mas/merch-card-collection.js
  libs/features/mas/dist/mas.js
  libs/features/mas/src/price/template.js
Labels: verified, commerce, Ready for Stage

#4015 MWPW-170630 Fix table link line break
  libs/blocks/table/table.js
Labels: verified, run-nala, Ready for Stage

#4020 MWPW-170901 [M@S] Incorrect WCS call in langstore
  libs/blocks/merch/merch.js
  libs/utils/utils.js
  test/blocks/merch/merch.test.js
Labels: verified, commerce, Ready for Stage

#4023 [MWPW-170098] - Tabs group label
  libs/blocks/tabs/tabs.css
  libs/blocks/tabs/tabs.js
Labels: Ready for Stage

#4031 MWPW-171966, 170758, 171272 [MEP][MMM] Updates for helping with Target cleanup
  libs/blocks/mmm/mmm.css
  libs/blocks/mmm/mmm.js
  test/blocks/mmm/mmm.test.js
Labels: verified, Ready for Stage

#4042 MWPW-171326: Fix text overflow in table heading
  libs/blocks/table/table.css
  libs/blocks/table/table.js
Labels: Ready for Stage

#4049 MWPW-171335: Add xxs-spacing to con-block
  libs/styles/styles.css
Labels: Ready for Stage

#4045 MWPW-171881 - Adding manual params to 3in1 URL
  libs/blocks/merch/merch.js
  libs/deps/mas/commerce.js
  libs/deps/mas/merch-card-collection.js
  libs/features/mas/dist/mas.js
  libs/features/mas/src/buildCheckoutUrl.js
  libs/features/mas/test/build-checkout-url.test.js
  nala/blocks/merch/three-in-one.page.js
  test/blocks/merch/mocks/threeInOne.html
  test/blocks/merch/three-in-one.test.js
Labels: verified, Ready for Stage

#4086 [DA] Refresh dev build with breadcrumb fixes and reference.xlsx for BCU
  tools/da-apps/dist/assets/index.js
  tools/da-apps/dist/static/files/reference.xlsx
Labels: trivial

#4089 [DA] Refresh dev build with correct reference.xlsx for BCU
  tools/da-apps/dist/static/files/reference.xlsx
Labels: trivial

#4039 MWPW-171131: cli update for M7 links
  libs/blocks/m7/m7.js
  test/blocks/m7/m7.test.js
Labels: verified, high priority, Ready for Stage

#4081 MWPW-172903: SUSI Light Login Fixes
  libs/blocks/susi-light-login/susi-light-login.css
  libs/blocks/susi-light-login/susi-light-login.js
Labels: verified, high priority, Ready for Stage

#4041 MWPW-171040: support for url formats lan/reg
  libs/blocks/region-nav/region-nav.js
  libs/utils/utils.js
  test/blocks/region-nav/region-nav.test.js
Labels: verified, Ready for Stage

#4048 Gnav lana: Put severity level as Tag(s) for LANA messages
  libs/blocks/global-footer/global-footer.js
  libs/blocks/global-navigation/features/breadcrumbs/breadcrumbs.js
  libs/blocks/global-navigation/features/profile/dropdown.js
  libs/blocks/global-navigation/features/search/gnav-search.js
  libs/blocks/global-navigation/global-navigation.js
  libs/blocks/global-navigation/utilities/keyboard/index.js
  libs/blocks/global-navigation/utilities/keyboard/mainNav.js
  libs/blocks/global-navigation/utilities/keyboard/mobilePopup.js
  libs/blocks/global-navigation/utilities/keyboard/popup.js
  libs/blocks/global-navigation/utilities/menu/menu.js
  libs/blocks/global-navigation/utilities/utilities.js
  libs/features/webapp-prompt/webapp-prompt.js
Labels: verified, Ready for Stage

#4059 [MWPW-171958] - video pause/play a11y
  libs/utils/decorate.js
Labels: Ready for Stage

#4064 MWPW-171674: 'Select' option in the CTA label drop-down
  libs/blocks/ost/ctaTextOption.js
  test/blocks/ost/textOption.test.js
Labels: verified, Ready for Stage

#4068 [MWPW-172157] - tab stacked mobile scroll fix
  libs/blocks/tabs/tabs.js
Labels: Ready for Stage

#4093 [DA] Update Build for Prod Release (7 May)
  tools/da-apps/dist/assets/index.js
  tools/da-apps/dist/static/files/reference.xlsx
Labels: trivial

#4104 [MWPW-172157] - fix tab error
  libs/blocks/tabs/tabs.js
Labels: Ready for Stage

#4099 Commerce cumulative PR
  libs/blocks/merch-card/merch-card.js
  libs/blocks/merch-offers/merch-offers.js
  libs/blocks/merch/merch.css
  libs/blocks/merch/three-in-one.js
  libs/blocks/ost/ost.js
  libs/deps/mas/commerce.js
  libs/deps/mas/merch-card-collection.js
  libs/deps/mas/merch-card.js
  libs/deps/mas/merch-offer-select.js
  libs/deps/mas/merch-quantity-select.js
  libs/deps/mas/merch-sidenav.js
  libs/deps/mas/merch-stock.js
  libs/features/mas/dist/mas.js
  libs/features/mas/src/buildCheckoutUrl.js
  libs/features/mas/src/checkout.js
  libs/features/mas/src/constants.js
  libs/features/mas/src/global.css.js
  libs/features/mas/src/hydrate.js
  libs/features/mas/src/mas.js
  libs/features/mas/src/merch-addon.js
  libs/features/mas/src/merch-card.js
  libs/features/mas/src/merch-gradient.js
  libs/features/mas/src/merch-quantity-select.js
  libs/features/mas/src/price/utilities.js
  libs/features/mas/src/variants/mini-compare-chart.css.js
  libs/features/mas/src/variants/mini-compare-chart.js
  libs/features/mas/src/variants/plans.css.js
  libs/features/mas/src/variants/plans.js
  libs/features/mas/src/variants/product.css.js
  libs/features/mas/src/variants/product.js
  libs/features/mas/test/build-checkout-url.test.js
  libs/features/mas/test/checkout-button.test.js
  libs/features/mas/test/checkout-link.test.js
  libs/features/mas/test/hydrate.test.js
  libs/features/mas/test/merch-addon.test.html
  libs/features/mas/test/merch-card-product.test.html
  libs/features/mas/test/merch-card-product.test.html.js
  libs/features/mas/test/merch-card.plans.test.html
  libs/features/mas/test/mocks/offers.json
  libs/features/mas/test/price/__snapshots__/template.snapshots.js
  libs/features/mas/test/price/template.test.js
  libs/styles/iframe.css
  nala/blocks/merch/three-in-one.page.js
  nala/blocks/tabs/tabs.test.js
  test/blocks/merch/three-in-one.test.js
Labels: verified, commerce, high priority, Ready for Stage

#4067 [LOC UI] MWPW-167155 Cancel language support
  libs/blocks/locui/actions/index.js
  libs/blocks/locui/actions/modal.js
  libs/blocks/locui/langs/index.js
  libs/blocks/locui/langs/view.js
  libs/blocks/locui/utils/miloc.js
Labels: trivial

#4112 [DA] Refresh dev build with BCU save payload change
  tools/da-apps/dist/assets/index.js
Labels: trivial

#4105 Adding the mweb test folder
  libs/mep/ace1052/carousel/carousel.css
  libs/mep/ace1052/carousel/carousel.js
Labels: verified, zero-impact, Ready for Stage

#4132 [DA] Refresh dev build with BCU save payload change
  tools/da-apps/dist/assets/index.js
Labels: trivial

#4016 [MWPW-170403] [NALA] [MEP] add a Nala test for the new updateAttribute feature
  nala/features/personalization/update-attribute-prepend.spec.js
  nala/features/personalization/update-attribute-prepend.test.js
Labels: zero-impact, Ready for Stage

#4066 MWPW-172578 Start Logging Gnav Related Performance Data
  libs/blocks/global-navigation/global-navigation.js
  libs/blocks/global-navigation/utilities/menu/menu.js
  libs/blocks/global-navigation/utilities/utilities.js
  libs/utils/utils.js
Labels: verified, high priority, Ready for Stage

#4102 MWPW-170933: support for bulk publisher with langauge-first localization
  tools/send-to-caas/bulk-publish-to-caas.js
  tools/send-to-caas/bulkpublish.css
  tools/send-to-caas/bulkpublisher.html
  tools/send-to-caas/send-utils.js
Labels: verified, CaaS, high priority, Ready for Stage

#4133 MWPW-173355 [MEP] MEP cannot find fragments when used in gnav
  libs/blocks/fragment/fragment.js
  libs/blocks/global-navigation/utilities/utilities.js
  libs/features/personalization/personalization.js
Labels: verified, high priority, Ready for Stage

#3981 MWPW-164498: Plans Education + Business cards
  libs/deps/mas/commerce.js
  libs/deps/mas/merch-card-collection.js
  libs/deps/mas/merch-card.js
  libs/features/mas/dist/mas.js
  libs/features/mas/docs/plans.html
  libs/features/mas/docs/src/plans.md
  libs/features/mas/docs/styles.css
  libs/features/mas/src/global.css.js
  libs/features/mas/src/hydrate.js
  libs/features/mas/src/merch-card-collection.js
  libs/features/mas/src/variants/catalog.js
  libs/features/mas/src/variants/ccd-slice.js
  libs/features/mas/src/variants/ccd-suggested.js
  libs/features/mas/src/variants/plans.css.js
  libs/features/mas/src/variants/plans.js
  libs/features/mas/src/variants/special-offer.js
  libs/features/mas/src/variants/variant-layout.js
  libs/features/mas/src/variants/variants.js
Labels: verified, commerce, Ready for Stage

#3996 [MWPW-171328] - Icon block link image focus
  libs/blocks/icon-block/icon-block.css
  libs/blocks/icon-block/icon-block.js
Labels: Ready for Stage

#4027 MWPW-170339: Move row title
  libs/blocks/columns/columns.css
  libs/blocks/columns/columns.js
Labels: high-impact, Ready for Stage

#4035 [MWPW-170305] - Dialog attributes
  libs/blocks/adobetv/adobetv.js
  libs/blocks/iframe/iframe.js
  libs/blocks/modal/modal.js
  libs/blocks/vimeo/vimeo.js
  libs/blocks/youtube/youtube.js
  libs/scripts/accessibility.js
  test/blocks/instagram/mocks/embed-utils.js
Labels: Ready for Stage

#4127 MWPW-171432 | Hero Marquee mweb changes in mep test
  libs/mep/ace1052/hero-marquee/hero-marquee.css
  libs/mep/ace1052/hero-marquee/hero-marquee.js
Labels: zero-impact

#4135 Merging the mweb changes to stage
  libs/mep/ace1052/carousel/carousel.css
  libs/mep/ace1052/carousel/carousel.js
  libs/mep/ace1052/hero-marquee/hero-marquee.css
  libs/mep/ace1052/hero-marquee/hero-marquee.js
Labels: zero-impact

#4143 MWPW-173130 lanafix
  libs/deps/mas/commerce.js
  libs/deps/mas/merch-card-collection.js
  libs/features/mas/dist/mas.js
  libs/features/mas/src/mas.js
Labels: verified

#4072 MWPW-164662: [3-in-1][Milo] Pass user selection to commerce (ex: quantity, stock add-on, etc.)
  libs/deps/mas/commerce.js
  libs/deps/mas/merch-card-collection.js
  libs/deps/mas/merch-card.js
  libs/features/mas/dist/mas.js
  libs/features/mas/src/buildCheckoutUrl.js
  libs/features/mas/src/merch-card.js
  libs/features/mas/test/build-checkout-url.test.js
Labels: verified, commerce, high priority, Ready for Stage

#4080 [MWPW-172825] Fix localized links getting localized again for language based site urls
  libs/utils/utils.js
Labels: verified, high priority, Ready for Stage

#4083 MWPW-170326: Consonant & A11Y Enhancements
  libs/blocks/share/share.css
Labels: verified, high priority, Ready for Stage

#4146 MWPW-173467: add support for dcp in susi light login
  libs/blocks/susi-light-login/susi-light-login.js
  test/blocks/susi-light-login/susi-light-login.test.js
Labels: verified, high priority, Ready for Stage

#3977 [MWPW-170108] - Notification a11y
  libs/blocks/notification/notification.css
  libs/blocks/notification/notification.js
  test/blocks/notification/notification.test.js
Labels: Ready for Stage

#4037 chore: Configure Trusted Hosts for Sidekick
  tools/sidekick/config.json
Labels: Ready for Stage

#4047 No zoom behaviour on localnav headline
  libs/blocks/global-navigation/global-navigation.css
Labels: verified, Ready for Stage

#4060 MWPW-171649: Improve load time of commerce modal (3-in-1)
  libs/blocks/merch/merch.js
  libs/utils/utils.js
  test/blocks/merch/mocks/embed-utils.js
  test/blocks/ost/mocks/ost-utils.js
Labels: verified, commerce, Ready for Stage

#4071 MWPW-171825 Improve lcp performance for favicon and breadcrumb
  libs/utils/utils.js
Labels: verified, Ready for Stage

#4077 [MWPW-172403] - Text headings strong font weight
  libs/styles/styles.css
Labels: Ready for Stage

#4084 MWPW-170454 : Visual list is not marked up as list
  libs/blocks/global-navigation/utilities/menu/menu.js
Labels: verified, Ready for Stage

#4153 [Dev][Loc][MWPW 173377] Add Transcreation Locales in Select Languages Screen
  libs/blocks/locui-create/store.js
  libs/blocks/locui-create/utils/constant.js
  tools/da-apps/auth.js
Labels: trivial

#4152 [Loc][MWPW-173377] Add Transcreation Locales in Select Languages Screen
  libs/blocks/locui-create/store.js
  libs/blocks/locui-create/utils/constant.js
Labels: trivial

#4131 Mwpw 170378 preflight assets unit test
  test/blocks/preflight/checks/assets.test.js
  test/blocks/preflight/panels/assets.test.js
Labels: zero-impact

#4154 Reduce gnav lana sampleRate to 0.01%
  libs/blocks/global-navigation/utilities/utilities.js
Labels: Ready for Stage

#4130 MWPW-169841 cta align fix
  libs/deps/mas/commerce.js
  libs/deps/mas/merch-card-collection.js
  libs/deps/mas/merch-card.js
  libs/features/mas/dist/mas.js
  libs/features/mas/src/buildCheckoutUrl.js
  libs/features/mas/src/checkout.js
  libs/features/mas/src/merch-card.js
  libs/features/mas/src/variants/mini-compare-chart.css.js
  libs/features/mas/src/variants/mini-compare-chart.js
  libs/features/mas/src/variants/product.js
  libs/features/mas/test/build-checkout-url.test.js
Labels: commerce, high priority, Ready for Stage

#4078 MWPW-172083 [MMM]: Target Metadata lookup
  libs/blocks/mmm/mmm.css
  libs/blocks/mmm/mmm.js
  libs/features/personalization/preview.js
Labels: verified, Ready for Stage

#4079 MWPW-145857: Redirects formatter clean
  libs/blocks/redirects-formatter/redirects-formatter.css
  libs/blocks/redirects-formatter/redirects-formatter.js
  libs/blocks/redirects-formatter/utils/checkboxes.js
  libs/blocks/redirects-formatter/utils/process-redirects.js
  libs/blocks/redirects-formatter/utils/redirect-inputs.js
  test/blocks/redirects-formatter/checkboxes.test.js
  test/blocks/redirects-formatter/mocks/locale-config.json
  test/blocks/redirects-formatter/mocks/redirects-formatter.html
  test/blocks/redirects-formatter/process-redirects.test.js
  test/blocks/redirects-formatter/redirect-inputs.test.js
  test/blocks/redirects-formatter/redirects-formatter.test.js
Labels: verified, Ready for Stage

#4100 quiz icon bug fix
  libs/blocks/quiz/quiz.css
Labels: verified, uar, Ready for Stage

#4103 Improve carousel accessibility
  libs/blocks/carousel/carousel.css
  libs/blocks/carousel/carousel.js
  nala/blocks/carousel/carousel.page.js
  nala/blocks/carousel/carousel.test.js
Labels: Ready for Stage

#4110 MWPW-172910: autodetect on language-first caas collections
  libs/blocks/caas/utils.js
  libs/utils/utils.js
Labels: verified, CaaS, Ready for Stage

#4121 MWPW-164457 Add injectblock metadata support
  libs/blocks/graybox/graybox.css
  libs/blocks/graybox/graybox.js
  libs/utils/injectblock.js
  libs/utils/utils.js
  test/blocks/graybox/globalnoclick.test.js
  test/blocks/graybox/graybox.test.js
Labels: verified, Ready for Stage

#4142 Remove libraries flag
  tools/sidekick/config.json
Labels: Ready for Stage

#4028 MWPW-169224-Increase max PR count/batch pre&post-RCP
  .github/workflows/helpers.js
  .github/workflows/merge-to-stage.js
Labels: zero-impact, Ready for Stage

#4165 [DA] Refresh dev build with search query bug fix
  tools/da-apps/dist/assets/index.js
Labels: trivial

#4167 [Loc][MWPW-173379] Add Date Time Picker in Enter URLs Screen
  libs/blocks/locui-create/components/dateTimePicker.js
  libs/blocks/locui-create/input-urls/index.js
  libs/blocks/locui-create/input-urls/view.js
  libs/blocks/locui-create/locui-create.css
  libs/blocks/locui-create/utils/utils.js
Labels: trivial

#4176 [Dev][Loc][MWPW-173379] Add Date Time Picker in Enter URLs Screen
  libs/blocks/locui-create/components/dateTimePicker.js
  libs/blocks/locui-create/input-urls/index.js
  libs/blocks/locui-create/input-urls/view.js
  libs/blocks/locui-create/locui-create.css
  libs/blocks/locui-create/utils/utils.js
Labels: trivial

#4175 Adding Color white variable for standalone gnav and adding non milo locale path link transform in region nav
  libs/blocks/region-nav/region-nav.js
  libs/navigation/navigation.css
Labels: verified, high priority, Ready for Stage

#4184 MWPW-173586: Dexter modals deeplink -backwards compatibility for 3in1
  libs/blocks/merch/merch.js
  test/blocks/merch/merch.test.js
  test/blocks/merch/mocks/body.html
Labels: verified, commerce, high priority, Ready for Stage

#4088 MWPW-172916 Pep prompt is seen loaded and redirected when geo popup is on and not closed
  libs/features/webapp-prompt/webapp-prompt.js
  libs/utils/utils.js
  test/features/webapp-prompt/test-utilities.js
Labels: verified, Ready for Stage

#4092 Adding arrow Up/Down navigation for localnav
  libs/blocks/global-navigation/global-navigation.js
  libs/blocks/global-navigation/utilities/keyboard/localNav.js
  libs/blocks/global-navigation/utilities/keyboard/utils.js
Labels: verified, Ready for Stage

#4107 MWPW-172474: await merch service before
  libs/blocks/merch-card/merch-card.js
Labels: verified, commerce, Ready for Stage

#4138 [MWPW-158022] - Text block bold break
  libs/blocks/text/text.css
Labels: Ready for Stage

#4139 MWPW-173130: Preserve regular links in merch-card footers
  libs/deps/mas/commerce.js
  libs/deps/mas/merch-card-collection.js
  libs/deps/mas/merch-card.js
  libs/features/mas/dist/mas.js
  libs/features/mas/src/hydrate.js
  libs/features/mas/src/mas.js
  libs/features/mas/test/hydrate.test.js
  nala/features/mas/ccd/masccd.page.js
  nala/features/mas/ccd/masccd.spec.js
  nala/features/mas/ccd/masccd.test.js
Labels: verified, Ready for Stage

#4183 Test Urls are not getting added when PR is created from fork repo
  .github/workflows/dynamic-pr-template.yml
Labels: trivial, zero-impact, Ready for Stage

#4189 MWPW-173721 [Locv3] Made Translation/Rollout selection pill accessible
  libs/blocks/locui-create/input-urls/view.js
Labels: trivial

#4173 MWPW-173649 CWV Logging Updates
  libs/utils/logWebVitals.js
  test/utils/logWebVitals.test.js
  test/utils/logWebVitalsUtils.test.js
Labels: trivial

#4193 [DA] Stage deployment (20 May)
  tools/da-apps/dist/assets/index.js
  tools/da-apps/dist/assets/vendor.js
Labels: trivial

#4073 Fixing Missing/Mismatched attributes in PageView call payload
  libs/martech/helpers.js
  libs/martech/helpers.md
  test/martech/helpers.test.js
Labels: verified, high priority, Ready for Stage

#4124 MWPW-172085, 173254, 173501, 173732, 173083 [MEP][MMM] Batch PR for Stage
  libs/blocks/mmm/mmm.js
  libs/features/personalization/preview.css
  libs/features/personalization/preview.js
  test/blocks/mmm/mmm.test.js
Labels: verified, high priority, Ready for Stage

#4137 MWPW-167709 [GNAV] [Pre-Load] | (Ghost) State when Mega Menu fragment has not loaded (Desktop & Mobile)
  libs/blocks/global-navigation/global-navigation.css
  libs/blocks/global-navigation/global-navigation.js
  libs/blocks/global-navigation/utilities/menu/menu.js
  libs/blocks/global-navigation/utilities/utilities.js
Labels: verified, high priority, Ready for Stage

#4151 [MWPW-173341] - Added ally fix for GNAV Promo heading text
  libs/blocks/global-navigation/utilities/menu/menu.css
  libs/blocks/global-navigation/utilities/menu/menu.js
Labels: verified, high priority, Ready for Stage

#4188 Removing text decoration none from region nav links
  libs/blocks/region-nav/region-nav.css
Labels: verified, high priority, Ready for Stage

#4097 [MWPW-170714] - Section metadata grid
  libs/blocks/section-metadata/section-metadata.css
Labels: Ready for Stage

#4120 MWPW-173121: Tax Exclusive & ABM labels for Plans body prices
  libs/deps/mas/commerce.js
  libs/deps/mas/merch-card-collection.js
  libs/deps/mas/merch-card.js
  libs/features/mas/dist/mas.js
  libs/features/mas/src/variants/plans.css.js
  libs/features/mas/src/variants/plans.js
  libs/features/mas/test/merch-card.plans.test.html
  libs/features/mas/test/mocks/offers.json
Labels: verified, commerce, Ready for Stage

#4155 Mwpw 170301 focus outside modal
  libs/blocks/modal/modal.js
  libs/styles/styles.css
Labels: Ready for Stage

#4163 MWPW-171825 Improve lcp performance for favicon and breadcrumb
  libs/utils/utils.js
Labels: verified, Ready for Stage

#4166 Breadcrumb last item value as current window url if not a link
  libs/blocks/global-navigation/features/breadcrumbs/breadcrumbs.js
  test/blocks/global-navigation/features/breadcrumbs.test.js
Labels: verified, Ready for Stage

#4190 Quiz option titles on mobile
  libs/blocks/quiz/quiz.css
Labels: verified, uar, Ready for Stage

#4208 MWPW-173816: remove stock checks temporarily
  nala/features/mas/acom/masacom.test.js
Labels: zero-impact

#4185 [MWPW-173470] - Korea free trial restrict
  libs/blocks/global-navigation/utilities/utilities.js
  libs/blocks/merch/merch.js
  libs/utils/decorate.js
  libs/utils/utils.js
Labels: high priority, Ready for Stage, DC SOT 👌, Homepage SOT 👌

#4200 MWPW-173239: fallback for addon
  libs/deps/mas/merch-card.js
  libs/features/mas/dist/mas.js
  libs/features/mas/src/merch-addon.js
  libs/features/mas/src/merch-card.js
  libs/features/mas/test/merch-addon.test.html
Labels: verified, high priority, Ready for Stage

#4222 [DA] Update Build for Prod Release (22 May)
  tools/da-apps/dist/assets/index.js
Labels: trivial

#4199 [MWPW-173717] Hyphenate large headings on mobile
  libs/styles/styles.css
Labels: high priority, Ready for Stage

#4101 MWPW-170535 - Ribbon Notification 'in-line' variant for mWeb
  libs/blocks/notification/notification.css
Labels: verified, Ready for Stage

#4159 MWPW-169410: Add download icon to sidekick
  libs/img/icons/icons.svg
Labels: Ready for Stage

#4180 MWPW-173425: Allow container to expand based on line height
  libs/blocks/card-horizontal/card-horizontal.css
Labels: Ready for Stage

#4196 Updating code owners for region nav and navigation folder
  CODEOWNERS
Labels: trivial, zero-impact, Ready for Stage

#4216 MWPW-173436 | Fix delay in split notification load
  libs/blocks/notification/notification.css
Labels: verified, high priority, Ready for Stage

#4058 Remove lana log error specific to localnav from non localnav gnav
  libs/blocks/global-navigation/global-navigation.js
  libs/blocks/global-navigation/utilities/utilities.js
Labels: verified, Ready for Stage

#4174 MWPW-170753 : [Mobile NAV][A11Y] | RWD Tablet Mobile
  libs/blocks/global-navigation/utilities/keyboard/index.js
Labels: verified, Ready for Stage

#4205 [Mobile NAV][A11Y] | RWD Tablet Mobile -Able to browse outside modal with screen reader
  libs/blocks/global-navigation/global-navigation.js
Labels: verified, Ready for Stage

#4147 MWPW-171937: fix cta urls for bulk publisher
  tools/send-to-caas/send-utils.js
Labels: verified, CaaS, Ready for Stage

#4225 MWPW-173888 + MWPW-173919: Appending extra options for relative urls & multiple cta reopen fix
  libs/blocks/merch/merch.js
  test/blocks/merch/merch.test.js
Labels: verified, commerce, high priority, Ready for Stage

#4235 Revert "[MWPW-173470] - Korea free trial restrict" (stage)
  libs/blocks/global-navigation/utilities/utilities.js
  libs/blocks/merch/merch.js
  libs/utils/decorate.js
  libs/utils/utils.js
Labels: Ready for Stage

#4237 MWPW-173888 + MWPW-173919: Appending extra options for relative urls & multiple cta reopen fix
  libs/blocks/merch/merch.js
  test/blocks/merch/merch.test.js
Labels: verified

#4238 MWPW-173875 direct to main
  libs/utils/logWebVitals.js
  test/utils/logWebVitals.test.js
  test/utils/logWebVitalsUtils.test.js
Labels: trivial, high priority

#4206 [Loc] Fix due date in edit workflow
  libs/blocks/locui-create/utils/utils.js
Labels: trivial, Stale

#4207 [Dev][Loc] Fix due date in edit workflow
  libs/blocks/locui-create/utils/utils.js
Labels: trivial
