Repository adobecom/milo, pull requests merged in 2025-07, with the labels that each got.

#4467 MWPW-173845: Fix collection header margin for edu plans cards
  libs/deps/mas/merch-card.js
  libs/features/mas/dist/mas.js
  libs/features/mas/src/variants/plans.css.js
Labels: verified

#4458 Table flaky/failing tests fix
  test/blocks/table/table.test.js
Labels: zero-impact, Ready for Stage

#4481 Fix(MWPW-168438): Video Abort error fix.
  libs/utils/decorate.js
Labels: high priority, Ready for Stage

#4341 There is a gap at the bottom of the Megamenu in both portrait and landscape mode on the FF browser
  libs/blocks/global-navigation/global-navigation.css
  libs/blocks/global-navigation/utilities/utilities.js
Labels: verified, Ready for Stage

#4422 Updating close gnav function to support desktop mode
  libs/blocks/global-navigation/global-navigation.js
Labels: verified, Ready for Stage

#4452 [MWPW-175093] - Table sticky header font size upscale with extension fix
  libs/blocks/table/table.js
Labels: Ready for Stage

#4493 MWPW-175097: Enable preview for stage.adobe.com
  libs/blocks/merch/merch.js
Labels: verified, Ready for Stage

#4504 [DA][Loc] Prod Release (7 July)
  libs/blocks/locui-create/input-locale/index.js
  libs/blocks/locui-create/input-locale/view.js
  libs/blocks/locui-create/utils/utils.js
  tools/da-apps/dist/assets/index.js
Labels: trivial

#4435 MWPW-167847 Support .ing domains for LANA
  libs/utils/lana.js
Labels: verified, Ready for Stage

#4440 MWPW-175246: Commerce docs page
  libs/features/mas/docs/commerce.html
  libs/features/mas/docs/mas-sidenav.js
  libs/features/mas/docs/src/build-docs.sh
  libs/features/mas/docs/src/commerce.md
  libs/features/mas/test/merch-card-collection.test.html
Labels: verified, Ready for Stage

#4451 Fix(MWPW-175129): url.canParse support for legacy browsers.
  libs/blocks/caas-config/caas-config.js
  libs/blocks/caas/utils.js
  libs/utils/utils.js
  test/blocks/caas/mocks/utils.js
Labels: verified, Ready for Stage

#4494 [MWPW-175634] Reading time color update for a11y
  libs/blocks/reading-time/reading-time.css
  nala/blocks/reading-time/reading-time.test.js
  nala/utils/nala.run.js
Labels: Ready for Stage

#4498 switched between portrait and landscape without refresh the gap is seen
  libs/blocks/global-navigation/global-navigation.js
Labels: verified, Ready for Stage

#4485 MWPW-175589 and MWPW-175712: Modal does not reopen when navigation back
  libs/blocks/merch/merch.js
  libs/blocks/merch/merch.md
  libs/blocks/merch/three-in-one.js
  libs/blocks/modal/modal.js
  nala/blocks/merch/three-in-one.test.js
  test/blocks/merch/merch.test.js
  test/blocks/merch/three-in-one.test.js
Labels: verified, commerce, high priority, Ready for Stage

#4450 [MWPW-174959] - Table border fix
  libs/blocks/table/table.css
  libs/blocks/table/table.js
Labels: Ready for Stage

#4510 [MWPW-170376] Preflight assets tab updates
  libs/blocks/preflight/checks/assets.js
  libs/blocks/preflight/checks/constants.js
  libs/blocks/preflight/checks/seo.js
  libs/blocks/preflight/panels/accessibility.js
  libs/blocks/preflight/panels/assets.js
  libs/blocks/preflight/panels/general.js
  libs/blocks/preflight/preflight.css
  libs/utils/decorate.js
  test/blocks/preflight/checks/assets.test.js
  test/blocks/preflight/panels/assets.test.js
Labels: Ready for Stage

#4474 feat: integrate GenStudio tracking
  libs/scripts/delayed.js
  test/scripts/delayed.test.js
Labels: Ready for Stage, Stale

#4524 MWPW-176120: use app id/ver from section metadata if not present in config
  libs/features/jarvis-chat.js
Labels: verified, Ready for Stage

#4512 MWPW-174353: Fix scroll to behavior for pdf viewer
  libs/blocks/pdf-viewer/pdf-viewer.js
Labels: verified, Ready for Stage

#4532 Sync milo auto importer with the nexter importer
  .github/workflows/import/index.js
Labels: zero-impact

#4526 MWPW-176125: Merch modal follow-up
  libs/blocks/merch/merch.js
  libs/blocks/merch/three-in-one.js
  libs/blocks/modal/modal.js
  nala/blocks/merch/three-in-one.test.js
  test/blocks/merch/merch.test.js
  test/blocks/merch/three-in-one.test.js
Labels: verified, high priority, Ready for Stage

#4527 [MWPW-175533] Hero Marquee lockup text overlap fix
  libs/blocks/hero-marquee/hero-marquee.css
  libs/blocks/hero-marquee/hero-marquee.js
Labels: Ready for Stage

#4536 MWPW-175671: Adapt quantity selector popover placement based on current scroll
  libs/deps/mas/merch-quantity-select.js
  libs/features/mas/dist/mas.js
  libs/features/mas/src/merch-quantity-select.css.js
  libs/features/mas/src/merch-quantity-select.js
Labels: verified, Ready for Stage

#4520 fix(css): TagSelector - add position: relative to .search-item to support absolute .cb checkbox
  libs/ui/controls/tagSelector.css
Labels: bug, verified, Ready for Stage

#4505 MWPW-175842: Remove size option from plans education card
  libs/deps/mas/merch-card.js
  libs/features/mas/dist/mas.js
  libs/features/mas/src/variants/plans.js
Labels: verified, commerce, Ready for Stage, plans

#4528 MWPW-175709: add commerce.preload request param to switch off/on 3in1 preload
  libs/blocks/merch/merch.js
Labels: verified, commerce, Ready for Stage

#4359 MWPW-172853: Loads 'maslibs' in merch blocks (merch card, merch and commerce)
  .gitignore
  head.html
  libs/blocks/merch-card-autoblock/merch-card-autoblock.js
  libs/blocks/merch-card-collection-autoblock/merch-card-collection-autoblock.js
  libs/blocks/merch-card-collection/merch-card-collection.js
  libs/blocks/merch-card/merch-card.js
  libs/blocks/merch-card/merch-offer-select.js
  libs/blocks/merch-mnemonic-list/merch-mnemonic-list.js
  libs/blocks/merch-offers/merch-offers.js
  libs/blocks/merch-whats-included/merch-whats-included.js
  libs/blocks/merch/merch.js
  libs/blocks/ost/ost.js
  libs/deps/mas/merch-card.js
  libs/features/mas/.gitignore
  libs/features/mas/dist/mas.js
  libs/features/mas/src/aem-fragment.js
  libs/mep/emea1443/merch-card/merch-card.js
  libs/mep/emea1443/merch-card/merch-offer-select.js
Labels: verified, Ready for Stage

#4396 MWPW-173815: Merch addon TRIAL fix & style update
  libs/deps/mas/merch-card.js
  libs/deps/mas/merch-secure-transaction.js
  libs/deps/mas/merch-sidenav.js
  libs/deps/mas/merch-stock.js
  libs/features/mas/dist/mas.js
  libs/features/mas/src/media.js
  libs/features/mas/src/merch-addon.js
  libs/features/mas/src/utils.js
  libs/features/mas/src/variants/mini-compare-chart.js
  libs/features/mas/src/variants/plans.css.js
  libs/features/mas/src/variants/plans.js
  libs/features/mas/src/variants/product.js
  libs/features/mas/test/merch-addon.test.html
Labels: verified, commerce, Ready for Stage, plans

#4519 implement arrows in geo routing pop up button which had multiple drop…
  libs/features/georoutingv2/georoutingv2.js
  test/features/georoutingv2/georoutingv2.test.js
Labels: verified, Ready for Stage

#4541 [MWPW-176288] Preflight check vids from open modal
  libs/blocks/preflight/checks/assets.js
Labels: Ready for Stage

#4539 navigate to get started in cta in bacom page via tab or arrow keys in…
  libs/blocks/global-navigation/utilities/keyboard/mobileGnav.js
  libs/blocks/global-navigation/utilities/keyboard/utils.js
Labels: verified, Ready for Stage

#4553 reverts PR #4514
  libs/deps/mas/merch-sidenav.js
  libs/features/mas/src/sidenav/merch-sidenav.js
  libs/features/mas/test/spectrum.js
  libs/features/spectrum-web-components/src/overlay.js
Labels: verified

#4550 [NALA][MWPW-176044] Redirect Nala test runs targeting main branch to milo.adobe.com
  nala/utils/global.setup.js
  nala/utils/nala.run.js
  nala/utils/pr.run.sh
Labels: zero-impact, Ready for Stage

#4509 Added Mini GNAV version for Standalone GNAV
  libs/blocks/global-navigation/global-navigation.js
  libs/blocks/global-navigation/utilities/keyboard/mobileGnav.js
  libs/blocks/global-navigation/utilities/utilities.js
  libs/navigation/navigation.css
  libs/navigation/navigation.js
  test/navigation/navigation.test.js
Labels: verified, high priority, Ready for Stage

#4469 MWPW-172799: Graybox Support for CaaS
  libs/blocks/caas/utils.js
  test/blocks/caas/send-to-caas.test.js
  test/blocks/caas/utils.test.js
  tools/send-to-caas/bulk-publish-to-caas.js
  tools/send-to-caas/send-utils.js
Labels: CaaS, Ready for Stage

#4555 MWPW-175935: Removed the __merch__spectrum_Overlay workaround
  libs/deps/mas/merch-sidenav.js
  libs/features/mas/src/sidenav/merch-sidenav.js
  libs/features/mas/test/spectrum.js
  libs/features/spectrum-web-components/src/overlay.js
Labels: verified, Ready for Stage

#4465 MWPW-174164: Collection header & UI fixes
  libs/blocks/merch-card-collection-autoblock/merch-card-collection-autoblock.js
  libs/blocks/merch-card-collection/merch-card-collection.js
  libs/deps/mas/commerce.js
  libs/deps/mas/merch-card-collection-header.js
  libs/deps/mas/merch-card-collection.js
  libs/deps/mas/merch-card.js
  libs/deps/mas/merch-offer-select.js
  libs/deps/mas/merch-quantity-select.js
  libs/deps/mas/merch-sidenav.js
  libs/deps/mas/merch-stock.js
  libs/features/mas/build.mjs
  libs/features/mas/dist/mas.js
  libs/features/mas/src/constants.js
  libs/features/mas/src/global.css.js
  libs/features/mas/src/merch-card-collection-header.js
  libs/features/mas/src/merch-card-collection.js
  libs/features/mas/src/sidenav/merch-sidenav-list.js
  libs/features/mas/src/sidenav/merch-sidenav.js
  libs/features/mas/src/utils.js
  libs/features/mas/src/variants/catalog.css.js
  libs/features/mas/src/variants/plans.css.js
  libs/features/mas/src/variants/plans.js
  libs/features/mas/src/variants/variants.js
  libs/features/mas/test/merch-card-collection.test.html
  libs/features/mas/test/merch-card-collection.test.html.js
  test/blocks/merch-card-collection/merch-card-collection.test.js
  test/blocks/merch-card-collection/mocks/merch-card-collection.html
Labels: verified, commerce, Ready for Stage, plans

#4566 Revert "MWPW-174164: Collection header & UI fixes (#4465)"
  libs/blocks/merch-card-collection-autoblock/merch-card-collection-autoblock.js
  libs/blocks/merch-card-collection/merch-card-collection.js
  libs/deps/mas/commerce.js
  libs/deps/mas/merch-card-collection-header.js
  libs/deps/mas/merch-card-collection.js
  libs/deps/mas/merch-card.js
  libs/deps/mas/merch-offer-select.js
  libs/deps/mas/merch-quantity-select.js
  libs/deps/mas/merch-sidenav.js
  libs/deps/mas/merch-stock.js
  libs/features/mas/build.mjs
  libs/features/mas/dist/mas.js
  libs/features/mas/src/constants.js
  libs/features/mas/src/global.css.js
  libs/features/mas/src/merch-card-collection-header.js
  libs/features/mas/src/merch-card-collection.js
  libs/features/mas/src/sidenav/merch-sidenav-list.js
  libs/features/mas/src/sidenav/merch-sidenav.js
  libs/features/mas/src/utils.js
  libs/features/mas/src/variants/catalog.css.js
  libs/features/mas/src/variants/plans.css.js
  libs/features/mas/src/variants/plans.js
  libs/features/mas/src/variants/variants.js
  libs/features/mas/test/merch-card-collection.test.html
  libs/features/mas/test/merch-card-collection.test.html.js
  test/blocks/merch-card-collection/merch-card-collection.test.js
  test/blocks/merch-card-collection/mocks/merch-card-collection.html
Labels: verified

#4557 [MWPW-176491] Re-add alt labels from Preflight
  libs/blocks/preflight/accessibility/audit-image-alt-text.js
Labels: Ready for Stage

#4538 feat(send-to-caas): support CTA URL localization via caasLocaleInject metadata flag
  tools/send-to-caas/send-utils.js
Labels: CaaS, Ready for Stage

#4540 MWPW-175674 Plans - Accessibility
  libs/blocks/merch-card-autoblock/merch-card-autoblock.js
  libs/blocks/merch-card-collection-autoblock/merch-card-collection-autoblock.js
  libs/blocks/merch/autoblock.js
  libs/blocks/merch/merch.js
  libs/deps/mas/merch-card.js
  libs/deps/mas/merch-quantity-select.js
  libs/features/mas/dist/mas.js
  libs/features/mas/src/merch-quantity-select.js
  libs/features/mas/src/variants/plans.js
  test/blocks/merch/merch.test.js
  test/blocks/merch/mocks/body.html
  test/blocks/merch/mocks/offers.json
Labels: verified, commerce, Ready for Stage, plans

#4554 daa-ll is seen as undefined in megamenu in mobile mode on initial page load
  libs/blocks/global-navigation/utilities/utilities.js
Labels: verified, Ready for Stage

#4529 MWPW-176072, MWPW-176077, MWPW-176169 seotech fixes
  libs/features/seotech/seotech.js
  test/features/seotech/seotech.test.js
  test/utils/utils.test.js
Labels: trivial, Ready for Stage

#4508 Mwpw 175766 marquee order
  libs/blocks/marquee/marquee.css
  libs/blocks/marquee/marquee.js
  nala/blocks/marquee/marquee.test.js
Labels: Ready for Stage

#4572 MWPW-175280: [Footer] | Add Grey Legacy Adobe icon
  libs/blocks/global-footer/global-footer.css
  libs/blocks/global-footer/global-footer.js
Labels: verified, Ready for Stage

#4571 Fixing getDomain function
  libs/martech/helpers.js
Labels: verified, Ready for Stage

#4568 [MILO][Preflight] Text overlapping in the Preflight Accessibility tab
  libs/blocks/preflight/preflight.css
Labels: Ready for Stage

#4565 MWPW-174422 - Section metadata spacing tokens update
  libs/blocks/section-metadata/section-metadata.css
Labels: Ready for Stage

#4587 [MWPW-176806] Icons not loading for the sidekick library
  libs/blocks/library-config/library-config.js
Labels: Ready for Stage

#4581 MWPW-174164: Collection header & UI fixes
  libs/blocks/merch-card-collection-autoblock/merch-card-collection-autoblock.js
  libs/blocks/merch-card-collection/merch-card-collection.js
  libs/deps/mas/commerce.js
  libs/deps/mas/merch-card-collection-header.js
  libs/deps/mas/merch-card-collection.js
  libs/deps/mas/merch-card.js
  libs/deps/mas/merch-offer-select.js
  libs/deps/mas/merch-quantity-select.js
  libs/deps/mas/merch-sidenav.js
  libs/deps/mas/merch-stock.js
  libs/features/mas/build.mjs
  libs/features/mas/dist/mas.js
  libs/features/mas/docs/styles.css
  libs/features/mas/src/constants.js
  libs/features/mas/src/global.css.js
  libs/features/mas/src/merch-card-collection-header.js
  libs/features/mas/src/merch-card-collection.js
  libs/features/mas/src/sidenav/merch-sidenav-list.js
  libs/features/mas/src/sidenav/merch-sidenav.js
  libs/features/mas/src/utils.js
  libs/features/mas/src/variants/catalog.css.js
  libs/features/mas/src/variants/plans.css.js
  libs/features/mas/src/variants/plans.js
  libs/features/mas/src/variants/variants.js
  libs/features/mas/test/merch-card-collection.test.html
  libs/features/mas/test/merch-card-collection.test.html.js
  test/blocks/merch-card-collection/merch-card-collection.test.js
  test/blocks/merch-card-collection/mocks/merch-card-collection.html
Labels: verified, commerce, Ready for Stage, plans

#4580 MWPW-176743 [MEP] loggedin tag does not work if user logs in and is taken directly back to a page
  libs/features/personalization/personalization.js
  libs/martech/martech.js
Labels: verified, Ready for Stage

#4579 MPWP-176498 - Media only brick
  libs/blocks/brick/brick.js
Labels: Ready for Stage

#4585 MWPW-176490 gnav console error is seen product pages in prod
  libs/blocks/global-navigation/global-navigation.js
Labels: verified, Ready for Stage

#4613 [Loc] | Stage Deployment | Eliminating custom merge option from regional editing
  libs/blocks/locui-create/input-urls/view.js
Labels: verified, trivial

#4545 [MWPW-175505] - Accordion image/video tablet/mobile fix
  libs/blocks/accordion/accordion.css
  libs/blocks/accordion/accordion.js
Labels: Ready for Stage

#4601 [MWPW-174201] - Hero marquee no min height desktop
  libs/blocks/hero-marquee/hero-marquee.css
Labels: Ready for Stage

#4602 MWPW-176962: Unit and plan type text stacked
  libs/deps/mas/commerce.js
  libs/deps/mas/merch-card-collection-header.js
  libs/deps/mas/merch-card-collection.js
  libs/deps/mas/merch-card.js
  libs/features/mas/dist/mas.js
  libs/features/mas/src/price/legal.js
  libs/features/mas/src/price/template.js
  libs/features/mas/src/variants/plans.css.js
  libs/features/mas/test/price/__snapshots__/legal.snapshots.js
  libs/features/mas/test/price/__snapshots__/template.snapshots.js
  libs/features/mas/test/price/legal.test.js
  test/blocks/merch/merch.test.js
Labels: verified, commerce, Ready for Stage, plans

#4607 MWPW-176429: adding perUnit to plans mapping
  libs/deps/mas/merch-card-collection-header.js
  libs/deps/mas/merch-card-collection.js
  libs/deps/mas/merch-card.js
  libs/features/mas/dist/mas.js
  libs/features/mas/src/variants/plans.js
Labels: verified, commerce, Ready for Stage, plans

#4610 MWPW-176866 v2 Placeholders within fragments are not resolved anymore
  libs/blocks/fragment/fragment.js
Labels: verified, Ready for Stage

#4627 MWPW-177011: only visible cards handle updates
  libs/deps/mas/merch-card.js
  libs/features/mas/dist/mas.js
  libs/features/mas/src/merch-card.js
Labels: verified, Ready for Stage

#4626 Improve share block accessibility
  libs/blocks/share/share.css
  libs/blocks/share/share.js
Labels: Ready for Stage

#4492 [MWPW-171875], [MWPW-171041] - Notification tab a11y issues, Modal escape
  libs/blocks/modal/modal.js
  libs/blocks/notification/notification.css
  libs/blocks/notification/notification.js
  libs/blocks/section-metadata/section-metadata.css
  libs/scripts/accessibility.js
  test/blocks/modals/modals.test.js
Labels: Ready for Stage

#4619 MWPW-176095: Analytics on Plans page
  libs/blocks/merch-card-collection-autoblock/merch-card-collection-autoblock.js
  libs/blocks/merch/autoblock.js
  test/blocks/merch-card-collection-autoblock/merch-card-collection-autoblock.test.js
  test/blocks/merch-card-collection-autoblock/mocks/fragment.json
  test/blocks/merch/autoblock.test.js
Labels: verified, commerce, Ready for Stage, plans

#4615 [MWPW-174911] - phone modal overflow fix
  libs/blocks/modal/modal.css
Labels: Ready for Stage
