Repository adobecom/milo, pull requests merged in 2025-06, with the labels that each got.

#4230 [MMM][MEP] "MMM data for last 7 days" should not appear in the MMM report
  libs/features/personalization/preview.js
Labels: verified, Ready for Stage

#4260 MWPW-174288 [MMM][MEP] Fix stying and DOM issue in new MMM report
  libs/blocks/mmm/mmm.js
Labels: verified, Ready for Stage

#4271 MWPW-174245: Add loc tests for CCD
  nala/features/mas/ccd/masccd.spec.js
  nala/features/mas/ccd/masccd.test.js
Labels: zero-impact, Ready for Stage

#4177 MWPW-170454 : Fixed visual list is not marked up as list and footer issue
  libs/blocks/global-navigation/utilities/menu/menu.js
Labels: verified, high priority, Ready for Stage

#4204 Mwpw 169219 a11y aside
  libs/blocks/aside/aside.css
  libs/blocks/aside/aside.js
Labels: high priority, Ready for Stage

#4254 [MWPW-170178] Table highlight a11y
  libs/blocks/table/table.css
  libs/blocks/table/table.js
Labels: high priority, Ready for Stage

#4256 [MWPW-171062] Allow decorative images through image links
  libs/utils/utils.js
Labels: high priority, Ready for Stage

#4262 [MWPW-174092] Authors cannot edit purpose of Play button
  libs/utils/image-video-link.js
Labels: verified, high priority, Ready for Stage

#3963 Fix(MWPW-171006): Removed pill and Split notification block flattening feature
  libs/blocks/section-metadata/section-metadata.css
Labels: verified, Ready for Stage

#4061 Gap is seen between promo banner and G-nav when page is scrolled fix
  libs/blocks/global-navigation/global-navigation.css
Labels: verified, Ready for Stage

#4277 MWPW-171542 | Hiding the hinting cards
  libs/mep/ace1052/carousel/carousel.css
  libs/mep/ace1052/carousel/carousel.js
Labels: zero-impact

#4255 Centralized DA importer hosted within milo
  .github/workflows/import/LOCAL_DEBUG_ENTRIES.js
  .github/workflows/import/constants.js
  .github/workflows/import/converters.js
  .github/workflows/import/daFetch.js
  .github/workflows/import/index.js
  .github/workflows/import/package-lock.json
  .github/workflows/import/package.json
  .github/workflows/import/poll-logs.js
  .github/workflows/track-bacom-publishes-for-da.yaml
Labels: zero-impact

#4280 Minor tweaks for mweb blocks
  libs/mep/ace1052/aside/aside.css
  libs/mep/ace1052/brick/brick.css
  libs/mep/ace1052/brick/brick.js
  libs/mep/ace1052/editorial-card/editorial-card.css
  libs/mep/ace1052/hero-marquee/hero-marquee.css
  libs/mep/ace1052/text/text.css
Labels: zero-impact

#4258 [3in1] MWPW-173962
  libs/blocks/merch/merch.js
  libs/deps/mas/commerce.js
  libs/deps/mas/merch-card-collection.js
  libs/features/mas/dist/mas.js
  libs/features/mas/src/buildCheckoutUrl.js
  libs/features/mas/src/checkout-mixin.js
  libs/features/mas/src/checkout.js
  libs/features/mas/test/build-checkout-url.test.js
  libs/features/mas/test/checkout-button.test.js
  libs/features/mas/test/checkout-link.test.js
  libs/features/mas/test/merch-addon.test.html
  nala/blocks/merch/three-in-one.page.js
  nala/blocks/merch/three-in-one.spec.js
  nala/blocks/merch/three-in-one.test.js
  test/blocks/media/media.test.js
  test/blocks/merch/merch.test.js
Labels: verified, commerce, high priority, Ready for Stage

#4203 Accessibility carousel
  libs/blocks/carousel/carousel.css
  libs/blocks/carousel/carousel.js
  nala/blocks/carousel/carousel.page.js
  nala/blocks/carousel/carousel.test.js
Labels: high priority, Ready for Stage

#4276 MWPW-174220 | Accessibility | Changing table heading roles to not have them treated as text.
  libs/blocks/table/table.js
Labels: verified, high priority, Ready for Stage

#4164 MWPW-173109, 173937, 174288 [MEP][MMM] Batch
  libs/blocks/mmm/mmm.js
  libs/features/personalization/personalization.js
  libs/features/personalization/preview.js
  libs/utils/utils.js
  test/features/personalization/personalization.test.js
  test/utils/utils-mep.test.js
Labels: verified, Ready for Stage

#4261 MWPW-173966: Hide jarvis popup behind modal
  libs/blocks/modal/modal.css
Labels: Ready for Stage

#4287 Carousel hinting card height
  libs/mep/ace1052/carousel/carousel.css
  libs/mep/ace1052/carousel/carousel.js
  libs/mep/ace1052/editorial-card/editorial-card.css
Labels: zero-impact

#4201 [NALA][MWPW-173773]Update the fleaky tests and aem.live url
  nala/features/personalization/all-elements.test.js
  nala/features/personalization/mep-actions.test.js
  nala/features/personalization/mep-order.test.js
  nala/features/personalization/nested-placeholders.test.js
  nala/features/personalization/personalization.test.js
  nala/features/personalization/ul-ol-li.test.js
  nala/utils/pr.run.sh
Labels: zero-impact, Ready for Stage

#4303 Revert "[MWPW-173717] Hyphenate large headings on mobile"
  libs/styles/styles.css
Labels: Ready for Stage

#4315 MWPW-174028 Invalid date is formatted as NaN
  libs/blocks/locui-create/input-urls/index.js
Labels: trivial

#4095 subheader referred as a link
  libs/blocks/global-navigation/global-navigation.css
  libs/blocks/global-navigation/utilities/keyboard/utils.js
  libs/blocks/global-navigation/utilities/menu/menu.js
  libs/blocks/global-navigation/utilities/utilities.js
Labels: verified, Ready for Stage

#4170 MWPW-173608 [M@S] Mnemonics filed disappear from card preview when …
  libs/deps/mas/merch-card.js
  libs/features/mas/dist/mas.js
  libs/features/mas/src/hydrate.js
  libs/features/mas/src/variants/plans.js
Labels: verified, Ready for Stage

#4214 Mwpw 173540 preflight preview publish
  libs/blocks/preflight/panels/general.js
  libs/blocks/preflight/preflight.css
Labels: Ready for Stage

#4245 [MWPW-173984] - Added fix for dark theme for promo
  libs/blocks/global-navigation/dark-nav.css
Labels: verified, Ready for Stage

#4263 MWPW-174127 | Accessibility | Set heading role for half height card
  libs/blocks/card/card.js
Labels: verified, Ready for Stage

#4270 [MWPW-171655] - table icon missalignement fix
  libs/blocks/table/table.css
Labels: Ready for Stage

#4285 [MWPW-174313] - Added missing parent role for localnav A11Y
  libs/blocks/global-navigation/global-navigation.js
  libs/blocks/global-navigation/utilities/utilities.js
Labels: verified, Ready for Stage

#4307 MWPW-170541: Add support for rtl
  libs/blocks/action-scroller/action-scroller.js
Labels: Ready for Stage

#4329 editorial css and carousel width changes
  libs/mep/ace1052/carousel/carousel.css
  libs/mep/ace1052/editorial-card/editorial-card.css
  libs/mep/ace1052/editorial-card/editorial-card.js
Labels: zero-impact

#4337 Bring the latest block changes into the mweb feature branch
  libs/mep/ace1052/aside/aside.css
  libs/mep/ace1052/aside/aside.js
  libs/mep/ace1052/carousel/carousel.css
  libs/mep/ace1052/carousel/carousel.js
  libs/mep/ace1052/notification/notification.css
  libs/mep/ace1052/section-metadata/section-metadata.css
  libs/mep/ace1052/tabs/tabs.js
  libs/mep/ace1052/text/text.css
Labels: zero-impact

#4301 [MWPW-173100][NALA] Automation test script for Timeline block
  nala/blocks/timeline/timeline.page.js
  nala/blocks/timeline/timeline.spec.js
  nala/blocks/timeline/timeline.test.js
Labels: zero-impact, Ready for Stage

#4333 Fixing replace check for Gnav test url
  .github/workflows/dynamic-pr-template.yml
Labels: zero-impact, Ready for Stage

#4109 [MWPW-173161] - Refactor preflight to export checks
  libs/blocks/preflight/checks/assets.js
  libs/blocks/preflight/checks/constants.js
  libs/blocks/preflight/checks/performance.js
  libs/blocks/preflight/checks/preflightApi.js
  libs/blocks/preflight/checks/seo.js
  libs/blocks/preflight/panels/accessibility.js
  libs/blocks/preflight/panels/assets.js
  libs/blocks/preflight/panels/performance.js
  libs/blocks/preflight/panels/seo.js
  test/blocks/preflight/checks/assets.test.js
  test/blocks/preflight/checks/performance.test.js
  test/blocks/preflight/checks/seo.test.js
  test/blocks/preflight/panels/assets.test.js
  test/blocks/preflight/panels/performance/performance.test.js
Labels: Ready for Stage

#4274 Exposing close gnav function for clients
  libs/blocks/global-navigation/global-navigation.js
  libs/navigation/navigation.js
Labels: verified, Ready for Stage

#4346 [Stage][Loc] MWPW-174737 Skip validation for "dueDate" during rollout workflow
  libs/blocks/locui-create/input-urls/index.js
Labels: trivial

#4350 [Locv3][Stage] MWPW-173721 A11Y Translation/Rollout selection pill
  libs/blocks/locui-create/input-urls/view.js
Labels: trivial

#4295 MWPW-173830: Add tooltip to notification pill
  libs/blocks/notification/notification.css
  libs/blocks/notification/notification.js
Labels: Ready for Stage

#4353 MWPW-174782 and MWPW-174694
  libs/mep/ace1052/carousel/carousel.css
  libs/mep/ace1052/tabs/tabs.css
Labels: zero-impact

#4272 Emea1443 mweb
  libs/mep/emea1443/accordion/accordion.css
  libs/mep/emea1443/accordion/accordion.js
  libs/mep/emea1443/action-item/action-item.css
  libs/mep/emea1443/action-item/action-item.js
  libs/mep/emea1443/card-horizontal/card-horizontal.css
  libs/mep/emea1443/card-horizontal/card-horizontal.js
  libs/mep/emea1443/carousel/carousel.css
  libs/mep/emea1443/carousel/carousel.js
  libs/mep/emea1443/carousel/img/arrow.svg
  libs/mep/emea1443/carousel/img/close.svg
  libs/mep/emea1443/carousel/img/expand.svg
  libs/mep/emea1443/collapsible-card/collapsible-card.css
  libs/mep/emea1443/collapsible-card/collapsible-card.js
  libs/mep/emea1443/collapsible-card/img/collapsible-icon.js
  libs/mep/emea1443/content-toggle/content-toggle.css
  libs/mep/emea1443/content-toggle/content-toggle.js
  libs/mep/emea1443/express-libs/relevant.js
  libs/mep/emea1443/express-libs/utils.js
  libs/mep/emea1443/hero-marquee/hero-marquee.css
  libs/mep/emea1443/hero-marquee/hero-marquee.js
  libs/mep/emea1443/icon-block/icon-block.css
  libs/mep/emea1443/icon-block/icon-block.js
  libs/mep/emea1443/merch-card/img/checkmark-white-small.svg
  libs/mep/emea1443/merch-card/img/chevron.js
  libs/mep/emea1443/merch-card/img/collapsible-icon.js
  libs/mep/emea1443/merch-card/img/ellipsis.svg
  libs/mep/emea1443/merch-card/img/secure-transaction.svg
  libs/mep/emea1443/merch-card/merch-card.css
  libs/mep/emea1443/merch-card/merch-card.js
  libs/mep/emea1443/merch-card/merch-offer-select.js
  libs/mep/emea1443/mweb-floating-button/mweb-floating-button.css
  libs/mep/emea1443/mweb-floating-button/mweb-floating-button.js
  libs/mep/emea1443/section-metadata/README.md
  libs/mep/emea1443/section-metadata/section-metadata.css
  libs/mep/emea1443/section-metadata/section-metadata.js
  libs/mep/emea1443/section-metadata/sticky-section.js
  libs/mep/emea1443/text/link-farms.css
  libs/mep/emea1443/text/text.css
  libs/mep/emea1443/text/text.js
Labels: verified, zero-impact, Ready for Stage

#4284 MWPW-167720 Show Gnav Earlier
  libs/blocks/global-footer/global-footer.js
  libs/blocks/global-navigation/global-navigation.css
  libs/blocks/global-navigation/global-navigation.js
  libs/blocks/global-navigation/utilities/menu/menu.js
  libs/blocks/global-navigation/utilities/utilities.js
  libs/blocks/merch/merch.js
  libs/utils/utils.js
  test/blocks/global-navigation/gnav-cross-cloud.test.js
  test/blocks/global-navigation/utilities/utilities.test.js
Labels: verified, high priority, Ready for Stage

#4290 MWPW-174265 Add url mapping to graybox envs
  libs/blocks/graybox/graybox.css
  libs/blocks/graybox/graybox.js
  test/blocks/graybox/graybox.test.js
Labels: verified, Ready for Stage

#4348 [MWPW-169805]Language selector block for language based sites
  libs/blocks/global-navigation/utilities/keyboard/popup.js
  libs/blocks/global-navigation/utilities/keyboard/utils.js
  libs/blocks/language-selector/language-selector.css
  libs/blocks/language-selector/language-selector.js
  libs/utils/utils.js
  test/blocks/language-selector/language-selector.test.js
  test/blocks/language-selector/mocks/languages.html
Labels: verified, high priority, Ready for Stage

#4384 [MWPW-174951] Allow centered text block link for mweb
  libs/mep/ace1052/text/text.css
Labels: zero-impact

#4383 [MWPW-174950] Update Brick block to body-s
  libs/mep/ace1052/brick/brick.js
Labels: zero-impact

#4368 [Fire-Drill] This will have to get reverted by ryan
  test/blocks/fire-drill-ryan/README.md
Labels: zero-impact, Ready for Stage

#4361 MWPW-174845 [MEP][MMM] 3 tiny fixes
  libs/blocks/mmm/mmm.js
  libs/features/personalization/personalization.js
  libs/utils/utils.js
Labels: verified, Ready for Stage

#4395 Merge ZeroImpact PRs before checking the mergeLimit
  .github/workflows/merge-to-stage.js
Labels: zero-impact, Ready for Stage

#4247 MWPW-172123 card titles must use H3 tag, for a11y
  libs/deps/mas/merch-card.js
  libs/features/mas/dist/mas.js
  libs/features/mas/src/variants/plans.js
  nala/features/mas/acom/masacom.page.js
Labels: verified, Ready for Stage

#4388 Adding mutation observer to support viewport change
  libs/blocks/global-navigation/global-navigation.js
Labels: verified, Ready for Stage

#4330 MWPW-168314 Localize Marketo Multi-Step
  libs/blocks/marketo/marketo-multi.js
  test/blocks/marketo/marketo-multi.test.js
Labels: verified, Ready for Stage

#4379 MWPW-174735 [Milo][Analytics] Tabs do not have a daa-lh attribute on the block
  libs/martech/attributes.js
Labels: verified, Ready for Stage

#4169 [MWPW-171291][NALA] Automation test script for Brick block
  nala/blocks/brick/brick.page.js
  nala/blocks/brick/brick.spec.js
  nala/blocks/brick/brick.test.js
Labels: zero-impact, Ready for Stage

#4340 Lnav title should be immediate child either anchor link or button
  libs/blocks/global-navigation/global-navigation.js
Labels: verified, Ready for Stage

#4382 MWPW-174786: remove local-nav class from empty gnav
  libs/blocks/global-navigation/global-navigation.js
Labels: verified, Ready for Stage

#4026 MWPW-170612 update description for stage to main
  .github/workflows/helpers.js
  .github/workflows/merge-to-main.yaml
  .github/workflows/merge-to-stage.js
  .github/workflows/pr-manual-merge.js
  .github/workflows/pr-manual-merge.yaml
  .github/workflows/pr-merge-notification.js
Labels: zero-impact, Ready for Stage

#4411 updated ZERO_IMPACT_PREFIX in helpers.js
  .github/workflows/helpers.js
Labels: zero-impact

#4412 Correct counting of zero impact PRs
  .github/workflows/helpers.js
  .github/workflows/merge-to-stage.js
  .github/workflows/pr-manual-merge.js
Labels: zero-impact

#4405 MWPW-174568: [Preflight] Metadata on hover overlaps with navigation bar
  libs/blocks/preflight/preflight.css
Labels: Ready for Stage

#4391 MWPW-174906: adds playVideo string to config.collection.i10n
  libs/blocks/caas/utils.js
  test/blocks/caas-config/expectedConfigs/defaultConfig.js
  test/blocks/caas/utils.test.js
Labels: caas-configurator, CaaS, Ready for Stage

#4377 ServiceNow CMR Fixes - [MWPW=173724]
  .github/workflows/servicenow.py
  .github/workflows/servicenow.yaml
  .github/workflows/snow-cr-notification.js
  .github/workflows/snow-pr-comment.js
Labels: trivial, zero-impact, Ready for Stage

#4375 [MWPW-173618] - Media checklist link fix
  libs/blocks/media/media.js
Labels: Ready for Stage

#4429 [MWPW-175210] - Added fix for close icon positon for rtl
  libs/blocks/global-navigation/global-navigation.css
Labels: verified, Ready for Stage

#4136 MWPW-172513: Columns block to adapt merch-cards on plans page
  libs/deps/mas/merch-card.js
  libs/features/mas/dist/mas.js
  libs/features/mas/src/variants/plans.css.js
  libs/features/mas/src/variants/plans.js
Labels: verified, commerce, Ready for Stage

#4351 MWPW-173897: add jarvis footer link feature
  libs/blocks/global-footer/global-footer.js
  libs/features/jarvis-chat.js
  test/blocks/global-footer/global-footer.test.js
  test/blocks/global-footer/mocks/fetched-footer.js
Labels: verified, Ready for Stage

#4398 [MWPW-174861] - table heading content height increase fix
  libs/blocks/table/table.js
Labels: Ready for Stage

#4293 DOTCOM-145774 Default values for commerce flags
  libs/blocks/ost/ost.js
  libs/deps/mas/commerce.js
  libs/features/mas/dist/mas.js
  libs/features/mas/docs/inline-price.html
  libs/features/mas/docs/src/inline-price.md
  libs/features/mas/price-literals.json
  libs/features/mas/src/commerce.js
  libs/features/mas/src/constants.js
  libs/features/mas/src/defaults.js
  libs/features/mas/src/inline-price.js
  libs/features/mas/src/settings.js
  libs/features/mas/test/mas-commerce-service.test.js
  libs/features/mas/test/mocks/offers.json
  libs/features/mas/test/price.test.js
  libs/features/mas/test/price/__snapshots__/price.snapshots.js
  libs/features/mas/test/settings.test.js
  nala/blocks/merch/default-flags.page.js
  nala/blocks/merch/default-flags.spec.js
  nala/blocks/merch/default-flags.test.js
Labels: verified, commerce, Ready for Stage

#4390 [MWPW-174690] Do not see the block functionality working when the sticky cta is present
  libs/mep/ace1052/notification/notification.css
  libs/mep/ace1052/section-metadata/section-metadata.css
Labels: zero-impact, Ready for Stage

#4442 Ps Mweb Journey | Carousel swiping
  libs/mep/ace1052/carousel/carousel.js
Labels: zero-impact, Ready for Stage

#4240 MWPW-172361: Having mas tooltip works as milo tooltip does.
  libs/deps/mas/merch-card-collection.js
  libs/deps/mas/merch-card.js
  libs/deps/mas/merch-stock.js
  libs/features/mas/dist/mas.js
  libs/features/mas/src/global.css.js
  libs/features/mas/src/variants/plans.css.js
  libs/features/mas/src/variants/plans.js
Labels: verified, commerce, Ready for Stage

#4268 MWPW-174157: [MEP][MILO] Add alloy event handling to links and ability in MEP to more easily add that data to a link
  libs/features/personalization/personalization.js
  libs/martech/alloy-links.js
  libs/utils/utils.js
  test/utils/mocks/body-marquee-alloy-cta.html
  test/utils/utils.test.js
Labels: verified, Ready for Stage

#4425 MWPW-174333: Cover Plans Page with Nala tests
  nala/features/mas/acom/plans/plans.page.js
  nala/features/mas/acom/plans/plans.spec.js
  nala/features/mas/acom/plans/plans.test.js
  nala/features/mas/acom/plans/plansdocs.spec.js
  nala/features/mas/acom/plans/plansdocs.test.js
Labels: zero-impact, Ready for Stage

#4352 MWPW-173962: refactor&simplify
  libs/blocks/merch/merch.js
  libs/blocks/ost/ost.js
  libs/deps/mas/commerce.js
  libs/deps/mas/merch-card-collection.js
  libs/deps/mas/merch-card.js
  libs/deps/mas/merch-offer-select.js
  libs/deps/mas/merch-quantity-select.js
  libs/deps/mas/merch-sidenav.js
  libs/deps/mas/merch-stock.js
  libs/features/mas/dist/mas.js
  libs/features/mas/package.json
  libs/features/mas/src/buildCheckoutUrl.js
  libs/features/mas/src/checkout.js
  libs/features/mas/src/constants.js
  libs/features/mas/src/defaults.js
  libs/features/mas/src/settings.js
  libs/features/mas/test/build-checkout-url.test.js
  libs/features/mas/test/checkout-button.test.js
  libs/features/mas/test/checkout-link.test.js
  libs/features/mas/test/checkout.test.js
  libs/features/mas/test/hydrate.test.js
  libs/features/mas/test/mas-commerce-service.test.js
  nala/blocks/merch/three-in-one.spec.js
  nala/blocks/merch/three-in-one.test.js
  test/blocks/merch/merch.test.js
  test/blocks/ost/ost.test.html.js
Labels: verified, commerce, Ready for Stage

#4417 MWPW-74582: add guardrails to prevent empty primaryCtas from being sent
  tools/send-to-caas/send-utils.js
Labels: CaaS, Ready for Stage

#4438 MWPW-174987: Change DOM order of elements based on viewport
  libs/blocks/hero-marquee/hero-marquee.css
  libs/blocks/hero-marquee/hero-marquee.js
  test/blocks/hero-marquee/hero-marquee.test.js
  test/blocks/hero-marquee/mocks/body.html
Labels: high priority, Ready for Stage

#4389 [MWPW-174860] - table mobile expanding fix, highlight column not in mobile filter fix
  libs/blocks/table/table.js
Labels: Ready for Stage

#4456 MWPW-173561: enable landscape draft for 3in1 modals
  libs/deps/mas/commerce.js
  libs/deps/mas/merch-card-collection.js
  libs/features/mas/dist/mas.js
  libs/features/mas/src/buildCheckoutUrl.js
  libs/features/mas/test/build-checkout-url.test.js
Labels: verified, Ready for Stage

#4445 Fix for Expand/collapse state of appswitcher
  libs/blocks/global-navigation/utilities/utilities.js
Labels: verified, Ready for Stage

#4460 Enable auto importer from express-milo to da-express-milo
  .github/workflows/track-express-publishes-for-da.yaml
Labels: zero-impact

#4448 Safeguard aria-label check to avoid JS errors
  libs/utils/utils.js
Labels: Ready for Stage

#4461 [MWPW-175255] Actionless action item a11y
  libs/blocks/action-scroller/action-scroller.js
Labels: Ready for Stage

#4453 MWPW-175427: mini-compare-chart bullet-list collapse icon fix
  libs/blocks/merch-card/merch-card.js
Labels: verified, Ready for Stage

#4463 MWPW-175550 [MMM][MEP] Updates to metada-optimization json does not always reflect in MMM
  libs/blocks/mmm/mmm.js
Labels: verified, Ready for Stage

#4470 [MWPW-173103][NALA] Automation test script for Mnemonic List
  nala/blocks/mnemonic/mnemonic.page.js
  nala/blocks/mnemonic/mnemonic.spec.js
  nala/blocks/mnemonic/mnemonic.test.js
Labels: zero-impact, Ready for Stage

#4482 Update env da apps dev
  tools/da-apps/dist/assets/index.js
Labels: trivial

#4475 Mwpw 174987 hero marquee order
  libs/blocks/hero-marquee/hero-marquee.css
  libs/blocks/hero-marquee/hero-marquee.js
  test/blocks/hero-marquee/hero-marquee.test.js
  test/blocks/hero-marquee/mocks/body.html
  test/blocks/hero-marquee/mocks/no-order-marquee.html
  test/blocks/hero-marquee/mocks/order-marquee.html
Labels: high priority, Ready for Stage

#4487 MWPW-175712: Prevents duplicate three-in-one
  libs/blocks/merch/merch.js
Labels: high-impact, verified, commerce

#4491 [DA & Loc] Stage deployment (30 June)
  libs/blocks/locui-create/input-locale/index.js
  libs/blocks/locui-create/input-locale/view.js
  libs/blocks/locui-create/utils/utils.js
  tools/da-apps/dist/assets/index.js
  tools/da-apps/dist/assets/vendor.js
Labels: trivial
