Repository adobecom/milo, pull requests merged in 2025-04, with the labels that each got.

#3808 MWPW-169089 [Analytics] Add the attribute daa-state=true to tab buttons.
  libs/blocks/tabs/tabs.js
  test/blocks/tabs/tabs.test.js
Labels: verified, Ready for Stage

#3832 MWPW-169943 [MEP] add ability to use placeholders in updateAttribute
  libs/features/personalization/personalization.js
  test/features/personalization/actions.test.js
  test/features/personalization/mocks/actions/manifestUpdateAttribute.json
  test/features/personalization/mocks/personalization.html
Labels: verified, Ready for Stage

#3837 MWPW-169423 [MEP] MEP button not reporting spoofed Target value
  libs/features/personalization/preview.js
Labels: verified, Ready for Stage

#3841 MWPW-169997: [3-in1] rtc=t param added to the commerce link
  libs/blocks/merch/three-in-one.js
  libs/deps/mas/commerce.js
  libs/deps/mas/mas.js
  libs/deps/mas/merch-card-collection.js
  libs/deps/mas/merch-card.js
  libs/deps/mas/merch-icon.js
  libs/deps/mas/merch-mnemonic-list.js
  libs/deps/mas/merch-offer-select.js
  libs/deps/mas/merch-secure-transaction.js
  libs/deps/mas/merch-sidenav.js
  libs/deps/mas/merch-stock.js
  libs/deps/mas/merch-subscription-panel.js
  libs/deps/mas/merch-twp-d2p.js
  libs/deps/mas/merch-whats-included.js
  libs/features/mas/dist/mas.js
  libs/features/mas/src/checkout-mixin.js
Labels: verified, Ready for Stage

#3843 MWPW-169160 [MEP] MEP button - made sure that non-target manifest paths match the current domain
  libs/features/personalization/personalization.js
  test/features/personalization/cleanAndSortManifestList.test.js
  test/features/personalization/mocks/manifestLists/two-manifests-one-from-target.json
  test/utils/utils.test.js
Labels: verified, Ready for Stage

#3853 MWPW-168300: [3-in-1] Add deep linking to tabs in 3-in-1 modal
  libs/deps/mas/commerce.js
  libs/deps/mas/mas.js
  libs/features/mas/dist/mas.js
  libs/features/mas/src/buildCheckoutUrl.js
  libs/features/mas/src/checkout-mixin.js
  libs/features/mas/src/checkout.js
  libs/features/mas/test/build-checkout-url.test.js
  libs/features/mas/test/checkout-link.test.js
  nala/blocks/merch/three-in-one.page.js
  nala/blocks/merch/three-in-one.spec.js
  nala/blocks/merch/three-in-one.test.js
Labels: verified, Ready for Stage

#3834 Graybox Promote - Helix 5 upgrade
  libs/blocks/graybox-promote/components/graybox-promote-lit.js
  tools/sidekick/config.json
Labels: do not merge

#3840 MWPW-169845: Fix action scroller navigation when in tab
  libs/blocks/action-scroller/action-scroller.js
  test/blocks/action-scroller/action-scroller.test.js
  test/blocks/action-scroller/mocks/body.html
Labels: Ready for Stage

#3863 Upgrading package version for bundled gnav to 0.0.7
  libs/navigation/package.json
Labels: trivial, Ready for Stage

#3850 MWPW-169814 | [MWeb] Split variant in notification block
  libs/blocks/notification/notification.css
  libs/blocks/notification/notification.js
  libs/blocks/section-metadata/section-metadata.css
  test/blocks/notification/mocks/body.html
  test/blocks/notification/notification.test.js
Labels: verified, Ready for Stage

#3786 MWPW-165461: Merch card collection autoblock
  libs/blocks/mas-autoblock/mas-autoblock.js
  libs/blocks/merch-card-autoblock/merch-card-autoblock.js
  libs/blocks/merch-card-collection-autoblock/merch-card-collection-autoblock.js
  libs/deps/mas/commerce.js
  libs/deps/mas/mas.js
  libs/deps/mas/merch-card-collection.js
  libs/deps/mas/merch-card.js
  libs/deps/mas/merch-icon.js
  libs/deps/mas/merch-mnemonic-list.js
  libs/deps/mas/merch-offer-select.js
  libs/deps/mas/merch-secure-transaction.js
  libs/deps/mas/merch-sidenav.js
  libs/deps/mas/merch-stock.js
  libs/deps/mas/merch-subscription-panel.js
  libs/deps/mas/merch-twp-d2p.js
  libs/deps/mas/merch-whats-included.js
  libs/features/mas/build.mjs
  libs/features/mas/dist/mas.js
  libs/features/mas/docs/common.js
  libs/features/mas/docs/plans.html
  libs/features/mas/docs/src/plans.md
  libs/features/mas/docs/styles.css
  libs/features/mas/package.json
  libs/features/mas/src/aem-fragment.js
  libs/features/mas/src/merch-card-collection.css.js
  libs/features/mas/src/merch-card-collection.js
  libs/features/mas/src/sidenav/merch-sidenav-list.js
  libs/features/mas/src/variants/plans.css.js
  libs/features/mas/test/merch-card-collection.test.html
  libs/features/mas/test/merch-card-collection.test.html.js
  libs/features/mas/test/mocks/sites/fragments/fragment-individual-plans-collection.json
  libs/utils/utils.js
  test/blocks/mas-autoblock/mas-autoblock.test.js
  test/blocks/merch-card-autoblock/merch-card-autoblock.test.js
  test/blocks/merch-card-autoblock/mocks/artifact.json
  test/blocks/merch-card-autoblock/mocks/fragment.json
  test/blocks/merch-card-collection-autoblock/merch-card-collection-autoblock.test.js
  test/blocks/merch-card-collection-autoblock/mocks/fragment.json
Labels: verified, commerce, high priority, Ready for Stage

#3845 MWPW-170007 [Footer] Fix horizontal scroll
  libs/blocks/global-footer/global-footer.css
Labels: verified, Ready for Stage

#3876 MWPW-170340 Table Block Expand / Collapse Functionality Broken on Mobiles
  libs/blocks/table/table.js
Labels: verified, Ready for Stage

#3704 MWPW-167207: Plans card pixel perfect
  libs/deps/mas/mas.js
  libs/deps/mas/merch-card.js
  libs/features/mas/dist/mas.js
  libs/features/mas/src/global.css.js
  libs/features/mas/src/variants/plans.css.js
  libs/features/mas/src/variants/plans.js
  nala/features/mas/acom/masacom.page.js
  nala/features/mas/acom/masacom.spec.js
  nala/features/mas/acom/masacom.test.js
Labels: verified, commerce, Ready for Stage

#3855 MWPW-170254 Placeholder are not getting replaced for aria-label
  libs/utils/utils.js
Labels: verified, Ready for Stage

#3896 MWPW-169814 | Change box shadow and button to close for split notification
  libs/blocks/notification/notification.css
  libs/blocks/notification/notification.js
  test/blocks/notification/mocks/body.html
  test/blocks/notification/notification.test.js
Labels: verified, Ready for Stage

#3805 MWPW-164491 [Plans] Wide merch card
  libs/blocks/merch-card-autoblock/merch-card-autoblock.js
  libs/deps/mas/mas.js
  libs/deps/mas/merch-card.js
  libs/deps/mas/merch-mnemonic-list.js
  libs/deps/mas/merch-quantity-select.js
  libs/deps/mas/merch-sidenav.js
  libs/deps/mas/merch-whats-included.js
  libs/features/mas/dist/mas.js
  libs/features/mas/src/global.css.js
  libs/features/mas/src/hydrate.js
  libs/features/mas/src/mas.js
  libs/features/mas/src/merch-card.css.js
  libs/features/mas/src/merch-card.js
  libs/features/mas/src/merch-mnemonic-list.js
  libs/features/mas/src/merch-whats-included.js
  libs/features/mas/src/utils.js
  libs/features/mas/src/variants/plans.css.js
  libs/features/mas/src/variants/plans.js
Labels: verified, Ready for Stage

#3913 [DA] Refresh dev build with Bulk Content Update
  tools/da-apps/auth.js
  tools/da-apps/dist/assets/index.css
  tools/da-apps/dist/assets/index.js
  tools/da-apps/dist/assets/vendor.js
Labels: trivial

#3814 MWPW-165805 [Mobile GNAV] | Close LNAV on Scroll
  libs/blocks/global-navigation/global-navigation.css
  libs/blocks/global-navigation/global-navigation.js
  libs/blocks/global-navigation/utilities/utilities.js
Labels: verified, Ready for Stage

#3905 Initial checkin. Good state.
  libs/features/personalization/preview.css
  libs/features/personalization/preview.js
Labels: verified, Ready for Stage

#3838 MWPW-163828-Slack-Notification-On-Merge
  .github/workflows/merge-to-main.js
  .github/workflows/merge-to-stage.js
  .github/workflows/pr-merge-notification.js
  .github/workflows/pr-merge-notification.yaml
Labels: zero-impact, Ready for Stage

#3918 Fix the pr merge notification workflow
  .github/workflows/pr-merge-notification.yaml
Labels: zero-impact

#3922 Use pull_request_target to properly access secrets
  .github/workflows/pr-merge-notification.yaml
Labels: zero-impact

#3901 Adding dynamic PR template for Gnav components
  .github/workflows/dynamic-pr-template.yml
Labels: verified, zero-impact, Ready for Stage

#3900 [Tabs] Center/Right alignment changes lockup alignment
  libs/styles/iconography.css
Labels: bug, Ready for Stage

#3890 MWPW-169300 [Plans] Custom colors on Plans card badges
  libs/blocks/merch-card-collection-autoblock/merch-card-collection-autoblock.js
  libs/deps/mas/mas.js
  libs/deps/mas/merch-card.js
  libs/features/mas/dist/mas.js
  libs/features/mas/src/global.css.js
  libs/features/mas/src/hydrate.js
  libs/features/mas/src/mas.js
  libs/features/mas/src/merch-badge.js
  libs/features/mas/src/merch-card.js
  libs/features/mas/src/variants/plans.js
  nala/features/mas/acom/masacom.page.js
Labels: verified, Ready for Stage

#3923 [DA] Refresh dev build with save file suffix fix
  tools/da-apps/dist/assets/index.js
Labels: trivial

#3929 [DA] Refresh dev build with download original excel in BCU project details
  tools/da-apps/dist/assets/index.js
Labels: trivial

#3930 [DA] Refresh dev build with updated analytics suite id
  tools/da-apps/dist/assets/index.js
  tools/da-apps/dist/assets/vendor.js
Labels: trivial

#3925 Gnav dynamic pr updating replace regex
  .github/workflows/dynamic-pr-template.yml
Labels: verified, zero-impact, Ready for Stage

#3833 [MWPW-169532] - iframe title added
  libs/blocks/adobetv/adobetv.js
  libs/blocks/iframe/iframe.js
  libs/blocks/vimeo/vimeo.js
  libs/blocks/youtube/youtube.js
  nala/blocks/video/video.spec.js
  nala/blocks/video/video.test.js
Labels: Ready for Stage

#3875 [MWPW-169395] - Table aria labels missing
  libs/blocks/table/table.css
  libs/blocks/table/table.js
  test/blocks/table/table.test.js
Labels: high-impact, Ready for Stage

#3882 MWPW-170382 [CME M7] Add lang param to M7 links for exception geos
  libs/blocks/m7/m7.js
  libs/blocks/merch/merch.js
  libs/utils/utils.js
  test/blocks/m7/m7.test.js
Labels: verified, Ready for Stage

#3906 MWPW-170567: update send to caas to support language-first localization
  libs/blocks/caas/utils.js
  tools/send-to-caas/send-utils.js
Labels: new-feature, CaaS, Ready for Stage

#3931 Fix the gradient feds navLink on dark mode
  libs/blocks/global-navigation/dark-nav.css
Labels: verified, Ready for Stage

#3948 [DA] Refresh dev build with some features and minor bug fixes
  tools/da-apps/dist/assets/index.css
  tools/da-apps/dist/assets/index.js
  tools/da-apps/dist/assets/vendor.js
Labels: trivial

#3949 [DA] Refresh dev build with BCU Screen fixes, Copy BulkOps, et al.
  tools/da-apps/dist/assets/index.js
  tools/da-apps/dist/assets/vendor.js
Labels: trivial

#3939 MWPW-170088 Graybox MEP support
  libs/blocks/graybox/graybox.js
Labels: verified, Ready for Stage

#3937 Quiz step indicator enhancement
  libs/blocks/quiz/quiz.css
  libs/blocks/quiz/quiz.js
  libs/blocks/quiz/stepIndicator.js
Labels: verified, uar, Ready for Stage

#3946 Color mismatch in the Gnav in dark mode on mobile device
  libs/blocks/global-navigation/dark-nav.css
Labels: verified, Ready for Stage

#3953 [DA] Refresh dev build with BCU fixes, Dialogs, et al.
  tools/da-apps/dist/assets/index.js
Labels: trivial

#3894 [NALA][MWPW-170695] Add automation tests for Notification Block
  nala/blocks/notification/notification.page.js
  nala/blocks/notification/notification.spec.js
  nala/blocks/notification/notification.test.js
Labels: zero-impact, Ready for Stage

#3910 Handle gnav promo bar overflowing gracefully
  libs/blocks/global-navigation/global-navigation.js
  libs/blocks/global-navigation/utilities/utilities.js
Labels: verified, Ready for Stage

#3951 MWPW-169933 catch case for no region match / fix nala
  libs/utils/utils.js
Labels: Ready for Stage

#3960 [DA] Refresh dev build with label changes and BCU Create Page fixes
  tools/da-apps/dist/assets/index.js
Labels: trivial

#3962 [DA] Refresh dev build with Versioning Changes
  tools/da-apps/dist/assets/index.js
  tools/da-apps/dist/assets/vendor.js
Labels: trivial

#3965 [DA] Refresh dev build with BulkOps Copy and Fragment table fixes
  tools/da-apps/dist/assets/index.js
Labels: trivial

#3970 [DA] Refresh dev build with copy move column swap fix
  tools/da-apps/dist/assets/index.js
Labels: trivial

#3941 MWPW-170620: [3-in-1][Milo] 3-in-1 revised
  libs/blocks/merch/merch.js
  libs/blocks/merch/three-in-one.js
  libs/deps/mas/commerce.js
  libs/deps/mas/mas.js
  libs/deps/mas/merch-card-collection.js
  libs/deps/mas/merch-card.js
  libs/deps/mas/merch-icon.js
  libs/deps/mas/merch-mnemonic-list.js
  libs/deps/mas/merch-offer-select.js
  libs/deps/mas/merch-secure-transaction.js
  libs/deps/mas/merch-sidenav.js
  libs/deps/mas/merch-stock.js
  libs/deps/mas/merch-subscription-panel.js
  libs/deps/mas/merch-twp-d2p.js
  libs/deps/mas/merch-whats-included.js
  libs/features/mas/dist/mas.js
  libs/features/mas/src/buildCheckoutUrl.js
  libs/features/mas/src/checkout-mixin.js
  libs/features/mas/src/checkout.js
  libs/features/mas/test/build-checkout-url.test.js
  libs/features/mas/test/checkout-link.test.js
  nala/blocks/merch/three-in-one.page.js
  nala/blocks/merch/three-in-one.spec.js
  nala/blocks/merch/three-in-one.test.js
  test/blocks/merch/merch.test.js
  test/blocks/merch/mocks/placeholders.json
  test/blocks/merch/mocks/threeInOne.html
  test/blocks/merch/three-in-one.test.js
Labels: verified, commerce, high priority, Ready for Stage

#3881 Mwpw 170384 lost info 320
  libs/blocks/modal/modal.css
Labels: Ready for Stage

#3907 MWPW-170349 [Article Header] Support no author link
  libs/blocks/article-header/article-header.js
  test/blocks/article-header/article-header.test.js
  test/blocks/article-header/mocks/body-without-author-link.html
Labels: verified, Ready for Stage

#3908 MWPW-170928[MEP] Add MEP pzn tags for a user's country
  libs/features/georoutingv2/georoutingv2.js
  libs/features/personalization/personalization.js
  libs/utils/utils.js
  test/features/personalization/mepGeolocation.test.js
  test/features/personalization/mepGeolocationSettings.js
  test/features/personalization/mocks/manifestMEPCountryChoice.json
  test/features/personalization/mocks/manifestMEPCountryIP.json
  test/features/personalization/mocks/metadata-mepgeolocation.html
  test/utils/mocks/head-personalization.html
  test/utils/mocks/mep/head-mepgeolocation-off.html
  test/utils/mocks/mep/head-mepgeolocation-on.html
  test/utils/utils-mep-with-params.test.js
  test/utils/utils-mep.test.js
Labels: verified, Ready for Stage

#3954 MWPW-169204: create QS from the link
  libs/blocks/merch-card/merch-card.js
  test/blocks/merch-card/merch-offer-select.test.js
  test/blocks/merch-card/mocks/selection-cards.html
Labels: verified, Ready for Stage

#3972 [DA] Milostudio dev to stage
  tools/da-apps/dist/assets/index.css
  tools/da-apps/dist/assets/index.js
  tools/da-apps/dist/assets/vendor.js
Labels: trivial

#3975 [DA] Fixed da bacom blog mapping & added ref in session storage
  tools/da-apps/auth.js
Labels: trivial

#3860 MWPW-170175: Dynamic Nav Reset
  libs/features/dynamic-navigation/dynamic-navigation.js
  libs/features/dynamic-navigation/status.css
  libs/features/dynamic-navigation/status.js
  test/features/dynamic-nav/dynamicNav.test.js
  test/features/dynamic-nav/mocks/reset.html
  test/features/dynamic-nav/mocks/status.html
  test/features/dynamic-nav/status.test.js
Labels: verified, Ready for Stage

#3919 [MWPW-167083] privacy-standalone.js order of operations
  libs/scripts/delayed.js
  libs/utils/utils.js
Labels: verified, Ready for Stage

#3947 Changing gnav height for standalone Gnav
  libs/navigation/navigation.css
Labels: verified, Ready for Stage

#3957 MWPW-171303: Fix preflight assets issues
  libs/blocks/preflight/preflight.css
Labels: Ready for Stage

#3964 Merging Tags: PersV2 and Hybrid-pers
  libs/features/personalization/personalization.js
  libs/martech/helpers.js
  libs/martech/helpers.md
  libs/utils/utils.js
  test/martech/helpers.test.js
Labels: verified, Ready for Stage

#3978 MWPW-171526 [MMM][MEP] MMM North America filter does not show US pages
  libs/blocks/mmm/mmm.js
Labels: verified, Ready for Stage

#3938 MWPW-16548: fix plans M@Sv2 CTA
  libs/blocks/merch-card-autoblock/merch-card-autoblock.js
  libs/blocks/merch/merch.js
  libs/deps/mas/commerce.js
  libs/deps/mas/mas.js
  libs/deps/mas/merch-card-collection.js
  libs/deps/mas/merch-card.js
  libs/deps/mas/merch-subscription-panel.js
  libs/deps/mas/merch-twp-d2p.js
  libs/features/mas/dist/mas.js
  libs/features/mas/docs/plans.html
  libs/features/mas/docs/src/plans.md
  libs/features/mas/src/checkout-mixin.js
  libs/features/mas/src/hydrate.js
  libs/features/mas/test/hydrate.test.js
  test/blocks/merch-card-autoblock/merch-card-autoblock.test.js
  test/blocks/merch-card-autoblock/mocks/fragment.json
Labels: verified, commerce, Ready for Stage

#3952 MWPW-170913 Fix graybox z-index issues
  libs/blocks/graybox/graybox.css
  libs/blocks/graybox/graybox.js
  libs/styles/styles.css
Labels: verified, Ready for Stage

#4000 MWPW-170402 [MEP] [NALA] nala test for MEP button functionality
  nala/features/personalization/mep-button.page.js
  nala/features/personalization/mep-button.spec.js
  nala/features/personalization/mep-button.test.js
Labels: verified, zero-impact, Ready for Stage

#3994 MWPW-171546 fix issue with localized links being localized again.
  libs/utils/utils.js
Labels: verified, high priority, Ready for Stage

#3886 Tooltips are hidden while hovering over top four icons on Safari browser.
  libs/blocks/global-navigation/global-navigation.css
Labels: verified, Ready for Stage

#3956 Fix(Mwpw-169955):share blocks copy to clipboard tooltip repositioned
  libs/blocks/global-navigation/global-navigation.js
  libs/blocks/share/share.css
Labels: verified, Ready for Stage

#3969 MWPW-170562: CaaS authoring dialog updates for language-first localization
  libs/blocks/caas-config/caas-config.js
  libs/blocks/caas/utils.js
Labels: caas-configurator, CaaS, Ready for Stage

#3979 MWPW-171172 Fix Image Links with Param
  libs/utils/utils.js
  test/utils/imageLinks.test.js
  test/utils/mocks/image-links.html
Labels: verified, Ready for Stage

#3983 MWPW-169540: Fix icon block in tab heading font size
  libs/blocks/icon-block/icon-block.js
  test/blocks/icon-block/icon-block.test.js
  test/blocks/icon-block/mocks/body.html
Labels: Ready for Stage

#3987 Added link to target activity manifest inside Target Report
  libs/blocks/mmm/mmm.css
  libs/blocks/mmm/mmm.js
Labels: verified, Ready for Stage

#3989 MWPW-171550 | Focus for split notification
  libs/blocks/notification/notification.css
  libs/blocks/notification/notification.js
  libs/blocks/section-metadata/section-metadata.css
  test/blocks/notification/mocks/body.html
  test/blocks/notification/notification.test.js
Labels: verified, high priority, Ready for Stage

#3926 MWPW-170110: [AH] Create new template - Promoted plans
  libs/deps/mas/merch-card.js
  libs/features/mas/dist/mas.js
  libs/features/mas/docs/adobe-home.html
  libs/features/mas/src/hydrate.js
  libs/features/mas/src/mas.js
  libs/features/mas/src/merch-card.js
  libs/features/mas/src/variants/ah-promoted-plans.css.js
  libs/features/mas/src/variants/ah-promoted-plans.js
  libs/features/mas/src/variants/ah-try-buy-widget.js
  libs/features/mas/test/merch-card.ah-promoted-plans.test.html
  libs/features/mas/test/merch-card.ah-promoted-plans.test.html.js
  libs/features/mas/test/merch-card.ah-try-buy-widget.test.html
Labels: verified, commerce, merch card, Ready for Stage

#3966 [MWPW-171113] - Automated iframe title cta
  libs/blocks/iframe/iframe.js
  libs/blocks/modal/modal.js
Labels: Ready for Stage

#3976 Gap is seen between promo banner and G-nav when page is scrolled.
  libs/blocks/global-navigation/global-navigation.css
Labels: verified, Ready for Stage

#3992 [MWPW-170383] Modal close button focus a11y
  libs/blocks/modal/modal.css
  libs/blocks/modal/modal.js
Labels: Ready for Stage

#3995 MWPW-171023: Fix seo body size check
  libs/blocks/preflight/panels/seo.js
Labels: Ready for Stage

#4006 MWPW-169639: Fix SEO visibility of CAAS card collections for search engine crawlers
  libs/blocks/caas/caas.js
Labels: Ready for Stage

#4046 [DA] Refresh dev build with view save popup changes etc.
  tools/da-apps/dist/assets/index.js
Labels: trivial

#4043 MWPW-165540 fix error if cta has no href
  libs/utils/automated-aria.js
Labels: Ready for Stage

#4053 Revert "Gap is seen between promo banner and G-nav when page is scrolled."
  libs/blocks/global-navigation/global-navigation.css
Labels: verified, Ready for Stage

#4032 [OPT-31767] MEP test: Add dark-table class for the emea1441 test
  libs/mep/emea1441/table/README.md
  libs/mep/emea1441/table/table.css
  libs/mep/emea1441/table/table.js
Labels: verified, zero-impact, Ready for Stage

#4013 [Footer] | Add legacy Adobe "A" logo to footer (Mobile & Desktop)
  libs/blocks/global-footer/global-footer.css
  libs/blocks/global-footer/global-footer.js
Labels: verified, high priority, Ready for Stage

#4030 MWPW-171967 Support for placeholders-stage
  libs/features/placeholders.js
  libs/utils/utils.js
Labels: high priority, Ready for Stage

#3798 [MWPW-167072][LANA] Add parameter for severity
  libs/utils/lana.js
  test/utils/lana.test.js
  test/utils/loadLana.test.js
Labels: Ready for Stage

#3865 MWPW-167717 Parallelize requests inside global-navigation.js
  libs/blocks/global-navigation/global-navigation.js
  libs/blocks/global-navigation/utilities/utilities.js
  libs/utils/utils.js
  test/blocks/global-navigation/global-navigation.test.js
  test/blocks/global-navigation/test-utilities.js
  test/navigation/bootstrapper.test.js
Labels: verified, Ready for Stage

#3898 Mwpw 169999 header obscures content
  libs/scripts/accessibility.js
  libs/styles/styles.css
  libs/utils/utils.js
Labels: Ready for Stage

#3993 [MWPW-170177] Move tooltip icon listeners
  libs/blocks/table/table.js
  libs/features/icons/icons.js
  test/blocks/table/table.test.js
  test/features/icons/icons.test.js
Labels: Ready for Stage

#3936 MWPW-170033: Secure transaction label
  libs/deps/mas/commerce.js
  libs/deps/mas/merch-card-collection.js
  libs/deps/mas/merch-card.js
  libs/features/mas/dist/mas.js
  libs/features/mas/src/aem-fragment.js
  libs/features/mas/src/hydrate.js
  libs/features/mas/test/hydrate.test.js
  libs/features/mas/test/mocks/sites/fragments/fragment-cc-all-apps.json
Labels: verified, commerce, Ready for Stage

#4057 MWPW-171967 Handle non-json
  libs/features/placeholders.js
  libs/utils/utils.js
Labels: Ready for Stage

#4063 [DA] Refresh dev build with breadcrumb updates
  tools/da-apps/dist/assets/index.js
Labels: trivial

#4050 MWPW-164494: Plans Business card
  libs/deps/mas/merch-card-collection.js
  libs/deps/mas/merch-card.js
  libs/features/mas/dist/mas.js
  libs/features/mas/docs/plans.html
  libs/features/mas/docs/src/plans.md
  libs/features/mas/docs/styles.css
  libs/features/mas/src/merch-card-collection.js
  libs/features/mas/src/variants/plans.css.js
  libs/features/mas/src/variants/plans.js
Labels: commerce

#4009 Ace1068 Marquee and Notification variant
  libs/mep/ace1068/hero-marquee/hero-marquee.css
  libs/mep/ace1068/hero-marquee/hero-marquee.js
  libs/mep/ace1068/notification/notification.css
  libs/mep/ace1068/notification/notification.js
  libs/mep/ace1068/section-metadata/section-metadata.css
  libs/mep/ace1068/section-metadata/section-metadata.js
  libs/mep/ace1068/section-metadata/sticky-section.js
Labels: verified, zero-impact, Ready for Stage

#3974 New Mobile Sub-header Enhancement - Making sub header visible on mobile
  libs/blocks/global-navigation/base.css
  libs/blocks/global-navigation/dark-nav.css
  libs/blocks/global-navigation/global-navigation.css
  libs/blocks/global-navigation/utilities/utilities.js
Labels: verified, Ready for Stage

#4007 [MWPW-171537] Marketo hide section onSuccess
  libs/blocks/marketo/marketo.js
  test/blocks/marketo/marketo.test.html
  test/blocks/marketo/marketo.test.js
  test/blocks/marketo/mocks/one-page-experience.html
Labels: verified, Ready for Stage

#4010 Upgrading package version for bundled Gnav to 0.0.8
  libs/navigation/package.json
Labels: verified, trivial, Ready for Stage

#4012 MWPW-169950: Product Sign In Pages with SUSI Light
  libs/blocks/susi-light-login/susi-light-login.css
  libs/blocks/susi-light-login/susi-light-login.js
  libs/utils/utils.js
  test/blocks/susi-light-login/mocks/susi-light-login.html
  test/blocks/susi-light-login/susi-light-login.test.js
Labels: verified, Ready for Stage

#4014 Quiz card accessibility
  libs/blocks/quiz/quiz.css
  libs/blocks/quiz/quizoption.js
Labels: verified, Ready for Stage
