Repository adobecom/milo, pull requests merged in 2025-10, with the labels that each got.

#4848 Mwpw-175184: Full pricing express merch card
  .gitignore
  libs/deps/mas/merch-card-collection.js
  libs/deps/mas/merch-card.js
  libs/features/mas/dist/mas.js
  libs/features/mas/docs/express.html
  libs/features/mas/src/global.css.js
  libs/features/mas/src/hydrate.js
  libs/features/mas/src/mas-tooltip.js
  libs/features/mas/src/merch-card.js
  libs/features/mas/src/utils.js
  libs/features/mas/src/variants/full-pricing-express.css.js
  libs/features/mas/src/variants/full-pricing-express.js
  libs/features/mas/src/variants/product.js
  libs/features/mas/src/variants/simplified-pricing-express.css.js
  libs/features/mas/src/variants/simplified-pricing-express.js
  libs/features/mas/src/variants/variant-layout.js
  libs/features/mas/src/variants/variants.js
  libs/features/mas/test/merch-card.full-pricing-express.test.html
  libs/features/mas/test/merch-card.full-pricing-express.test.html.js
  nala/features/mas/express/express.page.js
  nala/features/mas/express/express.spec.js
  nala/features/mas/express/express.test.js
  test/blocks/merch-card-autoblock/mocks/artifact.json
Labels: verified, high priority, Ready for Stage

#4833 [MWPW-179532] Adding externalLibs config attribute to enable external libs block loading
  libs/utils/utils.js
Labels: Ready for Stage

#4858 MWPW-178762 [Sev2][Catalog] Multiple links have the same programmatic…
  libs/blocks/merch-card/merch-card.js
  test/blocks/merch-card/merch-card.test.js
  test/blocks/merch-card/mocks/catalog.html
Labels: verified, Ready for Stage

#4872 MWPW-177481 [Plans M@S] Upgrade plan - Suppress stock checkbox
  libs/blocks/merch/merch.js
Labels: verified, Ready for Stage

#4941 MWPW-180338 [Plans] Issues with deep-linked tabs and modals
  libs/blocks/merch-card-collection-autoblock/merch-card-collection-autoblock.js
  libs/blocks/tabs/tabs.js
Labels: verified, Ready for Stage

#4951 MAS: fix deeplink Nala test
  nala/features/mas/acom/plans/plans.test.js
Labels: verified, zero-impact, Ready for Stage

#4957 Nala:Fix for MAS-Full-Pricing-Express-Pro
  nala/features/mas/express/express.spec.js
Labels: zero-impact, Ready for Stage

#4952 [DA Express Migration] Exclude Redirects from Sync
  .github/workflows/import/index.js
Labels: zero-impact
